### ISSUE TITLE
Disable Microsoft Family Safety.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1000]
Consider setting the pref _security.family_safety.mode_ to _0_ (set to _2_ by default). Microsoft Family Safety acts as a man-in-the-middle proxy which monitors and regulates the ability to access websites.

The value was switched to 2 in Firefox 52, whereas it was set to 0 up to and including Firefox 51.

**Comment by wolfbeast** [comment]
Something to consider for Pale Moon, as an app-specific default, but not for the platform.
