### ISSUE TITLE
Mozilla SSL error reporting is still active.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1003]
This is an oversight, I think. The Mozilla SSL error reporting is still active, but it shouldn't be.

Those preferences should be changed:

_security.ssl.errorReporting enabled_ - **false** (set to true by default).
_security.ssl.errorReporting.url_ - **empty string** (set to https://incoming.telemetry.mozilla.org/submit/sslreports/ by default)

**Comment by wolfbeast** [comment]
Actually, those are just dead prefs and aren't used anywhere.

See: http://xref.palemoon.org/uxp-trunk/search?string=errorReporting.enabled&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk
