### ISSUE TITLE
Further about:config pref cleanup (miscellaneous).

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1004]
This is a list of about:config preferences that are clearly no longer needed and some of which the pref should be changed to another value:

_dom.ipc.plugins.flash.subprocess.crashreporter.enabled_ - **false** (set to true by default)
_dom.ipc.plugins.reportCrashURL_ - **false** (set to true by default)

Crashreporter specifically for the Flash plugin, should be disabled (or removed if the related code is gone already).

_network.allow-experiments_ - **false** (set to true by default)

This pref allows Mozilla to silently install experiments. Should be disabled (or removed if the related code is gone already).

_camera.control.face_detection.enabled_ - **false** (set to true by default)

This enables the camera to focus on one's face. Not even sure if Pale Moon has even access to the built-in camera of laptops. It isn't needed to view websites, in any case. 

_toolkit.telemetry.debugSlowSql_ - false
_toolkit.telemetry.enabled_ - false
_toolkit.telemetry.infoURL_ - empty string
_toolkit.telemetry.reportingpolicy.firstRun_ - **false**
_toolkit.telemetry.server_ - empty string
_toolkit.telemetry.server_owner_ - empty string
_toolkit.telemetry.unified_ - false

Preferences related to standard telemetry, can all go IMHO.

Thanks for your attention, and big thumbs up to Moonchild for having reacted to my previous reports swiftly and efficiently.

**Comment by Peacock365** [comment]
Is this being investigated? Would like to hear some feedback on the entries I've mentioned, before I proceed with other left-over entries from Mozilla.

**Comment by wolfbeast** [comment]
> Is this being investigated?

Not at the moment. Also keep in mind that platform preferences need not all apply to Pale Moon as an application but may apply to other applications (e.g. the camera.* pref you pointed out)

Telemetry prefs will be tackled with telemetry cleanup.

**Comment by mattatobin** [comment]
Also, unused preferences have zero performance cost. Why are you so focused on them anyway?

**Comment by Peacock365** [comment]
> Also, unused preferences have zero performance cost. Why are you so focused on them anyway?

Because they are unnecessarily crowding about:config. Like to have it clean. And since they are unused, as you say, they might as well be deleted entirely.

**Comment by wolfbeast** [comment]
However, a good number of the prefs you have indicated are not unused. They are prefs that still have impact when changed. If they are truly dead prefs, then sure, kill them, but otherwise? no, it needs to be done properly if at all.

**Comment by Peacock365** [comment]
Why is this closed? This should be open until the pref clean-up is done, with the related code being deleted if necessary. What's more, this list is far from complete. Moonchild, please reopen this issue. I want to post some other prefs that can (most likely) be removed.

**Comment by mattatobin** [comment]
Because you don't get to decide how the issue tracker or what preferences are removed. Unless you are gonna do the work perhaps you should take this and similar discussion to the forum.

**Comment by Peacock365** [comment]
> Because you don't get to decide how the issue tracker is managed

Never claimed I do, Matt. I asked for this to be re-opened in the most friendly manner imaginable. Not sure what the problem is.

> or what preferences are removed. 

The telemetry settings are useless, all of them. The flash crash reporter settings are useless. The setting that allows Mozilla to silently install Firefox Experiments is useless... And so on. The camera setting isn't completely useless, maybe, although it's not exactly required to view websites.

> Unless you are gonna do the work perhaps you should take this and similar discussion to the forum.

If you want me to do the removal, then at least point me to the location of the settings I mentioned in this repo. Then I will gladly create some pull requests. Don't know what this forum bit means, Matt. The pull requests are being done here, not in the forum. Again, I am willing to create those pull requests.

> Also, UXP Applications != Waterfox.

I created some minor commits in the Waterfox repo. Is that reason to hold a grudge, Matt? You are a bit unfriendly, not sure why.

**Comment by g4jc** [comment]
@Peacock365 the tasks are being done one small peices at a time, have a look at #21 in regards to the telemetry settings. 

> If you want me to do the removal, then at least point me to the location of the settings I mentioned in this repo. 

The basic way of removing a pref is to [search for it in UXP](http://xref.palemoon.org/uxp-trunk/search?string=toolkit.telemetry.reportingpolicy.firstRun&find=) and [trace it back to it's implementation point](https://bugzilla.mozilla.org/show_bug.cgi?id=1137355#c20). Afterwards, you can very carefully begin to reverse the patch and remove it for good. I'm sure PRs would be welcomed if the removal is done properly and there are no bugs introduced.
