### ISSUE TITLE
Refresh branding

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1010]
To work better with what we have in art assets, we need a brand refresh to incorporate it better with design plans.
people want a more stylized logo anyway, so....

**Comment by mattatobin** [comment]
> [20190315.1117-16] Tobin: You know what elements I like the MOST when it comes to the artwork it is the distance with the sky the moon and mountains
> [20190315.1120-12] Tobin: which I think could work totally.. like I said the moon being white isn't the problem if that is the glyph logo but a little more color could be emphasized.. for instance.. the dark parts of the moon because it is on a darker sky because of atmospheric lighting and how that physically works.. if the darker elements were more emphasized and a bit more blue then it would be closer but also distinct from the current moon logo and if the pink to blue was smidge more emphasized it would also make the white pale moon work
> [20190315.1124-19] Tobin: so a somewhat more stylized moon logo would be beneficial i believe
> [20190315.1125-25] Tobin: and being more white but on the sky it is in the artwork and a touch more blue for the dark lava parts as part of that sky would work well i think
> [20190315.1125-39] Tobin: in my mind it would fit the PALE part of Pale Moon better

**Comment by Azarien** [comment]
Congratulations, you've changed a very cool-looking icon into what is now essentially a gray dot.
