### ISSUE TITLE
[Bug] Not able to register on github.com

### ISSUE THREAD

**Issue by mopsafe** [MoonchildProductions/UXP#1012]
Version: 27.8.2 (64-bit)
Windows 7 Pro / 10 Pro

Can`t register on Github because Pale moon does not supports Enforcement Challenges: https://www.arkoselabs.com/how-to-solve/

How to reproduce:

1) Goto https://github.com/join
2) Down below in a Verify account  section you will see only an image of a spinner:https://github.githubassets.com/images/spinners/octocat-spinner-128.gif

3) Visit same page in Chrome and you will see this: https://imgur.com/a/ueYx7MX

**Comment by kn-yami** [comment]
Upgrade to the latest version and then test it again.

**Comment by mopsafe** [comment]
Not reproduced on Version: 28.4.0 (64-bit)
