### ISSUE TITLE
Youtube - music still plays after video tab is closed

### ISSUE THREAD

**Issue by mopsafe** [MoonchildProductions/UXP#1013]
Version: 27.8.2 (64-bit)
Windows 7 / 10

How to reproduce:
1) Open Pale moon
2) Go to the video page (for example: https://www.youtube.com/watch?v=y_H9C4BUPz4 ) by one of the following ways:

2.1) Via Bookmark
2.2) Via History
2.3) Directly visit the page

3) As soon as video starts, click on the Youtube logo in the left upper corner.
4) Result: Youtube Main page opened and audio from the previous video is playing
5) If the ad is played before the video you need to close Pale moon and repeat steps 1-5.

**Comment by THEtomaso** [comment]
I was able to reproduce this behaviour in Pale Moon Tycho.
But since Pale Moon UXP is unaffected by this particular issue, there's no point in reporting it.

**Comment by mopsafe** [comment]
@THEtomaso 
Yes there is. Pale moon has this issue and it is still under developer`s support

**Comment by mattatobin** [comment]
Maybe you shouldn't be using an end of life milestone version.

**Comment by wolfbeast** [comment]
@mopsafe We do not provide support for the previous milestone (v27.* or below)

Please only report issues with the current, supported version insofar as the latest published release still has it (and it hasn't been already solved on trunk/unstable)
