### ISSUE TITLE
nsAppRunner: Allow applications to have case-sensative names

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1014]
When setting any XUL application's MOZ_APP_BASENAME via "Name=YourName" in application.ini, the program's name becomes normalized to lowercase in two locations, resulting in "Yourname". This negatively affects JWM and similar Window Managers on GNU/Linux as the application window itself appears with incorrect branding (lowercase).

The two locations are:
1) toolkit/xre/nsAppRunner.cpp [line 3211](http://xref.palemoon.org/uxp-trunk/source/toolkit/xre/nsAppRunner.cpp#3211)
2) old-configure.in [line 5181](http://xref.palemoon.org/uxp-trunk/source/old-configure.in#5181)

Removing the "ToLowerCase(program)" in nsAppRunner.cpp seems to be enough to solve the issue. The application will then properly contain the original casing and displays the application window correctly in Windows Managers that are using the X11 WM_CLASS(STRING).

Questions:
- Are there any negative effects to having a case-sensitive application name? (the profile folder still remains lowercase regardless)
- Could this lowercase enforcement be removed globally or by a compile time CONFVAR?

**Comment by mattatobin** [comment]
I have no way of evaluating this change on a cross platform level.. Also, How does it negatively affect Window managers? All I see here is a personal preference argument.

**Comment by wolfbeast** [comment]
> (the profile folder still remains lowercase regardless)

Only on Linux.

**Comment by mattatobin** [comment]
Even on the Linux, the profile directory follows exactly what is in `application.ini` spaces and case included. That is why on the Linux it is `~/Moonchild\ Productions/Pale\ Moon/`

**Comment by wolfbeast** [comment]
Changing this in nsAppRunner.cpp should be fine -- it's only used for GTK so has no cross-platform impact. See [bug 776325](https://bugzilla.mozilla.org/show_bug.cgi?id=776325) where this was added to allow different naming in the UI than the binary name.

**Comment by wolfbeast** [comment]
Do note however:
in general, g_set_prgname() should also match the name of the desktop file, so that window managers that do application tracking can match the WM_CLASS to the desktop file:

https://live.gnome.org/GnomeShell/ApplicationBased

**Comment by g4jc** [comment]
> Also, how does it negatively affect Window Managers? All I see here is a personal preference argument. 

Apparently JWM is throwing a corrupt icon for users, I received a bug report on it.

> in general, g_set_prgname() should also match the name of the desktop file, so that window managers that do application tracking can match the WM_CLASS to the desktop file

Makes sense now, thanks.

**Comment by wolfbeast** [comment]
So, is there still anything actionable here? I gather if you make sure the desktop file matches, the icon would be correct.

**Comment by g4jc** [comment]
It looks like an edge-case issue, since renaming the desktop file solves it on the Window Managers that are tracking the WM_Class. I'll do some more testing, but I don't think the nsAppRunner override is necessary after further review.

It's also nice to know about the --class override, since users affected by this can always override the WM_Classs from command line. Thanks again.

Closing.
