### ISSUE TITLE
SSL_ERROR_ACCESS_DENIED_ALERT

### ISSUE THREAD

**Issue by mopsafe** [MoonchildProductions/UXP#1015]
Afetr launching fresh Pale moon 28.4.0 Portable it goes to https://palemoon.start.me/ but gets an error:

**Secure Connection Failed**
An error occurred during a connection to palemoon.start.me. Peer received a valid certificate, but access was denied. (Error code: SSL_ERROR_ACCESS_DENIED_ALERT)

Apart from being not very pleasant thing to greet me with, setting security.tls.version.max = 0 and security.tls.version.min = 0 does not help :(

**Comment by wolfbeast** [comment]
Kindly go to the forum to troubleshoot connection errors before creating issues. This kind of error is normally caused by something interfering with your secure connection and is not a browser bug in that case.
You're free to come back here and reopen this if it turns out to be a browser bug.
