### ISSUE TITLE
Improve performance by disabling unboxed plain objects

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1017]
There are a number of downsides to unboxed object representation which may justify its disablement and removal. However, in some workloads it does provide a performance benefit.

[Tests performed on real-life sites by Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1505574#c4) have given a perf win (sometimes up to 25%) not using unboxed representations in most cases, and only a small percentage saw perf loss. So this is certainly something we should be taking. Additionally, if this turns out to be without issues (I don't expect any) we can follow this up with a cleanup bug to remove all this unboxed handling code from SpiderMonkey, significantly simplifying some parts of the JS engine.

**Comment by mattatobin** [comment]
Some more extensive background would be appreciated like what in the heck does this mean?

**Comment by wolfbeast** [comment]
Haha, okay. Typed Objects (objects of a specific defined type as specified in ES6) don't need to be as flexible as regular JS objects (which can be extended at will). Mozilla has worked on using this to make the memory allocation more compact for such objects which makes them more efficient (boxed). BUT, in some cases "unboxing" them to re-adding this flexibility was thought to be a good idea so in quite a few places unboxed versions are allowed to be used even for typed objects (and afaict that was decided based mostly on benchmark scores).
Some situations will do better with the more compact form, some will do better with the unboxed form.

Does that explain the situation enough?

**Comment by wolfbeast** [comment]
OK I think I swapped the two terms around. The "unboxed" version is less flexible than the "boxed" version, representing raw values rather than flexible properties or structures. Either way it's a trade-off.

**Comment by mattatobin** [comment]
So you put in a pref so we can test this in the real world and if successful we will kill code the pref disables?

**Comment by wolfbeast** [comment]
That is the idea.

**Comment by wolfbeast** [comment]
This has been baking on unstable for a week now without ill effects, so we can make this permanent and get rid of the non-functional "optimization" in JS. I'll file a follow-up issue for cleaning up the code.
