### ISSUE TITLE
Make DevTools work on Pale Moon

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#102]
This is a meta bug for all pull requests to initially get devtools working on Pale Moon.

@janekptacijarabaci will link future devtools pull requests to this one until DevTools is fully operational in Pale Moon instead of creating dozens of separate issues..

Blocks #57

**Comment by mattatobin** [comment]
Blocks #57

**Comment by mattatobin** [comment]
As near as I can tell the DevTools them selves seem fully functional.. What is your assessment of the devtools status, @janekptacijarabaci?

**Comment by janekptacijarabaci** [comment]
Most features are functional (but I haven't tested it in detail).
Currently (e.g.): I see some bugs with Developer Toolbar. But that's a special category...

**Comment by mattatobin** [comment]
Understood. Keep up the good work.

**Comment by mattatobin** [comment]
Can we get a status report.. Is this finished in the scope of Pale Moon regardless if DevTools them selves need further enhancements.. It is a blocker after all...

**Comment by mattatobin** [comment]
@janekptacijarabaci

**Comment by mattatobin** [comment]
Thanks!

**Comment by JustOff** [comment]
Sorry, but I just can't figure out how to enable the logging of request bodies in new devtools:
![2018-05-06_18-41-57](https://user-images.githubusercontent.com/340855/39675061-26ec103e-5145-11e8-83ab-51cb5a981018.png)
@janekptacijarabaci, could you give me a clue?

**Comment by janekptacijarabaci** [comment]
@JustOff 
See:
[bug 1064458](https://bugzilla.mozilla.org/show_bug.cgi?id=1064458) Remove 'Log request and response bodies' preference
and
https://hg.mozilla.org/mozilla-central/rev/8d816bd77d80#l10.154

In `Browser Console` - now the result will always be: `Response body was not stored.`
In `Web Console` - there is everything.

**Comment by JustOff** [comment]
@janekptacijarabaci, thanks for the info!

Too bad, it was a pretty stupid decision :-1:

**Comment by wolfbeast** [comment]
No. the browser console is the console for the browser code, not content. There won't ever ber request and response bodies there because you're not debugging CONTENT there. If you are, then you're using the wrong tool.

**Comment by JustOff** [comment]
I'm probably missing something, but what is the right tool, say, to inspect response body for extensions or blocklist update requests? I don't see anything suitable for this task in new devtools.
