### ISSUE TITLE
Update and build new SFX module

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1022]
Our current installer SFX module is very old (7-zip 4.42). It has the necessary patches applied to it for sec reasons, but should be upgraded to something more modern to take advantage of the improvements the 7-zip author has made to their archive format.

- [x] Import updated source to our tree (including the necessary customization for security)
- [x] Build a new binary (this requires a Visual Studio 6 setup)
- [x] Customize the binary with desired product info and icon

I'll tackle this myself, I've done this before and have the necessary VS licenses to set up a VM for it. We want VS6 because that is the designated version used by the 7-zip author for maximum compatibility (it doesn't build cleanly on later versions and I'd rather not hack/have to maintain the source), and although really old it will also allow us to have an installer that still runs on NT5 kernels so people can be properly informed about minimum system requirements in the installer itself instead of getting the dreaded "not a valid win32 application" error.

**Comment by mattatobin** [comment]
Feel free to create some for Borealis and Interlink while you are at it as well as a Basilisk specific one ;)

**Comment by wolfbeast** [comment]
Once I have a generic build binary, all it takes is some reshacker work for any application. I'll put the generic one in the tree too.
