### ISSUE TITLE
(Linux) Compilation failure on latest commit (aa816b3)

### ISSUE THREAD

**Issue by thenamewastaken** [MoonchildProductions/UXP#1024]
I'm attempting something, and I need to do it on the latest commit available rather than a previous stable version.
However, when I try to compile Pale Moon, the compilation fails with the following error:
```
dom/base/nsGlobalWindow.cpp:14889:5: error: invalid use of incomplete type ‘class mozilla::dom::OwningExternalOrWindowProxy’
     aResult.SetAsWindowProxy() = domWindow.forget();
     ^~~~~~~
```
Scanning the directory tree it appears that `OwningExternalOrWindowProxy` is never defined except as an incomplete type in `nsGlobalWindow.h`.
I performed the search with this command:
```
find . -type f -exec grep -l "OwningExternal" {} \;
```

```
$ gcc --version
gcc (Gentoo 8.2.0-r6 p1.7) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by trav90** [comment]
Can't reproduce here using GCC 7 in a standard build environment. Have you tried clobbering? What's your mozconfig/compiler flags look like?

**Comment by g4jc** [comment]
Also unable to reproduce on GCC 7.3.0

**Comment by thenamewastaken** [comment]
This is my mozconfig:
```
mk_add_options AUTOCLOBBER=1
mk_add_options MOZ_OBJDIR=/home/$USER/Projects/PM/UXP/objdir/
mk_add_options MOZ_MAKE_FLAGS='-j4'

mk_add_options PYTHON=/usr/bin/python2
mk_add_options AUTOCONF=/usr/bin/autoconf-2.13

ac_add_options --enable-application=palemoon
ac_add_options --enable-official-branding
export MOZILLA_OFFICIAL=1

ac_add_options --enable-optimize='-O2 -msse2 -mfpmath=sse'
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --enable-jemalloc
ac_add_options --enable-strip
ac_add_options --with-pthreads
 
ac_add_options --disable-tests
ac_add_options --disable-eme
ac_add_options --disable-parental-controls
ac_add_options --disable-accessibility
ac_add_options --disable-webrtc
ac_add_options --disable-gamepad
ac_add_options --disable-necko-wifi
ac_add_options --disable-updater
ac_add_options --disable-gconf
ac_add_options --disable-dbus
ac_add_options --disable-pulseaudio
```
Not sure where to get the compiler flags from. I run `./mach build` from a shell prompt, but I can't confirm if some other flags are added besides what would be added with this mozconfig.

**Comment by thenamewastaken** [comment]
I deleted the `objdir` directory and it compiled correctly.
I guess despite the current mozconfig, I busted something so bad it couldn't compile correctly anymore (though I'm not sure what could've caused this.)

Closing this issue as it's not actually an issue.
Apologies for the noise.
