### ISSUE TITLE
New tab + button is on right, not next to tab

### ISSUE THREAD

**Issue by zqqw** [MoonchildProductions/UXP#1025]
Using the latest unstable Linux version on XFCE : 28.5.0a1 (64-bit) (2019-03-24)
The new tab button was previously just to the right of the last opened tab. It now stays on the far right side with a black arrow.

**Comment by wolfbeast** [comment]
Are you using a custom theme?

**Comment by zqqw** [comment]
```

$ pacman -Qs xfce4
local/exo 0.12.4-1 (xfce4)
    Application library for Xfce
local/garcon 0.6.2-1 (xfce4)
    Implementation of the freedesktop.org menu specification
local/gtk-xfce-engine 2.10.1-2 (xfce4)
    Xfce Gtk+-2.0 engine and themes
local/libxfce4ui 4.13.4-1
    Commonly used Xfce widgets among Xfce applications
local/libxfce4util 4.13.2-1
    Basic utility non-GUI functions for Xfce
local/mousepad 0.4.1-1 (xfce4-goodies)
    Simple text editor for Xfce
local/ristretto 0.8.3-1 (xfce4-goodies)
    Fast and lightweight picture-viewer for Xfce4
local/thunar 1.8.4-1 (xfce4)
    Modern file manager for Xfce
local/thunar-volman 0.9.1-1 (xfce4)
    Automatic management of removeable devices in Thunar
local/tumbler 0.2.3-2 (xfce4)
    D-Bus service for applications to request thumbnails
local/xfce4-appfinder 4.12.0-5 (xfce4)
    An application finder for Xfce
local/xfce4-notifyd 0.4.3-1 (xfce4-goodies)
    Notification daemon for the Xfce desktop
local/xfce4-panel 4.12.2-1 (xfce4)
    Panel for the Xfce desktop environment
local/xfce4-power-manager 1.6.1-1 (xfce4)
    Power manager for Xfce desktop
local/xfce4-session 4.12.1-11 (xfce4)
    A session manager for Xfce
local/xfce4-settings 4.12.4-1 (xfce4)
    Settings manager for xfce
local/xfce4-terminal 0.8.7.4-1 (xfce4)
    A modern terminal emulator primarily for the Xfce desktop environment
local/xfconf 4.12.1-5 (xfce4)
    A simple client-server configuration storage and query system
local/xfdesktop 4.13.3-1 (xfce4)
    A desktop manager for Xfce
local/xfwm4 4.12.5-1 (xfce4)
    Xfce window manager
local/xfwm4-themes 4.10.0-3 (xfce4)
    A set of additional themes for the Xfce window manager

```

**Comment by zqqw** [comment]
It is still present in 28.5.0a1 (64-bit) (2019-03-26)
I have found that if I open lots of new tabs, so I need to use the arrows to scroll them left and right, then close those tabs, when the tabs are able to all fit on the screen width again, the arrows disappear and the new tab + button stays in the usual place for that session. I also tried right clicking in the bar and choosing customize, then adding several "flexible space's" to push the + button over, it sort of worked but meant the tabs were all at their minimum width even when not many were open.

**Comment by Lootyhoof** [comment]
Based on comments on the [forum](https://forum.palemoon.org/viewtopic.php?f=45&p=164267#p164267) related to a similar implementation I did in one of my themes, it seems like this might be related to #725. I'm not able to reproduce it though (even with the _same_ setup as the reporter..), nor are other Linux users in that thread. Some sort of weird GTK bug maybe?

@zqqw, are you able to revert to 28.4.1 and (assuming it's not broken in the default theme there) install the latest release of [Photonic](http://addons.palemoon.org/addon/photonic/) and see if the issue reappears?

**Comment by zqqw** [comment]
Reverting to the last good version I'd been using, 28.5.0a1 (64-bit) (2019-03-08) and deleting ~/.moonchild productions, the bug was not present. But when I installed the photonic theme it was present, but only on every other start up of Pale Moon, unlike the current situation where it is there all the time for me. Opening lots of tabs to bring the arrow buttons into use then closing some of those tabs fixed things as before. So I guess the reset behaviour works properly when the arrows are hidden away afterwards, the initial creation onscreen is the problem area and the 'too many tabs' arrows are being shown when they shouldn't be. The new tab + is on the right of the arrow so is probably in the correct place with respect to the arrow, but the arrows shouldn't be there when the browser starts. It seems a bit like a race situation too.

**Comment by Lootyhoof** [comment]
Alright, I've managed to confirm it. Though I still can't see what's causing it...

I'll take a look.

**Comment by zqqw** [comment]
Under Tools - Preferences - Tabs I had "Always show the tab bar" checked. When I uncheck this, so the tab bar is hidden on start up until I press ctrl T to open a new tab, the behaviour is normal afterwards. There are no recent commits under widget where the gtk code is.

**Comment by Lootyhoof** [comment]
I think I might've been able to mitigate this somewhat. If you try the [linked](https://app.box.com/s/osfvt461m0y09xl3vraua44tiqza1cdw) version of Photonic (with a small, currently-uncommitted change for this issue) can you let me know if you see the issue again? On my end it seems to vanish with this version.

If so, I'll look to getting this in the default theme, and of course get it in Photonic proper.

**Comment by zqqw** [comment]
Yes, that does work in 28.5.0a1 (64-bit) (2019-03-26) with that edition of the Photonic theme installed, while it was not working with the default theme before. I have tried closing and restarting it a few times and it has always appeared with the arrows hidden and the new tab + in the correct location. It also behaves normally when the "Always show the tab bar" check box is unchecked and when lots of tabs are opened then closed, so it looks good.
