### ISSUE TITLE
"Check for updates" hangs.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1028]
Seem to be a regression from #1021 and/or #1023.

Browser console throws:

> 14:46:35.796 NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.getCharPref] 1 nsUpdateService.js:2791

the problem seems to be the following passing `null` as a default value for a getCharPref:
```JavaScript
    // Use the override URL if specified.
    let url = Services.prefs.getCharPref(PREF_APP_UPDATE_URL_OVERRIDE, null);
```

@Ascrod can you look into this please?

**Comment by Ascrod** [comment]
Certainly. My earliest opportunity will probably be later tomorrow, though.

**Comment by wolfbeast** [comment]
No problem. the way it looks I'm having to put everything on hold until I get a reply from MozSec anyway

**Comment by JustOff** [comment]
As far as I can see, passing `null` as a default value for a `getCharPref` requires applying the [bug #1410794](https://bugzilla.mozilla.org/show_bug.cgi?id=1410794), ([mozregression](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d3910b7628b8066d3f30d58b17b5824b05768854&tochange=ee21e5f7f1c1726e0ed2697eb45df54cdceedd36)).

**Comment by wolfbeast** [comment]
Well whomever feels like fixing this first. if you have time JustOff, you're free to take this as well.

**Comment by JustOff** [comment]
I'm afraid that someone more experienced in C++ is needed to port the [bug #1410794](https://bugzilla.mozilla.org/show_bug.cgi?id=1410794), because I don't quite understand how to [apply all the necessary changes to our tree](http://xref.palemoon.org/uxp-trunk/search?string=GetCharPref%28&find=\.c&findi=\.c&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk).

Perhaps for now it's better to partially revert the changes to `nsUpdateService.js` made in #1023.

**Comment by Ascrod** [comment]
> 
> 
> I don't quite understand how to [apply all the necessary changes to our tree](http://xref.palemoon.org/uxp-trunk/search?string=GetCharPref%28&find=.c&findi=.c&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=uxp-trunk).

Did you mean to [escape the dot in the .c file name filter](http://xref.palemoon.org/uxp-trunk/search?string=GetCharPref%28&find=\.c&findi=\.c&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk)? The linked patches should only apply to C++ code and header files, and IDL files.

**Comment by mattatobin** [comment]
As a workaround use string null as default and check that maybe?

**Comment by wolfbeast** [comment]
Empty string instead of null should be fine. It will also fail the `if (!var)` condition.

**Comment by wolfbeast** [comment]
I'm plugging in empty strings. it makes a lot more sense to require a string type default value for getCharPref than feeding it `null`. I consider this a callsite error.
Since comparisons and checks will treat `null`, `undefined` and `""` the same way there's no real difference.
