### ISSUE TITLE
Remove "unboxed" typed objects

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1030]
Follow-up to #1017 

Disabling the "unboxed" object optimization gives us better performance in the real world. This has been baking without ill effects on unstable so we can remove the code now, simplifying typed object handling and reducing quite a bit of (complex) code in SpiderMonkey as a result.

We can use https://bugzilla.mozilla.org/show_bug.cgi?id=1505574 as a guideline.

**Comment by mattatobin** [comment]
Might be wise to let this sit for a release cycle so that it can get broad usership before we kill something we may have to put back in.

**Comment by wolfbeast** [comment]
Oh I agree with keeping the pref-controlled state for a while. No rush on this.

**Comment by mattatobin** [comment]
Planned removal for Pale Moon 28.5.1 and matched UXP Applications.

**Comment by wolfbeast** [comment]
There have been 0 reports of issues disabling these objects, so let's go ahead and remove this code.
@mattatobin are you taking this or shall I? Looks like this is at least something I won't brickwall with this week ;P

**Comment by mattatobin** [comment]
Have a blast with it.

**Comment by wolfbeast** [comment]
This is a lot of cleanup work. Going to take a while removing this and testing inbetween chunks.

**Comment by wolfbeast** [comment]
Depends on #1090. I'll have to split this issue up so I can remove arrays before continuing removing this.

**Comment by wolfbeast** [comment]
Because this is more work than expected, I'm pushing this back to 28.6

**Comment by g4jc** [comment]
FYI, there's a linker error introduced after the merge of Phase 1:

```
/js/src/jit/IonCaches.cpp:1545: error: undefined reference to 'js::UnboxedPlainObject::layout() const'
/js/src/jit/IonCaches.cpp:3414: error: undefined reference to 'js::UnboxedPlainObject::layout() const'
/js/src/jit/Recover.cpp:1543: error: undefined reference to 'js::UnboxedPlainObject::layout() const'
collect2: error: ld returned 1 exit status
```

**Comment by adeshkp** [comment]
@g4jc I encountered this on Mac few days ago. Linux build was somehow unaffected, so didn't bother. It can be remedied by including "vm/Unboxed-inl.h" header file.

**Comment by adeshkp** [comment]
@g4jc I encountered this on Mac few days ago. Linux build was somehow unaffected, so didn't bother. It can be remedied by including "vm/Unboxed-inl.h" header in the mentioned files.

**Comment by Kokokokoka** [comment]
I encountered this on Linux today. Can't build from master as ld fails.

**Comment by wolfbeast** [comment]
And this, kids, is why unified building is a bad thing. You've run into platform-dependent and build system dependent deprot.
