### ISSUE TITLE
Pale Moon P28.5.0a1(20190328) breaks TabMixPlus

### ISSUE THREAD

**Issue by shellye5** [MoonchildProductions/UXP#1031]
@wolfbeast @Ascrod This last update breaks TMP

Fresh profile

https://bitbucket.org/onemen/tabmixplus/downloads/tab_mix_plus-0.5.6.0-fx.xpi

install on Pale Moon P28.5.0a1(20190328) latest beta

open multiple bookmarks with ctrl+click or middle click
Nothing happens.

only opening in current tab works.
This happens with 28-03-2019 build.
worked perfectly on before that.

maybe something to do with 
this commit

https://github.com/MoonchildProductions/UXP/commit/c9d2e9bcfb77657b3be7d368e57f43747c23ddc4

just guessing.

P.S:Please Fix this as TMP+PM is very important.

**Comment by JustOff** [comment]
You should [report this issue to the TMP author](https://bitbucket.org/onemen/tabmixplus), so they provide compatibility with updated UXP applications, and not vice versa.

**Comment by shellye5** [comment]
> 
> 
> You should [report this issue to the TMP author](https://bitbucket.org/onemen/tabmixplus), so they provide compatibility with updated UXP applications, and not vice versa.

Isn't Legacy extensions closed for development for web-extensions?
So PM should maintain a fork or compatibility? 
Sorry not being ignorant just asking as switched to PM for legacy addons.

**Comment by JustOff** [comment]
These questions have been answered [here](https://forum.palemoon.org/viewtopic.php?f=46&t=11385).

**Comment by shellye5** [comment]
https://bitbucket.org/onemen/tabmixplus/issues/80/pale-moon-p2850a1-20190328-breaks

**Comment by shellye5** [comment]
Only happens in Palemoon 
Basilisk 2019.03.27 works fine so might be something else can you add technical details? as you are more equipped for that please

**Comment by wolfbeast** [comment]
TMP dev's task to provide compatibility to what it extends.

**Comment by Ascrod** [comment]
As best I can tell, it's trying to call some "getBoolPref" helper that no longer exists in the browser code. TMP dev should be able to fix this pretty easily.

**Comment by mattatobin** [comment]
Obviously.

**Comment by shellye5** [comment]
> 
> 
> As best I can tell, it's trying to call some "getBoolPref" helper that no longer exists in the browser code. TMP dev should be able to fix this pretty easily.

So it should not work in Basilisk  too right?
That's what i meant to ask
Why is it broken in one and works on the other as they both have the code merged.

**Comment by Ascrod** [comment]
> So it should not work in Basilisk too right?
> That's what i meant to ask
> Why is it broken in one and works on the other as they both have the code merged.

Not necessarily. Basilisk and Pale Moon both use the UXP _platform_ code, but the browsers' _application_ code is very different. It's also possible that TMP behaves differently based on what application it's running in, or even what code is present in the application. The person who can best answer that question (and fix this issue) is the TMP dev.

**Comment by shellye5** [comment]
> 
> 
> > So it should not work in Basilisk too right?
> > That's what i meant to ask
> > Why is it broken in one and works on the other as they both have the code merged.
> 
> Not necessarily. Basilisk and Pale Moon both use the UXP _platform_ code, but the browsers' _application_ code is very different. It's also possible that TMP behaves differently based on what application it's running in, or even what code is present in the application. The person who can best answer that question (and fix this issue) is the TMP dev.

Thank you for the explanation!!
will report it now if can register in the forums there.
TY for Both browsers.
