### ISSUE TITLE
Remove menu button

### ISSUE THREAD

**Issue by mopsafe** [MoonchildProductions/UXP#1032]
Basilisk 2019.03.27 (64-bit)

Can I remove the Menu button from the address bar?

Pale moon solution ([https://www.reddit.com/r/palemoon/comments/3q2om2/how_to_remove_pale_moon_menu/](url) does not work

**Comment by mattatobin** [comment]
Why is this posted on github.. We have a forum for a reason.

Anyway, the Hamburger Menu is an essential part of the Australis CustomizableUI framework and cannot be removed nor should you try lest you lose access to what it has.

The Menu Button and Panel != The AppMenu of old where if you do hide it you can still hit Alt to toggle the menu bar to get access to everything.
