### ISSUE TITLE
SVG mask code can crash under certain conditions

### ISSUE THREAD

**Issue by kn-yami** [MoonchildProductions/UXP#1034]
Reported on the forum [here](https://forum.palemoon.org/viewtopic.php?f=37&t=21779). Similar crash was discovered and labeled as [Bug 1360343](https://bugzilla.mozilla.org/show_bug.cgi?id=1360343) by Mozilla. Basically the `maskSurface` can point to `nil` due to hardware condition and `maskFrame` can point to `nil` if the SVG contains invalid mask URL.

**Comment by wolfbeast** [comment]
The mask check was wrong and backed out. A different nullcheck is necessary here.
