### ISSUE TITLE
openh264 not installed due fail in comprobation

### ISSUE THREAD

**Issue by katnatek** [MoonchildProductions/UXP#1037]
I build basilisk for mageia linux with the 2019.03.27 release and i noticed that
 the openh264 never get installed.
Using the Browser console i get the messages of the attached file..
I don't know why but even if i download the zip with wget the sha512sum don't coincide.
I make the test with the temporal file downloaded by Mozilla's firefox 66.0.2 (but is the same) 
and the sum is right
[openh264.txt](https://github.com/MoonchildProductions/UXP/files/3049953/openh264.txt)

The widevine plugin install successfully

**Comment by wolfbeast** [comment]
> I don't know why but even if i download the zip with wget the sha512sum don't coincide.

Means it's not a browser issue but an issue with your network/routing.
Please use https://forum.palemoon.org/ to troubleshoot.

**Comment by katnatek** [comment]
Today test with the download manager of basilisk and firefox as with wget, all get right sum.
So i tested again watch the browser console and now  open264 install, maybe a issue from cisco's server

BTW, sorry for the noise
