### ISSUE TITLE
Framework rendering issue (layout)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1038]
URL: https://www.leafly.com/indica/yoda-og

Mozregression: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d50abca6521baeae8ac6b07ddf843d63a1aa5f84&tochange=8f80d594c08d5c7a112e5d4b9eb44ffca717eb7b

Unfortunately this MR fix range is huge. The site itself also doesn't throw any errors but displays wrong.

**Comment by JustOff** [comment]
Here is a narrower interval: [d50abca6521b - 42593af5ec7e](
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d50abca6521baeae8ac6b07ddf843d63a1aa5f84&tochange=42593af5ec7ec9d5a07c9c0e899ac99244d15ae6).

My suspect: [Bug #1291515](https://bugzilla.mozilla.org/show_bug.cgi?id=1291515).

**Comment by mattatobin** [comment]
What is this? Why do we need this and what does the PR do?

**Comment by JustOff** [comment]
Because `<style scoped>` was [removed from HTML spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1291515#c0).

**Comment by mattatobin** [comment]
So what does this have to do with some website?

**Comment by JustOff** [comment]
I guess this website uses this feature incorrectly, but, despite this, in accordance with the standard, we should ignore it.

**Comment by mattatobin** [comment]
How does it use it incorrectly? What web framework? Are there usages internally? What about extensions and themes? Why is this our problem?

Just because Google or Mozilla removes something and they hold sway over the standards doesn't mean it benefits us to remove it.

**Comment by JustOff** [comment]
Sorry, I don't see the logic in maintaining the feature excluded from the web standard, the incorrect application of which breaks sites in the wild, but it's probably better to discuss this with @wolfbeast.

**Comment by mattatobin** [comment]
So you're not going to answer some to all my questions. That isn't helpful.

Removal of features impacts everyone and everything and cannot be done blindly.

**Comment by JustOff** [comment]
> So you're not going to answer some to all my questions.

By no means. I answered your question to the best of my competence. Unfortunately, I can hardly add anything useful to what I have already said.

**Comment by wolfbeast** [comment]
I've read through the discussion in https://github.com/whatwg/html/issues/552 and I think removal from the spec was an error. `<style scoped>` does not aim to replace Shadow DOM's way of doing this or the other way around. On top, Shadow DOM is extremely restrictive and prevents restyling of DOM nodes that are "owned" by the shadow DOM author, which is in direct opposition to being open about content manipulation by the user.

The real reason seems to be that Chromium refused to implement this, in favor focusing on Shadow DOM and Web Components. The removal from the spec is in the end only bercause Google didn't want to budge in this respect and instead of just accepting that Chromium doesn't implement that part of the whatwg html spec, the spec writers decided to give Google full control and removing it because Chrome doesn't implement it (due to some unsubstantiated complexity/perf issue).

The discussion also states that yes, they probably want to re-visit this later on anyway.

We've had scoped styles for a long while and they work well. In fact, IIRC this was specifically implemented in Tycho. Also, if this is disabled as proposed you also disable the entire API and that **will** also influence documents in our browser chrome (AFAIK we do use scoped styling in a few places).

From what I see, there is no real reason to remove this. The rendering issue on this particular site is due to improper use of scoped styles, **not** because there's something wrong with scoped styles as a feature. If sites don't use it, then it won't hurt being there either.

**Comment by wolfbeast** [comment]
If you want to support reinstating a useful feature to the html spec, I filed https://github.com/whatwg/html/issues/4508

**Comment by mattatobin** [comment]
The removal or change of things like this especially if it has only existed in gecko requires excessive scrutiny.

Even if it was only implemented in a few to no other browsers it was likely implemented for a reason and likely has seen usership internally or in add-ons to some degree.

So these things are not just web standards but also platform standards be it consistant with Google/W3C/WhatWG or not.

**Comment by JustOff** [comment]
Thanks, now I better understand the background of the issue.

**Comment by wolfbeast** [comment]
`<style scoped>` is currently being discussed again for inclusion by various other implementers.
In the meantime I've also opened a ticket with leafly to fix their styling -- but ultimately this will be a wontfix for us. I don't see any reason to remove this feature.
