### ISSUE TITLE
Performance issues due to TriggeringPrincipal

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1040]
After running into this issue out of the blue (which is likely the cause of many of the issues reported on the forum about "lag" and slow loading), I was able to investigate high CPU usage after navigation of any kind (including XHR) and found one commonality in all of the situations by examining with ProcessExplorer: the persistent presence of 2 or more threads with activity at `LoadInfo::TriggeringPrincipal` and/or `LoadInfo::GetTriggeringPrincipal`. This also seems to be Pale Moon specific as I have not seen Basilisk affected by this.

So this is likely directly related to/fall-out from #679 and #680  by @janekptacijarabaci where `OriginPrincipal` and `TriggeringPrincipal` were introduced to Pale Moon's front-end

**Comment by wolfbeast** [comment]
Potentially the changes made to Basilisk's SessionStore modules should also have been applied to Pale Moon... There seems to be a pretty big discrepancy there.

**Comment by wolfbeast** [comment]
I may have found the culprit being an extension that got recently updated. Sorry for the noise.

**Comment by JustOff** [comment]
Just out of curiosity, what was it?

**Comment by wolfbeast** [comment]
https://forum.palemoon.org/viewtopic.php?f=46&t=21818

**Comment by mattatobin** [comment]
Shouldn't this still be considered a bug in the platform or application even if it is being triggered by an extension?

**Comment by wolfbeast** [comment]
> 
> 
> Shouldn't this still be considered a bug in the platform or application even if it is being triggered by an extension?

That would require analyzing why it hangs. possibly coding error, recursive calls or what not. Maybe a race?
The extension author doesn't seem interested in doing that, as he he said he'll just stick with the core files that work for everyone and be very careful about future changes.
