### ISSUE TITLE
CSS parser stops processing subsequent styles after detecting an invalid URL token

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1046]
As it was [reported](https://forum.palemoon.org/viewtopic.php?f=61&t=21880) on the forum, the [site](https://www.wieistmeineip.de/) is displayed incorrectly if it contains a style with an error in the URL token.

According to the [CSS3 spec](https://drafts.csswg.org/css-syntax/#consume-url-token) we should just eat whatever is between parentheses, if it's wrong, and continue processing the styles further.

**Comment by mattatobin** [comment]
We should have just gotten @Ascrod to eat them instead of the parser!
