### ISSUE TITLE
Slowdowns with certain script combinations

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#1052]
### Issue:
Certain script combinations causes lags / slowdowns / unresponsiveness.

### Forum reference (four posts):
https://forum.palemoon.org/viewtopic.php?f=3&t=21881#p165249

### Affected browsers:
* Basilisk
* Pale Moon
* SeaMonkey

### Unaffected browsers:
* Firefox (Many builds tested through Mozregression, and even Firefox ESR v52.9 seems to be unaffected)
* Waterfox

### Example:
I've noticed the problem on several sites, but this seems to be a good place for reproducing / testing:
https://www.americanexpress.com/en-us/business/trends-and-insights/articles/7-tricks-to-help-you-remember-anything/

### Troubleshooting:
Blocking just ONE of these scripts (doesn't matter which one) fixes the loading problem @ americanexpress.com right away!:
```
https://www.aexp-static.com/cdaas/axp-app/modules/axp-forum-page-wrapper/2.2.0/axp-forum-page-wrapper.client.js
https://www.aexp-static.com/cdaas/axp-app/modules/axp-forum-root/2.2.0/axp-forum-root.client.js
https://www.aexp-static.com/cdaas/axp-app/modules/axp-root/4.0.0/axp-root.client.js
https://www.aexp-static.com/cdaas/one/app/4.23.1-23d464e9/app.js
https://www.aexp-static.com/cdaas/one/app/4.23.1-23d464e9/axp-common.js
https://www.aexp-static.com/cdaas/one/app/4.23.1-23d464e9/vendors.js
```

### Note:
In Firefox's logger, the load times for many of the scripts are reported to be **0ms** (as improbable as that sounds).
In Pale Moon's logger, the load times for the same scripts are reported to be as much as **150ms**!
Also, the order in which some of the scripts are loaded doesn't seem to be completely identical.
Could it be that the affected browsers doesn't perform asynchronous loading of all scripts correctly?

**Comment by wolfbeast** [comment]
Have you considered that this may be because these websites use scripts that use UA sniffing with very strict FF checks in them? And that have undefined or poor code paths when they find a UA that doesn't match their short list?

**Comment by THEtomaso** [comment]
UA sniffing is always the first thing that I check for, when troubleshooting issues.
I tried a bunch of different overrides for americanexpress.com, but couldn't find one that fixed the problem.
Not saying that UA sniffing isn't the cause, but the issue certainly appears to me like something worth looking into.
If there actually is a problem with the way scripts are loaded, then perhaps it might explain some of the performance issues, reported by several users?

**Comment by mattatobin** [comment]
@THEtomaso So who told you to escalate this to a github issue? That's right, no one did because this isn't issue worthy. At least not at this juncture. Maybe you should be banned from the repository, hmm?

**Comment by THEtomaso** [comment]
When following up on my theory, regarding an asynchronous loading problem, I came across this "**ff_async_bug**" test:
http://kidkarolis.github.com/ff_async_bug/
After pressing "OK" on the 'test' message, the page never loads in affected browsers.
(PS: As stated in the bugzilla report; the results may vary a bit, and "sometimes it takes a few refreshes to reproduce the problem")

The above test is refered to in this Bugzilla report ("**Combination of script with async flag and alert function stops the rendering of the page**"):
https://bugzilla.mozilla.org/show_bug.cgi?id=692754
> If the async script is executed before the page finished rendering - the page hangs.
> If the async script is executed after the page finished rendering - the page renders.

The issue is 8 years old, and still "Unassigned", so Firefox should be affected by the problem too.. at least to a certain degree.
However, I ran the test many times myself, and found huge differences, depending on the browser.
Here are the results:
* Basilisk: FAILED 19 out of 20 times.
* Firefox: PASSED 20 out of 20 times
* Pale Moon: FAILED 20 out of 20 times.
* SeaMonkey: FAILED 20 out of 20 times.
* Waterfox: PASSED 20 out of 20 times

**Comment by mattatobin** [comment]
@THEtomaso How many times do I have to tell you.. The Forum is your first point of contact for potential bugs. This issue tracker is not your personal complaint board.

**Comment by wolfbeast** [comment]
Please understand that if issues are not treated properly as asked, meaning use the **forum** first to **discuss** potential issues and get them **confirmed as actionable** before you use the tracker to get an implementation track going, that I will be forced to block you from creating more issues on our repo.

**Comment by wolfbeast** [comment]
@THEtomaso if you have a reproducible test setup then I'd like to ask you to use mozregression to see when Mozilla went from a broken to a fixed state.

**Comment by THEtomaso** [comment]
> if you have a reproducible test setup then I'd like to ask you to use mozregression to see when Mozilla went from a broken to a fixed state.

> Many builds tested through Mozregression, and even Firefox ESR v52.9 seems to be unaffected

**Comment by JustOff** [comment]
> "ff_async_bug" test: http://kidkarolis.github.com/ff_async_bug/

Actually, I'm not sure this test is related to the original issue, but:

Last bad: [/1484350104/firefox-53.0a1.en-US.win32.zip](http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1484350104/firefox-53.0a1.en-US.win32.zip)
First good: [/1484351124/firefox-53.0a1.en-US.win32.zip](http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1484351124/firefox-53.0a1.en-US.win32.zip)
Pushlog: [671a2f8542ca - ac3275723df5](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=671a2f8542cadcf9aad318ab76250a730a03b240&tochange=ac3275723df59db0f09198fdb61b51e7002c391a)
Suspect: https://bugzilla.mozilla.org/show_bug.cgi?id=1316330

**Comment by THEtomaso** [comment]
Thanks a lot, JustOff!

I can confirm that the "Last bad" FF build fails the "ff_async_bug" test, whilst the "First good" build passes it!

Also, the "Last bad" build DOES struggle to load the americanexpress.com page (which I linked to in the first post)!
The reason why I didn't notice this earlier (when I ran Mozregression), is that it doesn't hang like Pale Moon does..
Instead, when loading the page with an empty browser cache, it often fails to fetch all of the page elements (text mostly).
The "First good" build, on the other hand, seems to load the the page without any issues, every time!

Although FF's symtoms differ from the ones we see in Pale Moon, I think you just might have nailed it!! :)

**Comment by mattatobin** [comment]
You also confirmed that no version of Firefox did whatever this issue is about, So which is it?

**Comment by THEtomaso** [comment]
> You also confirmed that no version of Firefox did whatever this issue is about, So which is it?

> The reason why I didn't notice this earlier (when running Mozregression), is that it doesn't hang/lag like Pale Moon does..
> Instead, when loading the page with an empty browser cache, it often fails to fetch all of the page elements (text mostly).

I was about to run Mozregression to test against that "ff_async_bug" test too, but JustOff beat me to it.

**Comment by wolfbeast** [comment]
I don't see how the suspect bug (which is about e10s keypress events in forms) has anything to so with scripts running with async

**Comment by wolfbeast** [comment]
Okay, I understand what's going on after some further research. Yes, @JustOff was right that it is the suspect bug. The problem is that something got busted to make it work in e10s, and it should trap all events, not just (as it is now) animation events, then handle those individually at a later point in time.
With the events not being trapped, the state of the executed script never becomes "ready" and it keeps blocking the load as a result.

I've got a patch for this now based on that bug, and if it indeed fixes the "async bug" page then there's a good chance that it will also fix the sync/async script combinations which likely hang in a similar way when an event is purposefully (script-)triggered or synthesized.

**Comment by mattatobin** [comment]
Do we want this as an uplift to pm-rel?

**Comment by wolfbeast** [comment]
> 
> 
> Do we want this as an uplift to pm-rel?

Probably. the change is fairly low-risk.

**Comment by JustOff** [comment]
Unfortunately, I can't say that https://github.com/MoonchildProductions/UXP/commit/3424afccaebc71c4acd4fa9eadf519c408c5965b resolved the issue completely. Now the test did not always fail, as it was before, but at least in 30% of cases the page load still never ends. At the same time, in my case in Firefox, after the first good build, the problem goes away.

**Comment by wolfbeast** [comment]
I verified the async test and it succeeds every single time with this patch in.

**Comment by JustOff** [comment]
I have a problem after reloading the page.

**Comment by wolfbeast** [comment]
I've reloaded the page like 30 times now, mixed reload and bypass cache reload, and it succeeds every time.

**Comment by THEtomaso** [comment]
I just gave Pale Moon v28.6.0a1 (2019-04-27) a try, and I can confirm that Pale Moon passes the "ff_async_bug" with flying colours now, every time! :)
But unfortunately, like JustOff speculated before; this doesn't help with the original issue at all.
Pale Moon still has a major problem loading script heavy pages (like the one that I refered to in the first post), although such pages loads just fine in other browsers.
..so, I guess that the issue should be reopened.

In the Bugzilla reports that's already been refered to in previous posts here, there are links to related issues.. some of which contains different tests.
But instead of posting a bunch of possibly completely unrelated Mozilla bugs here (which I know that you guys wouldn't like), I'd rather run a series of thorough Mozregression sessions, when I find some time.
Then, if I get some conclusive results, I'll give you a heads up!

The only thing that worries me, is that when I ran Mozregression before, I weren't able to find a single Firefox version which showed the same symptoms as Pale Moon, Basilisk and SeaMonkey, when loading script heavy pages.
Therefore, I guess that feature-specific JavaScript tests, posted by developers, are the only things that I can work against, when troubleshooting this issue.

**Comment by THEtomaso** [comment]
At least, regarding async-related issues, I was able to confirm that Pale Moon indeed is affected by this bug (refered to in Bugzilla report #692754):

**Alerts break script execution semantics**:
https://bugzilla.mozilla.org/show_bug.cgi?id=637264
The 4th post includes links, which confirms that this is a specified HTML standard (Pale Moon really struggles to open those links too, btw).

--

Test:
http://dolske.net/mozilla/tests/prompt/script_load_order.html

--

Mozregression results:
* Last bad: Firefox v49.0a1 (2016-05-24)
* First good: Firefox v49.0a1 (2016-05-25)

Firefox v49.0a1 (2016-05-25) changelog:
http://forums.mozillazine.org/viewtopic.php?f=23&t=3007019
(Sorry for not being able to pin down the exact pushlog)

**Comment by wolfbeast** [comment]
Anything in the Firefox 49 range is already part of UXP, so that makes no sense to be a problem.

**Comment by wolfbeast** [comment]
Also, the americanexpress page is just bad. bad bad bad bad bad bad
You can't tell me that other browsers do NOT have issues with it because that simple article is loading no less than 10MB of javascript, all of which has to be interpreted and compiled. 43 individual scripts, many if not all minified code. 10.3 MB.... How much JS is that?
![aex1](https://user-images.githubusercontent.com/3359132/56868246-211b1000-69f0-11e9-8980-a16635575692.png)

**Comment by THEtomaso** [comment]
> Anything in the Firefox 49 range is already part of UXP, so that makes no sense to be a problem.

Then perhaps there's a regression in Pale Moon, because as you can see, it certainly fails that "script_load_order" test.
The "Last bad" and "First good" FF range checks out, so I'll look into finding the proper changelog then.

**Comment by wolfbeast** [comment]
Scroll up to where it states that it went as far as it could using nightlies. These builds are too old so no artifact builds exist on the mozilla servers. the nightly range is all you'll get (taskcluster mode will fail)

**Comment by THEtomaso** [comment]
Think I finally got my head around how to locate the pushlog.
Here it is:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=829d3be6ba648b838ee1953fdfa1a477dace752f&tochange=d6d4e8417d2fd71fdf47c319b7a217f6ace9d5a5

**Comment by wolfbeast** [comment]
That would likely be: https://bugzilla.mozilla.org/show_bug.cgi?id=1266611
That just addresses the fact that you can have multiple tab-modal prompts at the moment and that is why the order is reversed but that does NOT fix any script loading issue

**Comment by THEtomaso** [comment]
It's quite an coincidence though..
The "last bad" / "first good" FF builds which fails/passes the "script_load_order" test, also happens to be the exact same builds which marks a noticable change in performance, when loading that American Express page.

**Comment by wolfbeast** [comment]
Well I'm open to hear what other bug in that range would influence script performance.

**Comment by wolfbeast** [comment]
I've fixed the tab-modal ordering front-end code in [cd296c598], and I'm asking people at this point that if there are very specific things with script loading that don't work, to please open a new issue with a detailed description, OR take it to the forum to first pin down what exactly the problem is. As for blocking individual scripts on the example page: that will solve the load issue because it -breaks- the script dependencies and makes parsing of the largest chunks of js simply abort, reducing compiler load.

**Comment by THEtomaso** [comment]
> https://github.com/MoonchildProductions/UXP/commit/cd296c598a587b58a0e2a579c9be5aa255669829

Since I've discovered an issue which is directly related this commit, I figure that it's OK to make a note of it here.
If you run the test, you'll see that the fix doesn't solve the issue properly, becuse the page never finnish loading:
http://dolske.net/mozilla/tests/prompt/script_load_order.html

**Comment by wolfbeast** [comment]
So what part of my previous reply did you not understand? Or did you just choose to ignore it?

**Comment by mattatobin** [comment]
Backed out because it is causing a number of issues all over the platform and the web.

See: https://forum.palemoon.org/viewtopic.php?f=3&t=22586

**Comment by wolfbeast** [comment]
Potentially this needs to be traced back to the unspecified bug that first exhibited the wrong behavior (where things were changed for e10s) and back that out to solve these corner cases.

**Comment by wolfbeast** [comment]
I tested all the way back to v11.0 to see if any of them gave a good result on http://kidkarolis.github.com/ff_async_bug/ -- none of them do. I don't think that far back even supports async scripts, so this is obviously something else.

**Comment by wolfbeast** [comment]
I was wrong.. async was introduced in 3.6

INFO: Got as far as we can go bisecting nightlies...
INFO: Last good revision: 07e74f1f0561 (2009-11-09)
INFO: First bad revision: f4ef40336cc6 (2009-11-10)
INFO: Pushlog:
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=07e74f1f0561&tochange=f4ef40336cc6

Likely culprit: Robert O'Callahan — Bug 498340. Block script execution during the entire paint phase including when we call WillPaint to flush notifications. We don't want script to run and disturb (directly or indirectly) the widget hierarchy, because doing that during BeginPaint/EndPaint can confuse Windows. Other platforms might also be adversely affected. r=bz

**Comment by wolfbeast** [comment]
Ah no. the culprit is Jonas Sicking — Bug 503481: Implement async attribute

So it's never worked in FF either.

**Comment by wolfbeast** [comment]
I don't think this can be fixed. The problem with the test is that it runs a script async that throws up a dialog. This likely blows away the document depending on whether DOMContenLoaded has already been fired (hence the timing-related intermittent nature).
