### ISSUE TITLE
 Improve dead compartment collection

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1057]
https://bugzilla.mozilla.org/show_bug.cgi?id=1318384

Makes Garbage Collection more efficient and patches can be directly applied to UXP. 

Tested this with New Moon build together with Allow incremental GC when keepAtoms is set and it resulted improvements in ubench benchmark especially globalArrayBuffer part of benchmark.

**Comment by mattatobin** [comment]
But does it make any difference in the real world?

**Comment by wolfbeast** [comment]
> But does it make any difference in the real world?

Reducing the height of the GC spikes will most definitely impact the real world, as in reducing small pauses in page scrolling and animation due to GC.
@win7-7 can you please pour this into a PR for merging?

**Comment by mattatobin** [comment]
Is this dependent on the unsafe suggestion? Also, what about what doesn't directly apply.

ALSO, why wasn't an issue filed for this before any PR was created?

**Comment by win7-7** [comment]
No it is not dependent on other GC change. I have reverted that change in branch before doing pull request.

**Comment by mattatobin** [comment]
According to the PR you didn't revert it. Please force push a clean PR and word of advice? Don't use the same branch for different issues.

**Comment by win7-7** [comment]
New pull request done.

**Comment by mattatobin** [comment]
The hell did you do?! Change the line endings? Do it again.

**Comment by win7-7** [comment]
Does branch https://github.com/win7-7/UXP/commits/Improve-dead-compartment-collection look good?

I changed line endings to unix-style (LF) in Notepad++ and uploaded new versions of files to github branch.

If all look good I can do new pull request.

**Comment by mattatobin** [comment]
Yes, it compares properly. File your PR. Though, of course I can't attest to functionally correct.

**Comment by win7-7** [comment]
New pull request done.
