### ISSUE TITLE
Logical error in dialog "Add Security Exception"

### ISSUE THREAD

**Issue by CarstenGrohmann** [MoonchildProductions/UXP#1064]
Hi Pale Moon Developers,

today I failed to add a security exception for a certificate self-signed by a tape library. 

The warning dialog "This Connection Is Untrusted" is shown:
![image](https://user-images.githubusercontent.com/4849907/56889794-b6adb280-6a77-11e9-8fdf-a7a7df241c64.png)

After I click the "Add Exception" the next dialog is shown and stating the certificate would be **valid**.  That's wrong - please improve the certificate check!

![image](https://user-images.githubusercontent.com/4849907/56889762-98e04d80-6a77-11e9-9f8b-49498eb223f2.png)

Even `wget ` is complaining about this certificate:
```
# wget https://my_tape_library/lmc.jnlp
--2019-04-29 10:58:45--  https://my_tape_library/lmc.jnlp
Resolving my_tape_library (my_tape_library)... 192.168.14.214
Connecting to my_tape_library (my_tape_library)|192.168.14.214|:443... connected.
ERROR: cannot verify my_tape_library's certificate, issued by ‘/CN=Tape Library/OU=a59e7c97-7823-4f66-85ab-cf2b51ea8243/OU=TapeAutomation/O=SomeCompany/L=SomeWhere/ST=SomeState/C=US’:
  Self-signed certificate encountered.
    ERROR: certificate common name ‘Tape Library’ doesn't match requested host name ‘my_tape_library’.
To connect to my_tape_library insecurely, use `--no-check-certificate'.
```

Installed Versions:

- CentOS Linux release 7.5.1804 (Core)
- palemoon-28.4.1-1.x86_64

Regards,
Carsten

**Comment by kn-yami** [comment]
I can definitely confirm this. This happened to me a few dozen times. It is very annoying because there is no way to fix this other than waiting a few days.
https://freenode.logbot.info/palemoon/20190101#c1899037:
```
23:28 <kn-yami> For some unknown reason Pale Moon will sometimes refuse to accept a self-sighed cert.
23:29 <kn-yami> Once this happens it will persist for several days.
23:29 <kn-yami> And after that period of time you will be able to add the exception.
```

**Comment by wolfbeast** [comment]
Unfortunately without having any idea of the certificate involved (and things being blanked out), it's really not possible to even guess what is going on here. I understand the need to protect certain assets but it's essential information to understand what is going on.

**Comment by kn-yami** [comment]
In my case this happened each time I was upgrading firmware on a switch. When the firmware is upgraded the device will regenerate the certificate. When you connect to the device for the first time after the upgrade this will happen.

**Comment by wolfbeast** [comment]
Ah, so it's the problem with there being a previous valid self-signed cert in the certificate store for the same address that already had an exception for it.

**Comment by CarstenGrohmann** [comment]
I can share the certificate (`openssl s_client -connect <host>:443 -showcerts
`) and the original screenshots through a non-public channel like a security email address.

Do you have such a channel?

**Comment by CarstenGrohmann** [comment]
This issue also occurs if I don't store the self-signed certificate permanently and after the browser has been restarted.

Looks like parts of the certificate are still stored permanently and survive the browser restart - even if I choose not to store this certificate.

Steps to reproduce:
1. delete the Pale Moon profile `rm -rf .moonchild\ productions/`
1. start Pale Moon
1. open URL with (strange) self-signed certificate
1. add exception, but don't select "Permanenly store this exception"
1. use the website
1. restart the Pale Moon and enter the same URL
1. Click "Add Exception ..." 
1. The "Add Exception@XXX" dialog is opening and shows "This site provides valid, verified identification.  There is no need to add an exception."

**Comment by wolfbeast** [comment]
> Do you have such a channel?

Yes, via e-mail to: security-issues at palemoon dot org -- however I don't necessarily think it might be needed. We've already found a likely cause which is storage of the invalid certificate in the trust store even if no exception is entered. I'm thinking it might be entered as an authority in the certificate database because it is self-signed (meaning the cert acts as its own CA)

**Comment by CarstenGrohmann** [comment]
May this observation helps:
The certificate is listed in the "Certificate Manager" in tab "Servers" with lifetime "Temporary" during the first run (step 5) only.
After the browser restart the certificate isn't listed in any "Certificate Manager" tabs - not in "Servers" and not in "Authorities".

**Comment by wolfbeast** [comment]
I have a PR now with some code changes that should fix this logic error. Unfortunately I don't have a test setup handy where I can verify that this works as-intended (which is why I created a PR instead of merging directly). If this "tape archive" still has this problem and is publicly accessible for testing that would be great (mail me the address in that case, please) or otherwise if someone can make a webserver setup with self-signed for testing, that would be great.

**Comment by CarstenGrohmann** [comment]
I neither can't provide public access nor a web server with a self-signed certificate. But I test with a development build for CentOS 7.
Or is it posible to test the change with a public release and replace a js/jar file after the installation?

**Comment by wolfbeast** [comment]
it seems self-signed wasn't the only problem there. To reproduce it'd have to be self-signed as well as for an incorrect host.
I unfortunately don't have a Linux build environment available to build this for you. if you could build from source from the correct branch and test, that would be awesome :) If not, I'll just merge it into master and we can get new unstable channel builds to test, however I'd prefer this PR to be known-good before merging to keep our commits clean.

**Comment by CarstenGrohmann** [comment]
Ok, I build and test the fixed branch. I don't have access to my CentOS box for the next four weeks. You can expect my test results end of September.

**Comment by wolfbeast** [comment]
I'm not waiting for that.

**Comment by CarstenGrohmann** [comment]
Our tape library got a firmware update in August. Thereby I can't reproduce the reported issue using palemoon-28.4.1-1.x86_64. With 28.4.1 PM is complaining about the certificate but accpect the exception.

Today I've certexception-work branch to test the change. The certificates check is hanging for more than 10 minutes now: 
![grafik](https://user-images.githubusercontent.com/4849907/65324749-68778800-dbad-11e9-9043-a6a2669f6ce4.png)

**Comment by wolfbeast** [comment]
PR has been updated and tested on Windows. Please verify to merge.

**Comment by wolfbeast** [comment]
Merged and spinning new unstables today. Please let me know if this:
- Works on other platforms than Windows (it should)
- Solves this particular issue

**Comment by CarstenGrohmann** [comment]
Today I've compiled and tested this change with the current master branch on CentOS7 successfully. 

The initial problem has disappeared (probably due to a firmware update in August). It can also no longer be reproduced with an old version of PM.

The hanging dialog (as reported on September 20) works reliably now.

Thank you for your support.
Carsten
