### ISSUE TITLE
Focus address bar in new tab of private window in Basilisk

### ISSUE THREAD

**Issue by J0J0** [MoonchildProductions/UXP#1066]
Upon opening a new tab in a private window, the address bar does not get the keyboard focus.

Expected: focus on address bar.
Affected: at least **Basilisk** built from 34939b2d177be9d397e17d6a16837dd60e6b3906 and 871b926f635836d6a187534f6a6ad5b2bb30b27d
(Works as expected in Firefox ESR 52.9.0)

**Comment by kn-yami** [comment]
Works for me on the current release version.

**Comment by adeshkp** [comment]
Works here too, latest Pale Moon on Linux.

@J0J0 Are you using any tab related extensions, custom theme etc. This issue tracker is a place for actual bugs which developers can work on. Please take this to the Pale Moon forum for discussion.

**Comment by J0J0** [comment]
Ah, i didn't remember that this repo also contains Pale Moon. Sorry. I updated the issue to mention that i'm concerned with Basilisk.

@adeshkp I was in freenode/#palemoon yesterday and was asked to open this issue. :)

And to clarify: it also happens on a clean profile without any addons.

**Comment by adeshkp** [comment]
Yes, confirmed. First tab when opening private window gets the focus in address box, but opening new tab in existing private window has the issue.

**Comment by JustOff** [comment]
I guess this is due to this change: https://github.com/MoonchildProductions/UXP/commit/fb84e0f3226f1b9233aa2a6bfc55c38110694ffd#diff-3304ba45f9f8936e0ac0b6b715ea5582.

**Comment by wolfbeast** [comment]
Yup, specifically it's https://github.com/MoonchildProductions/UXP/commit/fb84e0f3226f1b9233aa2a6bfc55c38110694ffd#diff-3304ba45f9f8936e0ac0b6b715ea5582L38 -- the getter for `BROWSER_NEW_TAB_URL` specifically caters to private browsing windows, and just using `about:newtab` instead does not. Not sure why that was changed, to be honest.

**Comment by mattatobin** [comment]
Misunderstanding of what I ported. It was early days for Basilisk. Sorry about that.
