### ISSUE TITLE
Restore a getBoolPref global shim in utilityOverlay.js for Extension compatibility 

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1082]
In Issue #988 `nsIPrefBranch.get*Pref ` supports providing a default value
and in Issue #989 we removed all the `getPref` helper functions all over the codebase.

This issue will restore `getBoolPref()` in `utilityOverlay.js` for Phoenix-based browsers as a shim to satisfy extension compatibility.

It will emit a deprecation warning noting that this shim will be removed in future release.

----

Example:
```
Timestamp: 5/9/2019 12:57:39 PM
Error: DEPRECATION WARNING: getBoolPref is deprecated and will be removed in a future release. You should use Services.pref.getBoolPref (Services.jsm).
You may find more details about this deprecation at: https://github.com/MoonchildProductions/UXP/issues/989
Callstack:
Scratchpad 12 null
chrome://scratchpad/content/scratchpad.js 389 SP_evalInChromeSandbox
chrome://scratchpad/content/scratchpad.js 412 SP_evaluateForContext
chrome://scratchpad/content/scratchpad.js 424 SP_execute
chrome://scratchpad/content/scratchpad.js 434 SP_run
chrome://scratchpad/content/scratchpad.xul 1 oncommand

Source File: resource://gre/modules/Deprecated.jsm
Line: 85
```

**Comment by mattatobin** [comment]
Leaving open but status fixed for uplift to relbranches.

**Comment by wolfbeast** [comment]
Uplifted to Pale Moon release branch in 440b167d621beca26ce09de8afac82e3a0fb2393
