### ISSUE TITLE
Add null check for URL Bar in the writePlaceholder() method

### ISSUE THREAD

**Issue by FranklinDM** [MoonchildProductions/UXP#1084]
As [reported](https://forum.palemoon.org/viewtopic.php?f=29&t=22072&p=166725) on the forum, the browser interface (including places and others) becomes broken when the URL bar is removed.

![issue new](https://user-images.githubusercontent.com/11641537/57523545-d4bcc200-7357-11e9-85a7-b0ce505c0f0c.PNG)

The culprit seems to be a missing null check for `gURLBar` at the beginning of the writePlaceholder() method in [line 414](http://xref.palemoon.org/uxp-trunk/source/application/palemoon/base/content/browser.js#414) of `browser.js`.

**Comment by FranklinDM** [comment]
Please add the `App: Pale Moon` tag as Basilisk is not affected because the URL bar there is not removable by default.

**Comment by mattatobin** [comment]
The problem is with this that the placeholder will never be set until the next time the location bar is back on the toolbar.

**Comment by mattatobin** [comment]
Okay, I worked it out.. @FranklinDM do you want me to close your PR and just do it.. Or do you want to do it..

Either way in `browser.js` in function `BrowserToolboxCustomizeDone` after `gURLBar = document.getElementById("urlbar");` add:
```
    if (gURLBar) {
      gURLBarSettings.writePlaceholder();
    }
```

**Comment by FranklinDM** [comment]
I'll update the PR in a moment with the requested changes.

**Comment by mattatobin** [comment]
Re-opening for Uplift to Pale Moon RelBranch

**Comment by wolfbeast** [comment]
Uplifted in 0b16661fd55ddff866f77f373583431569ba6741
