### ISSUE TITLE
Implement ES2019 String.prototype.trimStart and trimEnd

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1089]
This is considered a "major feature" for ES2019/ES10.
Since string trimming is easy, no reason to not implement this right away, also considering we already have `trimLeft` and `trimRight` (which do the same thing)

**Comment by mattatobin** [comment]
I suggest renaming *Left and *Right to *Start and *End and the aliasing the old ones to the new ones.
