### ISSUE TITLE
Uplift the proxy bypass protection flag

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1093]
There are a few changes worthy of uplift that were introduced in the `--enable-proxy-bypass-protection` compile time option. These patches are to protect users from known proxy leaks that would reveal their actual IP outside of the assigned socks5 proxy IP. As the one issue directly targets GNU/Linux it will be nice for UXP to have.

The relevant patches are:
* Upload-file-dialog proxy bypass in Linux [1433357](https://bugzilla.mozilla.org/show_bug.cgi?id=1433357)
* Disallow access to GIO supported protocols (SMB etc.) when proxy is on [1433507](https://bugzilla.mozilla.org/show_bug.cgi?id=1433507)
* Ensure network tickler is not compiled when flag is set [1432907](https://bugzilla.mozilla.org/show_bug.cgi?id=1432907)

Commits have been applied without issue, PR to follow.

**Comment by mattatobin** [comment]
You need to let us respond BEFORE you submit pull requests.

**Comment by g4jc** [comment]
- This would be useful as an optional for applications that wish to override the system proxy and enforce the socks5 option.

- Commits can be restyled, but I was following with the original commit messages for clarity. (e.g. it could be reworded as "Issue 1093 - Add enable-proxy-bypass-protection compile time option"). Let me know what works best.

- I believe the current [old.configure](https://github.com/MoonchildProductions/UXP/pull/1094/commits/21e2815acb09d41152af725d76720d16ec0535e9#diff-09d108e071e099a6a43ddb14d7ff1bd4) option in the commit matches the same syntax as we did in [nsuserinfo](https://github.com/MoonchildProductions/UXP/commit/4f59678acd9b48284b6b23b3d6863a33739dfdff#diff-09d108e071e099a6a43ddb14d7ff1bd4)?

**Comment by mattatobin** [comment]
I missed the old.configure entry sorry.

**Comment by wolfbeast** [comment]
Closing this as a `wontfix`.

1. This breaks local network access in file I/O, which should be controlled by the O.S. in common dialogs. Whether you are using a SOCKS proxy to access the web or not should never influence your local file access. definitely busting and undesired behavior.
2. The network tickler is only used on mobile which we don't support any longer.
