### ISSUE TITLE
Add a pref for arrowpanel animations on Linux

### ISSUE THREAD

**Issue by mrnhmath** [MoonchildProductions/UXP#1098]
Backport of [1546542](https://bugzilla.mozilla.org/show_bug.cgi?id=1546542). As the issues related to arrowpanel animations on Linux seems to have vanished even by our fork point, a pref to toggle them makes testing easier. Should also work on Windows.

**Comment by wolfbeast** [comment]
This is front-end code. For which application is this issue?

**Comment by Lootyhoof** [comment]
This was discussed here: https://freenode.logbot.info/palemoon/20190604#c2229345

tl;dr We don't want this.

**Comment by mrnhmath** [comment]
@wolfbeast This would be applicable to both Pale Moon and Basilisk. 

@Lootyhoof Got it. Maybe we can revisit this once older versions of GTK+ 3 are no longer relevant.

**Comment by wolfbeast** [comment]
Right, I was involved there. Not sure why this wasn't closed at that time. sorry.
