### ISSUE TITLE
Web-Compat: Disable <meta http-equiv=set-cookie>

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1102]
This particular code is more or less a follow up to [Implement "cookie-averse document objects". ](https://github.com/MoonchildProductions/UXP/commit/85083fce2da7a270e324fd951b7f3d03a50aef1b#diff-df2e2c6060983ece1c6e0999fdb66025) which we already implemented. Since `<meta http-equiv=set-cookie>` is a non-standard way of setting cookies and has been removed from web standards, we can disable it and stuff it behind a pref. This was done in [m-c 1457503](https://bugzilla.mozilla.org/show_bug.cgi?id=1457503), but uses their `StaticPrefList.h` rather than our `modules/libpref/init/all.js`.

Preliminarily, this looks pretty easy to implement, and it doesn't fully remove the code if someone desperately needs it (which is highly unlikely since it's non-standard), so they can just flip the pref.

Patch: https://paste.debian.net/plainh/9547a6d2
_Note: Need to make sure my pref and true/false parameters are correct as the implementation does not use StaticPrefList. So far it is build passing._

**Comment by wolfbeast** [comment]
This isn't in ESR-60 but hopefully by now the world will have adjusted to stop using these. The pref is a good idea so we can easily recover if things go unexpectedly badly on release.

Please avoid static preference definitions at all costs in our tree. Always use the normal greprefs/app prefs mechanism.

**Comment by g4jc** [comment]
Confirmed working on http://w3c-test.org/cookies/meta-blocked.html.
Pref is defaulted to: `dom.metaElement.setCookie.allowed;false`

**Comment by g4jc** [comment]
Pref name changed to `dom.meta-set-cookie.enabled` [per request](https://github.com/MoonchildProductions/UXP/pull/1114#issuecomment-495708040).
