### ISSUE TITLE
Clicking a link with a target should open only 1 tab

### ISSUE THREAD

**Issue by FranklinDM** [MoonchildProductions/UXP#1104]
Split from #971.
>If you try my test case, clicking the link (with a target) multiple times will spawn multiple tabs in Pale Moon while clicking the link in Basilisk will open only one tab and subsequent clicks will trigger the load in the same open tab. This is regardless of the mentioned preference (set to default of 3 in both the browsers).

Attached test case: [issue971-inbrowser.zip](https://github.com/MoonchildProductions/UXP/files/3210397/issue971-inbrowser.zip)

**Comment by adeshkp** [comment]
I confirm that the proposed PR satisfies my test case. Good to merge functionality-wise.
