### ISSUE TITLE
Spread syntax is not supported in Palemoon 28.5.0

### ISSUE THREAD

**Issue by linux40** [MoonchildProductions/UXP#1106]
[This document ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) shows what is spread syntax.

And following shows log in scratchpad:
```js
var obj = {a: 1}

{...obj, b: 2}
/*
Exception: SyntaxError: expected expression, got '...'
@Scratchpad/1:12
*/
```

**Comment by adisib** [comment]
There is already an issue open for this here (There is a bounty available for it):
https://github.com/MoonchildProductions/UXP/issues/802
