### ISSUE TITLE
Support exporting symbols for ES6 classes in Mozilla JSMs

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/UXP#1107]
I have a js file in my extension which looks like this:

```
const EXPORTED_SYMBOLS = [
  "Fetch_Error", /* exported Fetch_Error */
];

/** Failed to fetch url */
class Fetch_Error extends Error
{
  /** constructor
   *
   * @param {Event} event - event or null
   * @param {string} url - url being fetched
   */
  constructor(event, url)
  {
    super("Cannot fetch\n" + url);
    this.event = event;
    this.url = url;
    this.type = this.constructor.name;
  }
}
```

The class works fine if I put the code where it's actually used. However, in this form, when I do Component.Utils.import, I get nothing imported from this file.

It'd be nice if I could export classes using the existing export system

**Comment by mattatobin** [comment]
The Mozilla method doesn't and likely won't ever support classes. This is the difference between chrome and content code support.

The ES6 class support is an existing issue.. I would argue that they are mutually exclusive.

**Comment by wolfbeast** [comment]
Look at how Mozilla JSMs export symbols and do it the same way using one of the basic precepts in JavaScript: prototyping. Classes are only sugar on top of that and there is 0 reason to cater to sugar for sugar when existing methods already work.
