### ISSUE TITLE
[PALEMOON] "Page Info" - "Permissions"

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#112]
"Page Info" does not show correctly (falls into the background).

**Comment by mattatobin** [comment]
Is that all?

**Comment by janekptacijarabaci** [comment]
You are welcome.

> Since we are all moving at an accelerated pace feel free to omit creating issues for now just mention issue #57 on pull requests for fixing Pale Moon.

OK.

> Is that all to resolve this?

Yes. I don't know about any problem with `Page Info` - `Permissions`. Currently.

**Comment by janekptacijarabaci** [comment]
Merged: #116
