### ISSUE TITLE
Remove Firefox Developer Edition code

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1124]
Basilisk isn't Firefox and Firefox Developer Edition features at our level were barely implemented let alone useful considering we don't do Add-on Signing or other Modern Mozilla-y non-sense.

**Comment by wolfbeast** [comment]
@mattatobin with your more limited time available, do you think it's a realistic goal to keep this at the 28.7.0 release target? If not, do you still think you'll be ripping this out soon-ish or should it be re-assigned to someone else?

**Comment by mattatobin** [comment]
It should be simple to do. There shouldn't be much to kill.

**Comment by wolfbeast** [comment]
@mattatobin What do you think? Did I miss anything?

**Comment by mattatobin** [comment]
Looks like you got all of it to me.

**Comment by wolfbeast** [comment]
Great!. Closing.
