### ISSUE TITLE
Add application executable location to the about:support page

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#1132]
Spotted this on ghacks: [Bug 1555366](https://bugzilla.mozilla.org/show_bug.cgi?id=1555366). The patch is pretty easy to port, and it makes it easier for the user to find where the application is being run from, especially if they have multiple installations that they might run on the same machine.

I can PR this.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by mattatobin** [comment]
Thank you @JustOff
