### ISSUE TITLE
Incorrectly receives json document

### ISSUE THREAD

**Issue by em92** [MoonchildProductions/UXP#1138]
PaleMoon 28.5.2 on Debian 9

In about:config I have `devtools.jsonview.enabled` with value `true`.

I visit this: http://qlsb.eugenemolotov.ru/rawserverlist
It always shows something like this:
```
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 69376 of the JSON data
```

Clicked on tab RAW data. I get this: https://pastebin.com/FmGF3kF4

Yes, RAW data shows bad json, but server does not return bad json. Checked using
```
curl http://qlsb.eugenemolotov.ru/rawserverlist | python -m json.tool
```

Also I am maintainer of given server. So if there is problem on my side, I have to fix it.

**Comment by wolfbeast** [comment]
Looks like this is a bug in the devtools json parser.

**Comment by wolfbeast** [comment]
IIRC there is an extension for displaying pretty-printed json which you can use in the interim.

**Comment by JustOff** [comment]
It seems this issue can be fixed by backporting [Bug #1367894](https://bugzilla.mozilla.org/show_bug.cgi?id=1367894) (+ follow-ups).

Unfortunately at the moment I don't have enough time to work it out.

**Comment by wolfbeast** [comment]
Making this bounty material as an incentive for people to get involved with the project.
Difficulty: medium. Anyone with some knowledge of the languages involved can probably do this.

**Comment by kn-yami** [comment]
Is this issue reserved only for new contributors?

**Comment by wolfbeast** [comment]
Nope. anyone can take it if they want.

**Comment by kn-yami** [comment]
I see. May I take it?

**Comment by em92** [comment]
Sure!

**Comment by wolfbeast** [comment]
Assigned to @kn-yami

**Comment by wolfbeast** [comment]
When this is verified fixed, we should probably enable the json pretty-printer by default.

**Comment by wolfbeast** [comment]
@kn-yami Can you give a rough estimate how easy/difficult this was and how much time you've spent on it?

**Comment by kn-yami** [comment]
I think that the difficulty was medium (on a three-point "easy-medium-hard" scale). As for the time that I spend on this I estimate that it was around 4-5 hours (including time spent on building UXP "from scratch" and testing the implementation).

**Comment by wolfbeast** [comment]
Thanks. Can you please e-mail or PM me your PayPal address for payment of the bounty?

**Comment by kn-yami** [comment]
PM sent.

-----
Now that I think about it, you may have wanted to get my address after this has been verified fixed. If that the case then I am sorry for sending it to early.

**Comment by wolfbeast** [comment]
No, I asked for it, didn't I? It still needs verification before you'll get paid, of course.

**Comment by wolfbeast** [comment]
Current unstables have this patch in -- if people could test with various json documents that would be great (flip the preference for testing).

**Comment by wolfbeast** [comment]
@em92 @JustOff could you please test the unstable with various json documents with the pref flipped on so this can be verified fixed?

**Comment by em92** [comment]
It is not fixed. Tested with:
http://linux.palemoon.org/download/unstable/
Size: 46.54 MB
SHA-256 checksum: abb98e5953d9a049d0da51a54786e2cd0de2f19aee70c2a1c8ceecbd790282e7
Document is: http://qlsb.eugenemolotov.ru/rawserverlist

**Comment by JustOff** [comment]
@em92, it seems the latest linux unstable does not include json parser fix yet.

@wolfbeast, both http://qlsb.eugenemolotov.ru/rawserverlist (~384Kb) and https://bug1122483.bmoattachments.org/attachment.cgi?id=8656886 (~2Mb) json documents render just fine using the windows unstable build 20190809090310. Unfortunately, I don't know where to get more examples to check.

**Comment by wolfbeast** [comment]
Ah apologies I overlooked the fact you're using Linux. I don't build those binaries; @trav90 could you please spin some unstable Linux binaries off of master?

**Comment by trav90** [comment]
Apologies for just now seeing this (I have not been online the past several days). I will push out an updated Linux build tonight (approx. 12 hours from now).

**Comment by trav90** [comment]
A new Linux unstable build containing this fix has just been published.

**Comment by em92** [comment]
Checked. It is fixed. gj @kn-yami

**Comment by wolfbeast** [comment]
Bounty paid.
