### ISSUE TITLE
Pale Moon registers its self as default application for PDF

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1140]
This is a regression in UXP-based Pale Moon because we ported the Basilisk nsis code as a shortcut.

Removing the following lines should do the trick:
`application/palemoon/installer/windows/nsis/shared.nsh` - [325](http://xref.palemoon.org/uxp-trunk/source/application/palemoon/installer/windows/nsis/shared.nsh#325) and [329](http://xref.palemoon.org/uxp-trunk/source/application/palemoon/installer/windows/nsis/shared.nsh#329)
`application/palemoon/installer/windows/nsis/uninstaller.nsi` - [300](http://xref.palemoon.org/uxp-trunk/source/application/palemoon/installer/windows/nsis/uninstaller.nsi#300)

**Comment by wolfbeast** [comment]
Resolved by e4b2fa17baea1d35d80de19ffb90d9ba2a1033f8
