### ISSUE TITLE
Add mousewheel overall scroll multiplier UI

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1147]
It's probably a good idea to include a UI pref for `mousewheel.default.delta_multiplier_y` to the scrolling preferences pane so the user can control overall scroll speed without tweaking the individual metrics and behavior.

Default is 100 (%), range should probably be 20-400

**Comment by wolfbeast** [comment]
Sane range as indicated, limiting the input field to 1-999 for input ease on a number field.

**Comment by wolfbeast** [comment]
@JustOff please take note of the added string.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by mattatobin** [comment]
Thank you @JustOff
