### ISSUE TITLE
WhatsApp Web not working on Pale Moon 28.6.0

### ISSUE THREAD

**Issue by CharlesDWard** [MoonchildProductions/UXP#1152]
When visiting: "https://web.whatsapp.com/" on  Pale Moon 28.6.0

I get the following message:

"WhatsApp works with Google Chrome 49+. To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera."

**Comment by wolfbeast** [comment]
This is a change on Google's side making our previous SSUAO no longer functional.
As a workaround, change the user agent in `general.useragent.override.whatsapp.com` to a later Chrome version one.
