### ISSUE TITLE
site doesn't show content because of notification

### ISSUE THREAD

**Issue by RiNoWaR** [MoonchildProductions/UXP#1153]
after sign in in site coub.com
site doesn't show content because of notification
when you select a communities
example :https://coub.com/community/anime

![coub_test](https://user-images.githubusercontent.com/33617286/60537586-eac47e80-9d19-11e9-8510-dd6d19e5ec65.jpg)

**Comment by wolfbeast** [comment]
Content seems to load fine -- not logged in because I don't have an account.
Likely not a browser issue; please contact the site owners and/or discuss on the forum.

**Comment by RiNoWaR** [comment]
wihout login in contents shown, yes.
but when you login, it stop to work.
in opera, when you login, site ask to allow send notification and after you say "yes' it work fine

**Comment by wolfbeast** [comment]
Web notifications are fully supported in Pale Moon, unless of course you have disabled them yourself. It will ask you similar to what Opera does.

**Comment by RiNoWaR** [comment]
can you guide me please where i can check this options?
how can i re enable these options?

**Comment by adeshkp** [comment]
> can you guide me please where i can check this options?

In about:config, `dom.webnotifications.enabled` should be `true`.

**Comment by RiNoWaR** [comment]
thanks. i checked it, is enabled
but site doesn't show content and site don't ask about notification
:(

**Comment by RiNoWaR** [comment]
> 
> 
> Content seems to load fine -- not logged in because I don't have an account.
> Likely not a browser issue; please contact the site owners and/or discuss on the forum.

seems you was right, that's was a site troubles

thanks for help all

**Comment by mattatobin** [comment]
In the future please don't close issues yourself and indeed report stuff to the Pale Moon forum not this issue tracker. It is not for you.
