### ISSUE TITLE
Location Bar Preferences Checkboxes

### ISSUE THREAD

**Issue by RealityRipple** [MoonchildProductions/UXP#1156]
The History, Bookmarks, and Open tabs checkboxes in the Location Bar Privacy Preferences behave incorrectly. If you uncheck all of them and then check any one of the three, all three will become checked. Tested with a blank profile, with and without saving/closing the Preferences between unchecking and checking. Possibly a bitwise flag issue, if I had to guess?

**Comment by wolfbeast** [comment]
PR #1200 fixes this behavioral issue in a normal pref-apply situation. It's unknown whether it still toggles the `autocomplete.enabled` pref properly when instantApply is enabled (e.g. on Mac).

**Comment by Ascrod** [comment]
This issue doesn't manifest at all on the Linux release build, which also uses `instantApply` by default. I can build from trunk today and test on Linux as well as Windows with `instantApply` enabled.

**Comment by Ascrod** [comment]
LGTM in both cases. `browser.urlbar.suggest.*` and `browser.urlbar.autocomplete.enabled` appear to be set properly.

**Comment by wolfbeast** [comment]
Fantastic! Just superfluous introduced code then.
