### ISSUE TITLE
"LocalStorage" and "Cookies and Data - Keep Until I Close Pale Moon"

### ISSUE THREAD

**Issue by RealityRipple** [MoonchildProductions/UXP#1157]
I'm working on a site that uses LocalStorage and recently changed the layout of the data, only to discover that the storage data kept getting set back to the way it was before, even after erasing webappsstore.sqlite. After a lot of testing and disabling extensions and trying new profiles and different sites, I tracked the problem down to the custom history settings. If a site has no LocalStorage, the "Keep until: I close Pale Moon" option behaves as expected, resetting the LocalStorage to nothing after the browser closes. If, however, the LocalStorage has already been set, it still resets - back to whatever it was set to before. Essentially, instead of "don't keep", "don't save" was the implemented action, so erasures aren't saved either.

I did manage to get it to play nicely by adding the subdomain to the exceptions list (the parent domain was already in the list but didn't apply to the subdomain? maybe because it's set to first-party only?), so that's probably an easy way to test - add "s.codepen.io" to the exception list, visit https://codepen.io/gab/pen/AxFoB and set a value in the test page, restart your browser to test it works, remove the exception, and experiment with restarting and changing/unsetting the value.

**Comment by mattatobin** [comment]
Where you requested to open this issue here?

**Comment by RealityRipple** [comment]
> 
> 
> Where you requested to open this issue here?

No, but it seems like a potential security issue to me, and I was posting another one at the same time.

**Comment by wolfbeast** [comment]
> If a site has no LocalStorage, the "Keep until: I close Pale Moon" option behaves as expected, resetting the LocalStorage to nothing after the browser closes. If, however, the LocalStorage has already been set, it still resets - back to whatever it was set to before.

This is expected behavior. Any previously-existing state should not be touched by session-limited manipulations/mutations. "Keep until: I close Pale Moon" means "Keep whatever happened in this browsing session until I close Pale Moon" and not "Clear everything I ever had when I close Pale Moon".

**Comment by RealityRipple** [comment]
> 
> 
> > If a site has no LocalStorage, the "Keep until: I close Pale Moon" option behaves as expected, resetting the LocalStorage to nothing after the browser closes. If, however, the LocalStorage has already been set, it still resets - back to whatever it was set to before.
> 
> This is expected behavior. Any previously-existing state should not be touched by session-limited manipulations/mutations. "Keep until: I close Pale Moon" means "Keep whatever happened in this browsing session until I close Pale Moon" and not "Clear everything I ever had when I close Pale Moon".

In that case, the contents of the help page at <http://www.palemoon.org/support/prefs-privacy> need to be changed. It clearly says "If selected, your cookies will be **deleted** when you close Pale Moon."

**Comment by wolfbeast** [comment]
Website updated to clarify it will delete your session cookies.
