### ISSUE TITLE
Remove leftover code for Hotfixes.

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1160]
Per Mozilla Wiki:

> The add-on hotfix is a tool used to ship changes to Firefox users that don't need to be distributed under the normal update mechanism. Examples of this are configuration changes that don't justify a point release, or changes that need to be pushed to users in older versions of Firefox.
> 
> Hotfix updates are automatically pushed to all Firefox users (starting from version 11). 

We aren't currently using this update mechanism in any of our applications, and the current setting is still a Mozilla Signing Cert. These prefs can be safely removed from all applications.

It may also be worthwhile to remove it from Telemetry and Tests in toolkit.

**Comment by wolfbeast** [comment]
We aren't currently using this (hence the untouched setting for a Mozilla cert) -- does this mean it should be removed from the platform? Think a little broader, please. 

I think it would be worthwhile to keep this option, at least for the time being. Other applications may want to use hotfixing.

**Comment by mattatobin** [comment]
It is already gone from the Add-ons Manager. This is just rements of it.

**Comment by wolfbeast** [comment]
Okay then. It's gone.
Feel free to clean up after it then.
