### ISSUE TITLE
Update the application icon to provide better visuals on light backgrounds.

### ISSUE THREAD

**Issue by EMH-Mark-I** [MoonchildProductions/UXP#1165]
This is in response to v28.6.0.1 (2019-07-04) commit: 15e8d1c & 8096258 

> Updated the application icon to provide better visuals on Windows classic and other grey backgrounds.

I recommend adding a thin border around application launcher icons so that the icon should stand out against grey backgrounds.

Draft image for recommendation:
![image](https://user-images.githubusercontent.com/28378002/60761403-3f634480-a00d-11e9-8082-469d42e9a996.png)
Link to clearer image: https://i.imgur.com/tD8XBd0.png

I can submit a PR for review with the png launcher icons if this is a desired direction. If not, then close this issue. 

Thank-you

**Comment by wolfbeast** [comment]
The icon was already updated in 28.6.0.1 to provide contrast against grey backgrounds. Adding a border takes away from the artistic merit the image has.

**Comment by EMH-Mark-I** [comment]
@wolfbeast

Understandable. I was pointed over to the forum this morning that the decision had been finalized and appeared to be a bit of a topic of debate, which I didn't realize when opening my issue here, sorry.

**Comment by mattatobin** [comment]
Nah, just bickering and crying from a couple of people.
