### ISSUE TITLE
Fullscreen YouTube is broken

### ISSUE THREAD

**Issue by johnb-xp** [MoonchildProductions/UXP#1169]
When Pale Moon's window isn't maximized, entering full screen on YouTube causes the player to be in a strange box instead of filling the screen.

To replicate: Un-maximize Pale Moon, go to a YouTube video, and click fullscreen. I think.

**Comment by khronosschoty** [comment]
I just attempted to duplicate this; but I am unable to reproduce the issue. I suggest providing more details; such as the OS your using, the Pale Moon version; and if applicable, what desktop and or windows manager you might be using.

**Comment by mattatobin** [comment]
Also include where you got the binary.

**Comment by johnb-xp** [comment]
After restarting my PC it looks like the issue fixed itself lol.
