### ISSUE TITLE
 Scripting on website makes UXP completely unresposive

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1179]
https://bugzilla.mozilla.org/show_bug.cgi?id=1317032

test: http://umlnotation.sparxsystems.eu/#chapter_EE843E93_9D9B_44d5_AD15_6B6F3371710C

This website makes UXP completely unresponsive. Pull request will fix this hang.

If a page uses or removes many <object> elements which are not actually plugins, loading the page goes to a crawl because UXP recalculates the plugin UI every time.

 Don't do that by only dispatching a PluginRemoved event for actual plugins, not images/unknown/iframe-type <objects>.

**Comment by wolfbeast** [comment]
I'm afraid this causes a regression as reported [on the forum](https://forum.palemoon.org/viewtopic.php?f=29&t=22832) on websites that add and remove actual plugin objects from the DOM tree like https://get.adobe.com/flashplayer/ does as part of its detection routine.

**Comment by wolfbeast** [comment]
@win7-7 any idea?

**Comment by wolfbeast** [comment]
I've resolved the regression in #1222
