### ISSUE TITLE
Add-on Bar shouldn't be called "Status Bar" in the UI if --disable-browser-statusbar

### ISSUE THREAD

**Issue by mrnhmath** [MoonchildProductions/UXP#1193]
Currently, if Pale Moon is built with --disable-browser-statusbar, the toolbar dropdown wrongly lists the Add-on Bar as "Status Bar".
![1](https://user-images.githubusercontent.com/13562431/61585401-28eeda00-ab31-11e9-98f7-66bc5763b912.png)

**Comment by mattatobin** [comment]
Perhaps.. But we can't make it conditional because it is l10n.. other langpacks would have it localized to Status Bar anyway. Besides, that conditional needs removed anyway.. It was only meant for debug from all the way back when we were doing `Tycho` and I first integrated the S4E components.
