### ISSUE TITLE
running "mach install" fails after building w/ clang 7.1.0 and 8.0.1

### ISSUE THREAD

**Issue by mssx86** [MoonchildProductions/UXP#1203]
i tried building palemoon `28.5.1` and `28.5.2` back at june with `clang 7.1.0` and `28.6.1` with `clang 8.0.1` today. all of the attempts ended up with builds actually finishing with no errors but running `mach install` always ended up failing. this is the complete output i get after running `python2.7 mach install` as root: [mach install output](https://gist.github.com/mssx86/024275d271132f1d856e38747ef2bf41)

this is the mozconfig i've used: [mozconfig](https://gist.github.com/mssx86/7ba7cf735a828a6570b25e5dbb187731)

i'm able to build all of the versions i've stated above with `gcc 9.1.0` with that exact `mozconfig`, only difference being the `ac_add_options --enable-optimize="-O2 -Wno-format-overflow"` instead of `ac_add_options --enable-optimize="-O2"` and the lack of `CC` and `CXX` variables since it defaults to `gcc` already.

these are the exact steps i followed, which ended up with the said error:
1. `wget https://github.com/MoonchildProductions/UXP/archive/PM28.6.1_Release.tar.gz`
2. `tar xf PM28.6.1_Release.tar.gz`
3. `mv UXP-PM28.6.1_Release /mss/work/UXP`
4. `cp ../mozconfig /mss/work/UXP/`
5. `cd /mss/work/UXP`
6. `export MOZBUILD_STATE_PATH="/mss/work/UXP/mozbuild"`
7. `export MOZCONFIG="/mss/work/UXP/mozconfig"`
8. `python2.7 mach build`
9. `su -c "python2.7 mach install"`

is there something wrong with the `mozconfig` i used that makes it incompatible with `clang`? i have also disabled the system library usage flags and let palemoon use its own with the official branding and it failed the same way as above.

**Comment by kn-yami** [comment]
I do not know if this is related to the `mach install` failure, but your `mozconfig` does contain options that make no sense in UXP (`ac_add_options --enable-alsa`) and options that are not recommended (`ac_add_options --with-system-*`)

**Comment by mssx86** [comment]
>`ac_add_options --enable-alsa`

it's an old habit to disable pulseaudio and enable alsa from the firefox quantum mozconfigs i had, but i've been using that option for ages, never had a build fail to be built with it with gcc, i don't think that's the cause.

>`ac_add_options --with-system-*`

as i stated above, it builds fine with gcc using these options, i don't think this is the main problem.

i'm currently building with `ac_add_options --disable-startupcache` since it's mentioned in the python error. if it won't fix the issue, i'll try to play with `optimize` options as i saw some old bug reports of firefox mentioning it.

**Comment by kn-yami** [comment]
`ac_add_options --enable-alsa` makes no sense in UXP because ALSA support is always enabled. As for building with system libs: you can do this, but is is not recommended or supported. Also I may be wrong but I think that building with clang is also not supported.

**Comment by mssx86** [comment]
- adding `ac_add_options --disable-startupcache` to the mozconfig got rid of the python error that running `mach install` gave but pale moon **segfaulted** when i executed it.
- adding both `ac_add_options --disable-startupcache` and `ac_add_options --enable-optimize="-O1"` got built and installed with no errors but **segfaulted again**.
- adding `ac_add_options --disable-startupcache` and `ac_add_options --disable-optimize` and got built and installed fine and **runs perfectly fine, no segfaults or crashes so far**.

**Comment by wolfbeast** [comment]
Our supported compilers are MSVC on Windows and gcc on *nix. clang on *nix is not supported.
Please use gcc.
