### ISSUE TITLE
 Convert dom/base/nsImageLoadingContent.cpp to use AsyncOpen2 and followups

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1204]
As followup to Mozilla work in https://bugzilla.mozilla.org/show_bug.cgi?id=1206961, pull request that would solve this will convert nsImageLoadingContent.cpp to use AsyncOpen2() and also includes followups to main patch (1267075).

https://bugzilla.mozilla.org/show_bug.cgi?id=1267075 (main patch) (part 1,2,3 and 4 / without adding tests)

Part 1: call SetBlockedRequest when CSP check failed.

Remove calling CanLoadImage. Also in the case of CSP check failed, we will call SetBlockedRequest in those cases.

Part 2: bail out early if it's for data document.

Check the document earlier before calling into imageLoader, this could save us tons of time if in the end the document isn't allowed to load images.

Part 3: cancel imgRequestProxy if asyncOpen2 failed

The problem is if we found a cache hit, then we could go through ValidateRequestWithNewChannel to validate the cache. Then if the CSP check fail(asyncOpen2() will fail), then the imgRequestProxy will remain there, and cause the timeout.

Part 4: add a boolean to prevent calling asynchronously

Use a boolean to prevent calling SetBlockedRequest asynchronously. Also use the same boolean to prevent some evil code reentering LoadImage.

https://bugzilla.mozilla.org/show_bug.cgi?id=1373780 (part 2 and 3)

Part 2: remove calling nsContentUtils::CanLoadImage().

Part 3: add isImgSet argument.

https://bugzilla.mozilla.org/show_bug.cgi?id=1445670

 Make sure to clear out the pending request when our image gets blocked by the data document policy.

**Comment by wolfbeast** [comment]
Reopening for verification

**Comment by wolfbeast** [comment]
Verified in x64-unstable portable. No regressions seen with a casual check.
Performance in http://www.hixie.ch/tests/adhoc/perf/dom/real-world/005.html
x64-release: 8326 ms total, 396.5 ms/iter.
x64-unstable: 638 ms total, 30.4 ms/iter.
