### ISSUE TITLE
Can't run Basilisk browser with AppArmor + Couldn't load XPCOM

### ISSUE THREAD

**Issue by trancemind65** [MoonchildProductions/UXP#1216]
Hi!

I can't run Basilisk browser with AppArmor.

I get this error message:

Couldn't load XPCOM.

I'll did this:
...added to my Basilisk AppArmor profile:

/path/to/basilisk/liblgpllibs.so r,

but this did not help.

Which files must I add to my AppArmor profile to run Basilisk without the XPCOM error?

**Comment by wolfbeast** [comment]
Please ask for support from the AppArmor devs/community or on the Pale Moon forum.
This is an issue tracker, not a forum.

Closing, not a bug.
