### ISSUE TITLE
Add support for Windows 10 SDK

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#1217]
Splitting this off from #1213 as requested. The patch for this should be [Bug 1356493](https://bugzilla.mozilla.org/show_bug.cgi?id=1356493).

**Comment by wolfbeast** [comment]
Try builds built with VS2015 against Win10 SDK 10.0.17763.0, 32-bit:
http://testserver.palemoon.org/try/palemoon-28.8.0a1.win32.installer.exe
http://testserver.palemoon.org/try/palemoon-28.8.0a1.win32.zip
