### ISSUE TITLE
Pale Moon creates an unneeded file in the user's home directory.

### ISSUE THREAD

**Issue by arms7** [MoonchildProductions/UXP#1220]
Pale Moon Browser version 28.7.0a1
OS: Linux Debian 10 "Current Stable"
OS: Linux Debian 9 "Old Stable" 
 
I install palemoon like so:
sudo tar xvf \
/home/mike/downloads/palemoon-unstable-latest.linux-x86_64.tar.bz2 --directory=/opt && \
sudo ln -s /opt/palemoon/palemoon /usr/bin/palemoon 

After installing and opening Pale Moon it creates the file:
 "/home/mike/Desktop".

The file can be deleted after closing Pale Moon. If Pale Moon is opened again then it will then 
recreate the file. 

Why Pale Moon creates this "Desktop" file I do not know.

Desired behavior is to not have Pale Moon create the aforementioned file because it is
not needed.

**Comment by wolfbeast** [comment]
This is likely not an issue -- the browser uses some standard directories that are available on most Linux distributions (e.g. a default download directory). Please check your preferences, report back, and change location if it's undesired.

**Comment by arms7** [comment]
Was just somewhat puzzled as to why, whenever the terminal emulator is opened, you could this see this new Desktop file that had not been there before, was wondering why Pale Moon would need create and make use of it.

Some Linux users choose to use a window manager (like i3, openbox, awm, fluxbox, 9wm, etc.) without an actual Desktop Environment installed. This type of minimal interface will likely not have  "Desktop" folder. Most Linux users will use a DE (like KDE, XFCE, or Gnome).  These users, who happen to be the majority of Linux users, will certainly have a "Desktop" folder. So those who use a DE are definitely the default.

Pale Moon's creation of a "Desktop" file does not really alter the way it behaves. It can write "Desktop" files to my home directory over and over. The browser still works fine.  So this (bug?) seems to perhaps be sort of a niche issue for those who use a window manager only.

Concerning downloads: Pale Moon downloads all files to my "Downloads" folder since that is the folder that is selected in the preferences menu. Pale Moon seems to download to any file that I choose in my home directory, including the home directory itself.

Just want to double check that this file creation is the default behavior for Pale Moon. If it is then I can just close the issue.

**Comment by wolfbeast** [comment]
I'm sure this is the default behavior of Pale Moon on Linux -- it's assumed people who run it will be running some form of desktop environment; if not, then it'll create `Desktop` on startup as part of its initialization checks.
While this behavior _could_ be changed, it's not considered a bug since in the targeted environments `Desktop` will exist. If changed, the browser would need some kind of alternative for that location to be used internally, which is probably going to be even more distribution-dependent and not a chase I feel particularly compelled to take on ;)
