### ISSUE TITLE
Build bustage on non-x86 CPU architectures with GNU-cc

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1226]
When trying to build Linux binaries on non-Intel hardware, the build process halts due to `-msse2` and `-mfpmath=sse` compiler flags for GNU-cc that aren't defined for those architectures.

As reported on the [forum](https://forum.palemoon.org/viewtopic.php?f=57&t=22905#p174467)

The solution is simple: test for CPU_ARCH `x86` and add sse2 flags appropriately only there.

**Comment by mattatobin** [comment]
Reopened for uplift.

**Comment by wolfbeast** [comment]
Uplifted in e5488f14db386a54fbfae275655241d2a6e80800
