### ISSUE TITLE
Nintendo's site is displayed not correctly

### ISSUE THREAD

**Issue by hawkeye116477** [MoonchildProductions/UXP#1227]
Welcome! Just like on title. Go to `https://www.nintendo.com/switch/lite/`, scroll down and you will see the difference.
On Basilisk
![Screenshot_20190922_110145](https://user-images.githubusercontent.com/19818572/65384912-6128b980-dd28-11e9-9ceb-8433c20c4a74.png)
On Firefox 69
![Screenshot_20190922_110209](https://user-images.githubusercontent.com/19818572/65384915-6f76d580-dd28-11e9-8608-ea079c3ded53.png)

Appears that elements from section class „compare-systems" are missing on Basilisk.

**Comment by wolfbeast** [comment]
```
12:04:39.779 Config Section: switch  
dependencies.min.261e39ed2a653b0f03ccad0743df9125.js:3039:3
12:04:39.873 AT: Rendering mbox failed target-global-mbox Object { status: "error", error: "disabled due to optout" }  
all.min.js:1:181818
12:04:40.079 downloadable font: rejected by sanitizer (font-family: "LatoLight" style:normal weight:normal stretch:normal src index:1) source: https://www.nintendo.com/content/dam/noa/en_US/resources/asset/font/lato/Lato-Lig-Webfont.woff  
overrides.css:935:11
12:04:40.091 downloadable font: rejected by sanitizer (font-family: "LatoBold" style:normal weight:normal stretch:normal src index:1) source: https://www.nintendo.com/content/dam/noa/en_US/resources/asset/font/lato/Lato-Bol-Webfont.woff  
overrides.css:934:11
12:04:41.028 downloadable font: download failed (font-family: "LatoBold" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: https://www.nintendo.com/content/dam/noa/en_US/resources/asset/font/lato/Lato-Bol-Webfont.ttf  
overrides.css:934:11
12:04:41.028 downloadable font: no supported format found (font-family: "LatoBold" style:normal weight:normal stretch:normal src index:4) source: (end of source list)  
overrides.css:934:11
12:04:41.111 downloadable font: rejected by sanitizer (font-family: "LatoLight" style:normal weight:normal stretch:normal src index:2) source: https://www.nintendo.com/content/dam/noa/en_US/resources/asset/font/lato/Lato-Lig-Webfont.ttf  
overrides.css:935:11
12:04:41.111 downloadable font: no supported format found (font-family: "LatoLight" style:normal weight:normal stretch:normal src index:4) source: (end of source list)  
overrides.css:935:11
12:04:43.961 The resource from “https://analytics.twitter.com/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nutyw&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0&tw_iframe_status=0&tpx_cb=twttr.conversion.loadPixels&tw_document_href=https%3A%2F%2Fwww.nintendo.com%2Fswitch%2Flite%2F” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
```

**Comment by THEtomaso** [comment]
Mozregression result:

* Last bad: **Firefox v62.0a1 (2018-05-27)**
* First good: **Firefox 62.0a1 (2018-05-28)**

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=db78be8dbc1c81844eb7d35c1a3073078eb5d923&tochange=35aa0dde259f5f51c0aaf86935a54b8087c2e8c6

**Comment by hawkeye116477** [comment]
@THEtomaso Are you sure? I checked build 2018-05-28 and it crashes on this site.

From my observation:
* Last bad: Firefox 64.0a1 (2018-09-17)
* First good: Firefox 64.0a1 (2018-09-18)

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5165e750ffabb930deb846410ab62dcc6d1f9e52&tochange=85b4d2bf888afa32b67638602a3338d0a6935ff9

**Comment by THEtomaso** [comment]
> Are you sure?

I've retested it now, and got the same result as I did before, without any crashing (tested with both 32-bit and 64-bit builds).
The rage which you posted is wrong, as the page renders just fine in both of those builds from my end.

**Comment by hawkeye116477** [comment]
Ok, seems that crash occurs only on Linux.

**Comment by hawkeye116477** [comment]
And I checked something on FF 62 and seems that's the fix => `https://bugzilla.mozilla.org/show_bug.cgi?id=1460069`.

**Comment by mattatobin** [comment]
Shadow DOM is an abomination. You do it.

**Comment by mattatobin** [comment]
RESOLVED WORKSFORME
