### ISSUE TITLE
Searching on NerdyData doesn't work

### ISSUE THREAD

**Issue by hawkeye116477** [MoonchildProductions/UXP#1228]
Just like on title. Go to https://nerdydata.com, then try to search something and appears message `this.searchRequestController is undefined`.
![Screenshot_20190923_002416](https://user-images.githubusercontent.com/19818572/65395242-7d643f00-dd98-11e9-803c-f8c2d2003288.png)
From console:
`ReferenceError: AbortController is not defined`

Related:

https://bugzilla.mozilla.org/show_bug.cgi?id=1394085
https://bugzilla.mozilla.org/show_bug.cgi?id=1128959

In brief - Basilisk currently doesn't support Abort API.

**Comment by wolfbeast** [comment]
We don't support cancellable fetch requests to begin with; I'm not sure why this site wants to use this for something as simple as search; cancelling fetch requests is only really important for high data volume requests like streams when requested through the DOM.
Either way, it should do feature detection if it wants to use it and not hard fail like this.

**Comment by mattatobin** [comment]
RESOLVED WONTFIX

**Comment by Vangelis66** [comment]
Actually, this issue has been now **fixed** as a result of #1587 (Implement **abortController**): 

![ND](https://user-images.githubusercontent.com/9669492/88871187-ea99f980-d21f-11ea-9009-2e4b0a743649.JPG)

so perhaps, for _completeness_ reasons, it should be labelled as such... 😉 😄 

A big **THANK YOU** to the devs for implementing `AbortController` BTW 🥇 !

Best wishes...

**Comment by wolfbeast** [comment]
While fixed with the Abort API, the following still stands:

> I'm not sure why this site wants to use this for something as simple as search; cancelling fetch requests is only really important for high data volume requests like streams when requested through the DOM.
