### ISSUE TITLE
Back-computing percentages for intrinsic sizing causing negative percentages

### ISSUE THREAD

**Issue by hawkeye116477** [MoonchildProductions/UXP#1230]
Just go to https://lichess.org/editor/8/8/8/8/8/8/8/8_w_-_- and you will see the difference.

On latest Basilisk
![Screenshot_20190924_132458](https://user-images.githubusercontent.com/19818572/65507754-e3eb7900-dece-11e9-82ea-5ee1a0859286.png)

On Firefox 69.0
![Screenshot_20190924_132628](https://user-images.githubusercontent.com/19818572/65507772-ecdc4a80-dece-11e9-9643-bf257c05cf5d.png)

Console doesn't show interesting info, but looking at css seems that something is not right with `grid-area`. Seems that works fine from Firefox 61.

**Comment by THEtomaso** [comment]
Mozregression result:

* Last bad: **Firefox v61.0a1 (2018-04-09)**
* First good: **Firefox v61.0a1 2018-04-10**

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=83de58ddda2057f1cb949537f6b111e3b115ea3d&tochange=0528a414c2a86dad0623779abde5301d37337934

**Comment by adeshkp** [comment]
Probably this: https://bugzilla.mozilla.org/show_bug.cgi?id=1434478

**Comment by g4jc** [comment]
@adeshkp confirming. I'll take this bug and #1233 if no one else is working on it. It's in a range of patches I've started working on.

**Comment by mattatobin** [comment]
@hawkeye116477 Please in the future report issues with websites to the Pale Moon forums. This issue tracker is for our benefit. Not yours.

**Comment by hawkeye116477** [comment]
@mattatobin Ok, anyway I don't need fast solution, I can wait, it's not my main browser :smile:

**Comment by mattatobin** [comment]
@hawkeye116477 You will post issues such as these on the forum and not our issue tracker in the future. Is that understood?

**Comment by hawkeye116477** [comment]
Ok

**Comment by mattatobin** [comment]
The Basilisk site says a lot of things and maybe it needs to be updated to reflect current policy. The Pale Moon forum is your first point of contact for issues and support so that we can keep the issue tracker for confirmed issues and plans of action for changes.
