### ISSUE TITLE
Stop using ICC profiles on Linux

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#1231]
Reported on forum: https://forum.palemoon.org/viewtopic.php?p=175368#p175357

This got lost with UXP.

**Comment by mattatobin** [comment]
Reopened for uplift.

**Comment by wolfbeast** [comment]
Actually, it should probably be adjusted. Mac likely has calibrated color displays (more likely than Windows, actually) and they don't get ICC with this patch either. We should switch it on for all platforms where it can reasonably be expected to be present (currently Windows and OS X).

Also, using ICCv4 is -always- preferred even for platforms that disable by default. Renderin intent and default profile string are also universal. The conditional block should only be for the mode switch.

**Comment by wolfbeast** [comment]
Corrected in 38feb30d4e1dd0126fd4944fa47d4f445213aed4 and uplifted in 5d3b13dbec3c4b81cb67f60f7dbc8ba88ba58036 and 50b875bff1ccf12925246c4df3a3aff6f624e0d4
