### ISSUE TITLE
Grid item overflows grid column when <pre> overflows width

### ISSUE THREAD

**Issue by hawkeye116477** [MoonchildProductions/UXP#1233]
Go to https://www.mediamarkt.de/de/product/_motorola-moto-g7-plus-64-gb-viva-red-dual-sim-2522327.html, scroll little and you will see the problem.

On Basilisk
![Screenshot_20190927_172536](https://user-images.githubusercontent.com/19818572/65781398-dc84d380-e14b-11e9-864d-c07ee69a34aa.png)

On Firefox
![Screenshot_20190927_172629](https://user-images.githubusercontent.com/19818572/65781491-f6beb180-e14b-11e9-85cf-0d083dfd616d.png)
![Screenshot_20190927_172645](https://user-images.githubusercontent.com/19818572/65781500-fd4d2900-e14b-11e9-86e8-9ffb15939b0e.png)

So text in **Produktbeschreibung** is too long, lacks wrapping and some information is missing on **Technische Daten**.

Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1418727

**Comment by wolfbeast** [comment]
Assigned to @g4jc

**Comment by mattatobin** [comment]
@hawkeye116477 https://github.com/MoonchildProductions/UXP/issues/1230#issuecomment-536244756
