### ISSUE TITLE
libwebp NEON-specific files are missing

### ISSUE THREAD

**Issue by dimag0g** [MoonchildProductions/UXP#1234]
The issue happens when building basilisk for Raspbian Buster (using gcc-4.9, but that's not a part of the issue). 3 NEON-specific files are missing in libwebp, causing the build to fail due to missing functions defined in those files. 

The issue can be reproduced by adding `ac-add-option --with-fpu=neon-vfpv4` and building with an `armhf` toolchain.

I already have a fix which consists in adding missing files from `https://github.com/webmproject/libwebp/tree/1.0.2`. Let me know if a pull request is necessary.

**Comment by wolfbeast** [comment]
Go for it.

**Comment by JustOff** [comment]
For completeness, [update.sh](https://github.com/MoonchildProductions/UXP/blob/master/media/libwebp/update.sh) needs to be updated as well.

**Comment by dimag0g** [comment]
@JustOff Thanks for the hint. Can you tell me if I should make another pull request? AFAIK the original pull request (that's already closed) isn't easily amended.

**Comment by JustOff** [comment]
Unfortunately, I noticed that a little late, so yes, you need to make a new PR.

**Comment by mattatobin** [comment]
Don't feel too bad I always forget those scripts I never use but might be used at some point.
