### ISSUE TITLE
 The application has been updated, but the SQLite library wasn't updated properly

### ISSUE THREAD

**Issue by clort81** [MoonchildProductions/UXP#1236]
Overnight 'something happened' with pm auto-updater.

"The application has been updated, but the SQLite library wasn't updated properly"

Current OS has libsqlite3-0 Version: 3.27.2-3

Just rebuilt Pale Moon from source.  Error persists.   What can I do to diagnose?

**Comment by wolfbeast** [comment]
Please go to the forum and post in the Linux board.
