### ISSUE TITLE
Re-add numAcceleratedWindows to about:support

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1242]
At some point between 38 and 52 Mozilla removed the output of the number of accelerated windows from the about:support page. This info still exists in the reports copied to the clipboard so we just need to restore it being displayed on the Troubleshooting page its self.

**Comment by wolfbeast** [comment]
> This info still exists in the reports copied to the clipboard

It doesn't, actually. It was completely ripped out (including the localization for it). The only thing that was retained was the compositor information.

**Comment by wolfbeast** [comment]
@JustOff Please take note of the added string for localization.

**Comment by JustOff** [comment]
@wolfbeast, it seems you accidentally duplicated this localization note:

https://github.com/MoonchildProductions/UXP/blob/4f6a779e0c05599a2c01155d2599595bad279bcf/toolkit/locales/en-US/chrome/global/aboutSupport.properties#L30-L32

https://github.com/MoonchildProductions/UXP/blob/4f6a779e0c05599a2c01155d2599595bad279bcf/toolkit/locales/en-US/chrome/global/aboutSupport.properties#L63-L65

**Comment by wolfbeast** [comment]
Hmm I see it was apparently moved down at some point outside of my field of view when editing the file. it _used_ to be where I placed it.

**Comment by wolfbeast** [comment]
Fixed in e97cb2f75fd9750bbb96d1eec43b7a968a611f9c

**Comment by JustOff** [comment]
Thanks, string changes were pushed to CrowdIn.

**Comment by Vangelis66** [comment]
> At some point between **38** and **52** Mozilla _removed the output of the number of accelerated windows from the about:support page_. 

FTR, it was done as part of Bugzilla bug **1263849**:

[Reorganize the graphics section in about:support](https://bugzilla.mozilla.org/show_bug.cgi?id=1263849)

which landed in Firefox Nightly 48.0a1: 

https://hg.mozilla.org/mozilla-central/rev/efaa8959220e

(I hope you don't mind me posting this 😉 )

**Comment by wolfbeast** [comment]
Thanks but the reference to the Mozilla bug wasn't necessary. It was dead simple to just restore what was there before in Tycho.
