### ISSUE TITLE
Update List of NSS Exported Symbols

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1243]
Several security patches for S/MIME (only in comm) require `NSS_CMSSignedData_GetDigestAlgs` and `NSS_CMSSignedData_hasDigests`. Our version of NSS already has these, but they are not being exported in `security/nss.symbols`. While we are here it wouldn't hurt to export all the latest symbols being used in NSS so that other applications can utilize them.

**Comment by mattatobin** [comment]
What security patches?

**Comment by mattatobin** [comment]
Go ahead an open a PR to expose what we need but I don't think it is a good idea to expose every possible symbol.

**Comment by wolfbeast** [comment]
Policy is to only expose those symbols of imported libraries that we actually use/need. This is a security consideration to keep attack surfaces minimal.

**Comment by mattatobin** [comment]
We are gonna want this pretty soon cause sec-cycle is coming up and I would like to have them in the mail client. I assume you are gonna need it too, dude.

**Comment by mattatobin** [comment]
Thank you @g4jc

**Comment by mattatobin** [comment]
Keeping open for uplift

**Comment by wolfbeast** [comment]
Uplifted in d36d11042e6f7503960c4c7ca379623228c68d4a
