### ISSUE TITLE
Undefined functions isMarkable() / toMarkablePointer() in ARM build

### ISSUE THREAD

**Issue by dimag0g** [MoonchildProductions/UXP#1245]
This issue is ARM-specific and concerns `MacroAssembler-arm.cpp`. One of the overloaded versions of `MacroAssemblerARMCompat::storePayload` use undefined functions `isMarkable()` / `toMarkablePointer()`, while other overloaded versions use `isGCThing()` / `toGCThing()`. This results in a compilation error in `MacroAssembler-arm.cpp`.

An obvious fix would be to [replace](https://github.com/dimag0g/UXP/commit/9f2d3c15e9fd26326c265900038c05027b45d05a) undefined functions with their defined "equivalents", in case they are indeed equivalents.

**Comment by wolfbeast** [comment]
Looks like this is some fallout from the JS update we did. And yes, in the new code they are indeed equivalent.
`isMarkable()` -> `isGCThing()`
`toMarkablePointer` -> `toGCThing()`
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1325075 where Mozilla did this work; might be good to check peripheral changes there to see if we haven't dropped anything in the process. @g4jc should probably be involved here as reviewer.

**Comment by dimag0g** [comment]
@wolfbeast So, converting `isMarkable()` to `isGCThing()` seems to be a step back, compared to what Mozilla did. Do we want that, or the opposite? Or should we stick to `isGCThing()` for now, and do the conversion to `isMarkable()` at a later time?

**Comment by wolfbeast** [comment]
Carefully read the bug in its entirety.

**Comment by g4jc** [comment]
Using a diff between the bug and @trav90 commit [here](https://github.com/MoonchildProductions/UXP/commit/bbd4001cb261cc54e2adf804ea7cbeb09078d7d9), it looks to me like this was just a missed line. The particular change is r+ and only affects ARM. However, I haven't had time to review all files that were touched by said commit. Will check to see if anything else was missed when I have a few spare cycles and update here.

**Comment by mattatobin** [comment]
Thank you @g4jc

**Comment by g4jc** [comment]
Looks OK, I didn't see any missed isMarkable -> isGCThing on the 30 other files.
