### ISSUE TITLE
Untracked commits that need uplifted for 28.7.2

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1250]

**Comment by mattatobin** [comment]
That should be all of them to date.

**Comment by wolfbeast** [comment]
Uplifted in bda981d78661df5a07c1750f1275ce5b57938d73 b374f59ab5ed2d130db011c4d3e4eee024f42fed 0d6f1e11ba26646c21eff61dcee78d17914bfd81 4f038bf39a4806ec7339bf062a184e4e1f20758e and adbbcab423fba28939d73f9a8cadf3b26c5845fc
