### ISSUE TITLE
[Basilisk] aWindow is null

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1252]
Minor Error Console spam that can be triggered occasionally in `base/content/tabbrowser.xml`

The line `let browser = aWindow.QueryInterface(Ci.nsIInterfaceRequestor)` should have a null check first to check and see `if (aWindow)` actually exists.

**Comment by wolfbeast** [comment]
Line numbers, please

**Comment by g4jc** [comment]
[Line 378](https://github.com/MoonchildProductions/UXP/blob/master/application/basilisk/base/content/tabbrowser.xml#L378)

It doesn't always occur, some legacy extensions can trigger it occasionally. Doesn't appear to have an usability bustage beyond the log spam.

**Comment by mattatobin** [comment]
Why don't we just kill that so called "fast path".. Pale Moon and Borealis don't have that.

http://xref.palemoon.org/uxp-trunk/source/application/palemoon/base/content/tabbrowser.xml#324
http://xref.binaryoutcast.com/binoc-central/source/projects/navigator/base/content/tabbrowser.xml#2157
