### ISSUE TITLE
Make sticky positioning of table headers/rows possible

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1256]
Sticking table header rows is a requested design feature for the web. The problem is we don't create display list items for individual table parts because that's never been needed.

There's probably a quick solution available for this by hacking around with `display:relative` support that we already have since Goanna v3, but it may have some display glitches.

See also: https://forum.palemoon.org/viewtopic.php?f=3&t=23151

**Comment by SpockFan02** [comment]
Is this the same as #146/#248?

**Comment by wolfbeast** [comment]
No, not really. Although doing it the #146 way is probably better, but more involved.

**Comment by wolfbeast** [comment]
Closing this as a dup of #146 -- let's just do it correctly.
