### ISSUE TITLE
Import MailNews Core and Friends to the tree

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1258]
To better facilitate cross-community organization and reduce redundancy it has been decided that mailnews, ldap, and mork should be returned to their rightful place in the platform.

This work will entail importing these components and modules fresh from `comm-52.9` and applying security and performance improvements from later versions of comm.

The hardest hit in this will be Interlink which will have to be adapted for any changes in mailnews specifically but aside from the expected build system changes, Hyperbola's IceDove and IceApe will be largely unaffected after the patching has been caught up since they started with the later comm code.

We will be working inside of a branch here and on our respective repositories so that if we don't meet the relative Pale Moon 28.8 deadline we can just continue status quo for current releases.

----

This work will be conducted by @g4jc and @mattatobin who will co-own the component and modules.

**Comment by wolfbeast** [comment]
@g4jc if you're going to be a component (co-)owner, for the sake of being able to organize things (like being able to assign you to issues, etc.), you should become part of the MCP org. I've sent you an invite.

**Comment by athenian200** [comment]
As someone who has tried to build UXP-based applications from both repos, this change seems logical to me. When I forked both trees and had to put them both together in the same directory on my hard drive to build MailNews, I thought it would be easier to have it all together. That said, sorry to hear you're having to rebase your entire project on 52.9, and hope that you don't lose too much of your existing work in the process of doing that. I had no idea things were that rough, assumed everything was going well on your side of the tree.

**Comment by mattatobin** [comment]
That isn't quite the case.. There will still be a binoc-central and it will still be the place where my application lives. But since both I and Hyperbola both use mailnews core and friends AND the code is built and used as platform code and always was.. it makes sense to pool our efforts in the common platform codebase on that front.

I may have some incompatibilities that may be tedious to work out but Interlink will be fine. It won't be as bad as it sounds from that perspective.
