### ISSUE TITLE
Evaluate the need for watch/unwatch shim in global browser scope

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1264]
As a follow-up to #1261 we should investigate if we need to temporarily include a `watch`/`unwatch` shim in `browser.xul` as a chrome-only workaround for extensions that rely on the `watch`/`unwatch` debugging feature of past Firefoxes.

Factors here are:
- How many extensions rely on this? Just IHG and S4E? More? How many?
- How long does this need to remain in the browser? Are extension authors willing to work on no longer relying on these non-standard functions? "indefinitely" is not an acceptable answer.
- Is there a template change that can be offered to extension authors? i.e. a generic way to convert calls to `watch()` and `unwatch()` to functionally equivalent code?

If it needs to be included, then it should be included deprecated with a warning every time `watch` or `unwatch` are called.

**Comment by mattatobin** [comment]
Two that we know of, IHG and S4E the extension. We are gonna just have to ship without it and see if anyone complains beyond those two extensions I think.

**Comment by wolfbeast** [comment]
> when was watch/unwatch added to the codebase?

Firefox 1

**Comment by JustOff** [comment]
> if we need to temporarily include a `watch`/`unwatch` shim in `browser.xul`

I think this is not really necessary.

**Comment by mattatobin** [comment]
Same. Extension developers can do some development for once.
