### ISSUE TITLE
Update libcubeb to a1200c34

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1267]
Our current version is quite old and does not include a number of stability fixes that improve audio output quality.

Tag #1254

**Comment by g4jc** [comment]
These patches give us the latest libcubeb minus the massive DOM refactor that occurred and is outside of scope for this bug. Those changes may or may not add some additional optimization, but all that was needed to get it working with the current code was change the bindings to match the current library. Rust bindings and bloat were also avoided.

**Comment by mattatobin** [comment]
'''
20:17.93 cubeb_wasapi.obj : error LNK2019: unresolved external symbol _AvSetMmThreadCharacteristicsA@8 referenced in function "unsigned int __stdcall `anonymous namespace'::wasapi_stream_render_loop(void *)" (?wasapi_stream_render_loop@?A0x37e6c402@@YGIPAX@Z) 
20:17.93 
20:17.93 cubeb_wasapi.obj : error LNK2019: unresolved external symbol _AvRevertMmThreadCharacteristics@4 referenced in function "unsigned int __stdcall `anonymous namespace'::wasapi_stream_render_loop(void *)" (?wasapi_stream_render_loop@?A0x37e6c402@@YGIPAX@Z) 
20:17.93 
20:17.93 xul.dll : fatal error LNK1120: 2 unresolved externals
'''

**Comment by mattatobin** [comment]
I have had to back this out because for some reason, on Windows, it is using the assigned Communications device and nothing else. It SHOULD be using the Default audio device.

I am guessing that was all that "DOM stuff" you didn't bother backporting which gives the platform and websites control over which audio device is used for whatever.

**Comment by g4jc** [comment]
On hold per feature creep. This lib update affects DOM / WebRTC, and apparently changes the default audio device on Windows.
