### ISSUE TITLE
Upgrade MailNews Core

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1273]
We want to update MailNews Core to a state similar to Hyperbola's IceDove.

The main concern about the patches from the IceDove repository is desirability. While a great majority are very likely to be relevant to our shared interests I am just not sure about some of them.

It would be helpful, @g4jc, to list all the bugs dealing with mailnews, mork, and ldap you have backported here. Perhaps in the form of a checkbox list and marking those that touch a mail application for ease of reference for Interlink.

I can likely do a lot of the porting my self but it would help to have a good list.

----

Blocks #1258

**Comment by g4jc** [comment]
- [ ] [Bug 1328847](https://bugzilla.mozilla.org/show_bug.cgi?id=1328847) - a4159ca33429a9cb03ad9f66ab167b4794ec2a66 (*)
- [ ] [Bug 1328847](https://bugzilla.mozilla.org/show_bug.cgi?id=1328847) - 1ebcdce50182a7be99e836bc9774a5b3950cd53c (*)
- [ ] [Bug 1249562](https://bugzilla.mozilla.org/show_bug.cgi?id=1249562) - f795ec645d878d6cb4cdc55dd25837116a08f53c (a)
- [ ] [Bug 516464](https://bugzilla.mozilla.org/show_bug.cgi?id=516464) - 8a247d3ae6d670f00746e019ab474cd602f4acc6 (*)
- [ ] [Bug 1461106](https://bugzilla.mozilla.org/show_bug.cgi?id=1461106) - 22bc2d66a338f368a8f64fd88cf47e32b7ec8a56 (*)
- [ ] [Bug 654362](https://bugzilla.mozilla.org/show_bug.cgi?id=654362) - bac3024eacfd84e52c1269f6c2b8032d5a2b5b35 (a)
- [ ] [Bug 1446697](https://bugzilla.mozilla.org/show_bug.cgi?id=1446697) - 37122f548c1c9e3ce3922a0e70858efdaf3c473b (a)
- [ ] [Bug 1339436](https://bugzilla.mozilla.org/show_bug.cgi?id=1339436) - 8bad3ea14edf4022da894179a99220c6888253e7 (a)
- [ ] [Bug 1404049](https://bugzilla.mozilla.org/show_bug.cgi?id=1404049) - 62e5e954575cb612346c35a3b946975de555daff (*)
- [ ] [Bug 1079280](https://bugzilla.mozilla.org/show_bug.cgi?id=1079280) - 5d78cc140d90b34bfb44ebb516096293a7158697 (*)
- [ ] [Bug 1227761](https://bugzilla.mozilla.org/show_bug.cgi?id=1227761) - 8a8df1191b608eff88c15b7043ba71825fa08a40 (*)
- [ ] [Bug 1427732](https://bugzilla.mozilla.org/show_bug.cgi?id=1404049) - 1deaaf319c04e239923a2a37176743a516b4f85c (*)
- [ ] [Bug 1485884](https://bugzilla.mozilla.org/show_bug.cgi?id=1485884) - e05379715e6b3b7132f8ff362e74700edbb142d5 (c)
- [ ] [Bug 1488084](https://bugzilla.mozilla.org/show_bug.cgi?id=1488084) - d6635dd187b265703aedbaee0dc92ffdcfd07522 (a)
- [ ] [Bug 1487653](https://bugzilla.mozilla.org/show_bug.cgi?id=1487653) - a2defa057bae463cc36acb706537d0a341b93c96 (c)
- [ ] [Bug 758493](https://bugzilla.mozilla.org/show_bug.cgi?id=758493) - de5aa21f17f97bd2c3f2826b507af575808dbc5e (c)
- [ ] [Bug 1334489](https://bugzilla.mozilla.org/show_bug.cgi?id=1334489) - dd20b77bbfac62a112cb958cc4d655078d8656a7 (*)
- [ ] f82bdb417f84209e0364c03a13a0760863cb110f / 6cf36912c3f7bf409af85b19fe492e65079ca57f (t)
- [ ] [Bug 1487082](https://bugzilla.mozilla.org/show_bug.cgi?id=1487082) - 585f27517e5680caa6ec1b4a47684704aea3e384 (*)
- [ ] [Bug 646901](https://bugzilla.mozilla.org/show_bug.cgi?id=646901) - 85769f6569734e761e9a8a46a3000fdf2a5aba46 (*)
- [ ] [Bug 1462316](https://bugzilla.mozilla.org/show_bug.cgi?id=1462316) - 4698b7bd76d126ddbb2e806f342a4ad6e9b0ad8f (*)
- [ ] [Bug 825513](https://bugzilla.mozilla.org/show_bug.cgi?id=825513) - 7088bff67ce34efb2115b14d5ce10a94e0cdeb21 (*)
- [ ] [Bug 1393219](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - f3c38413e7ff0936c8b26d3aeab255acea3a8687 (*) [cleanup/trivial]
- [ ] [Bug 1393219](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - 378cb34dbe0a0d5872f3a228dec0b3e218c3a2a0 (*)
- [ ] [Bug 1393219](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - 13a7a2ee004c5ff9bcd00166f0ebfc38d7c0d5db (*)
- [ ] [Bug 1393219](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - b8945841fb3bd54689b2c38aea47f2d497f1fee4 (*)
- [ ] [Bug 1393219](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - 9cb60d3eff168e77954e88091b01e0393e4d97a3 (*)
- [ ] [Bug 1399756](https://bugzilla.mozilla.org/show_bug.cgi?id=1393219) - 770e42c7bb820690bc0223c5e9911306e117a3ab (*) [spelling/trivial]
- [ ] [Bug 1416033](https://bugzilla.mozilla.org/show_bug.cgi?id=1416033) - 7999fa84dcb53aac65b56c0f24d267f37cc4a2d1 / 810c86ea9915c820d5065bd98f361042d8f2a8a0 (*) [cleanup]
- [ ] [Bug 1216951](https://bugzilla.mozilla.org/show_bug.cgi?id=1216951) - 46de42829784510a120e7c9130db4de8518f1d1c (*)
- [ ] [Bug 1444389](https://bugzilla.mozilla.org/show_bug.cgi?id=1444389) - aff2c50e6936cc9a210addf49fe8c1b60b5bca87 (*)
- [ ] [Bug 1317117](https://bugzilla.mozilla.org/show_bug.cgi?id=1317117) - cc8392572a30f1a989716f39b4641f973090cc99 (*)
- [ ] [Bug 1442648](https://bugzilla.mozilla.org/show_bug.cgi?id=1442648) - 76cd269326ed2e38227a97b507700977ab03f1e1 (*) [mingw]
- [ ]  6d4408620b1a2547ae646ab3a81e03107dac0767 (*) [mingw]
- [ ] [Bug 1498152](https://bugzilla.mozilla.org/show_bug.cgi?id=1498152) - 2af9207ce40bb8f587398852bcc024997da691d9 (c)
- [ ] [Bug 1451137](https://bugzilla.mozilla.org/show_bug.cgi?id=1451137) - 816038c7c61bb77fd7db67b117fb6d3990693863 (*)
- [ ] [Bug 1494764](https://bugzilla.mozilla.org/show_bug.cgi?id=1494764) - 8900f3f355150458e5f2b129ccc2afa09fd7394e (*)
- [ ] [Bug 1333038](https://bugzilla.mozilla.org/show_bug.cgi?id=1333038) - 3aea66c997f34add7e6b2593dd740ec36d2d9244 (*)
- [ ] [Bug 1257058](https://bugzilla.mozilla.org/show_bug.cgi?id=1257058) - 3eb8b51de1e1f4d852665b3d57a4c84915c2a786 (*)
- [ ] [Bug 344205](https://bugzilla.mozilla.org/show_bug.cgi?id=344205) - 1a3f8366ad7683681afa9800f9e14cc6a930d3d5 (*)
- [ ] [Bug 1460001](https://bugzilla.mozilla.org/show_bug.cgi?id=1460001) - 4a7a839127e3768dde60ba23f6e1ef6a86b61aef (c)
- [ ] [Bug 1320475](https://bugzilla.mozilla.org/show_bug.cgi?id=1320475) - bb14f9af49cb24a0faaaec7b0f5e71c04f81c5cf (a)
- [ ] [Bug 1507718](https://bugzilla.mozilla.org/show_bug.cgi?id=1507718) - cc16ac97da449fa9997177fcea6a6a37ea1a2ebd (*)
- [ ] [Bug 1508046](https://bugzilla.mozilla.org/show_bug.cgi?id=1508046) - a2d1e6016b7586468f1285375101b1df7b64be55 (*)
- [ ] [Bug 394216](https://bugzilla.mozilla.org/show_bug.cgi?id=394216) - bf69f9a74be0389f879c5aad50f4cb90dfca8f3b (a)
- [ ] [Bug 342632](https://bugzilla.mozilla.org/show_bug.cgi?id=342632) - 702ba0fc40d7dc1ca6404c974edb12f3fa67a101 (c)
- [ ] [Bug 342632](https://bugzilla.mozilla.org/show_bug.cgi?id=342632) - 1f6b11bc542c90f69aae66ee95046cd159706523 (*)
- [ ] [Bug 1401858](https://bugzilla.mozilla.org/show_bug.cgi?id=1401858) - 8c0d316b4c9cbe293d9def1cce50e3b6278e8d8e (*)
- [ ] [Bug 1271353](https://bugzilla.mozilla.org/show_bug.cgi?id=1271353) - f119f57934865ae6939a553e3f38689bd3677c12 (*)
- [ ] [Bug 809513](https://bugzilla.mozilla.org/show_bug.cgi?id=809513) - f853879ee540215b0c9823422f65799ed4ccbeb6 (*)
- [ ] [Bug 390721](https://bugzilla.mozilla.org/show_bug.cgi?id=390721) - cf0bc09f6c6af9a669c6409087f0a60ef1e777f1 (*)
- [ ] [Bug 947771](https://bugzilla.mozilla.org/show_bug.cgi?id=947771) - 1ae69cfc646a0a8f67614b6c9662c28913816798 (*)
- [ ] [Bug 1512557](https://bugzilla.mozilla.org/show_bug.cgi?id=1512557) - de870b40934d33a433dfa97beb753ccdb6227693 (*)
- [ ] [Bug 1470716](https://bugzilla.mozilla.org/show_bug.cgi?id=1470716) - de870b40934d33a433dfa97beb753ccdb6227693 (*)
- [ ] [Bug 906469](https://bugzilla.mozilla.org/show_bug.cgi?id=906469) - 7339b4e15daff465a2a5ec7448a046773f03261d (*)
- [ ] [Bug 1342670](https://bugzilla.mozilla.org/show_bug.cgi?id=1342670) - f909c8e027701b13e2d4b1e322a9ea3e366aad85 (a)
- [ ] [Bug 1517464](https://bugzilla.mozilla.org/show_bug.cgi?id=1517464) - 57983839e345148c47eac2c5b7705874091452f9 (*)
- [ ] [Bug 393302](https://bugzilla.mozilla.org/show_bug.cgi?id=393302) - 4e86bfbd463e9def5f5ab35bbacdf15d6f3e76f8 (*)
- [ ] [Bug 393302](https://bugzilla.mozilla.org/show_bug.cgi?id=393302) - 7b25a285202e54ffaf2f48ba20bd81400ef9e0b7 (*)
- [ ] [Bug 1523048](https://bugzilla.mozilla.org/show_bug.cgi?id=1523048) -  4ca450b53a9806291288e3e7e1e38df3c3597396 (*)
- [ ] [Bug 1275400](https://bugzilla.mozilla.org/show_bug.cgi?id=1275400) - d3491169302da11cbf7df2933d0c47d140e8fe9b (*)
- [ ] [Bug 1402750](https://bugzilla.mozilla.org/show_bug.cgi?id=1402750) - 659aebc3be0f77b622f7b6a4454f15aa574d8631 (*)
- [ ] [Bug 1490331](https://bugzilla.mozilla.org/show_bug.cgi?id=1490331) - 659aebc3be0f77b622f7b6a4454f15aa574d8631 (*)
- [ ] [Bug 1515937](https://bugzilla.mozilla.org/show_bug.cgi?id=1515937) - cc4afb969e2873d30abf881a92ce9dcab2de8d26 (c)
- [ ] [Bug 1515937](https://bugzilla.mozilla.org/show_bug.cgi?id=1515937) - ec742ecac4f820f6e011e527f24ab13fd78aded4 (c)
- [ ] [Bug 1507218](https://bugzilla.mozilla.org/show_bug.cgi?id=1507218) - 90108dc6b09d73cd2115bbdf92aaa1c239220379 (*) [sec]
- [ ] [Bug 1528615](https://bugzilla.mozilla.org/show_bug.cgi?id=1528615) - 2ee39d69de34b0b44190e52963bcf9582533cda8 (*) [sec]
- [ ] [Bug 1525120](https://bugzilla.mozilla.org/show_bug.cgi?id=1525120) - 37443479768f225b4623f04ef5bb1044653c27fb (*)
- [ ] [Bug 1495698](https://bugzilla.mozilla.org/show_bug.cgi?id=1495698) - 46cea20c61a292d57570c0feb8f6c7985de264b3 (*)
- [ ] [Bug 1386601](https://bugzilla.mozilla.org/show_bug.cgi?id=1386601) - 480532c058f63d5740e919edbe65cd66fec09f5e (*)
- [ ] [Bug 1536268](https://bugzilla.mozilla.org/show_bug.cgi?id=1536268) - 6462b8f7c99db8d5012c7dc9d06b117955792efc (a)
- [ ] [Bug 1508054](https://bugzilla.mozilla.org/show_bug.cgi?id=1508054) - 8b4174b86aa456d2615249d3bdf0a976def14b2d (*)
- [ ] [Bug 1546840](https://bugzilla.mozilla.org/show_bug.cgi?id=1546840) - 2158945363aff867e410d8e1e38404afd1c44a58 (*)
- [ ] [Bug 1020971](https://bugzilla.mozilla.org/show_bug.cgi?id=1020971) - 6b0abef156d682c06a3c0abf1c783321997c24b5 (*) [cleanup]
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - c431335051b00b22173b12b7baa3607f94360703 (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - cb8355b78ba032ff71c6a3b3836deb968432e4b4 (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - 05f6a989c3645a4e47cad74a718a9f4900a6d637 (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - bfaad62c215d121f8624b8d117def7ece1cd42b7 (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - 2814aad2bb45decf26059d7fd5d26ddc1c4db8e1 (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - f8b300d3011f97482c1fd87defa2b1368a1031af (*/aw)
- [ ] [Bug 971347](https://bugzilla.mozilla.org/show_bug.cgi?id=971347) - 5cf8df691e4ad4f6df362f6a14173650e13eed0f (*/aw)
- [] [T6156](https://redmine.tails.boum.org/code/issues/6156) - 104ec51eaa0606e881d658a73f8df749db8a217a (*/aw)
- [] [T6156](https://redmine.tails.boum.org/code/issues/6156) - d4aade3a897dfeb7bc510a8e422841311b9c98f5 (*/aw)
- [] [Bug 522450](https://bugzilla.mozilla.org/show_bug.cgi?id=522450) - cfe6982da10a047ac5d9de143f4adc7ef2b4f27b (*/aw)
- [ ] [Bug 1167982](https://bugzilla.mozilla.org/show_bug.cgi?id=1167982) - dc317ab53e6fbe1e2d7042d12abcd101238d2317 (*)
- [ ] [Bug 1423487](https://bugzilla.mozilla.org/show_bug.cgi?id=1423487) - 76037d9e49f8a86edded81968f313ac6b73f2adb (*)
- [ ] [Bug 1528496](https://bugzilla.mozilla.org/show_bug.cgi?id=1528496) - 422f3eac00b97fca063e7f4a9ce73562ad109150 (*)
- [ ] [Bug 1526985](https://bugzilla.mozilla.org/show_bug.cgi?id=1526985) - 94ffe4920f5af84c54237af27680fe12549a7812 (*)
- [ ] [Bug 1480063](https://bugzilla.mozilla.org/show_bug.cgi?id=1480063) - 086135ab52c68e53474037558e96e217cc3d8065 (*) [cleanup]
- [ ] [Bug 1008735](https://bugzilla.mozilla.org/show_bug.cgi?id=1008735) - 355a9ba2308e76a8a0025d040614f235ea8d69e5 (c)
- [ ] [Bug 1008735](https://bugzilla.mozilla.org/show_bug.cgi?id=1008735) - e201ce67493fbb4b38f7833ce4e8947fa1e822b0 (c)
- [ ] [Bug 1494160](https://bugzilla.mozilla.org/show_bug.cgi?id=1494160) - 238e9ab0c389d06c0b31eec79ed6e4c3e27e671c (c)
- [ ] [Bug 1554098](https://bugzilla.mozilla.org/show_bug.cgi?id=1554098) - baefde0ccf813df16722ac67b1497ee491f85dde (*)
- [ ] [Bug 1553814](https://bugzilla.mozilla.org/show_bug.cgi?id=1553814) - bc8402f2aff2ac25befb8e3b1e9c8ac6c7d9fe72 (c) [sec]
- [ ] [Bug 334356](https://bugzilla.mozilla.org/show_bug.cgi?id=334356) - ce7351be7d85440ab632b3a35d92daf134e0290e (*) [cleanup]
- [ ] [Bug 334356](https://bugzilla.mozilla.org/show_bug.cgi?id=334356) - 85a895b336f9b774cac1593f2ec40f92d4e86b8e (*) [cleanup]
- [ ] [Bug 1338715](https://bugzilla.mozilla.org/show_bug.cgi?id=1338715) - 3fec713810fcf34382299c72bf616e8894015351 (*) [cleanup]
- [ ] [Bug 1552996](https://bugzilla.mozilla.org/show_bug.cgi?id=1552996) - 22dfc3ae566d6f985aeabe23c42713349aaf821f (c)
- [ ] [Bug 1553808](https://bugzilla.mozilla.org/show_bug.cgi?id=1553808) - d29146864449d95213c457f6c83d7248d7924d08 (c)
- [ ] [Bug 1553820](https://bugzilla.mozilla.org/show_bug.cgi?id=1553820) - 22d46125f45fa04fc2b2da2d154c5eb6bc10f43e (c)
- [ ] [Bug 1553820](https://bugzilla.mozilla.org/show_bug.cgi?id=1553820) - 6ef151077859bf42c34fcbb66df7f053eb40eb3b (c)
- [ ] [Bug 1555646](https://bugzilla.mozilla.org/show_bug.cgi?id=1555646) - 7feed426db9bf81e1f19da1eabd2ba68de485e1d (c)
- [ ] [Bug 680620](https://bugzilla.mozilla.org/show_bug.cgi?id=680620) - de78692d924b0deb2dbda7f4043f6772e344b07f (c)
- [ ] [Bug 1315662](https://bugzilla.mozilla.org/show_bug.cgi?id=1315662) - aaa6de4100e7fd7322fa2c2e2e4c2838742a1ebe (*)
- [ ] [Bug 1558595](https://bugzilla.mozilla.org/show_bug.cgi?id=1558595) - a21b9957f3d98e18f40c7854b2bdec05fdbaa955 (*) [sec]
- [ ] [Bug 1562832](https://bugzilla.mozilla.org/show_bug.cgi?id=1562832) - 5f1341f073b64f41ddad551dd3360635788be9eb (c)
- [ ] [Bug 1437282](https://bugzilla.mozilla.org/show_bug.cgi?id=1437282) - 5e5398d1e47395b540d864e81584b70948819a61 (*) [mime]
- [ ] [Bug 1438590](https://bugzilla.mozilla.org/show_bug.cgi?id=1438590) - e8528c852cc66ea6c5cac0abc9a30212ee56f343 (*) [mime]
- [ ] [Bug 1506587](https://bugzilla.mozilla.org/show_bug.cgi?id=1506587) - b89a0d3d164bc5e8ab9ab61753849668e6c7e078 (*) [mime]
- [ ] [Bug 1498795](https://bugzilla.mozilla.org/show_bug.cgi?id=1498795) - 08431f0d6f2414e313fbbe5b80642bc21cefd02f (*) [mime]
- [ ] [Bug 1568095](https://bugzilla.mozilla.org/show_bug.cgi?id=1568095) - 32bb5ab85cca8b24172bc443001446d4dc479703 (*) [mork]
- [ ] 7cf6eb6b3cba4677af73a19d390824c10797e924 (*/aw) [ID specific]
- [ ] [Bug 1580187](https://bugzilla.mozilla.org/show_bug.cgi?id=1580187) - 494f01d92d5eabf831e9849fafd65f699dc38dd3 (*) [sec/DiD]
- [ ] [Bug 1582411](https://bugzilla.mozilla.org/show_bug.cgi?id=1582411) - d8dfa7f8910721a6af0d73d01f227d9d1823d8ea (c)
- [ ] [Bug 1240290](https://bugzilla.mozilla.org/show_bug.cgi?id=1240290) - 80f58c7880e6279d98d0b1209f9fc2ec54961e4a (*) [sec]
- [ ] [Bug 1584473](https://bugzilla.mozilla.org/show_bug.cgi?id=1584473) - fa0f28a17065cb573ce45ac542a09e4453623f62 (*)
- [ ] [Bug 1584473](https://bugzilla.mozilla.org/show_bug.cgi?id=1584473) - b7fd2f133ee262cd5af6fa8da7b5e32143fd1bff (*)
- [ ] [Bug 1584473](https://bugzilla.mozilla.org/show_bug.cgi?id=1584473) - 5765eafde0a4c33a559317eddbe28b95be505c83 (*)
- [ ] [Bug 1584473](https://bugzilla.mozilla.org/show_bug.cgi?id=1584473) - 5063489863a96e66b0c60703af08964ed54a6eb0 (c)
- [ ] [Bug 786683](https://bugzilla.mozilla.org/show_bug.cgi?id=786683) - b1cd13ca94038cbd02c659160e567d874908a06f (*)
- [ ] [Bug 726655](https://bugzilla.mozilla.org/show_bug.cgi?id=726655) - 28e09e88c1a13064d8dd5d8033b25da2e8fe33fe (*)
- [ ] [Bug 1584473](https://bugzilla.mozilla.org/show_bug.cgi?id=1584473) - 20f781ee2a32bc03f624a36c897ce26cefa4134d (*) [mork]

**Comment by mattatobin** [comment]
4db1ae8 needed reverted for further research

**Comment by mattatobin** [comment]
Bug 1494764 is wrong and needs fixed

**Comment by mattatobin** [comment]
I'm not going to do [Bug 334356](https://bugzilla.mozilla.org/show_bug.cgi?id=334356) because I don't want to remove `nsIImportMimeEncode`.

**Comment by mattatobin** [comment]
https://github.com/binoc-graveyard/icedove-premerge/commit/7cf6eb6b3cba4677af73a19d390824c10797e924 should really be in IceDove's application preferences

**Comment by mattatobin** [comment]
The remaining bugs on the list are either application or calendar related plus a few to be researched.
