### ISSUE TITLE
Remove HPKP

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1280]
HPKP's adoption is very low, is being abused for ransoms (locking out visitors from sites through hijacking, and enabling this feature on the hijacked websites with the attacker's keys) and mainstream browsers have dropped it or will drop it soon.
In theory a good feature, but more of a risk and/or footgun in practice.

Some background: https://scotthelme.co.uk/the-death-knell-for-hpkp/

**Comment by wolfbeast** [comment]
Short-term, we should short-circuit this with a pref and kill the preload list. It's weaved in pretty good and removal must be done with care.

**Comment by wolfbeast** [comment]
Removing this from the 29.0.0 milestone. This will take more time than anticipated and shouldn't block the milestone.

**Comment by mattatobin** [comment]
UI Clean up required. @g4jc @Ascrod

**Comment by JustOff** [comment]
Do I understand correctly that this now belongs to the [28.11.0](https://github.com/MoonchildProductions/UXP/milestone/18) milestone?

**Comment by wolfbeast** [comment]
Yes, correct. I've been merging unedited redwood and master for 28.11 because we need to simplify the branches to keep overview.
Basically 28.11+ will be trunk minus webcomponents (and the outlier marquee because it's complicated to port to redwood)

**Comment by JustOff** [comment]
Ok, I will take this into account when preparing language packs.

String changes were pushed to CrowdIn.
