### ISSUE TITLE
Implement asynchronous iterators (ES2018)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1287]
I'm not entirely sure if we really need this; it seems very much a corner case use scenario.

But for standards compliance, we should at least investigate it.

Blocks #1282

**Comment by g4jc** [comment]
I really dislike Async Iteration because of the parser changes (it's what held back parser_tuneup branch before), but because I already have most of this logged I will attempt it again.

**Comment by wolfbeast** [comment]
As said I'm not even sure we need this for anything (aside from the potential Magpie Syndrome users)

**Comment by wolfbeast** [comment]
Blocks #1322

**Comment by wolfbeast** [comment]
The spec is a little unclear on some points so we've discussed things to get these in while dodging some potentially dangerous corner cases that Mozilla found by fuzzing (and which are using some things that would not be used in the wild) for which the solution were refactoring and potentially opening up much worse issues (including sec)

**Comment by wolfbeast** [comment]
@g4jc Were you going to open up a pull request for this or... ?

**Comment by g4jc** [comment]
I was awaiting confirmation that we landed all the additional spec you would like, but yes I can submit a PR. It builds and has the implementation inspired by FF57, avoiding a few refactors.

**Comment by wolfbeast** [comment]
Sorry if I wasn't entirely clear in my e-mail and the above comment in that case. We agreed the skipped bits were not actually all that relevant, and if they might become relevant in the future (although my suspicion will be that this entire feature won't see much use in the wild at all) then we can always revisit.

I was waiting on you since it blocks my intended cleanup work ;P
