### ISSUE TITLE
Option to disregard "high contrast" colors in Pale Moon on Windows

### ISSUE THREAD

**Issue by b9AcE** [MoonchildProductions/UXP#1299]
As Windows 10 no longer supports specifying color schemes natively any other way than enabling "high contrast" while the normal contrast option only covers some software and only parts of other software, the "high contrast" option is how many now set their color schemes to ensure as unified a look between applications as possible.
Unfortunately, it seems Pale Moon then has no option to completely disregard the background ("window") color of the "high contrast" setting and it seems when some pages don't explicitly set a background color, but only text colors, it will default to the background by the "high contrast" color scheme, which can make text and other elements unreadable.

I therefore propose there should be an additional option under "Preferences"→"Colors", to the effect of always completely disregarding the "high contrast" color scheme for the displayed pages' content and behaving as if it was not set at all, which none of the current options do, while of course respecting that colors setting for all other elements of the application.

**Comment by mattatobin** [comment]
I dunno how easy this would be since we use css selectors to control how the themeing responds. Such a feature cannot be limited to one application in scope.

**Comment by wolfbeast** [comment]
It is not our task to fix poor webdesign that sets one color (text) but not the other (background), effectively breaking any negative color scheme use, whether it be by accessibility features or forced dark theming.

**Comment by b9AcE** [comment]
It's surprising to hear that it's impossible to make Pale Moon capable of displaying such content the same way as the current versions of Chrome, Tor Browser and Opera does.

**Comment by mattatobin** [comment]
No one said it was impossible. Though your transparent ploy makes it even less likely that it would be revisited for consideration.

Thanks for playing!
