### ISSUE TITLE
The message manager script cache should be cleared when updating and removing add-ons

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1300]
Clearing the message manager script cache is necessary so that restartless add-ons are updated correctly and to prevent memory leaks when they are removed.

See the discussion on the forum starting from [here](https://forum.palemoon.org/viewtopic.php?p=178901#p178901).

**Comment by mattatobin** [comment]
Why is this including e10s code?

**Comment by JustOff** [comment]
This is because I'm not sure it's safe to skip the global broadcast of the flush event until other existing e10s things are removed from the platform. In any case, we will have to clean up the entire add-on manager as part of #953, so I think it would be better to do everything just then, so as not to break anything.
