### ISSUE TITLE
Clean up jemalloc code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1307]
The jemalloc code has a bunch of code in it that is never exercised or used for any supported platform, as well as some generally undesirable code. We should tidy this up to make it leaner and less complicated to read and maintain.

**Comment by wolfbeast** [comment]
This set of patches changes one thing for Linux targets (no longer using VLAs). Windows has the all-green but should be built and tested on Linux before merging.

**Comment by g4jc** [comment]
Will give this a try build in a few moments, but you may also want to check [this branch](https://github.com/g4jc/UXP/commits/jemalloc_patches) to see if there is anything you want to lift.

I did some of the same work while experimenting with FreeBSD and never got around to opening a ticket. Cleaning up the code made it considerably easier to debug what was going on there.

**Comment by wolfbeast** [comment]
No, there's a specific reason I did not do the same as Mozilla. Unlike them we have been using and __are__ using multiple arenas to take advantage of multi-core/multi-thread memory management. Secondly, I don't want to always hard-enable statistics because some applications might not want it in the future and I don't want to force poisoning for filling on (de)alloc for the same reason.

As for the [sysctl.h removal](https://github.com/g4jc/UXP/commit/3dbdb04420483b4dcca0f2a143ab4010971200e5) I'll have to ask @athenian200 since it's for other OS...? is this for *BSD again? Also what is this "follow-up" that has no description deleting `__pthread`?
Also, what advantage does having `moz_abort()` hard-coded instead of `abort()` have?

**Comment by athenian200** [comment]
The reason I added that ifdef is because Solaris/illumos lacks a sysctl.h header. This ifdef was there before Solaris support was removed, and is still needed. All the information I can find about it refers to Linux and BSD. It appears to be a kernel-specific interface. On Solaris/illumos, it's recommended to use POSIX or SysV semaphores for handling shared memory segments.  Additionally, JEMALLOC_USES_MAP_ALIGN appears to be required for all current versions of Solaris.

**Comment by wolfbeast** [comment]
Thanks.
Seems sysctl.h is a BSD-ism which means it should just go altogether. The patch is wrong anyway since testing for `__linux__` shouldn't be done, instead it should test for `MOZ_MEMORY_LINUX`, and the `_win32` test has no place there since it's already in a non-windows block.

**Comment by athenian200** [comment]
Mac OX X is BSD-based, though. I don't own any Macs or have any idea what the impact would be on that. @SpockFan02 do you know if MacOS needs sysctl.h?

**Comment by mattatobin** [comment]
Ping @adeshkp for macintosh insight as well.

**Comment by wolfbeast** [comment]
There's no mention anywhere of this in relation to OS X or Darwin, Only for *BSD (Free/Net/Open/Dragonfly-*) and Linux, afaict. But, I will defer to the Mac gurus in the house.

**Comment by mattatobin** [comment]
> [20191202.0606-29] <adesh> CaptainTobin I'll report about jemalloc stuff later in the evening, currently busy at work.

**Comment by adeshkp** [comment]
As expected, no issues seen on Mac. Checked Pale Moon and Basilisk both. Builds and runs are OK.

**Comment by mattatobin** [comment]
Thank you @adeshkp

**Comment by wolfbeast** [comment]
Various builds on various O.S.-es have been made without issues seen, so this got merged.
