### ISSUE TITLE
Display issue with tables

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1308]
Seems when a table is animated such as a fade in "it blanks the rect -after- it fades in". This is likely caused by changes to cairo or less likely the sticky table header work.

----

Screenshot:
![3ca40691-b273-4bb3-befe-8edb7b44f3af](https://user-images.githubusercontent.com/3889475/69905500-56bb1980-1382-11ea-8a75-b10fb79b34e1.jpg)

**Comment by wolfbeast** [comment]
I think it might be fallout from the table work done because of the simplification of table painting to use straight-up display lists. I think its a visibility issue that "optimizes away" the cell backgrounds over-zealously -- working on it.

**Comment by wolfbeast** [comment]
Confirmed it's because of the table work - Issue #146 Part 3 (a and b) need a third part to deal with background color to avoid display list collisions.

What I hinted at in the previous comment is also an issue, but unrelated to this painting problem so I'll deal with that separately.
