### ISSUE TITLE
Suppress more warnings from MSVC when compiling ICU

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1316]
When compiling ICU using MSVC, there are a lot of warnings about `' WIN32_LEAN_AND_MEAN ': macro redefinition`, which are of no use and only litter the console.

This was fixed by Mozilla in [bug #1370511](https://bugzilla.mozilla.org/show_bug.cgi?id=1370511), don't we want to do the same?

**Comment by g4jc** [comment]
Speaking for myself, I find the redefinition annoying log spam when trying to debug certain things, so I think suppressing it would be fine as long as no major refactoring or other things are needed to do it.

**Comment by wolfbeast** [comment]
If we're doing this, we may also want to make sure that -GR- isn't passed down to ICU since it requires RTTI to compile which spews a ton of useless command-line warnings as well.

**Comment by wolfbeast** [comment]
Tag #457

**Comment by JustOff** [comment]
> we may also want to make sure that -GR- isn't passed down to ICU

Unfortunately, this is beyond my skills.

**Comment by wolfbeast** [comment]
Took some trial and error but Tobin worked it out. I'll pour both into a commit to solve this.
