### ISSUE TITLE
Make MOZ_PHOENIX_EXTENSIONS pref controlled

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1318]
In Milestone 29 we want to make the Dual-GUID System have a controlling preference will be disabled by default unless the profile already contains an active Phoenix extension.

**Comment by wolfbeast** [comment]
Taking this.

**Comment by wolfbeast** [comment]
Unassigning myself to focus on other things first.

**Comment by wolfbeast** [comment]
With the various discussions happening around this topic it's been decided to make this an installation restriction and to change the way people are informed about compatibility mode add-ons so as to not break this for already-installed extensions. To do this properly would require a bigger rewrite of the add-on manager which should not be blocking progress at the moment.

**Comment by wolfbeast** [comment]
It was decided this isn't a good approach due to technical limitations of the code and how it's all been "optimized" by Mozilla, making it impossible to properly control the various parts with a pref.

**Comment by JustOff** [comment]
One way or another, I just hope all restrictions will be applied as gently as possible.
