### ISSUE TITLE
TeamWork UI not working now

### ISSUE THREAD

**Issue by danykey** [MoonchildProductions/UXP#1326]
Hi,

I have use Palemoon to navigate TeamWork (teamwork.com project managment software) for many years.

I guess that TeamWork was update the application JS and now Palemoon throws:
```
ReferenceError: event is not defined[Learn More]  
app.5ff87c384d3f050eacc6.js:1:63953
```

https://cdn-pjs.teamwork.com/tko-hybrid/static/js/app.5ff87c384d3f050eacc6.js

Tested on Palemoon 28.7.1 and Palemoon 28.8.0 
Arch: i686
OS: Ubuntu Linux 16.04

Stack trace:
```
[456] https://cdn-pjs.teamwork.com/tko-hybrid/static/js/app.5ff87c384d3f050eacc6.js:1:63953
	a https://cdn-pjs.teamwork.com/tko-hybrid/static/js/manifest.a35f52bd18176de49aa1.js:1:96
[460] https://cdn-pjs.teamwork.com/tko-hybrid/static/js/app.5ff87c384d3f050eacc6.js:1:66354
	a https://cdn-pjs.teamwork.com/tko-hybrid/static/js/manifest.a35f52bd18176de49aa1.js:1:96
[377] https://cdn-pjs.teamwork.com/tko-hybrid/static/js/app.5ff87c384d3f050eacc6.js:1:36514
	a https://cdn-pjs.teamwork.com/tko-hybrid/static/js/manifest.a35f52bd18176de49aa1.js:1:96
[436] https://cdn-pjs.teamwork.com/tko-hybrid/static/js/app.5ff87c384d3f050eacc6.js:1:43574
	a https://cdn-pjs.teamwork.com/tko-hybrid/static/js/manifest.a35f52bd18176de49aa1.js:1:96
	window.webpackJsonp https://cdn-pjs.teamwork.com/tko-hybrid/static/js/manifest.a35f52bd18176de49aa1.js:1:418
	<anonymous>
```

**Comment by danykey** [comment]
This issue also reproduced in Firefox 65. 
So, it's TeamWork code problem.

**Comment by danykey** [comment]
TeamWork developers recommend to update Firefox. 
So, for example, this bug not reproduced in Firefox 68 ESR and newer.

Could you fix this problem?

**Comment by mattatobin** [comment]
I recommend upgrading to a service that doesn't recommend abandoning your chosen browser to use it.

But you or them tell us what we need and it will be researched and considered.

**Comment by Sa-Ja-Di** [comment]
@danykey 

I suggest to ask the webmaster/maintainers of Teamwork if the page needs specific ecmascript  features to work properly - afterwards you can post the answers here.

**Comment by wolfbeast** [comment]
Stale for more than 3 months - closing for no follow-up
