### ISSUE TITLE
Issue with latest unstable - full themes not compatible

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/UXP#1329]
Updated to the latest unstable a bit earlier, and now i am unable to use a full theme, as constantly is stated, that they are "not compatible"

Thanks :)

**Comment by mattatobin** [comment]
For the record in case someone else asks.. Themes always use strict compatibility. Currently `Pale Moon` themes have a `maxCompatibility` of `28.*` which is strictly lower than `29.0.0a1`.
