### ISSUE TITLE
Places - throws an error: 0x80004005 (NS_ERROR_FAILURE) [nsIEditor.transactionManager]

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#133]
__Steps to reproduce:__

1) The main menu:
`Tools` - `Preferences` - `Privacy` - `History`:
[x] `Remember my browsing and download history`

2) The main menu:
`History` - `Clear Recent History...`:
`Today`/`Everything` - `Browsing & Download History` - `OK`

3) Go to: `https://www.palemoon.org/`

4) The main menu:
`History` - `Show All History`

5) Clicking right mouse button on an item `https://www.palemoon.org` in `History`,
clicking on `Delete This Page`.

6) Clicking on `History`:

__Throws an error in Browser Console:__
```
NS_ERROR_FAILURE: Component returned failure code:
0x80004005 (NS_ERROR_FAILURE) [nsIEditor.transactionManager]
editBookmarkOverlay.js:341
```

**Comment by wolfbeast** [comment]
What's the status of this?
