### ISSUE TITLE
loom videos cannot be played - Giving error on UXP based browsers

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/UXP#1331]
Topic opener
(https://forum.palemoon.org/viewtopic.php?f=3&t=23467)

has experienced that videos here for example do not work!
https://www.loom.com/share/6601f93702f3486aa2fe9f314f8b17e9

athenian200 confirmed that it is happening on UXP based browsers in general.

Justoff did additional research with the output:

Last bad: firefox-53.0a1.en-US.win32.zip (20161210063617)
First good: firefox-53.0a1.en-US.win32.zip (20161210082451)
Pushlog: f58f3fb82b - 6c34fef363
Suspect: bug #1244768 - Implement returning a Promise from HTMLMediaElement.play()

So, it is something which was implemented in Firefox 53 and still missing in UXP in general.

**Comment by wolfbeast** [comment]
Diplucate of #1332
