### ISSUE TITLE
Update NSS to a Goldilocks version

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1338]
We are currently using DBM in NSS for storing passwords and certificates.
DBM has been deprecated for use and will eventually be removed from NSS; even though we don't necessarily prefer using SQL database storage for this, we will have to move away from DBM if we are to continue using updated NSS library versions long-term, so we should move to using SQL.

NSS has built-in migration routines for this. We need to ensure that we update the surrounding SSL manager code to use the different format, and that the NSS version in use for migration supports the storage of rounds inside the DBM database for master passwords which should be part of NSS 3.48

**Comment by mattatobin** [comment]
I still don't want this.

**Comment by g4jc** [comment]
There's quite a bit of upstream bugs regarding profile corruption and master passwords being leaked after migration to SQL, we'll want to make sure and avoid that. Alternatively is it possible to update NSS and retain the existing DBM code? It might just be a matter of applying some patches.

**Comment by mattatobin** [comment]
3.48 MIGHT work in that configuration but after that libnssdbm is not going to be built by default so on the path to it's removal.

Thinking more on this, maybe we should try the upgrade keeping it on dbm and just backport patches from then on.. It would be easier to keep up with them on 3.48 than 3.41.

It is at least worth a shot.

**Comment by wolfbeast** [comment]
Hmm.. If there's a risk for db security with sql then keeping it on dbm is definitely better.

But, I certainly want to push an update because of spec changes and improvements; sounds like 3.48 is a "Goldilocks" version, offering most of the functionality we want without deprecating what we need. After 3.48 with dbm no longer being built there is a serious risk of bitrot since Mozilla will no longer be building (and testing) it by default.

**Comment by wolfbeast** [comment]
Initial tests with NSS 3.48, first by patching it and later by using the environment variables early in `nsAppRunner` are proving positive. This way we can continue to update NSS without much issue; dbm is needed for Mork (mailnews) so as long as it's present in NSS and not broken, we can keep using later versions in the future (with thorough testing of course to avoid the bitrot issues) and we can see about forking/downstreaming patches after that point in time.

For now, I'm happy with the results so far using the designated method of environment variables to pass run-time parameters to NSS. Since we are hardcoding `dbm:` in `nsNSSComponents` already anyway, there's no issue using additional params in `nsAppRunner` to go along with that until (when and if) the platform needs more flexibility at which point it can be made a build system variable.
