### ISSUE TITLE
Remove support for critical system libraries

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1342]
Our tree currently supports building with system libraries for a number of platform-critical functions that are neither tested nor supported, and have caused severe issues more than once on certain platforms (most notably *nix derivatives) due to broken dependencies or incompatible library versions. In most cases only a "minimum" version is supported, assuming at all times that later library versions are backwards compatible. In practice, this is not the case and the subtleties in differences between lib versions can lead to all sorts of build-time and run-time issues that are out of our hands but often take significant time to find the cause of.

We should remove most of our `--with-system-*` configuration options and enforce the use of known-good in-tree versions of the libs in question.

**Notable removals:**
- [x] NSPR and NSS: We can't rely on this being usable since many platforms (out of necessity) patch or will patch these libs in the near future to remain usable and/or have to force different build parameters for system use. e.g. we require dbm support that isn't built by default in 3.49+
- [x] libevent - known incompatibilities causing crashes with certain version/application combinations.
- [x] ICU - system ICU will break JS Intl.
- [x] sqlite - at the core of our profile manipulation, places, and many functions. If the lib API ever deviates in the slightest it will kill us.
- [x] libpng for APNG and misc fixes
- [x] libvpx for strict compat

**Undecided:**
- compressor libs (zlib, xz, libbz2, etc.)
- image decoders (libjpeg, libwebp, etc.)

**Notable exceptions:**
- cairo: system-cairo is required on some platforms. Our in-tree cairo is heavily modified and primarily focused on Windows use, which may not play nice with some *nix environments.
- pixman: similar reasoning to cairo, and system-cairo depends on system-pixman.
- libffi - Used exclusively from chrome code js-ctypes; if wrong/incompatible, will likely break extension functionality that relies on js-ctypes, but isn't available on all architectures with our in-tree code.

**Comment by wolfbeast** [comment]
@mattatobin Updated the list after researching. Did I miss anything? What do you think about the "undecided" category?

**Comment by mattatobin** [comment]
libpng has to be ours. Same with libvpx.
