### ISSUE TITLE
Potential hang on bad FTP sequence

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1349]
FTP servers should always send a 1xx response before a 2xx response in the case of `LIST`, `RETR` and `STOR`. Our code assumes this is always the case but bad FTP servers might not adhere to the FTP spec which would result in a hang.

[This bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1584490) handles the `LIST` case; the exact same method should be used for the other 2 cases to make it complete.

Good first issue for whomever wants to try their hand at this since it's a very simple fix, otherwise anyone else can take it.

**Comment by mattatobin** [comment]
@athenian200 is gonna look into this. See what happens.

**Comment by wolfbeast** [comment]
From the commit comment:
> Even though it makes no logical sense for a server to say an action was completed before it was initiated

For FTP, it does and is in fact part of the protocol and needed because of the separate data channel;  it needs to respond with a 1xx confirmation of the command and that a data channel is being opened for the actual transfer, then send a 2xx when the transfer is completed.
A poor/buggy FTP server implementation sending the 2xx response immediately would confuse the logic prior to this patch.
