### ISSUE TITLE
Forms: Click() isn't executing properly when elements are defined disabled

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1356]
There are two controls for elements being disabled/enabled which can confuse event handlers. `@disabled` is what is usually used to set an element disabled or not from js, `-moz-user-input: disabled/enabled` resulting from raw element properties.

We currently look at the `-moz-user-input` attribute; this is normally not manipulated by websites and can remain in the wrong state when enabling controls in forms through js, resulting in not registering the event the first time since the state is still incorrect during the event.

This is an old bug going back to at least Gecko/20. Mozilla solved this by removing `-moz-user-input: enabled/disabled` making everything use a single control. We should follow that.
Potential impact on the web would only be where websites would use Mozilla-prefixed css properties (which would have broken when Mozilla landed this) so that should be of no consequence.

Relevant BZ bug: [1405087](https://bugzilla.mozilla.org/show_bug.cgi?id=1405087)
Forum thread (title misnomer): https://forum.palemoon.org/viewtopic.php?f=29&t=23587#p181959

**Comment by wolfbeast** [comment]
So you've done some work, and opened+closed a PR for this... what's going on here?

**Comment by mattatobin** [comment]
It is slightly incomplete and collides with the big work going on.
