### ISSUE TITLE
Simplify and streamline HWA on various OSes

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1360]
Following discussion with @mattatobin and further evaluation of the state of HWA on Linux, it was decided that things should be simplified for HWA and directly accessible from the preferences UI.

- Simplify the prefs to `layers.acceleration.enabled` and `layers.acceleration.force`
- Link the UI control for HWA to `layers.acceleration.enabled`
- Expose the `force` pref additionally in the UI on Linux

HWA should be enabled on Windows and disabled on Linux by default.
~~Change of the pref should spawn a restart prompt.~~

Tobin indicated that he'd write the pref migration bit for upgrades once the functionality is in.
@g4jc Please take note of this for Hyperbola projects, as the changed prefs will need UI updates.

**Comment by mattatobin** [comment]
How are we gonna do the restart prompt behavior? Do any changes in UI preferences do this? Not that I am opposed to it by any means.

**Comment by JustOff** [comment]
The same questions also occurred to me. I somehow doubt that changing the pref should spawn a restart prompt.

**Comment by mattatobin** [comment]
It should because a restart is required for a change in the prefs to take effect.

**Comment by athenian200** [comment]
Well, I think it will probably be fine to leave this enabled on Solaris, for two main reasons:

1. Usually on Solaris machines, there's not a lot of graphics drivers. Basically only proprietary nVidia driver working with X11, and it's quite limited, but fairly reliable. So there's no ATI stuff, no nouveau, etc. It has limited hardware compatibility, but what it does have is rock solid.

2. Of the ones that aren't using nVidia drivers, hardware acceleration just wouldn't be available at all because it's likely a headless X11 server or a VM.

All I know is, it works fine on my machines I've tested that have nVidia cards installed.

**Comment by JustOff** [comment]
The only similar case I can remember is installing and removing non-restartless extensions, and even there, an inline notification is used instead of a restart prompt.

**Comment by mattatobin** [comment]
This would be new functionality. There ARE other prefs that require an application restart. Of course, this would be enforced on a per-application basis but it makes sense.

**Comment by JustOff** [comment]
Not that I am opposed to it by any means (с), just shared my doubts.

**Comment by wolfbeast** [comment]
There are other options that spawn a restart prompt, like enabling FIPS mode if I recall correctly.

**Comment by wolfbeast** [comment]
@athenian200 Re; Solaris, that's good news! So we can be pretty confident it will just work because people are using solid and complete drivers.

**Comment by wolfbeast** [comment]
Alternatively, we can of course just add a line to the preferences dialog that a restart is required for the change to take effect. This is the case regardless of O.S. and has confused many people over time anyway, so we can just be informative? We can always look at adding a forced restart prompt later, if needed.

**Comment by wolfbeast** [comment]
@mattatobin Since I need to touch the front-end anyway for this, it's probably easier if I do the pref migration in one go while I'm in there. That way things can just be landed in one go.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by wolfbeast** [comment]
This should be complete.
Closing.
