### ISSUE TITLE
Appcrash executing 0x0 when visiting avvo.com

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1362]
https://forum.palemoon.org/viewtopic.php?f=3&t=23646

Crashing URL: https://www.avvo.com/legal-answers/could-i-use-the-superman-logo-for-my-business-if-i-3325520.html

The program crashes trying to execute the instruction at 0x0 which is (obviously) protected memory.
No crashing module given; the address in the debugger output which is the only piece of information we have to go on lies outside our components. Crashing window when reproducing indicates it may be a data block which would be nulled by DEP in the OS.

Preliminary component is JS as it seems to be caused by a script on `consent.trustarc.com`

When executing from a built source the JIT debugger won't function as the application closes upon attaching the debugger to the crashing process. When run on a standalone release binary, there is no obvious usable information.

**Comment by athenian200** [comment]
The crash doesn't occur in 28.7.2, and as far as I can tell, the issues start after changes to the RegExp engine made to resolve this issue: https://github.com/MoonchildProductions/UXP/issues/1279

I'm not an expert on this kind of thing, all I could really tell from testing various intermediate builds is that the changes here line up with approximately when that website starts crashing, though I can't tell whether that's the core issue or what exactly is causing it to try and execute protected memory. I hope this information is helpful.

**Comment by JustOff** [comment]
Nice catch! I can confirm that reverting #1279 commits eliminates the crash.

**Comment by wolfbeast** [comment]
Hah, I independently came to the same conclusion after attaching a debugger and running a few scenarios.

**Comment by wolfbeast** [comment]
So, there's an issue with the lookbehind implementation in the regexp parser code sourced from Google.

**Comment by wolfbeast** [comment]
Backout should be uplifted to Release.

**Comment by wolfbeast** [comment]
Uplifted in [ea51616e3] and [35dc8e5abb]

**Comment by JustOff** [comment]
I leave here a snapshot of the page which crashed in case someone needed it later when re-landing regex lookaround.

[www.avvo.com_crash_page.zip](https://github.com/MoonchildProductions/UXP/files/4087614/www.avvo.com_crash_page.zip)
