### ISSUE TITLE
Remove showModalDialog

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1366]
As per [IRC](https://freenode.logbot.info/binaryoutcast/20200122#c3122253-c3122304) discussion, this blocks #1344. It was disabled in PM 27.6.0 and was a useless proprietary IE4 feature that nobody uses anymore and the existing implementation doesn't even work.

https://docs.microsoft.com/en-us/previous-versions/ms536759(v=vs.85)

**Comment by wolfbeast** [comment]
Unfortunately building on windows is busted with this merged.

```
54:57.29 nsGlobalWindow.obj : error LNK2019: unresolved external symbol "public: static struct alrea
dy_AddRefed<class nsGlobalWindow> __cdecl nsGlobalWindow::Create(class nsGlobalWindow *)" (?Create@n
sGlobalWindow@@SA?AU?$already_AddRefed@VnsGlobalWindow@@@@PAV1@@Z) referenced in function "public: v
irtual enum nsresult __thiscall nsGlobalWindow::SetNewDocument(class nsIDocument *,class nsISupports
 *,bool)" (?SetNewDocument@nsGlobalWindow@@UAE?AW4nsresult@@PAVnsIDocument@@PAVnsISupports@@_N@Z)
54:57.29
54:57.29 nsDocShell.obj : error LNK2001: unresolved external symbol "public: static struct already_A
ddRefed<class nsGlobalWindow> __cdecl nsGlobalWindow::Create(class nsGlobalWindow *)" (?Create@nsGlo
balWindow@@SA?AU?$already_AddRefed@VnsGlobalWindow@@@@PAV1@@Z)
54:57.29
54:57.29 nsGlobalWindow.obj : error LNK2019: unresolved external symbol "protected: void __thiscall
nsGlobalWindow::InitWasOffline(void)" (?InitWasOffline@nsGlobalWindow@@IAEXXZ) referenced in functio
n "public: static struct already_AddRefed<class nsGlobalChromeWindow> __cdecl nsGlobalChromeWindow::
Create(class nsGlobalWindow *)" (?Create@nsGlobalChromeWindow@@SA?AU?$already_AddRefed@VnsGlobalChro
meWindow@@@@PAVnsGlobalWindow@@@Z)
54:57.29
54:57.29 xul.dll : fatal error LNK1120: 2 unresolved externals
```

**Comment by wolfbeast** [comment]
Looks like you may have removed too much in nsGlobalWindow (i.e. the implementations of `::Create` and `::InitWasOffline`)! Did this build on Linux? I would be surprised if so...

**Comment by wolfbeast** [comment]
Fixed the build bustage but please check if that would be all of it.

**Comment by g4jc** [comment]
Sorry about that, I had the same commit stashed locally but it didn't get uploaded on the PR branch. As far as I know that is all of it, it builds fine here as well.

**Comment by wolfbeast** [comment]
Okay, thanks for confirming.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
