### ISSUE TITLE
Unity Web Player opens in a separate Plugin Container window

### ISSUE THREAD

**Issue by SuperBobb** [MoonchildProductions/UXP#1368]
Hello.
I've noticed a strange behavior when a web page containing a Unity game is getting opened with the Pale Moon browser form the desktop (using a shortcut or the command line).
In that case the opened page displays the Unity loading progress bar but then the game itself is displayed outside the browser, in a some kind of frameless overlay window stick to the top-left (0,0) coordinate in the main desktop. I cannot move this extra window, although it is represented on the Taskbar with the "Unity Web Player" title. If I right-click this Taskbar item, it displays the context menu with the "Plugin Container for Pale" first menu item (does nothing if I click it).
If I then click the browser's Reload button the web page is reloaded and the game is displayed inside the page as it should be displayed. And if I just type the web page's url in a new tab (when the browser is already running) the game is displayed properly again. That Plugin Container window is displayed only when the browser wasn't running but was started manually with a game's url.
For example, this is a page with a Unity game that I used for testing: https://ru.y8.com/games/speed_rally_pro_2. 
You can try to open it from the command line:
`"C:\Program Files (x86)\Pale Moon\palemoon.exe" https://ru.y8.com/games/speed_rally_pro_2`
And you'll see the behavior I've described here. The same issue occurs on other computers I have access to, both in the installed and portable versions of the Pale Moon browser, for this and for all other Unity games. Meanwhile it is working properly with other browsers (IE, Maxthon) whenever I start then from the command line or type a url in the address bar (so that's not the issue with the Unity Web Player plugin).
I can provide you with the screenshots if you wish.

**Comment by wolfbeast** [comment]
I've tried reproducing this but it just opened a normal browser window, and loaded the game in the web page properly placed.
![image](https://user-images.githubusercontent.com/3359132/74603529-8c83ba80-50b4-11ea-8490-73dc3b17f749.png)

**Comment by wolfbeast** [comment]
@SuperBobb please go to the forum to go through regular troubleshooting steps (including providing troubleshooting information and any details about your system setup that might interfere like sandboxing applications or non-standard shell extensions, etc. and see if others are able to reproduce your issue reliably. There's currently nothing to go on here.

**Comment by wolfbeast** [comment]
Closing; no followup.
