### ISSUE TITLE
Filter action "Move Message to" missing the option to choose folder

### ISSUE THREAD

**Issue by laniakea64** [MoonchildProductions/UXP#1377]
**Environment**

Interlink 7333 (other UXP mailnews applications are also affected)
Xubuntu 18.04 64-bit
new profile

**Steps to reproduce**

1) set up an email account and open its Inbox folder

2) Tools > Message Filters, click "New..."

3) Under "Perform these actions", look at the existing "Move Message to" action

**Expected results:** Should be able to pick which folder to move messages to

**Actual results:**

There is no option to select which folder to move messages to.  There is just a blank space where the folder selection should be.

Relevant Error Console message -
```
Error: ReferenceError: Ci is not defined
Source File: chrome://messenger/content/searchWidgets.xml
Line: 228
```

Workaround: select some other filter action, then set it back to "Move Message to".

**Comment by wolfbeast** [comment]
@mattatobin 
This is probably Interlink front-end?

**Comment by wolfbeast** [comment]
Looks like the shorthand `Ci` isn't defined; we probably just want to use the longhand `Components.interfaces` there.

**Comment by mattatobin** [comment]
That should do nicely. comm historically has resisted defining shorthand for these. Guess that has changed in recent years.

I'll patch shortly.

**Comment by mattatobin** [comment]
Possible uplift should we do another point release.

**Comment by laniakea64** [comment]
> That should do nicely.

I confirm that fixed it.  Thanks for the fast fix! :smiley:
