### ISSUE TITLE
Findbar is busted

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#138]
The findbar is busted again.. Looks like they e10sified it..

See: https://github.com/mozilla/gecko-dev/commits/esr52?after=d2fc5db6dba36a9e6f81545b02eb3777bd7f5fd1+34&path[]=toolkit&path[]=content&path[]=widgets&path[]=findbar.xml March 11th, up.

@janekptacijarabaci ?

----
Blocks #57 and #121

**Comment by janekptacijarabaci** [comment]
I'm sorry, I can't do it now.

**Comment by mattatobin** [comment]
Heh, yeah i didn't say right this second. Just when you get to it if it isn't gotten to by someone else before then :P

**Comment by janekptacijarabaci** [comment]
Thank you.

I've been here for a while (I'm working on it)...

**Comment by janekptacijarabaci** [comment]
I'm busy...

Some temporary code:
[tree@pm_findbar_1](https://github.com/janekptacijarabaci/UXP/tree/pm_findbar_1)

Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1133981
https://bugzilla.mozilla.org/show_bug.cgi?id=1154799
https://bugzilla.mozilla.org/show_bug.cgi?id=1320095

Also:
http://xref.palemoon.org/uxp-trunk/source/toolkit/modules/Finder.jsm#49

Tested very swiftly, only...

Throws an error:

```
Error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED)
[nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"
location: "JS frame :: chrome://browser/content/browser.js
:: onLocationChange :: line 10377"  data: no]
```
