### ISSUE TITLE
Remove "copy raw data" from about:support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1383]
People, when asked to copy troubleshooting information for support purposes, keep insisting on using "raw data" instead of "text" even when asking to copy text, from the troubleshooting information page. Most likely this is because it's the first button of the two they see on the page.

The json format is annoying to read and we never use it in any sort of process that consumes json, so there's no real reason to keep this option alongside the "as text" option.

**Comment by wolfbeast** [comment]
@JustOff some strings were removed from l10n here.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
