### ISSUE TITLE
Get rid of the Presentation Web API

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1390]
This has been a WIP in Gecko since 42. It's never been enabled on release versions, and really is more gadgeteering to pollute the code base with unnecessary proprietary messaging systems.

Do we care about sending pages to Chromecast, Roku or DIAL-enabled devices? Nope.
Do we need to be able to talk to "Smart TVs"? Nope.

The 2-UA setup is dead anyway since we have no counterpart "apps" that could run on smart displays.

**Comment by mattatobin** [comment]
Blocks #1391
