### ISSUE TITLE
Re-implement JPEG-XR decoder

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#144]
WebP is already in our tree, but we should port JXR decoding from Pale Moon.

**Comment by wolfbeast** [comment]
Looks like the decoder needs some serious work because Mozilla moved to using so-called "lexers" for images.

**Comment by JustOff** [comment]
Until this is done, we need to remove `image/jxr` from `image.http.accept` when migrating the profile from PM27, see "[Images do not appear](https://forum.palemoon.org/viewtopic.php?f=63&t=19412)" on the forum.

**Comment by mattatobin** [comment]
RESOLVED WONTFIX

**Comment by wolfbeast** [comment]
Just to add to the wontfix:
Edgium doesn't support JPEG-XR anymore so the chances of JPEG-XR being broadly supported are basically zero.
