### ISSUE TITLE
Please extend disabling DNS prefetching to HTTPS/expose the pref for it.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1443]
You have set _network.dns.disablePrefetch_ to _true_ already, which is a good and sensible default. However, I want to hint at the fact that a new boolean _network.dns.disablePrefetchFromHTTPS_ must be created and set to _true_ if this is to be extended to HTTPS. Please consider.

Thank you for your attention and support.

**Comment by wolfbeast** [comment]
Please see http://xref.palemoon.org/moonchild-central/source/platform/dom/html/nsHTMLDNSPrefetch.cpp#68

The default value if the pref doesn't exist is `true` meaning it's already disabled by default.

**Comment by Peacock365** [comment]
Well, that's great! Last question would be: Do you think that it would be worthwhile to unhide this setting by default, even though the default value wouldn't change?

**Comment by wolfbeast** [comment]
I'm not sure in what way exposing this pref would help anyone. It's not like one would need easy access to it if it's already at a desirable default for 99.9% of people :)
As it is we already have too many exposed prefs in about:config, and I don't particularly feel for exposing more, but feel free to ask our community on the forum for feedback. I'll leave this issue open in the meantime.

**Comment by wolfbeast** [comment]
In case you missed it this requires you to take action on the forum, @Peacock365
If this goes stale otherwise the question to expose it will be closed and nothing will happen.

**Comment by wolfbeast** [comment]
No action was taken in the past fortnight. closing.
