### ISSUE TITLE
Clarify status of Firefox extensions in add-on manager

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1445]
The `•` indicators currently used need to go, and be replaced with a more clear warning about legacy Firefox extensions that are installed.

Blocks #1444

**Comment by wolfbeast** [comment]
@JustOff Please take note of the string changes here.

**Comment by Lootyhoof** [comment]
Please also tag this for `Theme Changes` as it touches `toolkit/themes`.

**Comment by wolfbeast** [comment]
@Lootyhoof Of course. sorry!

**Comment by JustOff** [comment]
@wolfbeast, could you please clarify to what `%1$S was not designed for %2$S` is closer in meaning in our context:

`%1$S was not intended to be used in %2$S` or `%1$S was not developed for %2$S`?

**Comment by wolfbeast** [comment]
Both, to be fair, but primarily `...not developed for`. Using the other wording, people are likely to twist it into us saying "we don't want you to" resulting in moral outrage, which I want to avoid.

**Comment by JustOff** [comment]
Thanks. I asked, because not all languages have an analogue of the verb "designe", which would contain all these shades, so we have to choose the main one for translation.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by Lootyhoof** [comment]
I've had chance to fully look into this now, and I'm not happy with the current design. On Windows, it looks inconsistent:

![Windows](https://i.imgur.com/aLFSEzb.png)

On Linux, it looks outright garish:

![Linux](https://i.imgur.com/7jdAe10.png)

Instead of just moaning though, I'd like to propose a different take on this. Why not the below instead?:

![Proposed new design](https://i.imgur.com/wcxC11q.png)

This way also, any compatibility issues are separated from any other warnings, which keeps things visually separate in case there ARE warnings around, that users may otherwise ignore.

I'm happy to implement this if you're willing to accept it.

**Comment by mattatobin** [comment]
I think the only issue is the extra warning sign. Also, any other compatibility issues are of higher priority than the general Firefox extension message.

**Comment by wolfbeast** [comment]
The warning sign is a standard unicode code point. Linux might have a terrible "garish" font rendering. No idea why it's pink of all things. 
But yeah it's pretty much redundant at this point -- I didn't start off with the actual warning and used the previous indicator element (the dots) to have a warning, but all of that can just go at this point, anyway.

**Comment by wolfbeast** [comment]
Reopening for cleanup.

**Comment by wolfbeast** [comment]
I'll take this myself and finish it up.

**Comment by wolfbeast** [comment]
Will build new unstables today with it.

**Comment by JustOff** [comment]
Apparently then we can also safely remove these strings:

https://github.com/MoonchildProductions/UXP/blob/43d44975b1f49df640916cca5f6a0b138696da3c/toolkit/locales/en-US/chrome/mozapps/extensions/extensions.dtd#L214-L215

**Comment by JustOff** [comment]
I have one more idea, how about providing a `_warningLink` pointing to [this](https://forum.palemoon.org/viewtopic.php?f=46&t=23697)?

![palemoon_2020-02-19_16-39-02](https://user-images.githubusercontent.com/340855/74844911-dd0a4a80-5336-11ea-8401-c856da4713fb.png)

I can submit a PR if you find it useful.

**Comment by mattatobin** [comment]
That could be a good idea for it to link to the forum post.
