### ISSUE TITLE
Only allow extension class add-ons to use the dual-GUID system

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1446]
Of the various add-on types, only extensions should be allowed to use the dual-GUID system/Firefox compatmode.
So far we've allowed e.g. Firefox full themes to be installed as well but that can't reasonably be continued due to compat issues.

Blocks #1444

**Comment by wolfbeast** [comment]
Unless I'm mistaken, the one-liner change in [e8417ac] should do it?

**Comment by JustOff** [comment]
It seems so.
