### ISSUE TITLE
Drop an Atomic Bomb on Windows Maintenance Service

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#145]
We have tried fire and acid and it keeps coming back.. Time to pull out that ol' 1952 special.

----

_LAST TIME ON MOZ_MAINTENANCE_SERVICE_

https://github.com/MoonchildProductions/Pale-Moon/commit/4c7fc4f188e52e365ca3323c55cb0499b34ce89a
https://github.com/MoonchildProductions/Pale-Moon/commit/83044bbb69c7d48e5fb9679622062f27eeb9169b
https://github.com/MoonchildProductions/Pale-Moon/commit/e3299799b1ed4b741a562b5499248be24ce9ddea
https://github.com/MoonchildProductions/Pale-Moon/commit/dd88f4376e7f0675247480c3608293c4e065946f

----
AND NOW, THE CONCLUSION!

- [x] Remove conditional MOZ_MAINTENANCE_SERVICE code
http://xref.palemoon.org/moebius-trunk/search?string=MOZ_MAINTENANCE_SERVICE
- [x] `toolkit/mozapps/update/nsUpdateService.js`
`isServiceInstalled`
`useService`
`shouldUseService`
- [x] Non ifdef'd code from `toolkit/mozapps/updater/updater.cpp`
- [x] Remove `toolkit/components/maintenanceservice/`
- [x] `Basilisk` Windows Installer

**Comment by wolfbeast** [comment]
Taking this

**Comment by JustOff** [comment]
It seems this somehow broke the updater, see https://forum.palemoon.org/viewtopic.php?f=5&t=21520.

```
NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]  
utilityOverlay.js:570
	buildHelpMenu chrome://browser/content/utilityOverlay.js:570:7
	onpopupshowing chrome://browser/content/browser.xul:1:1
```

**Comment by wolfbeast** [comment]
So
```JavaScript
  var um =
      Components.classes["@mozilla.org/updates/update-manager;1"].
      getService(Components.interfaces.nsIUpdateManager);
```
fails for some reason.
