### ISSUE TITLE
Implement optional catch binding (ES2019)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1465]
Since websites are _going_ to use this because it saves a few keystrokes, this inconsistency-promoting spec will have to be implemented; if not, the resulting syntax error will break those websites.

**Comment by wolfbeast** [comment]
Making it optional was fairly simple. Performed some basic tests in the console and calling up a known-bad website (chat.mozilla.org actually used it - got a blank screen... :P )

**Comment by JustOff** [comment]
OMFG, you call this simple? :upside_down_face:

**Comment by wolfbeast** [comment]
I said _fairly_ simple.

Look at the surrounding code, we already had things in place that were optional because of Mozilla's `catch (error if condition)` construct. It just needed to be applied to the first node in a similar way; the only additional thing needed was making the actual existence of the whole parameter block optional.

**Comment by wolfbeast** [comment]
Uplifted for release in 9f04e24
