### ISSUE TITLE
NSS db back-end flexibility

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1467]
We're currently forcing DBM use with a prefix on initializing NSS.
It does look like at least for Basilisk and Pale Moon we should move to SQL storage format anyway due to the performance issues with handling more rounds for PBKDF and further deprecation in NSS of the lib.
Other applications might not want this or not at the same time, so we'd need a build-time config parameter to determine which db format needs to be used.

**Comment by wolfbeast** [comment]
The first step is to create a usable SQLite back-end build, but additional work is needed to set up the tree for SQL use avoiding potential usability issues. The work needed for this is referred to in https://github.com/MoonchildProductions/UXP/issues/265#issuecomment-395039106

I intend to first use the workaround for forced initialization of mozstorage to prevent the sql_config race, and afterwards solve this is a more generic way.
Unlike what Mozilla has done, this will remain a build-time option (not pref-controlled) to prevent the undesired situation of users trying to switch aback-and-forth between the back-eds (which is asking for a can of worms being opened and spilled all over the floor).

**Comment by wolfbeast** [comment]
As it turns out, the bugs linked to in the referred comment are additional enhancements and not prerequisites or bugs that need fixing, with the exception of the sqlite_config patch to remove the workaround by ensuring no race a different way; however that one is using a construct that is incompatible with our code and build environment, so we are simply going to have to continue to use the mozStorage initialization workaround to prevent the race. This means that what we have now is all that's needed to make UXP applications capable of switching to sqlite.

**Comment by JustOff** [comment]
This looks promising, but I still don't quite understand why the last time we tried to switch to the SQLite backend, we had a problem closing the browser. Is it really the only thing we were missing was to eliminate the race condition during initialization?

**Comment by mattatobin** [comment]
Why did we have so much trouble before? Lack of primary knowledge while feeling under the gun on this. That is what went wrong.

This time we can do it at our own pace fully exploring all repercussions and effects especially knowing all the soft points to poke at to make sure it works properly.
