### ISSUE TITLE
Pale Moon cannot be built on SPARC64 Linux

### ISSUE THREAD

**Issue by JMadgwick** [MoonchildProductions/UXP#1471]
Attempting to build Pale Moon on Linux with SPARC64 architecture results in build errors. These are caused by incorrect compiler definitions. These problems can be fixed using patches from [bugzilla bug #1275204](https://bugzilla.mozilla.org/show_bug.cgi?id=1275204).
Pale Moon is then able to build on SPARC64, [see Pale Moon Forum](https://forum.palemoon.org/viewtopic.php?f=5&t=23934).

**Comment by mattatobin** [comment]
So is this fixed now?

**Comment by JMadgwick** [comment]
Yes, the pull request has been merged so this is no longer a problem. Apologies for not closing this already.

**Comment by mattatobin** [comment]
Please don't close issues yourself also thanks!
