### ISSUE TITLE
Captive Portal Detection cannot be pref'd off

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1474]
Received a user report via e-mail that setting `network.captive-portal-service.enabled;false` does not actually have any affect in all UXP browsers and still occasionally polls the detect server. They traced this back to [m-c bug 1359697](https://bugzilla.mozilla.org/show_bug.cgi?id=1359697), but that's already in our tree. I assume there may have been a follow up as users in that ticket also reported that the proposed fix did not solve the issue.

Worth investigating at some point.

**Comment by wolfbeast** [comment]
On it.

**Comment by wolfbeast** [comment]
Since I can't reproduce this from my workstation and there's no STR, I can't verify, but this _should_ fix it.

**Comment by wolfbeast** [comment]
Reopening for verification.

**Comment by wolfbeast** [comment]
Latest unstable has the fix in; maybe you can ask your reporter to check so it can be verified.

**Comment by wolfbeast** [comment]
28.9.* has this fix in. @g4jc _please_ report if this is fixed for your contact so this issue can be closed.

**Comment by wolfbeast** [comment]
Assuming fixed without further feedback. closing. Please reopen if not fixed.
