### ISSUE TITLE
Python can't find config.guess on builds not using MOZ_OBJDIR

### ISSUE THREAD

**Issue by dbsoft** [MoonchildProductions/UXP#1477]
During ./mach configure a python errno 2 No such file or directory is raised when building using the newly separated Pale Moon/Basilisk and UXP. 

Result: OSError: [Errno 2] No such file or directory File "/Users/..../work/github/dbsoft/Basilisk/platform/python/mozbuild/mozbuild/base.py", line 364, in resolve_config_guess
Expected result: No error.
Steps to reproduce: Checkout Pale-Moon or Basilisk, git submodule init && get submodule update && ./mach configure
Affected versions: Pale Moon 29 and current Basilisk
Affected environments: All macOS versions

Adding 'platform' to line 354 fixes the problem, can anyone test if this change breaks other platforms?

p = os.path.join(self.topsrcdir, 'platform', 'build', 'autoconf', 'config.guess')

**Comment by mattatobin** [comment]
Blocks #1469

**Comment by mattatobin** [comment]
This needs to be backwards compatible.. Please check for file existence of p at 
`build/autoconf/config.guess`
-or-
`mozilla/build/autoconf/config.guess`
-or-
`platform/build/autoconf/config.guess`.

**Comment by mattatobin** [comment]
You need to slow the hell down and stop trying to shove patches at me.

**Comment by dbsoft** [comment]
I figured that is what the drafts were for, so people could grab the draft and see if it works or needs changes... but sure.  Will do.

**Comment by mattatobin** [comment]
You really should stop assuming things and trying to rush. This isn't an emergency or a crisis dude.

**Comment by mattatobin** [comment]
See a similar situation @ http://xref.palemoon.org/moonchild-central/source/platform/python/mozbuild/mozbuild/controller/clobber.py#54 for reference.

**Comment by dbsoft** [comment]
Thanks I'll look into making the change you requested to check the multiple locations.   I don't think I am rushing or acting like it is an emergency I am trying to use the tools that you use for the project as you instructed.   I am sorry I used the draft PR incorrectly but I see no direction explaining anywhere when they are supposed to be used.

**Comment by mattatobin** [comment]
Do you use IRC? Perhaps it would be beneficial to come around to my channel on freenode for a crash course. This is really the kind of thing real time communication would be a benefit to.

**Comment by dbsoft** [comment]
Yeah I do, used to use it all the time, what is your channel?

**Comment by mattatobin** [comment]
#binaryoutcast

**Comment by dbsoft** [comment]
Here is the diff to apply since my commit is unmergeable as is. 

[base.py.diff.zip](https://github.com/MoonchildProductions/UXP/files/4321244/base.py.diff.zip)

**Comment by wolfbeast** [comment]
How about using the normal clone -> edit -> submit pull request method? You already did the first two steps, having a `dbsoft/UXP` repo.

**Comment by mattatobin** [comment]
Because he is new to git and even newer to this method of doing things and is struggling so I suggested just sending a patch file.

**Comment by wolfbeast** [comment]
Communicate this things, please

**Comment by wolfbeast** [comment]
If you suggest something like that's fine but communicate that fact too, please? How am I to guess this was as-directed?

**Comment by wolfbeast** [comment]
> +        # Try looking for mozilla, for comm-central
> +        if not os.path.isfile(p):
> +            p = os.path.join(self.topsrcdir, 'mozilla', 'build', 'autoconf', 'config.guess')
> +
> +        if not os.path.isfile(p):
> +            p = os.path.join(self.topsrcdir, 'platform', 'build', 'autoconf', 'config.guess')

Do we need the "mozilla" one? How would that ever be used?
Also... how would simply assuming UXP is going to be installed in directory X from within itself be a good solution? isn't `self.topsrcdir` already pointing to the srcdir of the platform?

**Comment by mattatobin** [comment]
Hyperbola has not renamed the platform directory yet.

**Comment by mattatobin** [comment]
`self.topsrcdir` is not the root of the platform tree when building not `js` or `xulrunner`.
