### ISSUE TITLE
Incorrect outline drawn on position:sticky table elements

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1480]
URL: https://kangax.github.io/compat-table/es2016plus/

The left-hand-side headers are sticky, and have white borders outside of their respective elements.
This is caused by the use of `outline` in the CSS; the spec isn't entirely clear but the behavior of all other browsers have (eventually) aligned on one interpretation of it, which seems to be the most logical interpretation that we're currently not following.

Our current implementation includes out-of-flow elements like absolutely-positioned children and floats, but that's likely not the spec's intent; it would make little sense to include something that might be positioned somewhere completely different on the page in an outline drawing routine.

The fix for this is simple: a few lines to exclude abspos, fixpos and float (and any pseudo placeholders) from the elements to consider in `/layout/nsFrame.cpp` -- @g4jc do you mind if I slide that in while you're still working on this massive project that touches layout?

**Comment by g4jc** [comment]
> @g4jc do you mind if I slide that in while you're still working on this massive project that touches layout?

No problem, you can slide it in.

**Comment by wolfbeast** [comment]
Thanks
