### ISSUE TITLE
Dynamic SSUAO rules have insufficient priority

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1482]
As I mentioned [here](https://github.com/MoonchildProductions/UXP/issues/1473#issuecomment-595888333), сurrently all static SSUAO rules always take precedence over those received dynamically, which does not allow using dynamic updating to adjust builtin static rules, but only to add new ones. Considering that we [are not going to](https://github.com/MoonchildProductions/Pale-Moon/issues/1733#issuecomment-595273585) do everything with dynamic SSUAO and to refuse of using pre-set overrides, but to use this service mainly for hot-fixes, this behavior looks like a serious flaw.

I propose to resolve this by giving dynamic SSUAO rules priority over static rules from the default preference branch (where pre-set SSUAO rules live), but keeping the highest priority for static rules created by the user.

**Comment by JustOff** [comment]
I already have a PR to submit, if you don't have any other considerations.

**Comment by wolfbeast** [comment]
Sounds like it aligns with what its intended use is.

**Comment by JustOff** [comment]
Sorry, but by "it" do you mean current or proposed behavior?)

**Comment by wolfbeast** [comment]
what you propose

**Comment by JustOff** [comment]
Ok, thanks, then I take it, a PR will follow.
