### ISSUE TITLE
Popup window failures on MacOS 10.14 and later

### ISSUE THREAD

**Issue by dbsoft** [MoonchildProductions/UXP#1491]
On MacOS 10.14 and later anything that opens up a popup style window may fail after the initial activation.  This is most obvious on the Bookmarks,History and Downloads buttons on the toolbar. 

Affected versions: All versions
Affected platforms: MacOS 10.14 and 10.15
Steps to reproduce: Repeatedly click the Bookmarks, History or Downloads toolbar buttons
Expected result: Popup window appears and disappears with each click
Actual result: Popup window stops appearing eventually and will never appear again

After some investigation it appears this behavior is a result of a workaround for an Apple bug introduced during the 10.4 and 10.5 versions of MacOS 13 years ago. 

https://bugzilla.mozilla.org/show_bug.cgi?id=378645
https://bugzilla.mozilla.org/show_bug.cgi?id=387164

Mozilla discovered this behavior during the 10.14 beta.

https://bugzilla.mozilla.org/show_bug.cgi?id=1468053

They initially released a patch that disabled the workaround for Mojave (10.14) and later:

https://hg.mozilla.org/releases/mozilla-beta/rev/9eb2810ff638

Finally just removing the workaround entirely.

https://hg.mozilla.org/mozilla-central/rev/c3c7401b4277

I implemented the patch removing the workaround entirely and have tested in 10.7, 10.11, 10.14 and 10.15.   It fixes the incorrect behavior on 10.14 and 10.15 and I see no ill effects on 10.7 and 10.11, however the original mozilla bug report does say it is difficult to see the behavior by the user.  

I personally would lean towards removing the workaround entirely since it is definitely not needed on 10.14 and later, and if it is still an issue on 10.7 through 10.13 it is rarely visible on the user end.  The original versions of MacOS that the workaround was directed at are no longer even supported by Pale Moon.

The forum thread that inspired this issue is located here:

https://forum.palemoon.org/viewtopic.php?f=41&t=23935#p185346

**Comment by mattatobin** [comment]
Why not do the patch that disables the workaround for point 14 or higher. Mozilla doesn't care about backwards compatibility. We kinda do when possible.

**Comment by dbsoft** [comment]
Well that is always an option, I just have a feeling this bug had been long fixed and the workaround has had just been hanging around until it started causing problems.  Firefox and Waterfox both support back to 10.9 and both of those have removed the workaround. Pale Moon supports 10.7 and 10.8 which those don't, so there could be versions still affected but the number of users on those platforms will be low I think.

**Comment by mattatobin** [comment]
I don't care what Firefox and it's minor rebuilds do or support or anything. Our codebase supports `10.7` and up and i see no reason at this time to bust that or cause glitches when there doesn't need to be.

If you want to talk about usership.. Well Mac its self is so low it could be considered insignificant and should have support in the codebase ripped out completely. Sure would put an end to the Macintosh question wouldn't it.

You will need to update the `widget` features control for `cocoa` though to know what a `MojaveOrLater` is and while you are at it go ahead and get ALL the `CodenameOrLater` bools added.

**Comment by dbsoft** [comment]
Well, I'll do whatever type of patch you want, was just putting in my two cents and explaining the reasons I think that. :)

**Comment by mattatobin** [comment]
Do it in two commits. `Update CocoaFeatures for newer versions of MacOS X` and whatever the hell commit message seems appropriate for the panel things.

Use https://github.com/mozilla/gecko-dev/commits/esr68/widget/cocoa/nsCocoaFeatures.h history as your guide to add the new bools. Please maintain code style predominate in the files you edit though.

**Comment by mattatobin** [comment]
@wolfbeast Please uplift this to the next minor release.

**Comment by wolfbeast** [comment]
Uplifted in 8c7ca10cfe4c5ec4cee81632893a9ec46f066c2b and df9ab936f298037212f8f8f759e0de9ffed153d2

**Comment by mattatobin** [comment]
@dbsoft because the release binaries needed rebuilt along with a revised commit pointer, this is now included in 28.9.0. Thus you do not have to patch locally.
