### ISSUE TITLE
Clang: replacement function 'operator new' cannot be declared 'inline' 

### ISSUE THREAD

**Issue by dbsoft** [MoonchildProductions/UXP#1493]
Building Pale-Moon, Basilisk, UXP generate numerous warnings on newer versions of clang.

According to this mozilla bug, this is done for performance reasons that we don't really want to remove, their solution was just to disable the warning when using recent versions of clang:

https://bugzilla.mozilla.org/show_bug.cgi?id=928808

However their patch uses configure macros that don't seem to exist in the Pale Moon/UXP source base. 

The clang in Xcode 7 does not generate these warnings, but  the clang in Xcode 10 and 11 do.

**Comment by mattatobin** [comment]
Thing is, these ARE only warnings so not really something that must be dealt with any time soon. This would be part of #457 actually.

**Comment by wolfbeast** [comment]
FTR the listed Mozilla bug was fixed in gecko 30, the follow-up (to also use the workaround in /js) was landed in gecko 40 -- this is old code we have had for a long time so I don't see why this would even come up. anymore. The info in the linked BZ bug at least is outdated and shouldn't apply to us anyway.

**Comment by dbsoft** [comment]
The reason I linked the mozilla bug was to show we should add the -Wno-inline-new-delete when using recent versions of clang, it had some tests for it and adds it when necessary, and as I said it is no longer in the code base.  mattatabin is right it should be in that other issue, I didn't notice that one but it does belong in there.

**Comment by mattatobin** [comment]
If this is desired behavior we override it on the moz.build level and then only for what we need to not globally in ac or moz configure. Please stay away from either configure systems.

**Comment by dbsoft** [comment]
Well, it looks like it is already in there, just not functioning with clang or with macos...  looks like the test is failing in config.log:

INFO: checking whether the C++ compiler supports -Wno-inline-new-delete... 
DEBUG: Creating `/var/folders/44/x_38dgxx70s1gbg8ptfq3fhc0000gn/T/conftest.NwUyVq.cpp` with content:
DEBUG: | 
DEBUG: | int
DEBUG: | main(void)
DEBUG: | {
DEBUG: | 
DEBUG: |   ;
DEBUG: |   return 0;
DEBUG: | }
DEBUG: Executing: `/usr/bin/clang++ -std=gnu++11 -Werror -Winline-new-delete -c /var/folders/44/x_38dgxx70s1gbg8ptfq3fhc0000
DEBUG: The command returned non-zero exit status 1.
DEBUG: Its error output was:
DEBUG: | error: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ st
DEBUG: | 1 error generated.

**Comment by dbsoft** [comment]
Looks like it does add -stdlib=libc++ to the CXXFLAGS in the darwin section during configure, but it does not seem to use it for the tests.

**Comment by mattatobin** [comment]
Please don't override compiler flags globally. I told you that suppressing warnings is a targeted proceedure not a club also emitted warnings are just that..

Really you should be using the older clang compiler anyway if you intend on getting toward making official binaries.

**Comment by dbsoft** [comment]
Adesh is the one that suggested export CXXFLAGS=-stdlib=libc++ to get it to build.  This isn't required prior to Xcode 10 because it still had libstdc++ from GNU but it was removed in Xcode 10.  The warnings are supposed to be disabled in the current source base as I pointed out, the test for the option is just failing due to the missing libstdc++ and it not using the CXXFLAGS.  The export shouldn't be needed, and these tests shouldn't be failing but they are.  I am trying to figure out why and how to fix it.

I can definitely continue to do my distribution builds with the old compiler on 10.11 but it should work on newer systems and compilers too.

**Comment by mattatobin** [comment]
Why? Why does it need to on newer systems. All that is required is that the binaries run on newer systems. Build environment is gonna be different sometimes. See our Linux history for that.

**Comment by dbsoft** [comment]
Well at some point these computer systems are going to die, and new Macs can't run the old systems.   But for the time being it isn't an issue, but I am going to keep pushing that things can build on newer systems.

**Comment by wolfbeast** [comment]
>  I am going to keep pushing that things can build on newer systems.

One critical consideration you have to keep in mind is that something built on an older system usually runs on old and new systems. But something built on a newer system usually only runs on a newer system. e.g. if you build against Xcode 11, does it still run on OS X 10.7?
After all we are looking at building binaries _for_ people, not asking that people all build the browser from source.

**Comment by dbsoft** [comment]
Yeah I test back to 10.7 it does run on the older systems when using the older SDK.  The problem is the build systems are sort of tied to the OS version.  So the new Xcode runs on two versions... the new version it is designed for and the previous version.   So Xcode 11 the latest version runs on 10.14 and 10.15.  Xcode 10 ran on 10.13 and 10.14.  

On 10.12 and older Homebrew doesn't officially support them anymore so the secondary software starts getting difficult to get.  It officially supports back to 10.13. 

https://docs.brew.sh/Installation  

I have a build system setup on my old MacPro1,1 with all the required software, but if it dies, even if I get another old MacPro to use it might become difficult or impossible to setup the build environment in the future.

**Comment by dbsoft** [comment]
An update on what I've discovered in the past couple days... I checked out the current Firefox and did a build to see how it deals with this, and it seems they distribute their own custom clang build that does not have this problem.   I also discovered a different but similar workaround that adesh originally recommended.  Adesh suggested adding:

export CXXFLAGS=-stdlib=libc++ 

to .mozconfig ... this partially works, but only for things that use CXXFLAGS which the compiler tests do not use.  old-configure.vars detects CXX=/usr/bin/clang++ -std=gnu++11 

export CXX="/usr/bin/clang++ -std=gnu++11 -stdlib=libc++"

Using this instead fixes all the problems I have seen, including the compiler tests which eliminate most of the warnings.   This works as a stop-gap while we determine where the fix should be, could potentially add -stdlib=libc++ to CXX during compiler detection instead of adding it to the CXXFLAGS

**Comment by adeshkp** [comment]
I'm not a Mac developer by any means, but have some general understanding. Yes, my solution is not totally perfect, it just gets the builds going.
But if it is decided to add it to configure stage for CXX export, I must say that it needs to be done only for "Mojave or later". Earlier systems work without this stdlib=libc++ thing.

@dbsoft I think it is discouraged to continue discussion on a closed issue. Let's discuss on forum if really required. I'm out.

**Comment by mattatobin** [comment]
We'll just add those as a note for the revised mac build intructions for the time being. Alright?

**Comment by dbsoft** [comment]
Yeah that works for now, but it isn't Mojave, it is the Xcode version... you can run Xcode 9 on Mojave and not have the problem.  It is Xcode 10 and higher have removed libstdc++.   So it would be a note that Xcode 10 or higher add that.

**Comment by mattatobin** [comment]
Well collect the notes and we will revamp the content with them.
