### ISSUE TITLE
Issues with leftover pref "layers.acceleration.disabled"

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1495]
This is a regression from #1360 apparently causing issues with some websites and preventing the password popup overlays from working properly if the old pref still exists.
Sounds like there is some leftover code still looking at the old pref instead of the new one...

**Comment by wolfbeast** [comment]
I haven't been able to find anything leftover in xref (aside from the missed Basilisk FE changes which I did just now). Anyone else have any idea?

**Comment by JustOff** [comment]
I don't see any leftovers either. And what are the steps to reproduce the problem after setting `layers.acceleration.disabled = true`?

**Comment by JustOff** [comment]
I tried updating from 28.8.4 and got an error:

`ReferenceError: Service is not defined[Learn More]  nsBrowserGlue.js:1442:13`

in

```
    if (currentUIVersion < 22) {
      if (Services.prefs.prefHasUserValue("layers.acceleration.disabled")) {
        let HWADisabled = Service.prefs.getBoolPref("layers.acceleration.disabled");
        Services.prefs.setBoolPref("layers.acceleration.enabled", !HWADisabled);
        Services.prefs.setBoolPref("gfx.direct2d.disabled", HWADisabled);
      }
      if (Services.prefs.getBoolPref("layers.acceleration.force-enabled", false)) {
        Services.prefs.setBoolPref("layers.acceleration.force", true);
      }
      Services.prefs.clearUserPref("layers.acceleration.disabled");
      Services.prefs.clearUserPref("layers.acceleration.force-enabled");
    }
```

**Comment by JustOff** [comment]
Well, to upgrade is also the steps to reproduce `
We’ll stop supporting this browser soon. For the best experience please update your browser.
` warning on YouTube.

**Comment by wolfbeast** [comment]
Yeah I just found this typo out myself as well. Not sure why we didn't catch that during dev/testing.
The problem is that this error would abort browser glue init and not clear out dirty cache/rdf/dataSource which is likely why there are these strange errors all over the place.

**Comment by wolfbeast** [comment]
@trav90 I'm going to push out another update for this because it's critical.

This is actually caused by Pale Moon front-end stuff but I'll keep this issue in UXP's repo for reference.

**Comment by trav90** [comment]
@wolfbeast sounds good I'll push out new Linux releases by end of day today.

**Comment by wolfbeast** [comment]
@trav90 Please note there's one more pref reversion change in the FE that also needs to be picked up - I've moved the tag accordingly.

**Comment by trav90** [comment]
@wolfbeast Noted. I'll be sure it's included in the new Linux builds.

**Comment by mattatobin** [comment]
Perhaps we should give this a day before building new releases in case anything else comes up.

**Comment by wolfbeast** [comment]
@trav90 @mattatobin 
Sounds like we could give it a day, also considering another thing popped up that wasn't previously reported.... #1496

**Comment by wolfbeast** [comment]
I'll publish this today anyway. Incorrect init of the glue can cause havoc, apparently.
This needs to be fixed now rather than later.

**Comment by wolfbeast** [comment]
Published Windows.

**Comment by trav90** [comment]
Linux has now been published also.
