### ISSUE TITLE
Form-fill pop-ups do not function

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1496]
This is a recent regression; form autofill pop-ups sometimes no longer appear when they should.
A browser restart seems to fix it.

**Comment by JustOff** [comment]
Are you sure this is not related to #1495? I ask because of [[1]](https://forum.palemoon.org/viewtopic.php?p=186313#p186313), [[2]](https://forum.palemoon.org/viewtopic.php?p=186328#p186328), [[3]](https://forum.palemoon.org/viewtopic.php?p=186340#p186340).

**Comment by wolfbeast** [comment]
... well in that case there's no point delaying the .2

**Comment by wolfbeast** [comment]
Published 28.9.0.2 -- can you still reproduce?

**Comment by JustOff** [comment]
I performed sequential updates and here are the results:

|28.8.4 | 29.9.0 | 29.9.0.1 | 29.9.0.2 |
|-------|--------|---------|----------|
| Ok | Fail | Fail | Ok |

**Comment by wolfbeast** [comment]
Okay
Closing.
