### ISSUE TITLE
Re-implement and activate TLS 1.3

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#15]
Re-forking, we lost our TLS 1.3 capabilities. This needs to be re-implemented.

Considering I've already plugged in sufficiently-recent NSPR/NSS for this, it's a matter of hooking up the correct ductwork and porting some of the fixes we have added in Möbius.

**Comment by janekptacijarabaci** [comment]
I suggest i.e. [bug 1340164](https://bugzilla.mozilla.org/show_bug.cgi?id=1340164) - native in moebius / FF53, also in PM now [Pale-Moon#1055](https://github.com/MoonchildProductions/Pale-Moon/pull/1055).

**Comment by wolfbeast** [comment]
Buddy, this is going to take more than one bug to port. What would be more useful would be an index of everything that needs to be adopted (either from Pale Moon or from Möbius) to get to a working state.

**Comment by janekptacijarabaci** [comment]
AFAIK - for TLS 1.3 (not tested):
https://bugzilla.mozilla.org/show_bug.cgi?id=1340164
\+
https://github.com/MoonchildProductions/moebius/pull/62

And generally, e.g.:
https://github.com/janekptacijarabaci/UXP/wiki/Label:-UXP-task
(there are some new things; `Old UXP-task` == I want to check after a rebase is done)

But that's my internal list (from my PRs only).

**Comment by wolfbeast** [comment]
Question @janekptacijarabaci : did you want to work on this? because the tree is in a state right now where this wouldn't be blocked any longer.

**Comment by wolfbeast** [comment]
NSS 3.35 will be required for TLS 1.3 draft 23 (current support is for draft 16 I believe) which seem to be incompatible with each other.

**Comment by wolfbeast** [comment]
Putting this on hold for now until NSS has been updated.

**Comment by janekptacijarabaci** [comment]
@wolfbeast:

> did you want to work on this?

No, thank you.

But I suggest starting with:
- https://github.com/janekptacijarabaci/UXP/commits/_native_52ESR_http_events_1
(https://bugzilla.mozilla.org/show_bug.cgi?id=1340164)

and

- https://github.com/janekptacijarabaci/UXP/commits/security_tls_1-3_1
(https://github.com/MoonchildProductions/moebius/pull/62)

**Comment by wolfbeast** [comment]
Right.
