### ISSUE TITLE
Building UA is broken in Native mode and version=buildid doesn't work.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1505]
There's something very wrong with the building of the UA:

- Native mode uses compatmode version in rv and Goanna version in Goanna slice while it should be Goanna version in rv and buildid in Goanna slice.
- appVersionIsBuildID also doesn't seem to be doing anything

**Comment by wolfbeast** [comment]
Back in 2018 we decided that rv: should be the compatmode version for "web compatibility"; does that still hold? Are websites still looking at rv: to determine browser version/capacities?

**Comment by wolfbeast** [comment]
`appVersionIsBuildID` works but requires a browser restart because it's not rebuilding the appVersion string. That's easy to fix.

**Comment by JustOff** [comment]
You may also want to completely get rid of `mCompatDevice` and `mDeviceModelId`, see #1494.

**Comment by wolfbeast** [comment]
> You may also want to completely get rid of mCompatDevice and mDeviceModelId, see #1494.

Not in this issue, no.

**Comment by mattatobin** [comment]
Ah, well then. That explains it. Hmm, we might want to think about it for a bit though. But yeah there is as much chance rv is used as there is any of the slices.

**Comment by wolfbeast** [comment]
Yeah I'm just not happy about _native_ mode still having a firefox compat in there. I'd say that should belong in Gecko compatmode but not native... I just have no idea about the potential breakage though.

**Comment by mattatobin** [comment]
Well, native should mean native I suppose. Maybe fixing this will give us a better idea and also get users on whatever the proper setting for them is instead of catering to ridiculousness.

**Comment by wolfbeast** [comment]
Righto. This does mean that setting Firefox compat and not setting Gecko compat (by forcing it) will probably give a weird result ;-)

**Comment by mattatobin** [comment]
Perhaps, but that is only an issue for `about:config` surfers in Basilisk and crazies using my Navigator. No one knows how to get Pale Moon into that configuration.
