### ISSUE TITLE
Do something about moz://a being a valid address.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1508]
Apparently they went there just before our fork point.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1331968

This needs to either go away or redirect to something advocacy-ish, or something.

**Comment by mattatobin** [comment]
Send it to thereisonlyxul.org

**Comment by wolfbeast** [comment]
Well since that's now suggested twice I guess it's as good as anything.

The whole idea is retarded. not only [moz://a] as a branding concept, but actually going as far as creating a protocol handler just so the easter egg works...

**Comment by mattatobin** [comment]
So if we settled on what to do with the moz: protocol handler, why is this issue still open?
