### ISSUE TITLE
Remove pocketsphinx/speech recognition

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1538]
We really don't want to maintain this in UXP.
Unless there are specific plans by anyone to make a speech-recognition supported/focused application building on UXP we should remove this as a whole.

**Comment by wolfbeast** [comment]
Following a community poll on the forum it's clear there are literally 0 people interested in keeping this in the platform.
*grabs axe*

**Comment by wolfbeast** [comment]
So, it turns out Mozilla made a mess of things here, using `MOZ_WEBSPEECH` originally for synth, then mis-repurposing it for recognition.
I've fixed all that; commit incoming.

**Comment by mattatobin** [comment]
Outstanding. BinOC applications plus Pale Moon should be immune due to blanket package-manifest but Hyperbola deff needs theirs updated iirc. Not sure which Ambassador is.
