### ISSUE TITLE
Add modern MIPS Support

### ISSUE THREAD

**Issue by FlyGoat** [MoonchildProductions/UXP#1542]
Hi there,

I did some work about UXP support on MIPS[1], mostly backport commits.
Now a Pale Moon build can work on MIPS64EL system.

Just wondering if it's possible to upstream these changes? If so, I'm going to start to clean up my changes to let them meet UXP's requirements.

As most of the MIPS code is lying in tree for years and most backported commits are just bug fixes, I think it won't give you too heavy maintenance overhead.

Thanks.

[1]: https://github.com/FlyGoat/UXP/tree/mips

**Comment by g4jc** [comment]
Ultimately it's up to the other team members, but we would need someone to maintain it.
No one here is running a MIPS box in order to test it.

If you're willing to help with that I think it could be arranged, presuming the `#ifdefine` are properly in place so as not to conflict with other architectures.

**Comment by FlyGoat** [comment]
I'm going to help with further maintainance on MIPs as well.

My expectation is just treat MIPS like how UXL treat arm & powerpc. We don't have official release but downstream distros can take source from here to build their own binary, if they meet any issues they can just raise a issue here and ping me. If MIPS blocked any UXL development plan then just ping me and I'll try my best to come out a solution.

If that sounds ok to UXL project members I'll propose a PR with some urgent IonMonkey fixes for MIPS.

Thanks.

**Comment by mattatobin** [comment]
Depends on what is required. Also, seriously how much usership does `MIPS` have. Also, there SHOULD be an active use for everything in the codebase including target os support,

Are _you_ going to be doing something?

**Comment by mattatobin** [comment]
Ignore my previous comment if you read it.

Thinking more I am fine with this as long as someone is maintaining it. It does still depend but I wanna see what you got. Though, I am liking your enthusiasm.

**Comment by FlyGoat** [comment]
Btw: Can we use this issue as a meta issue to track MIPS support?

**Comment by mattatobin** [comment]
Care to explain what you are changing in detail? None of the commits are tagging this issue. You CAN use the Mozilla commit messages but they have to also tag the issue.

Is this all that is needed?

**Comment by FlyGoat** [comment]
@mattatobin Most of them are need together with several small optimization.

I'm going to tidy commit messages. So I should link all of them to this issue and add some explanations about their changes?

**Comment by wolfbeast** [comment]
I'm fine with keeping and expanding MIPS support as long as it's actually going to be maintained long term. None of our current team have MIPS hardware so @FlyGoat it'll be up to you to be our maintainer and to not vanish without a trace ;)

**Comment by FlyGoat** [comment]
I'll try my best to keep MIPS up.

AOSC is going to reboot their MIPS port so we'll have official branded build for MIPS very soon.

**Comment by wolfbeast** [comment]
MIPS support PR has been merged. Closing this assuming this completes MIPS support and brings it to a runnable state on appropriate target hardware.
If there are further enhancements needed, please open (a) new issue(s).
