### ISSUE TITLE
 Border radius is not painted correctly on border-collapsed table-cell elements

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1545]
Regression from issue #146 

https://bugzilla.mozilla.org/show_bug.cgi?id=1375518

Steps to reproduce:

Apply border-radius to an element displayed as table-cell, contained within a border-collapsed table-row element.

https://bug1375518.bmoattachments.org/attachment.cgi?id=8883713

Actual results:

The border-radius doesn't apply.

Expected results:

The border radius applies.

I can do PR to resolve this to @Wolfbeast to review. There is also one more (should be last regression from #146) regression from issue #146 left. I can open issue and also do PR to that regression after this is resolved.

**Comment by wolfbeast** [comment]
> Apply border-radius to an element displayed as table-cell, contained within a border-collapsed table-row element.

How would that even apply if you collapse the border? IMO collapsed border = you don't draw borders = no border styling applies.

**Comment by win7-7** [comment]
Attachment did work in Firefox ESR 52 when tested. So should this be fixed in UXP? I found this and https://bugzilla.mozilla.org/show_bug.cgi?id=1394226 as remaining regressions from issue #146.

**Comment by wolfbeast** [comment]
I looked a bit closer at it; the issue is that the borders of the table (surrounding) are collapsed, not of the cells themselves. so yeah that's a bug, although a corner case (same with the other one, which is even MORE of a corner case)
