### ISSUE TITLE
[PALEMOON] Frontend: Mass replace toplevel 'let' with 'var' in preparation for global lexical scope

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#155]
__AFAIK:__

Block #121 / #57

These things should be resolved (otherwise it will be endless...):

# 1)

[Bug 1202902](https://bugzilla.mozilla.org/show_bug.cgi?id=1202902)
(https://hg.mozilla.org/integration/mozilla-inbound/rev/c609df6d3895)

- [x] 1a) https://hg.mozilla.org/integration/mozilla-inbound/rev/380817d573cd
- [x] 1b) https://hg.mozilla.org/integration/mozilla-inbound/rev/c6b267589d0d
- [x] 1c1) https://hg.mozilla.org/integration/mozilla-inbound/rev/cfc1820361f5
- [x] 1c2) https://hg.mozilla.org/integration/mozilla-inbound/rev/d6793bb3e45b
1c1) and 1c2) - Not all files are repeated, e.g.: `urlbarBindings.xml`

# 2)

- [x] [Bug 1213620](https://bugzilla.mozilla.org/show_bug.cgi?id=1213620) DownloadsButton defined as const so extensions can't access it
Fixed: #156

# 3)

- [x] [Bug 1217070](https://bugzilla.mozilla.org/show_bug.cgi?id=1217070) Fix accessing the bootstrap methods when they are declared in the new lexical scope
@JustOff ?

**Comment by janekptacijarabaci** [comment]
@JustOff
https://github.com/MoonchildProductions/UXP/pull/124#issuecomment-380774104 :-)

**Comment by mattatobin** [comment]
I am confused.

**Comment by mattatobin** [comment]
Most of the let var crap has been changed in Pale Moon as near as I can tell.. So explain what else needs changed please..

Also thanks for running down the original bugs.. All I could remember was from shifts from var to let to var in commit history in the past.

**Comment by janekptacijarabaci** [comment]
> So explain what else needs changed please

I haven't reviewed specific files (and potential errors / bugs) yet. Nor have I tried much extensions (whether of any type).

I suggest adding of `Research` (label).

**Comment by wolfbeast** [comment]
It just needs to be verified that it was all done properly, and change parts missed.

**Comment by wolfbeast** [comment]
I'll do this verification today. it's something I can do at my own pace and is straightforward.

**Comment by mattatobin** [comment]
This was the second try patch to resolve the let/var issue btw 588a484

**Comment by wolfbeast** [comment]
I just manually went through all js and jsm files to change global-scope `let` to `var`

**Comment by mattatobin** [comment]
Is this done now?

**Comment by wolfbeast** [comment]
I don't know about (3)
I think I covered (1)

**Comment by JustOff** [comment]
> I don't know about (3)

I didn't touch this since the whole issue was assigned. The patch itself is pretty straightforward (thanks to @janekptacijarabaci catched the corresponding bug). I'll submit the PR as soon as I verify it.

**Comment by wolfbeast** [comment]
Not sure how to easily verify the result of these things... Any idea?

**Comment by JustOff** [comment]
It's difficult to say... I guess this can lead to a visible error, or just break silently.

**Comment by wolfbeast** [comment]
I think we've pretty much tackled this. Closing as completed.
