### ISSUE TITLE
Fieldset disabled no longer works

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1557]
Regression 28.8.4 -> 28.9.0, still broken in 28.9.3

Potentially a regression from the html5 parser work done? Marking as parser component for now.

http://jsbin.com/bibiqi/1/edit?html,css,output -- test input fields should all have a red background in the disabled fieldset.

**Comment by mattatobin** [comment]
As I said in the reporting thread: https://forum.palemoon.org/viewtopic.php?f=62&t=24431

I made sure when I imported the codegen that the generated code was code equal save for formatting when I was done. I am almost positive it isn't because of the parser codegen.

**Comment by mattatobin** [comment]
I reverted 1ebbb0a on `redwood` but no dice.. Trying a build reverting the entire regen (and of course 1ebbb0a).

**Comment by mattatobin** [comment]
Yeah.. it is Issue #1356... I spent three hours and that is it. But of course, if we restore it str8 up then the issue it was to solve will be back..

I don't know what to do about it personally.

Ping @athenian200 because he did these patches.

**Comment by fifonik** [comment]
If I'm not mistaken, the change in nsGenericHTMLFormElement::IsElementDisabledForEvents looks strange. Fiedset's check not executed as 'return true' issued earlier.

**Comment by wolfbeast** [comment]
The parser changes was just a first guess as most likely -- since I don't really think `<fieldset>` behaviour was touched otherwise specifically.
OT: I'm surprised redwood is busted. it needs an update anyway so I'll look into that.

**Comment by athenian200** [comment]
Yeah, I'm sorry I didn't catch this during testing. The issue that prompted this change involved forms being erroneously disabled when they should be enabled. Now we apparently have an issue with forms being erroneously enabled when they should be disabled.

The problem seems likely to stem from one of two things, or a combination of both. In the comments on the original Mozilla bug, they talk about event-driven updates to properties in CSS not working properly, and not having a good way to fix that. 

It seems that the changes I made to nsCSSProps.cpp, they removed the disabled and enabled properties, and that seems to have had the effect that it's no longer possible to disable or enable forms at all via CSS. You can still do it via JS, though.

**Comment by wolfbeast** [comment]
Yeah I just ended up with the same conclusion that it was Issue #1356 (Remove -moz-user-input disabled to improve event handling.)
Perhaps the issue is that we internally still use `-moz-*` versions of these properties to style form elements that weren't part of the BZ bug's changes. The disabling here isn't actually done via CSS, either, but via a property on the html element itself.

@athenian200 should I assign you to look into this?

**Comment by athenian200** [comment]
I'm definitely interested in looking into this, especially since it is something I've worked on.

**Comment by wolfbeast** [comment]
If we actually _have_ to choose a short-term solution it's probably better to back out the change since that's been established behavior `pre-emilio` and would actually be used broadly on input forms to enable/disable groups of form elements without needing JS, like:
``` html
<fieldset name="clubfields" disabled>
 <legend> <label>
  <input type=checkbox name=club onchange="form.clubfields.disabled = !checked">
  Use Club Card
 </label> </legend>
 <p><label>Name on card: <input name=clubname required></label></p>
 <p><label>Card number: <input name=clubnum required pattern="[-0-9]+"></label></p>
 <p><label>Expiry date: <input name=clubexp type=month></label></p>
</fieldset>
```

**Comment by mattatobin** [comment]
My opinion long term is that maybe we should try and make the enabled/disabled state update properly instead of flat removing the property.

**Comment by athenian200** [comment]
I agree that I'd rather keep the enabled/disabled state update. I wasn't particularly happy with the way my own patch resolved the issues, and I was eyeing a different solution, but I didn't really feel confident in my ability to find one.

I may actually have found our solution in a very old Bugzilla bug (329509) that was resolved fairly recently. I haven't tested this at all yet, but what it does is it allows event dispatch on disabled form controls. Apparently the way DOM is designed now, several kinds of events simply aren't processed _at all_ if there's a disabled control, unfortunately including events that would re-enable them. This was the best work around they could come up with. 

Even though it's from Firefox 65 and I'm really skeptical about it working flawlessly with our codebase, I haven't found any issues with it yet. I'm mostly posting to let you know that I am making progress in my research. 

Both the site that was originally broken in the other bug, and the site testing disabled form controls seem to work fine with what I have so far. Ideally I would like to have someone more qualified look over what I did to see if it makes sense, though.

**Comment by wolfbeast** [comment]
If you have something that works, then that would certainly be having a lot of pluses in my book.
I suggest you make a PR out of it, and give the PR a good description what it does or post the details here in this issue how this is solving the problem (might be better) so I have a background for evaluating the code changes.

**Comment by athenian200** [comment]
That's what I have so far. It works with both test cases (the originally broken website and the disabled CSS form test), so I can tell disabled forms are still closed to user input, but can now be targeted by events. This has the benefit of solving the original problem without a need for removing -moz-input-disabled.

**Comment by wolfbeast** [comment]
The only slight worry I have with the chosen solution is that events might target disabled elements now that would previously block them -- I'm not sure if any frameworks rely on that quirk.

**Comment by wolfbeast** [comment]
Reopening for uplift.

**Comment by wolfbeast** [comment]
Uplifted in 15a1f78f8 with a minor conflict patch.
