### ISSUE TITLE
Null deref crash in webrtc ~WebrtcVideoConduit

### ISSUE THREAD

**Issue by Feodor2** [MoonchildProductions/UXP#1558]
You can check it on the Basilisk only because webrtc disabled in Palemoon.
file - media\webrtc\signaling\src\media-conduit\VideoConduit.cpp

~WebrtcVideoConduit() has SyncTo(nullptr); which is coded as
```

   mPtrViEBase->DisconnectAudioChannel(mChannel);
   mPtrViEBase->SetVoiceEngine(nullptr);
```

meanwhile DeleteStreams() has

`mPtrViEBase = nullptr;`

and executed earlier ~WebrtcVideoConduit(), so you get excpetion 0xc0000005 in result
I moved SyncTo(nullptr) to DeleteStreams() before mPtrViEBase = nullptr and bug seems gone

**Comment by mattatobin** [comment]
Please familiarize your self with https://github.com/MoonchildProductions/UXP/blob/master/docs/CONTRIBUTING.md

**Comment by Feodor2** [comment]
**Description of the bug is above** 

**Affected versions/features:**
Basilisk 2020.05.08 (32-bit)

**Steps to reproduce the bug:** 
1. Start any videochat, _tinnychat.com_ allows to test free without an account
2. Stop the videochat close the page

**Expected result when performing the steps:**
Continue work in the browser

**Actual result when performing the steps:**
The browser will crash

**Comment by wolfbeast** [comment]
> Stop the videochat close the page

Stop the video first THEN close the page, or stop the video BY closing the page? Please be exact in STR.

If you indicate code affected or proposed changes it is also imperative that you indicate in what file and at what line you are referring to. We don't know which part of the 25 million lines of code you are looking at.

**Comment by Feodor2** [comment]
If to close a chat page the browser will crash right away, if only to stop a chat and not to close it will crash not right away but later.

The file is 2129 lines, links here
[~WebrtcVideoConduit()](https://github.com/MoonchildProductions/UXP/blob/5d6691e9d08dce30b461fced32ece77fd3ff1933/media/webrtc/signaling/src/media-conduit/VideoConduit.cpp#L105)

[DeleteStreams()](https://github.com/MoonchildProductions/UXP/blob/5d6691e9d08dce30b461fced32ece77fd3ff1933/media/webrtc/signaling/src/media-conduit/VideoConduit.cpp#L481)

**Comment by wolfbeast** [comment]
The question is: if moved out of the dtor, won't that leave a dangling pointer to the audioconduit?

**Comment by wolfbeast** [comment]
I don't think there's a hard guarantee that `DeleteStreams` will always be called (otherwise it'd always crash immediately, IIUC)
I think what needs to be done here is add the `SyncTo(nullptr)` call to `DeleteStreams()` but leave it in the dtor as well, and make `SyncTo` resilient to `mPtrViEBase` already being nulled.

**Comment by Feodor2** [comment]
It crash immediately on ~WebrtcVideoConduit() which executed not immediately if not to close page.
If to check the possibility of it executed before DeleteStreams - put log string if mPtrViEBase not null.

**Comment by wolfbeast** [comment]
So have you tested with logging (on a multitude of sites) if the dtor is ever called without having a deletestreams call first?

**Comment by Feodor2** [comment]
On one site though, others not allow chat without account and google-moogle stuff. 
But pay attention that it is written **"Call DeleteStreams prior to ~WebrtcVideoConduit."** so was intended at the first place.

**Comment by wolfbeast** [comment]
Well in that case we should have the "just in case" call in the dtor as well (because of lack of conclusiveness with it only being tested on one site) and make `SyncTo` check for existence of the pointer before trying to use it. Dangling pointers are a sec risk and should always be avoided.
Please make a PR to that effect.

**Comment by Feodor2** [comment]
https://github.com/MoonchildProductions/UXP/pull/1565
I never did it so check if done all right

**Comment by wolfbeast** [comment]
Tag #1515
