### ISSUE TITLE
Make --disable-webspeech work again

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1560]
Due to some intertwining with IPC, `MOZ_WEBSPEECH` needs to be checked in more places for conditional web speech synthesis to build again if disabled.

**Comment by Feodor2** [comment]
This simple patch fixes the issue
```
diff --git a/dom/media/webspeech/moz.build b/dom/media/webspeech/moz.build
index 677e065..f174160 100644
--- a/dom/media/webspeech/moz.build
+++ b/dom/media/webspeech/moz.build
@@ -5,3 +5,8 @@
 
 if CONFIG['MOZ_WEBSPEECH']:
     DIRS += ['synth']
+else:
+    IPDL_SOURCES += [
+        'synth/ipc/PSpeechSynthesis.ipdl',
+        'synth/ipc/PSpeechSynthesisRequest.ipdl',
+    ]
```
As about more places for conditional, these ipdle files does not work with _if CONFIG_ stuff, searched a command like for js files, but nothing found. What do you think?

**Comment by wolfbeast** [comment]
Yeah since IPDLs can't be preprocessed, this will have to do.
Could you make a PR for this please?

**Comment by wolfbeast** [comment]
Never mind, I'll do it myself.
