### ISSUE TITLE
Use asyncOpen2 instead of asyncOpen everywhere in Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#157]
Since `UXP` platform already uses `asyncOpen2` instead of `asyncOpen` everywhere, it would be nice (required?) to align `Pale Moon` code accordingly.

Here is the corresponding tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1182535.

Here are the paths that should be checked against the meta bug above:
- `application/palemoon/*`
- `toolkit/mozapps/extensions/*`

Tag (Blocks?) #57.

**Comment by JustOff** [comment]
@mattatobin, could you please check whether any other paths except for listed above need to be considered?

**Comment by wolfbeast** [comment]
Issue with merged PR -- resolved?

**Comment by JustOff** [comment]
> Issue with merged PR -- resolved?

Not at all, there is still a lot of work to be done based on [bug #1182535](https://bugzilla.mozilla.org/show_bug.cgi?id=1182535).
I plan to do this as soon as I have enough free time, so please don't rush to close it.
