### ISSUE TITLE
SunOS 64-bit build crashes on certain websites.

### ISSUE THREAD

**Issue by athenian200** [MoonchildProductions/UXP#1571]
I didn't catch this in testing because I tested the 32-bit build more extensively, having gotten that working first. Anyway, visiting either of these two sites:

https://www.linuxquestions.org/questions/linux-software-2/how-to-change-gnome-main-menu-icon-applications-menu-563658/

https://www.mezzoguild.com/japanesepod101-review/

In a 64-bit browser results in the following error message:
`
IPDL protocol error: Error deserializing 'data' (SerializedStructuredCloneBuffer) member of 'MessagePortMessage'`

A core file is produced, and parsing it results in the following.

[test.txt](https://github.com/MoonchildProductions/UXP/files/4706800/test.txt)

On a 32-bit build, conversely, everything works as you would expect and the sites don't crash. The main thread of interest here in this text file seems to be Thread 36, IPDL Background. I notice that although the final error message comes in talking about SeralizedStructuredCloneBuffer, the initial messages pass through PickleIterator and an nsTArray, which stands out to me because a lot of work was implemented relating to those things around Firefox 51, specifically implementation of BufferLists. There's a lot of worrying code around this area, stuff like MOZ_STACK_CLASS and MOZ_NON_MEMMOVABLE. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1264642

The main issue is that SunOS might interact with the code a bit strangely because we have unusual [memory requirements](https://bugzilla.mozilla.org/show_bug.cgi?id=577056). For instance, I came across the requirement for JEMALLOC_USES_MAP_ALIGN, and while I know it's [not needed](https://github.com/mozilla/gecko-dev/commit/d3f17931b7babb0f93154215ccb0adfaa8891b55) in later versions of Firefox, I can't really tell if it helps or hurts here from how the program behaves with or without the code. What's even more unusual is what SunOS definitely seems to require in order to work on x86_64 in Memory.cpp... https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/web/firefox/patches/patch-js_src_gc_Memory.cpp.patch 

As you can see, SunOS requires something on AMD64 that other operating systems only require on non-AMD64 architectures, and I am pretty sure it has something to do with the segmented memory model. That could be relevant because two branches of the code could be winding up in different segments when they shouldn't. And one issue that I never saw explored to my satisfaction while researching memory issues was this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1496713

Where a lot of worrying things were said about ArrayBufferObjects in relation to asm.js, and certain stack protection tricks not working properly on 64-bit SunOS. Given that the crash I'm experiencing now appears to involve BufferLists, reading from an nsTArray, and stuff in js/src/vm, the same part of the code I was concerned about when initially doing things, it does make me think something is going wrong there, though as of yet I haven't been able to touch on anything that seems directly related to the problem here.The fact that IPC and WASM stuff probably also ties in here and I had a lot of issues with that in porting to SunOS also makes me question whether the issue is there, but ultimately it seems like I'm really groping around in the dark a lot more than I'd like to admit, even though I've been studying this out for a long time.

**Comment by athenian200** [comment]
Well, it turns out it was just that the fix I had for 48-bit addressing in Memory.cpp needed to be extended to jemalloc.c, and the patches I found simply didn't do that. Also, the JEMALLOC_USES_MAP_ALIGN code was what prevented that fix from working when I tried it initially, but without either that fix or the correct 48-bit addressing fix, the 64-bit build doesn't start up at all.

**Comment by mattatobin** [comment]
Reopening for sync and uplift.

Tag @wolfbeast

**Comment by wolfbeast** [comment]
Uplifted; closing.
