### ISSUE TITLE
 Position absolute does not work as expected in table with border collapse

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#1575]
https://bugzilla.mozilla.org/show_bug.cgi?id=1379306

As reported on forum: https://forum.palemoon.org/viewtopic.php?f=29&t=24504

Steps to reproduce:

https://codepen.io/vr8088/pen/yLeBVbN

The table is set to "border-collapse: collapse"
A child td has "position: relative" and a non-zero border width
The td contains an element set to "position: absolute"

Expected result: The element with "position: absolute" should be positioned relative to the position of the td (= of the first not-static ancestor element).

Actual result: It is positioned relative to the td plus a small offset in the x and y directions. The size of this offset seems to depend on the td's border width.

Also testcases from 1379306, all of those will work after applying patch from 1379306.

I will do PR to resolve this.

**Comment by mattatobin** [comment]
Does this include the other bugs that the bug this blocks depends on?

**Comment by win7-7** [comment]
No. This does not include other bugs.

https://bugzilla.mozilla.org/show_bug.cgi?id=688556 

This bug is still not fixed by Mozilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=895096

Maybe I could take look to this bug later but it should be separate issue.

**Comment by mattatobin** [comment]
Whatever.

**Comment by wolfbeast** [comment]
895096 shouldn't be an issue because we already use naturally-rounded border widths, unlike Mozilla that does inconsistent hacking.
