### ISSUE TITLE
mozconfig isn't a dependency for reconfigure in comm configuration

### ISSUE THREAD

**Issue by mssx86** [MoonchildProductions/UXP#1577]
1. unpack the uxp and pale moon tarballs
2. `cd` to the clean tree, place a `mozconfig`
3. run `./mach build`, wait for the build to finish
4. `DESTDIR=$PWD/PMINSTALL ./mach install`
4. make changes in the `mozconfig` (`--enable-default-toolkit=`, `cairo-gtk3` -> `cairo-gtk2` as an example).
5. run `./mach build` again.

following the steps above, i have discovered that when you run `./mach build` for the second time after making changes to the original `mozconfig`, `mach` does not go through the "configure" phase (`/usr/bin/make -f client.mk MOZ_PARALLEL_BUILD=2 -s configure`) again before initiating the "build" phase (`/usr/bin/make -f client.mk MOZ_PARALLEL_BUILD=2 -s`), resulting in changes made to the `mozconfig` not getting picked up.

this occurs only on uxp+pm releases that got released after the repository split happened..

i have also tried to see if the `mach` on current firefox-esr release behaves the same and it does not. changes made to the `mozconfig` gets picked up because `mach` does go through the "configure" phase with every `./mach build` and picks up the changes. _(do note that i am aware of the fact that uxp+pm != firefox, just wanted to see if i can reproduce the issue on another project that uses `mach`.)_

**Comment by mattatobin** [comment]
`mach` is just a command launcher. It doesn't do anything else but that.

**Comment by mssx86** [comment]
you people deserve no support.

**Comment by g4jc** [comment]
What Tobin said is a fact. If you're referring to it not doing `clobber` that is something different. `mach` is just a wrapper script around a lot of autobuild magic. So it sounds like you're having an issue with that and then decided to go ad hominem and rage quit the issue. Does a `mach clobber` and `mach build` not solve this issue?

**Comment by mattatobin** [comment]
I was gonna investigate but guess I don't have to now. Though, I likely still will just no current priority attached.

That being said, mozconfig should be a dependency that can trigger a reconfigure.

**Comment by wolfbeast** [comment]
I did mention this before in our chat, that I have to mach configure manually if I change .mozconfig while it would previously be picked up automatically, since the comm-ization. We may as well keep this issue open to track it, despite the kneejerk ragequit of the OP.

**Comment by mattatobin** [comment]
Waiting for @Ascrod to update his `config.mk` before closing.

**Comment by mattatobin** [comment]
@g4jc Take note if you ever update your comm to current standards.

**Comment by wolfbeast** [comment]
Unfortunately it seems to bust Basilisk by not creating a processed `/configure` that the build system can use. I've had to back it out there.

**Comment by mattatobin** [comment]
That.. shouldn't be possible.

**Comment by mattatobin** [comment]
@ascrod see the `binoc-central` or `Pale-Moon` commit for your patch. Sorry about this oversight.

**Comment by mattatobin** [comment]
Guess I need to build my self a new build because `Github` is broken thanks to `getRootNode`. Anyway, if you run into the shell script errors `rm configure`.

**Comment by wolfbeast** [comment]
This should be fixed everywhere now. closing.
