### ISSUE TITLE
Pale Moon on macOS: System windows not localized.

### ISSUE THREAD

**Issue by Peacock365** [MoonchildProductions/UXP#1583]
Dear Pale Moon team,

I am using Pale Moon 28.10.0 (unofficial build) on macOS 10.15.5. I am using Pale Moon with a language pack provided by you. The language pack successfully transformed the localization of the main Pale Moon UI into my native language, no issue there.

However, whenever Pale Moon calls upon windows provided by the system itself, those windows would still appear in English. A prime example would be the printing menu that comes up when you click File -> Print... Pale Moon seems to be the only application on my system which does that, the bug isn't present in the most recent version of Firefox at the time of this writing. The issue apparently happens with all language packs your provide (I tested several).

I suspect that a change in Pale Moon's localization doesn't trigger a change in the localization of system windows it can call upon. Perhaps you missed some flag or something, no idea. I am just reporting what I am witnessing.

Please take a look at this, perhaps the maintainer of the Pale Moon for Mac builds can fix this oversight.

_PS: Somewhat off-topic, but: Keep up the good work! Pale Moon works on websites where even the other browsers I have installed on my system fail, it is an important compatibility fallback for me. Plus, a relative recently commented on how top notch my browser looks (optics: Pale Moon + White Moon theme on Mac), and wanted to know what browser it is. :)_

**Comment by Peacock365** [comment]
@wolfbeast 

Is the maintainer of Pale Moon for Mac on GitHub by chance? If so, I could relay the issue to him / her, if you know who it is.

I realize that Pale Moon for Mac is not an official release of the project, but since this seems to be a bug, I thought opening an issue on GitHub was the right course of action.

**Comment by wolfbeast** [comment]
I have no idea. They are on the forum, please go there to open up communication.

As for the problem at hand: I don't know off-hand if this can be done in a language pack or not. It requires research.

**Comment by Peacock365** [comment]
No movement here for over two months now, closing this. I'll try contacting the maintainer of Pale Moon for Mac one way or another, to see what can be done. 

Allow me one last word: You were extremely unfriendly and rude towards me in another issue here, without having been provoked by me at all. It's OK to have a bad day, but please do not let it out on your users who just try to help out. If this kind of tone and behavior is acceptable amongst the development team, fine, but it is definitely unacceptable conduct towards the public, or even any individual human being. Learn to behave or at least to communicate your disagreement properly if you have any, otherwise this project won't be going anywhere.

**Comment by mattatobin** [comment]
Don't let the door hit you.

**Comment by Peacock365** [comment]
@mattatobin 

Thank you for exemplifying my point, quod erat demonstrandum.

**Comment by wolfbeast** [comment]
Excuse me but I told you to go to the forum about this and contact the people building Mac. Don't blame us for your own inaction.
