### ISSUE TITLE
Uninstall doesnt work

### ISSUE THREAD

**Issue by nu8** [MoonchildProductions/UXP#1594]
If I run the uninstaller, the process runs and item is removed from the programs list.

However it doesnt actually uninstall the program. The full Pale Moon directory is left under Program Files untouched.

**Comment by wolfbeast** [comment]
As it turns out this is fallout from https://github.com/mozilla/gecko-dev/commit/a77bf2cf907573b51b5d98c4674105975845a151#diff-60a9c5ff3062b5aa8abd6641434bd3dfL5166 -- backing that out fixes the issue since it enforces elevation (either silent or with prompt) to remove permission-locked files.
