### ISSUE TITLE
Caching problem with javascript disabled

### ISSUE THREAD

**Issue by GarfieldsPipe** [MoonchildProductions/UXP#1597]
There seems to be a problem with Pale Moon and the caching function in combination with javascript disabled. When visiting https://zchan.cc/bypass.html with javascript disabled and clicking the little 'refresh' arrow in the corner, the captcha doesn't refresh. Only if you right-click the captcha image after clicking the refresh arrow, then click 'view image', then go back to the page with the captcha and click the refresh arrow again it shows a new captcha. It works fine with javascript enabled.
The developer of the software that uses the captcha says this:

> With JS disabled, what happens inside the frame is:
>     1. Refresh button submits to /newcaptcha
>     2. Response from /newcaptcha clears captchaid cookie and redirects to /captcha.html
>     3. captcha.html contains an <img src="/captcha", which serves a new captcha because you no longer have a captchaid cookie.
> Palemoon breaks on 3 because it never reloads the image after the page refreshes.

And also:

> Just checked and the issue is also present in Basilisk, another browser made by same dev team as palemoon.

It works fine in other browsers (Firefox, Chrome, Tor Browser) with javascript disabled so it seems to be a Pale Moon-specific problem. Here is a screen recording video to demonstrate the problem on Pale Moon with javascript disabled: https://files.catbox.moe/npysc6.mp4

Hopefully all of this is clear. If not, do ask for more information and I'll be happy to provide it. Thanks.

**Comment by wolfbeast** [comment]
Analysis in no-javascript mode:
1. /newcaptcha 302-redirects to /captcha.html and sets the following cookie:
    `captchaid=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT`
    This effectively removes the cookie.
2. /captcha.html 200-OK
3. /captcha (img-src in captcha.html) is unknown and requested: 302-redirects to a specific image and sets a captchaID cookie
    the ID is equal to the file name requested in the 302 minus .jpg
4. The image served has a long-duration cache directive and is stored in the browser's cache as a result.
5. Clicking the refresh sends a new cookie-clear
6. /captcha.html 200-OK
7. /captcha (img-src in captcha.html) is known as a cached image -> the cached image will be served

The cookie is effectively not used and is irrelevant to this sequence.

This is a server-side issue that can be solved several ways:
- no-store solution: If the captcha image is not supposed to be stored in cache, then the web server should send a cache directive accordingly (and not a long-duration image cache directive)
- captcha.html could be dynamic (directly linking to the target image) and not use a 302 redirect to a fixed name `/captcha`.

**Comment by wolfbeast** [comment]
There isn't really anything to do here. The browser is doing everything as-instructed. Closing.
