### ISSUE TITLE
Busy tab prevent user from switch to other tab.

### ISSUE THREAD

**Issue by K4tsuki** [MoonchildProductions/UXP#1598]
If there is a busy tab, overall browser experience is getting worse.
for example if one of the tab running infinite loop `while (true) { let r = 1 + 1;  }`
user cannot switch to other tab, and the browser hanging. Is this problem in the scope?

**Comment by wolfbeast** [comment]
This is not within scope. Busy scripts are already watched and will trigger the busy script dialog to terminate them if they cause issues.
