### ISSUE TITLE
Not respecting JPG exif orientation

### ISSUE THREAD

**Issue by Massimo-B** [MoonchildProductions/UXP#1601]
This is palemoon-28.10.0, compiled on Gentoo Linux with gcc x86_64-pc-linux-gnu-9.3.0.

This picture is not rotated correctly as it is in recent Firefox or Chrome:

![IMG_20200502_172208](https://user-images.githubusercontent.com/3286728/85857784-ca0ef780-b7ba-11ea-978b-3003373d2d3c.jpg)

**Comment by wolfbeast** [comment]
right-click -> view image: the image is rotated correctly according to exif information.
If this is supposed to occur in webpages, then ther web-page has to specify the following css on the img element: `image-orientation: from-image;`

**Comment by JustOff** [comment]
In fact, this is just another experimental feature approved by CSS-WG currently implemented by both Google and Mozilla:

* [Consider changing initial value of 'image-orientation' to from-image](https://github.com/w3c/csswg-drafts/issues/3799#issuecomment-516918322)

**Comment by wolfbeast** [comment]
OK so for reference "recent Firefox" in [comment 0](https://github.com/MoonchildProductions/UXP/issues/1601#issue-646234247) meaning Firefox 76+ (one cycle ago).
