### ISSUE TITLE
Does UXP still support BSDs system?

### ISSUE THREAD

**Issue by gh-legacy** [MoonchildProductions/UXP#1604]
I know the problem between you and the BSDs. I don't ask for a build of Pale Moon or Basilisk for the BSDs. I only wonder if UXP could be built on the BSDs so UXP based apps could run on these platforms. Just that.

I think I'm better just ask before fire up a VM installing a BSD and try compiling UXP.

**Comment by mattatobin** [comment]
No idea, maybe. Aside from Darwin via OS X we do absolutely no BSD testing. My guess is it won't successfully compile due to the continued purging of UNIFIED_SOURCES.

**Comment by smnthermes** [comment]
> My guess is it won't successfully compile due to the continued purging of UNIFIED_SOURCES.

I'd like to think that the reasons for it are totally legit, because due to Red Hat/IBM takeover of Linux (not to mention the [security mess](https://www.washingtonpost.com/sf/business/2015/11/05/net-of-insecurity-the-kernel-of-the-argument/) that is the kernel), many users are going to switch from it in the future.

**Comment by gh-legacy** [comment]
> > My guess is it won't successfully compile due to the continued purging of UNIFIED_SOURCES.
> 
> I'd like to think that the reasons for it are totally legit, because due to Red Hat/IBM takeover of Linux (not to mention the [security mess](https://www.washingtonpost.com/sf/business/2015/11/05/net-of-insecurity-the-kernel-of-the-argument/) that is the kernel), many users are going to switch from it in the future.

I disagree. The takeover of Red Hat doesn't effect the way I use Linux. I have never used their distros, both RHEL, CentOS or Fedora. I started with Ubuntu and now running Debian Testing.

BTW, I think the project should keep support these systems. If Windows and Linux are tier1, MacOSX is tier2, SunOS is tier3 then the BSDs should be tier4. That means building of UXP based apps on the BSDs still possible, but they won't be supported by any means: no forum board for them, no official release but only building guide, bugs reported about the BSDs will be the least priority... Building and running UXP based apps on the BSDs is the own business of the users using them.

**Comment by gh-legacy** [comment]
> No idea, maybe. Aside from Darwin via OS X we do absolutely no BSD testing. My guess is it won't successfully compile due to the continued purging of UNIFIED_SOURCES.

I will set up a BSD VM and try building Pale Moon. I don't use the BSDs at all. But it's just because of curiosity.

**Comment by mattatobin** [comment]
You should returrn to the forum for discussion. The issue tracker is not a forum and is for out benefit not yours.
