### ISSUE TITLE
Add-ons targeting the Toolkit ID (and not Firefox) are not being considered "native" in Pale Moon

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1612]
Since we are transitioning from Pale Moon's Dual-GUID system certain changes were made to warn people about old and insecure Firefox-targeted Add-ons.. Mainly extensions. Other add-on types namely themes and dictionaries were completely forbidden. 

However, those add-ons targeting the toolkit and not the application were (inconsistently) showing warnings and in the matter of dictionaries (which there is no reason to use anything BUT toolkit ID since dictionaries provided they work are usable on any application and maintaining large amounts of `targetApplication` blocks).

----
Reference: Issue #1446
Supplementary Background: [Tycho Implementation](https://github.com/MoonchildProductions/Tycho/commit/2cf4a11b8cef081ef584c1545bed8a609bbd3975) | [Original Implementation](https://github.com/MoonchildProductions/Pale-Moon/commit/4f62ea7ddf7ed8326ae003025206ae2059f8417f)

**Comment by mattatobin** [comment]
Leaving open for uplift.

**Comment by wolfbeast** [comment]
Uplifted in b9b9d5bfb9fc36b6cccb06e730674165872ad852
