### ISSUE TITLE
SunOS LDAP cleanup

### ISSUE THREAD

**Issue by athenian200** [MoonchildProductions/UXP#1615]
I actually meant to do this a long time ago and forgot about it, but there was some more old code in libldap that needed to be cleaned up. It does currently build, but the changes I want to make should make things a bit smoother and more future-proof.

Specfically, it assumes we don't have a ctime_r implementation in time.h, and we have had one for a while. Actually, we have two implementations of it and I basically added a build flag that says which one to use.

**Comment by mattatobin** [comment]
Reopened for uplift
