### ISSUE TITLE
Convert Intrinsic Ratio from nsSize to Float

### ISSUE THREAD

**Issue by RealityRipple** [MoonchildProductions/UXP#1619]
Aspect Ratio handling simplified by using floating point integers:
- Multiplication of value (or inverse value) to a known side for Scaling
- No unequal equal values such as "4/3" vs "8/6" vs "20/15"
- Truly "Empty" aspect ratios, even if one dimension is not 0

This is accomplished by the creation of a new AspectRatio structure to replace nsSize usage, which is just some useful functions wrapped around a float.

Ref: BZ [Bug 1547792](https://bugzilla.mozilla.org/show_bug.cgi?id=1547792) and BZ [Bug 1548768](https://bugzilla.mozilla.org/show_bug.cgi?id=1548768)

Blocks [Issue 1620](https://github.com/MoonchildProductions/UXP/issues/1620)

Resolved in [PR 1622](https://github.com/MoonchildProductions/UXP/pull/1622)

**Comment by RealityRipple** [comment]
I'm not certain, but BZ Bug 1548768 might need direct `aspect-ratio` CSS support before a testcase can be produced. It needs both sizes set as `auto` and a valid intrinsic ratio at the time `ComputeSizeWithIntrinsicDimensions` is called for the given nsFrame. I'm pretty sure the actual problem is fixed as `logicalRatio` is what values are `ApplyTo()`'d, which is what the Phabricator comments suggest doing, but without a testcase, I can't be sure. If it does all look good, we can just delete those comments and apply the patch for now, and come back to the testcase if `aspect-ratio` makes its debut.

**Comment by wolfbeast** [comment]
...or write a testcase that specifically tests what you're supposed to be fixing here.

**Comment by RealityRipple** [comment]
That's kind of part of the problem. I'm not sure exactly when `ComputeSizeWithIntrinsicDimensions` is called, and if the code in question ever gets run. Despite being about this change, the testcase itself would be reliant on the existence of `aspect-ratio` as a CSS property (which we're not doing), because even after #1620 is done, the internal aspect-ratio value will still need both a width and height set for a ratio to exist, which means the changed code won't run because both a width and height are set to something other than `auto`. I can write a testcase to make sure images and objects are the right size in both horizontal and vertical writing modes, both in general and upon their immediate creation, but I can't guarantee that's the right thing to test.

**Comment by mattatobin** [comment]
I know this won't reflect your changes but you do know we have a Code Cross-Reference, right?

----
http://xref.palemoon.org/moonchild-central/ident?i=ComputeSizeWithIntrinsicDimensions

**Comment by wolfbeast** [comment]
I'm not sure I understand. You can write a testcase that addresses THIS ISSUE, right? Because if you're saying there's no way to test it because the code won't be called without css-aspect-ratios, then how are you going to solve this particular issue with that code?

**Comment by RealityRipple** [comment]
As far as I know, there is no existing issue. The issue was when the original author of the code didn't correctly handle vertical writing modes. Two key changes, `layout/generic/nsFlexContainerFrame.cpp` line 1532 and `layout/generic/nsFrame.cpp` line 4924 (in proposed code) were wrong, but are currently right, both in the proposed code and in the final FF code. The point was that they expose a potential issue with future code implementations that should be checked for if ever similar additions are made, such as `aspect-ratio`.

**Comment by RealityRipple** [comment]
> 
> 
> I know this won't reflect your changes but you do know we have a Code Cross-Reference, right?
> 
> http://xref.palemoon.org/moonchild-central/ident?i=ComputeSizeWithIntrinsicDimensions

No, I did not. That is extremely useful.

**Comment by RealityRipple** [comment]
Just finished my compile with the "bad" lines. Yes, the code gets called. Yes, it's noticeable. Yes, the testcase can be made, pretty simply.

**Comment by wolfbeast** [comment]
*headdesk* when I say "this issue" I mean this. right here. #1619

**Comment by RealityRipple** [comment]
The conversion from nsSize to float is supposed to be entirely transparent, with no functional change. And the testcase I made for vertical writing kind of covers the usage of intrinsic aspect ratios by specifying one dimension and leaving the other as auto. The vertical writing mode code isn't broken - creating a testcase was the only thing that needed fixing. While the original author was writing it, the need for the testcase was exposed by his using the wrong checks. Those wrong checks were made right before FF implemented the changeset, and the conversion to float does not change expected behavior.

**Comment by RealityRipple** [comment]
This issue didn't get closed because the Pull Request didn't get linked. I don't have access to do it.
