### ISSUE TITLE
Input - datetime

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#162]
I'm not sure if any of this was ported across from Moebius yet, but if not, we should do so.

https://github.com/MoonchildProductions/moebius/pull/92

**Comment by janekptacijarabaci** [comment]
IMHO - the base is ready:
[tree@html_input_datetime_1](https://github.com/janekptacijarabaci/UXP/tree/html_input_datetime_1)

**Comment by wolfbeast** [comment]
Question... if Mozilla's "fill" hack isn't implemented, did you actually compensate for that in the svg?

**Comment by janekptacijarabaci** [comment]
> if Mozilla's "fill" hack isn't implemented, did you actually compensate for that in the svg?

The only "compensation" is:
https://github.com/janekptacijarabaci/UXP/commit/bbfe249fd06ffa7b7084755578c06f43fe0fe474

An assumption is that this style (CSS) will be tuned later.

**Comment by wolfbeast** [comment]
I see. thank you!

**Comment by mattatobin** [comment]
RESOLVED AFAIKIHMOFFSJANEK

**Comment by wolfbeast** [comment]
RESOLVED PERSONVANISHED
