### ISSUE TITLE
[MailNews] E-mail Wizard - Failed to get string authOAuth2 in bundle with OAuth2 disabled

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1625]
The "baby mode" `emailWizard.js` is not properly working with OAuth2 disabled at compile time. The SMTP drop downs are all busted, even though IMAP and POP are working properly. This is a apparently unresolved since Issue #1258 `Ifdef MailNews OAuth2 Support`, but was not reported until now.

Screenshot:
![baby mode](https://i.imgur.com/T6z2WV8.jpg "Unable to select SMTP options")

Error:
```
*** Failed to get string authOAuth2 in bundle: chrome://messenger/locale/messenger.properties
JavaScript error: XStringBundle, line 22: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]
```

On an initial investigation it appears everything has been ifdef'd in `mailnews`, but the fields still do not work unless `authOAuth2` has been added to `messenger.properties` in the mail application. 

I'm unsure if the preprocessor is just not picking our ifdef's up or if we overlooked something. 
@mattatobin you're the specialist on ifdefs and did work on this previously in #1258, perhaps you can take a peek at it?

**Comment by mattatobin** [comment]
Wrong tags and assumptive assignments. I cannot test this because your applications don't build on Windows and my application isn't stripped of Oauth2.

You have the issue, you figure it out.

**Comment by wolfbeast** [comment]
Like it or not but OAuth is in fact used by people with mail accounts, and RSS/ATOM feeds :D 
Maybe you want to re-think building without it? Just saying.

**Comment by g4jc** [comment]
`MOZ_MAILNEWS_OAUTH2` is being enforced at compile when `MOZ_MAILNEWS` is built per [old-configure.in#L2759](https://github.com/MoonchildProductions/UXP/blame/master/old-configure.in#L2759). Disabling it in `confvars.sh` has no affect as it is apparently overridden. Removing this line results in a functioning build.

**Comment by wolfbeast** [comment]
So it'd be a build system issue then.

**Comment by mattatobin** [comment]
Is it? Just use the disable flag in mozconfig. It will work.

**Comment by mattatobin** [comment]
I am not willing to make it available to `confvars.sh` because this feature is very much desired for any consumers of `mailnews` that may crop up.. This is only a concern for Hyperbola because of insane "non-free" definitions.

**Comment by wolfbeast** [comment]
Ah sorry for misunderstanding the situation.

**Comment by g4jc** [comment]
Using Thunderbird's OAuth identifier is not a mere freedom issue, it's also an issue of getting unwanted attention by Google or Mozilla for impersonating their application ID. Assuming that they would even give us a key, one would have to apply for support from Google to get official OAuth2 support from my understanding.

Off-topic @mattatobin:
> Since we are no longer even listed as "unaligned" am I supposed to go back to my own branch of `mailnews` now? You've banned me from your channel as well so I guess it's your way of telling me to move on to better things. I'm hardly co-maintainer of the `mailnews` when we can't even communicate so that we can correlate on our applications.

**Comment by mattatobin** [comment]
Looks like we are communicating just fine here. Doesn't it. Stop over-reacting.

If it will stop your crying...

**Comment by wolfbeast** [comment]
For the record, this is still UXP, a generic platform. If we provide `mozconfig` options to disable or enable certain features, you are expected to **use them** for your **individual** application needs at build time. `Confvars.sh` is generally only an place to put configuration variables that are known to differ **often** or are a common decision to make per application, not outliers, which is why far from everything can be configured there.
