### ISSUE TITLE
Disabled attribute cannot be set on <link> elements from HTML

### ISSUE THREAD

**Issue by athenian200** [MoonchildProductions/UXP#1629]
This functionality appears to have been implemented by beta Chrome and Firefox, and is being proposed as a new standard:

https://github.com/whatwg/html/issues/3840
https://bugzilla.mozilla.org/show_bug.cgi?id=1281135
https://chromestatus.com/feature/5110851973414912

It involves making the link element respect the disabled content attribute as other HTML elements do, and the creation of a new "Explicitly Enabled" flag that gets set when a linked stylesheet has the "disabled" content attribute removed.

I'm wondering if we actually want this? One problem this feature seems to cause is that once you implement this feature and disable a stylesheet in this manner, that stylesheet then disappears from View->Page Style until it is re-enabled via JS.

**Comment by wolfbeast** [comment]
Of note, in the WhatWG spec issue emilio is constantly pushing for what Chrome's implementation is.

Honestly, I don't care. if it improves web compat and you've already done the work then I'll just throw my hands in the air and go with the program.

**Comment by mattatobin** [comment]
Please pref it default on.

**Comment by athenian200** [comment]
Yeah, my main gripe with the final spec they came up with is that I think the disabled HTML attribute should do exactly the same as what disabling the element via JS does now, and leave the stylesheet in document.styleSheets, but I didn't really think it made sense for me to pursue an idea like that given that the spec is already implemented in both mainstream browsers. In my opinion, disabled <link> elements that contain a stylesheet should just be regarded as alternate stylesheets. That would have been the simplest solution, since we already enable alternates when the disabled attribute is removed anyway.

Anyway, I put the "meat" of the implementation behind preferences so it no longer does anything when the pref is switched off and behaves the old way, but I wasn't able to pref off every implementation detail, so there might be slight differences in behavior between how it acts with the pref off and the default behavior, but I haven't noticed any.

**Comment by wolfbeast** [comment]
FTR this throws compiler warnings on IsExplicitlyEnabled:

```
26:00.13 Loader.cpp
26:00.13 Warning: C4700 in c:\mozdev\palemoon\platform\layout\style\loader.cpp: uninitialized local variable 'isExplicit
lyEnabled' used
26:00.13 c:\mozdev\palemoon\platform\layout\style\loader.cpp(2409) : warning C4700: uninitialized local variable 'isExpl
icitlyEnabled' used
26:00.13 Warning: C4700 in c:\mozdev\palemoon\platform\layout\style\loader.cpp: uninitialized local variable 'isExplicit
lyEnabled' used
26:00.13 c:\mozdev\palemoon\platform\layout\style\loader.cpp(2286) : warning C4700: uninitialized local variable 'isExpl
icitlyEnabled' used
```
We probably need to address those before closing this issue.

**Comment by athenian200** [comment]
I didn't get that warning actually. Hmm.... I don't think I can make this work. Every other way I tried this failed miserably. It looks like I would have to pass in the variable in one of the ways that makes it choke, and thus I can't actually make it work safely/reliably with our codebase at all. It's just not compatible.

**Comment by wolfbeast** [comment]
The problem seems to be that you define a local boolean, then use it in the function call in those two places. They are simply not initialized to an initial value there (which I assume will be "false" if uninitialized otherwise). I'm assuming initializing them to false is the right thing in both functions?

In `Loader::InternalLoadNonDocumentSheet`
```C++
  StyleSheetState state;
  bool isAlternate;
  bool isExplicitlyEnabled;
  RefPtr<StyleSheet> sheet;
  bool syncLoad = (aObserver == nullptr);
  const nsSubstring& empty = EmptyString();

  rv = CreateSheet(aURL, nullptr, aOriginPrincipal, aParsingMode,
                   aCORSMode, aReferrerPolicy, aIntegrity, syncLoad,
                   false, empty, state, &isAlternate, &sheet);
  NS_ENSURE_SUCCESS(rv, rv);

  PrepareSheet(sheet, empty, empty, nullptr, nullptr, isAlternate, isExplicitlyEnabled);
```

In `Loader::LoadChildSheet`
```C++
  if (aReusableSheets && aReusableSheets->FindReusableStyleSheet(aURL, reusableSheet)) {
    sheet = reusableSheet;
    aParentRule->SetSheet(reusableSheet);
    state = eSheetComplete;
  } else {
    bool isAlternate;
    bool isExplicitlyEnabled;
    const nsSubstring& empty = EmptyString();
    // For now, use CORS_NONE for child sheets
    rv = CreateSheet(aURL, nullptr, principal,
                     aParentSheet->ParsingMode(),
                     CORS_NONE, aParentSheet->GetReferrerPolicy(),
                     EmptyString(), // integrity is only checked on main sheet
                     parentData ? parentData->mSyncLoad : false,
                     false, empty, state, &isAlternate, &sheet);
    NS_ENSURE_SUCCESS(rv, rv);

    PrepareSheet(sheet, empty, empty, aMedia, nullptr, isAlternate, isExplicitlyEnabled);
  }
```
I think in both case: when you are loading the stylesheet and preparing the new sheet for use, it's likely you don't want to also explicitly enable it during load.
So initializing to false would be the right initial value there, don't you think?

**Comment by athenian200** [comment]
I'm testing that now to see if it works, because the more I think about it, the more I realize there's no way to know that during initial load. I thought it was getting a value here from somewhere outside, and that's why I was so confused on this. If there was no outside value coming in, and it defaults to false... then if I set them to false, nothing should change.

**Comment by athenian200** [comment]
It appears to work fine with the two variables explicitly set to false after all, and I actually understand the last piece of the puzzle of how this all works now. Even after I got this working, I was still unsure how the value was getting passed in here and how it started working with just a local variable here. I was worried that worried that somehow the value was being passed in too late or depending on undefined behavior... but it turns out that it was getting a false value from the default value of a boolean and that just happened to be correct in this instance.

**Comment by wolfbeast** [comment]
So, we can just scrap the local variable in these instances and pass `false` to the `prepareSheet()` call directly, since it's not being used elsewhere AFAICT.

**Comment by athenian200** [comment]
Yeah, I was thinking of doing that but wasn't confident enough in my assessment to make that change. However I tested that and it does still work fine. It really clears things up in a way because now it's clearer that the explicitly enabled flag is always passed as false to the PrepareSheet function initially and can be set to some other value only later in the process.

**Comment by wolfbeast** [comment]
So, will you toss this in a PR or do you want me to just edit it?

**Comment by athenian200** [comment]
Ah, I apologize. I didn't realize that my original PR had already been merged. I created another one.

**Comment by mattatobin** [comment]
Seems you jumped the gun on merging this and he didn't use the draft functionality.

**Comment by wolfbeast** [comment]
Only in as much as that I wanted the fix in our latest release. It's only by chance that I saw the compiler warning later on.

**Comment by mattatobin** [comment]
Ah ok.
