### ISSUE TITLE
Remove plugin check leftovers

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1644]
There are still some (actively used) plugin checking leftovers in the tree that need to be removed.
This will likely also need FE changes in Pale Moon and Basilisk (but potentially only a pref thing)

**Comment by wolfbeast** [comment]
Basilisk seems properly devoid of any leftovers so this should be all done.

**Comment by wolfbeast** [comment]
@JustOff Please note cleanup of some unused strings.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
