### ISSUE TITLE
disabled all "not designed for PaleMoon" extensions in 29.0.0a6 & 28.13.0

### ISSUE THREAD

**Issue by gogerald116** [MoonchildProductions/UXP#1645]
Hi @wolfbeast @mattatobin 

THERE IS A MAJOR PROBLEM IN THE LATEST UNSTABLE BUILD

Windows 10 20h2 64bit
32/64bit PM
Upgrading to latest 29.0.0a6  build disables most add-ons(Which do not target PM but FF and work fine)
sometimes Upgrading to 28.13, non-native extensions and the current unstable version 29.0.0a6 does disable non-native extensions. 

Please fix it or many extensions which work fine will be disabled which is
PM biggest asset

**STR1**

install 29.0.0a5 

install addons(or use the old ones)

Eg: Flashgot works fine with PM but no longer updated

Update to 29.0.0a6 

addons disabled

**STR2**

29.0.0a6 
install Flashgot
cannot install

install v28.13.0 
install 
Flashgot
installs fine and works

now copy profile of v28.13.0 or 29.0.0a5 to 29.0.0a6(run once so profile is created) except pref.js(so PM upgrade/release update is not triggered)
Flashgot works fine

now just to verify that 29.0.0a6  change is culprit
edit prefs.js and delete platform version (so PM upgrade/release update is not triggered)

restart

Addons disabled again

the problem started after one of these Me thinks between 29.0.0a5 -29.0.0a6 
https://github.com/MoonchildProductions/Pale-Moon/commit/f7a1deb67deb399a3c1446891a6c1f65ccbc61c3

https://github.com/MoonchildProductions/Pale-Moon/commit/0882134ff760e71c54f2f952979f702a933cd519

https://github.com/MoonchildProductions/Pale-Moon/commit/202766decef670ed78874653758c26baf32ca2a6

https://github.com/MoonchildProductions/Pale-Moon/commit/0aa10d7302c4cfec530347949e73fa64477a5751

PLEASE FIX THIS AS IT'S A VERY MAJOR PROBLEM/REGRESSION FOR THE PM USER BASE
Many people will loose old addons which work fine but are disabled

Also can you guys provide a way to bypass checking addons?
So the user knows the risks but can use the addons if they work fine but do not target PM
like xpinstall.signatures.required
something like

xpinstall.allow all

Thank you for this lovely browser
regards
Gerald

**Comment by gogerald116** [comment]
Found similar issue but don't have an account there

reported here but only on linux and mac
https://forum.palemoon.org/viewtopic.php?f=40&t=25156

**Comment by wolfbeast** [comment]
Please read: https://forum.palemoon.org/viewtopic.php?f=46&t=23697

If you need release stability without future changes, then do not use the unstable version.

**Comment by gogerald116** [comment]
So"not designed for PaleMoon" extensions in 29.0.0a6
will not be fixed?
Cannot use those addons anymore?
and will be merged with 28.1x.0?
any overrides?

So for the pings new to github.

**Comment by Nuck-TH** [comment]
Stability and overall workability of extensions is responsibility of their developers, not browser. Extensions extend browser, not other way around, and browser not bound to cater to backwards compatibility with extensions at expense of it's own development(and, most importantly, scarce time of its developers) . Milestone 29 will break more of Firefox extensions merely by version number - australis came in FF29 and if extensions assume australis by app version - they will break. However this is not as severe as Mozilla dropping XUL extension support alltogether, and nobody really impactfully "trashed" them for that.
This all was endlessly explained on the Pale Moon forums btw, yet nobody listens or understands.

**Comment by gogerald116** [comment]
> 
> 
> Stability and overall workability of extensions is responsibility of their developers, not browser. Extensions extend browser, not other way around, and browser not bound to cater to backwards compatibility with extensions at expense of it's own development(and, most importantly, scarce time of its developers) . Milestone 29 will break more of Firefox extensions merely by version number - australis came in FF29 and if extensions assume australis by app version - they will break. However this is not as severe as Mozilla dropping XUL extension support alltogether, and nobody really impactfully "trashed" them for that.
> This all was endlessly explained on the Pale Moon forums btw, yet nobody listens or understands.

Here's the thing they work fine.
it's just a Number Change is making them useless not that they are broken.
merely by version number if they break then allow to keep he internal number constant
or
_**there should be a way to by-pass via a pref if the user want's to install them,**_
let them choose, PM already shows warning about them but people like to use them & that's not hidden.
Those extensions are archived so they won't be adding a new api or changing things because they are Stable, so why not let them be?
they are fixed so supporting them (PM already does) is not about them not working as intended.
they are being blocked because of a arbitrary NUMBER CHANGE!!
**_That all saying here, let the user choose & decide for themselves._**

Please try to understand the user & why they choose PM @Nuck-TH

**Comment by wolfbeast** [comment]
If you think the version number is the only thing that changes in the platform between releases, then you clearly haven't taken notice of the release notes and the development going on here. Pale Moon/UXP is actively developed. Extensions can and do break. A good number of Firefox-focused extensions already no longer work and that will just get worse.

Now if you have more you think you need to say, kindly first go to the forum and read up on what is happening in the extension ecosystem.

**Comment by wolfbeast** [comment]
... and then they nuked their github account. Wow. Just wow.
