### ISSUE TITLE
Crash on www.pbs.org

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1650]
As [reported](https://forum.palemoon.org/viewtopic.php?f=29&t=25207) on the forum.
Preliminary investigation shows this to be a null crash in `HitTestBasicShapeClip`which gets hit with us having enabled `layout.css.clip-path-shapes.enabled` in Pale Moon 28.12.0/RELBASE_20200730

**Comment by wolfbeast** [comment]
The added null check should prevent these crashes. Could someone please verify?

**Comment by mattatobin** [comment]
I'll do it. I need to build anyway.
