### ISSUE TITLE
Pale Moon incorrectly declares invalid property value

### ISSUE THREAD

**Issue by GarfieldsPipe** [MoonchildProductions/UXP#1664]
Pale Moon incorrectly declares the CSS property `word-break: break-word;` an invalid property value on a certain webpage. Using 28.14.1 on Windows.
![bug](https://user-images.githubusercontent.com/66557589/94915590-70028a00-04ad-11eb-9de0-c24cf4efe60e.png)

**Comment by wolfbeast** [comment]
`word-break: break-word` is a deprecated property value that websites should not use.
See also: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
We do not support it and it is therefore invalid; other browsers may drop support for it at any time.

**Comment by GarfieldsPipe** [comment]
> `word-break: break-word` is a deprecated property value that websites should not use.
> See also: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
> We do not support it and it is therefore invalid; other browsers may drop support for it at any time.

That's incorrect. Nothing on the page you linked implies it's deprecated. It is also used as a valid example on https://www.w3schools.com/cssref/css3_pr_word-break.asp and https://www.w3.org/TR/css-text-3/

**Comment by wolfbeast** [comment]
> That's incorrect. Nothing on the page you linked implies it's deprecated.

You probably didn't look very closely since it's clearly marked as deprecated.

>  Removing support for it would be absurd.

We didn't remove support for it. We never supported it to begin with and what would be absurd would be adding support for it when it's a deprecated value.
