### ISSUE TITLE
Implement ES6 iterable closures

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#17]
Even though this hovered a long time on being removed from the spec or not, it ended up becoming final.

For closures, we need to port 2 main bugs (+ possible follow-ups) to our version of SpiderMonkey that landed in Firefox 53:
- [Bug 1180306](https://bugzilla.mozilla.org/show_bug.cgi?id=1180306) - new Map(iterable) should close the argument iterator after a value is not Object error.
- [Bug 1147371](https://bugzilla.mozilla.org/show_bug.cgi?id=1147371) - Implement IteratorClose

**Comment by janekptacijarabaci** [comment]
For [bug 1180306 - new Map(iterable) should close the argument iterator after a value is not Object error](https://bugzilla.mozilla.org/show_bug.cgi?id=1180306)

---

Some test/personal branch:
[tree@js_iterable_closures_1](https://github.com/janekptacijarabaci/UXP/tree/js_iterable_closures_1)

Not tested, only:

Before:
![1_1](https://user-images.githubusercontent.com/2373486/37488836-b9d93132-288d-11e8-883b-5e6c57d877d3.png)
![1_2](https://user-images.githubusercontent.com/2373486/37488837-b9f97df2-288d-11e8-88cb-61c4cd5121bf.png)
![1_3](https://user-images.githubusercontent.com/2373486/37488838-ba151f26-288d-11e8-9bce-2161c4bc3074.png)
![1_4](https://user-images.githubusercontent.com/2373486/37488839-ba37f924-288d-11e8-80d8-704d300903df.png)

After:
![2_1](https://user-images.githubusercontent.com/2373486/37488849-beb64604-288d-11e8-90a2-4e88d0cac7be.png)
![2_2](https://user-images.githubusercontent.com/2373486/37488852-befd0738-288d-11e8-9a56-9b9897d68424.png)
![2_3](https://user-images.githubusercontent.com/2373486/37488853-bf2370e4-288d-11e8-8785-9ff9b8bbe00f.png)
![2_4](https://user-images.githubusercontent.com/2373486/37488855-bf43dfb4-288d-11e8-914e-dfe9b5708361.png)

---

Please you let me know if I do not write it (it is the core, but I'm doing a test build for personal use - sometimes) or add descriptions (in commits) to an existing issue (`Issue #17`, in this case).

**Comment by wolfbeast** [comment]
> Please you let me know if I do not write it (it is the core, but I'm doing a test build for personal use - sometimes) or add descriptions (in commits) to an existing issue (Issue #17, in this case).

I'm sorry, I don't know what you're trying to say here.

Looks like your implementation is kosher! Feel free to make a pull request for it.

**Comment by janekptacijarabaci** [comment]
> I'm sorry, I don't know what you're trying to say here.

...then I should not do it at all (if it's not complete or fully functional - maybe).

**Comment by wolfbeast** [comment]
#66 indicated it's a partial fix - what are we still missing here?

**Comment by janekptacijarabaci** [comment]
[Bug 1147371](https://bugzilla.mozilla.org/show_bug.cgi?id=1147371) - Implement IteratorClose
IMHO, there are dependencies
(e.g. in BytecodeEmitter - [Bug 1204028 - Evaluate LHS reference before RHS in destructuring](https://bugzilla.mozilla.org/show_bug.cgi?id=1204028)).

And IMHO/AFAIK: Some other things (ECMAScript 6 - from FF53/moebius) should fix before this, e.g. (I suggest):

---

- __ECMAScript 6 - new Function() support__

https://www.ecma-international.org/ecma-262/6.0/index.html#sec-function-p1-p2-pn-body

> 19.2.1.1 Function ( p1, p2, … , pn, body )
>
> The last argument specifiies the body (executable code) of a function; any preceding arguments specify formal parameters.
> When the Function function is called with some arguments p1, p2, … , pn, body
> (where n might be 0, that is, there are no “p” arguments, and where body might also not be provided),
> the following steps are taken:
> 1. Let C be the active function object.
> 2. Let args be the argumentsList that was passed to this function by [[Call]] or [[Construct]].
> 3. Return ? CreateDynamicFunction(C, NewTarget, "normal", args).
>
> NOTE
> It is permissible but not necessary to have one argument for each formal parameter to be specifiied. For example, all three of the following expressions produce the same result:
> new Function("a", "b", "c", "return a+b+c")
> new Function("a, b, c", "return a+b+c")
> new Function("a,b", "c", "return a+b+c")

[Bug 755821](https://bugzilla.mozilla.org/show_bug.cgi?id=755821)

__Some test/personal branch:__
[tree@js_function_new_1](https://github.com/janekptacijarabaci/UXP/tree/js_function_new_1)
(I've created the new build (x32, Windows) and tested (shortly))

---

- __ECMAScript 6 - Error.prototype and .prototype should be ordinary objects__

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-error-prototype-object

> 19.5.3 Properties of the Error Prototype Object
>
> The Error prototype object is the intrinsic object %ErrorPrototype%. The Error prototype object is an ordinary object. It is not an Error instance and does not have an [[ErrorData]] internal slot.
>
> The value of the [[Prototype]] internal slot of the Error prototype object is the intrinsic object %ObjectPrototype% (19.1.3).

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-nativeerror-prototype-objects

> 19.5.6.3 Properties of the NativeError Prototype Objects
>
> Each NativeError prototype object is an ordinary object. It is not an Error instance and does not have an [[ErrorData]] internal slot.
>
> The value of the [[Prototype]] internal slot of each NativeError prototype object is the intrinsic object %ErrorPrototype% (19.5.3).

[Bug 1213341](https://bugzilla.mozilla.org/show_bug.cgi?id=1213341)

---

- __ECMAScript 6 - RegExp.prototype should be an ordinary object__

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-regexp-prototype-object

> 21.2.5 Properties of the RegExp Prototype Object

> The RegExp prototype object is an ordinary object.

e.g.
`RegExp.prototype.exec();` should throws exception:
`exec method called on incompatible Object`

`alert(Object.prototype.toString.call(RegExp.prototype));`
`[object Object]`

[Bug 1192038](https://bugzilla.mozilla.org/show_bug.cgi?id=1192038)

---

- __ECMAScript 6 - Function `name` property__

https://www.ecma-international.org/ecma-262/6.0/#sec-setfunctionname


> 9.2.11 SetFunctionName (F, name, prefix)
>
> The abstract operation SetFunctionName requires a Function argument F, a String or Symbol argument name and optionally a String argument prefix. This operation adds a name property to F by performing the following steps:
>
> 1. Assert: F is an extensible object that does not have a name own property.
> 2. Assert: Type(name) is either Symbol or String.
> 3. Assert: If prefix was passed then Type(prefix) is String.
> 4. If Type(name) is Symbol, then
>    a) Let description be name’s [[Description]] value.
>    b) If description is undefined, let name be the empty String.
>    c)     Else, let name be the concatenation of "[", description, and "]".
> 5. If prefix was passed, then
>    a)    Let name be the concatenation of prefix, code unit 0x0020 (SPACE), and name.
> 6. Return DefinePropertyOrThrow(F, "name", PropertyDescriptor{[[Value]]: name, [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true}).
> 7. Assert: the result is never an abrupt completion.

[Bug 883377](https://bugzilla.mozilla.org/show_bug.cgi?id=883377)

**Comment by wolfbeast** [comment]
All of this should now be in the tree. Closing.
