### ISSUE TITLE
Remove Solaris support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#187]
Blocks #184

**Comment by CitoplasmaX** [comment]
Actually, OpenIndiana has only a Firefox ESR version supported and it is outdated (and others text mode web browsers). It would be great if you provide support for OpenIndiana.

**Comment by mattatobin** [comment]
What does this have to do with Solaris?

**Comment by CitoplasmaX** [comment]
Illumos and OpenIndiana project are derivated from OpenSolaris...

**Comment by mattatobin** [comment]
Well it is being ripped out because we can't reasonably support edge platforms.

**Comment by CitoplasmaX** [comment]
> It would be great if you provide support for OpenIndiana.

Why then?

**Comment by wolfbeast** [comment]
Any projects that depend on the Solaris build system support will fall by the wayside.
If you want to port UXP to any of them, you need to fork it. What Firefox does or does not support has no bearing on what we support or do not support. We are removing target platforms that our project simply can not reasonably continue to "pretend" to support.

**Comment by CitoplasmaX** [comment]
I am asking Why?

**Comment by wolfbeast** [comment]
I already answered that question.

**Comment by wolfbeast** [comment]
Let me put it another way: This issue will be resolved and Solaris support removed unless someone with Solaris hardware/software and Solaris knowledge steps up, becomes part of our team, and makes a solid promise to support and maintain the code necessary to keep the platform updated for Solaris on an ongoing basis. Our team simply can not support edge platforms, no matter how actively they are developed, because it is simply beyond our capacity and expertise. Leaving support in our tree implies we officially support it and are able to solve issues with that target platform -- which is not true, hence "pretend" to support.
