### ISSUE TITLE
Always pre-process jar.mn entries

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#19]
Instead of having to constantly keep tabs on if entries in jar.mn need to be pre-processed or not, we should simply **always** pre-process text-type entries (xul, xml, xhtml, js, css, etc.) and be done with this "must keep it in sync all the time"

**Comment by mattatobin** [comment]
I dunno if that is such a good idea... Also, I have no idea how to modify the build system to do this.. We are talking about a 160 some jar manifests and undoubtedly hundreds of files that would be run through the preprocessor..

**Comment by wolfbeast** [comment]
I know it's going to be a few hundred files run through the preprocessor; it's just a thing I run into time and again: remove some preprocessor blocks or add some preprocessor blocks and you have to manually check if it is the first/last block present in the file and then adjust the manifest. It's a PITA, there must be a better solution for it.

**Comment by mattatobin** [comment]
I've looked at the code and it is a bit ridiculous.. I have also looked at the emitter code for the various moz.build keywords as well..

I just don't think it is worth the trouble of modifying the build system to make everything go through the preprocessor when, as I said, the shuffling around of files in and out of preprocessing will became fairly rare once things are settled..

On a fundamental level, I really think sending all files through the preprocessor is a bad idea.. It will emit hundreds of warnings and increase build time to an unacceptable degree.. As well as some quirks with the preprocessor especially when it comes to files with alternative markers like css.

**Comment by wolfbeast** [comment]
Okay
