### ISSUE TITLE
DevTools - inspector - markup view: add a visual hint between opening and closing tags of a collapsed node

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#2]
__Actual results:__

![before](https://user-images.githubusercontent.com/2373486/35751006-d1be0ad4-084e-11e8-8906-611b83cda9ad.png)

__Expected results:__

![after](https://user-images.githubusercontent.com/2373486/35751000-ca1c647e-084e-11e8-9d6f-2ea319276a5c.png)

**Comment by janekptacijarabaci** [comment]
@wolfbest 
I'm sorry, but that's another commit...

**Comment by wolfbeast** [comment]
I've been cherry-picking commits from moebius - references in the commit message don't apply to this repo.
