### ISSUE TITLE
Badged button renders incorrectly on the main toolbar

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#202]
Here is the test add-on [badged-button.zip](https://github.com/MoonchildProductions/UXP/files/1925374/badged-button.zip) which defines badged-button:
```
  <toolbarbutton id="badged-button-test"
    class="toolbarbutton-1 chromeclass-toolbar-additional badged-button"
  />
```
Pale Moon 27:
![palemoon_2018-04-18_21-40-26](https://user-images.githubusercontent.com/340855/38951751-1e40a392-4339-11e8-9811-ca45cf938952.png)
Pale Moon 28:
![palemoon_2018-04-18_21-44-36](https://user-images.githubusercontent.com/340855/38951770-2f071d14-4339-11e8-8ccc-db118fb5a07f.png)

And here [badged-button3.zip](https://github.com/MoonchildProductions/UXP/files/1925477/badged-button3.zip) - with the badge :
```
  <toolbarbutton id="badged-button-test"
    class="toolbarbutton-1 chromeclass-toolbar-additional badged-button"
    badge="3"
  />
```
Pale Moon 27:
![palemoon_2018-04-18_22-14-55](https://user-images.githubusercontent.com/340855/38953096-3df438d0-433d-11e8-8874-5e51e8711d13.png)
Pale Moon 28:
![palemoon_2018-04-18_22-16-29](https://user-images.githubusercontent.com/340855/38953110-47a75ace-433d-11e8-8bfa-6d1d24351236.png)

Blocks #120, tag #121.

**Comment by janekptacijarabaci** [comment]
See: [bug 1029937](https://bugzilla.mozilla.org/show_bug.cgi?id=1029937) (and depends on)

`.toolbarbutton-badge-container` was renamed to `.toolbarbutton-badge-stack`

**Comment by JustOff** [comment]
> Why was it renamed?... 

Just as always - because they can :imp: 

> This likely means that @Lootyhoof would have to adjust themes for it.

I'm afraid he will have to...
