### ISSUE TITLE
Improvements to cross-compartment wrapper handling when managing tabs

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#208]
Mozilla has resolved this bug with different final implementation and Tycho/Pale Moon currently uses initial implementation.

Would it be possible to backport Mozilla final implementation (Mozilla 55) to UXP?

Bug 816784 - Lots of time spent in WindowDestroyedEvent::Run/js::NukeCrossCompartmentWrappers when closing tabs/windows

https://bugzilla.mozilla.org/show_bug.cgi?id=816784

**Comment by mattatobin** [comment]
Depends on refactoring.. Give it a shot.

**Comment by wolfbeast** [comment]
Be aware that Mozilla's hashtables (and therefore hashmaps) suck, and can lead to bad crashes.
I still prefer the original fix which is a good, straightforward fix for this perf sink without introducing rooting hazards or using hash tables.

That said, if backporting is trivial, it may be better as it does address a few more cases of tab abuse perf hits.

**Comment by wolfbeast** [comment]
I'll be looking at this next.

**Comment by wolfbeast** [comment]
Backporting is not trivial because of xpconnect refactoring between 52 and 55 -- the solution used by Mozilla is likely completely incompatible with our code.

**Comment by wolfbeast** [comment]
Forward porting wasn't trivial either, but I think I got it.
Will make a PR with changes as I'm sure it could use a review by someone or at least some testing by someone other than me before merging.

**Comment by wolfbeast** [comment]
Seems there is no real need for this based on the comments in #482 so wontfixing this for now.
