### ISSUE TITLE
Prep and release Basilisk/UXP

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#219]
It's about time to push Basilisk to UXP, and publish it, so we can archive Möbius.

Checklist:
- [x] Use of extensions
- [x] Use of plugins
- [x] Use of Themes
- [x] Use of FxA Sync
- [x] Video playback/streaming
- [x] Use of DRM/EME
- [x] Use of DRM/Silverlight
- [x] Places (bookmarks/history)
- [x] Tab manipulation
- [x] Preferences check
- [x] System (about:*) pages
- [x] CustomizableUI customization
- [x] Social media
- [x] JS-heavy frameworks
- [x] Lock down e10s
- [x] Switch default search engine to DuckDuckGo

**Comment by trav90** [comment]
Added a point to make DDG the default search engine again.

**Comment by wolfbeast** [comment]
> Added a point to make DDG the default search engine again.

I thought that was already the case... Just in case I emptied the region-specific overrides list but I don't think it's actually used (unless I missed something)

**Comment by trav90** [comment]
I've not looked into it yet but noticed during my testing the past couple days that builds were using Yahoo as default in a new profile. I'll run a new build from tip of master and confirm shortly.

**Comment by khronosschoty** [comment]
Last time I checked the default was yahoo and I'm pleased to see the
return of DDG.

**Comment by wolfbeast** [comment]
Oh, I see what's happening. Pref geospecificdefaults will grab a preferred list on-line from Mozilla... Because screw build files, XD

**Comment by trav90** [comment]
Confirmed in current trunk build (as of  fb37ed0) that DDG is default in a new profile.

**Comment by wolfbeast** [comment]
I went down the rest of the checklist and I think we're good to go on this.
@trav90 could you make Linux builds for this today (04-23)?

**Comment by trav90** [comment]
No problem! I’ll kick off a build and will upload it to the FTP this evening when I get home from work.

**Comment by trav90** [comment]
I seen a new commit on the release branch. Do I need to rebuild with the new commit?

**Comment by wolfbeast** [comment]
I thought that would have been picked up by you by the time you got home from work. Yes, preferably - it's just a pref change to make add-on updates from AMO work.

**Comment by trav90** [comment]
They did, however I had kicked off a build just before leaving this morning. I just kicked off a new build that I’ll upload to the FTP within the hour.

**Comment by trav90** [comment]
Signed tarball is uploading to the FTP site now. Looks like I just missed the date with the new build (sorry for my delay), so the 4/23 build is this mornings and the 4/24 is what I built just now containing the latest commit.

**Comment by wolfbeast** [comment]
That's all right, I'll just bump mine to 24 and publish today

**Comment by wolfbeast** [comment]
Published.

**Comment by wolfbeast** [comment]
Of course there's a bunch of critical things that popped up but they should be reasonably solved now for a v2018.04.26 release ;)
Commit is tagged, @trav90 build any time on the 26th if you can :)

**Comment by trav90** [comment]
I'm on it!

**Comment by wolfbeast** [comment]
Mind UTC time zone ;)

**Comment by trav90** [comment]
A signed, release ready, UTC time zone minded tarball + all the goodies are uploading to FTP as I post this.

**Comment by wolfbeast** [comment]
Aand.. live
