### ISSUE TITLE
"Please note that GitHub no longer supports old versions of Firefox."

### ISSUE THREAD

**Issue by whitestone8214** [MoonchildProductions/UXP#23]
Hi.

It seems newer milestones of Basilisk/UXP is suffering the "Your browser is not supported anymore" problem, that older milestones aren't suffering.

May I ask you how do you think about this problem?

**Comment by whitestone8214** [comment]
Correction:

'It seems newer milestones of Basilisk/UXP is suffering the "Your browser is not supported anymore" problem'
-> 'It seems newer milestones of Basilisk/UXP is suffering the "Your browser is not supported anymore" problem on many sites incl. GitHub, YouTube, etc.'

**Comment by mattatobin** [comment]
Gotta love user agent sniffing.. You aren't building using this repo are you?

**Comment by whitestone8214** [comment]
Ah, it seems an addon that installed on previous milestone caused this problem. After I removed it, the problem not occured.

Sorry for hassle.
