### ISSUE TITLE
Make safebrowsing optional at build time

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#230]
The reliance on Google Safebrowsing is no longer configurable at build time and currently purely controlled with preferences (i.e.: always built/included).

This needs to be made a build-time decision again.

**Comment by trav90** [comment]
I'll take this one.

**Comment by trav90** [comment]
Gonna need another set of eyes on this one. I've restored the configure option and most of the #ifdef's for safebrowsing (still need to make another pass through and make sure I didn't miss any areas that still need them), but in the process I've completely broken the "in-content" preferences page (about:preferences) in Basilisk. The error console throws a warning about an invalid character [here](https://github.com/MoonchildProductions/UXP/commit/41d68e3f70b0aabc01cf9a49c43cf1aab0f4bdce#diff-0cc486f5fbab6f1b1f8b2ee1fd60adb6R26).

What is confusing me is that other in-content .js files are using #ifdef's and no errors are being throws (such as the one here: http://xref.palemoon.org/uxp-trunk/source/browser/components/preferences/in-content/content.js#81). So I'm not sure what it is that I'm overlooking.

The work I've done thus far is here: https://github.com/trav90/UXP/tree/safebrowsing-work

**Comment by JustOff** [comment]
It seems you simply missed to include `security.js` into pre-processing [here](https://github.com/MoonchildProductions/UXP/blob/41d68e3f70b0aabc01cf9a49c43cf1aab0f4bdce/browser/components/preferences/in-content/jar.mn#L17).

**Comment by trav90** [comment]
Thanks @JustOff I knew it had to be something simple I was overlooking. I'll include that file in pre-processing and give it another go.

**Comment by trav90** [comment]
Thanks @JustOff that did the trick. This should now be mostly done. I’ll submit a PR once I’ve had a chance to go back over it and properly test.
