### ISSUE TITLE
Remove geo-specific selection of default search engines.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#245]
This is a Mozilla-ism that defaults to probing a Mozilla server to get non-default server selections for search in an undocumented way for individual locales (the default way is apparently "not good enough" to have search engines and orders set in locale-specific properties).

Prefs are even used to set individual fallbacks in case the lookup fails and a custom list can't be grabbed from a URL.

Reference prefs: `browser.search.geoSpecificDefaults.*`, `browser.search.defaultenginename.{locale}` and `browser.search.order.{locale}.{n}`.

- [X] Disable geo-specific changes and the Mozilla service lookup for release
- [ ] Remove `browser.search.geoSpecificDefaults`
- [ ] Remove the relevant code of the search engine update client

All this needs to go.

**Comment by wolfbeast** [comment]
P1 was solved in fb37ed0a373a0bbc29bbe6e20ca684e856185c5c

**Comment by Ascrod** [comment]
Taking a look at this issue, I think we can also remove `browser.search.countryCode` and `browser.search.region`. See also this comment, which is present in both version of the search service:
https://github.com/MoonchildProductions/UXP/blob/e0116ac2b78eb4e621a4d0769e01f8358a6d661c/toolkit/components/search/current/nsSearchService.js#L396-L408

The comment states that the region is "actually used for search", but I see nothing using it except the URL formatter for the geoip lookup URLs, which we're removing anyway.

I can PR this.
