### ISSUE TITLE
Remove code for sponsored "enhanced" tiles in NewTab page

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#246]
Commit d2a0a16054771b4b0bee38ee7241a976bc1dac75 hard-disabled the use of sponsored tiles ("enhanced" tiles) in the NewTab page already.
The relevant code behind this "sponsored" (ad) tile system should be removed from our tree.

**Comment by wolfbeast** [comment]
Backed out 277fa0afdc50b707b3227ca327c29766cdcd20f1 because it broke things. I must have made a mistake.
@mattatobin maybe you can look over that commit and spot what I did wrong?

**Comment by mattatobin** [comment]
I have no idea what you did wrong what I do know is that a promise chain failed.

```
Timestamp: 6/29/2018 1:49:07 PM
Error: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Jun 29 2018 13:49:03 GMT-0400 (Eastern Standard Time)
Full Message: Error: page-thumbnail:error
Full Stack: observe@resource://gre/modules/BackgroundPageThumbs.jsm:116:22
_onCaptureOrTimeout@resource://gre/modules/BackgroundPageThumbs.jsm:305:7
done@resource://gre/modules/BackgroundPageThumbs.jsm:451:7
_done@resource://gre/modules/BackgroundPageThumbs.jsm:471:7
receiveMessage@resource://gre/modules/BackgroundPageThumbs.jsm:419:7

Source File: resource://gre/modules/BackgroundPageThumbs.jsm
Line: 116
Source Code:
116
```

**Comment by JustOff** [comment]
Is there any specific way to reproduce this error? I don't see anything like that after re-applying https://github.com/MoonchildProductions/UXP/commit/277fa0afdc50b707b3227ca327c29766cdcd20f1.

**Comment by mattatobin** [comment]
Basilisk.

**Comment by wolfbeast** [comment]
Someone please verify by thoroughly testing #1122 that this doesn't break anything?

**Comment by g4jc** [comment]
@wolfbeast this patch [completely removes history tiles](https://github.com/adeshkp/UXP/commit/8db31d53674d6b9d7f15f50d06d73c5661fc0c0a#diff-dc7d1b10a47be536f4e914faae5170c7L260) on new tab page, not just enhanced (sponsored) tiles. Not sure if this was intended? Now there are no tiles on new tab page, only a search bar.
