### ISSUE TITLE
Basilisk - change the default bookmarks set

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#261]
Currently, Basilisk includes the same set of bookmarks as Pale Moon. I think basilisk should include a few of its own.

**Comment by wolfbeast** [comment]
Basilisk includes a link to its home page, and some generic Mozilla links...
It doesn't include Pale Moon links.

https://github.com/MoonchildProductions/UXP/blob/master/browser/locales/generic/profile/bookmarks.html.in

**Comment by adeshkp** [comment]
Yes, indeed.
Sorry for the noise. It was an issue with a stale profile.
