### ISSUE TITLE
NSS 3.35 busts Content Permissions in Basilisk

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#265]
As reported on the forum:

> In Basilisk-20180424, all of my cookie permission exceptions are gone.
(They display nowhere, have no effect - and new ones, though effective for the session, cannot be permanently saved.)

> The "Exceptions" window (in custom settings for history) is empty.
They're gone from the "Permissions" pane of "Page Info".

> New cookie permissions could be created for the current session, but are gone after a restart.

> After rolling back to Basilisk-20180321, the cookie exceptions came back like normal.
(For clarity, brand new exceptions created in v20180424 did not come back, but all earlier ones did.)

> Tried a new profile: same result.

**Comment by JustOff** [comment]
Browser | Result
------------------ | -- 
Basilisk Moebius 2018.03.21 | Ok 
Basilisk UXP 2018.04.23 | Fail
Basilisk UXP ... | ?
Basilisk UXP [CP1](https://github.com/MoonchildProductions/UXP/tree/FullFunction_CP1) | Ok

PS : Pale Moon 28.0.0a1 does not allow to add exception for cookies at all - throws error in the console.

**Comment by janekptacijarabaci** [comment]
> Pale Moon 28.0.0a1 does not allow to add exception for cookies at all - throws error in the console.

[Bug 1173523](https://bugzilla.mozilla.org/show_bug.cgi?id=1173523) Change nsIPermission to expose a principal rather than a host, appId, and inBrowserElement

This also relates to `5)` in:
https://github.com/MoonchildProductions/UXP/issues/121#issuecomment-381395695

**Comment by JustOff** [comment]
The test table was updated with the Pre-PM28 result - Fail.

**Comment by janekptacijarabaci** [comment]
@JustOff 

FYI:

Browser      | Date                             | Results
------------ | ----------------------- | ----
Basilisk UXP | 2018.03.19 (cca 12:00) | Fail

(I don't have an exact commit)

**Comment by mattatobin** [comment]
This is wider than JUST cookies.. No site permissions are being preserved.

**Comment by wolfbeast** [comment]
Building 912aa47acf658ae26ac24bb3f6ca52b04919f2ee  pre path-traversal-restriction (2018.03.18)

**Comment by janekptacijarabaci** [comment]
I can build e.g. https://github.com/MoonchildProductions/UXP/commit/d2a0a16054771b4b0bee38ee7241a976bc1dac75 pre `ported-upstream` (2018.03.15)

I don't know when... sometimes today.

**Comment by JustOff** [comment]
[Pre-NSS-3.35](https://github.com/MoonchildProductions/UXP/tree/7eb2c156ba826a0ebf05db56a9fccf46094478ea) -> Ok

Building from [Pre-e10-UI-cleanup](https://github.com/MoonchildProductions/UXP/tree/7eb2c156ba826a0ebf05db56a9fccf46094478ea) 2018.03.03 ...

**Comment by wolfbeast** [comment]
I really hope this isn't NSS fallout

**Comment by mattatobin** [comment]
I don't see how.. Pale Moon and my [Navigator](https://github.com/binoc-central/navigator) have zero issues with Site Permissions.

**Comment by wolfbeast** [comment]
NSS 3.35 made Tycho unstable as hell.. while there's no clear reason for that either.
so....

**Comment by JustOff** [comment]
My PC is so slow, so it takes about 90 minutes for each full build. Nonetheless I'm going to continue, please keep our research in sync.

**Comment by wolfbeast** [comment]
Yeah I clock about half that per build. I'll try the last commit prior to the tls 1.3 branch merge.

**Comment by wolfbeast** [comment]
Last commit prior to TLS 1.3 merge (NSS 3.35) = Ok. So it's likely more NSS 3.35 fallout.

**Comment by wolfbeast** [comment]
As far as I can gather it's because of the partial rewrite Mozilla did with NSS 3.35, and I think NSS's internal sqlite driver is now interfering with the normal sqlite lib. It would also explain the Pale Moon crashes and instability we've seen on Tycho with it. I'll toss this ball upstream, but it's possible Mozilla simply doesn't give a shit.

**Comment by wolfbeast** [comment]
verified with the last in-branch build without any other commits: NSS update to 3.35 breaks it. NSPR is fine.

**Comment by JustOff** [comment]
Just wondering if there is a chance NSS 3.36.1 can help?

**Comment by mattatobin** [comment]
> NSS 3.36 requires NSPR 4.19 or newer

**Comment by wolfbeast** [comment]
Not until https://bugzilla.mozilla.org/show_bug.cgi?id=1443020 at least has some clarity on what is going on. Just trial-and-erroring here is NOT a good thing to do with a lib that is at the heart of all secure connections.

**Comment by JustOff** [comment]
I'm afraid Mozilla is just as interested in discussing compatibility between NSS 3.35 and ESR 52, as Pale Moon core developers - in supporting Windows XP :-/

**Comment by wolfbeast** [comment]
There is a big difference here. NSS is **NOT** a Firefox-exclusive library, and if we run into these issues here, other consumers of NSS can (and likely will) run into similar problems sooner or later. We're also not asking for support of a long since EoL OS -- ESR52 is, in fact, still supported and updated by Mozilla, to boot. You can't compare the two.

**Comment by JustOff** [comment]
You are probably right, and my view of this case is rather limited, so I'm not trying to judge anyone, I just think out loud.

**Comment by JustOff** [comment]
It seems I finally was able to get NSS 3.35 to work properly with UXP, there are even two ways to achieve this.

The first method is to [force the storage service to initialize first](https://hg.mozilla.org/mozilla-central/rev/b8e722cacf61) in `nsNSSComponent.cpp` (as [done in the FreeBSD firefox-esr port](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225364)), and the second one is to [change the default storage file format back](https://hg.mozilla.org/projects/nss/rev/b0658ed36763) to `DBM` (as [recommended by one of the NSS contributors](https://bugzilla.mozilla.org/show_bug.cgi?id=1380706#c8)).

I made test builds of Basilisk for both options ([[1]](https://github.com/JustOff/UXP/commits/nss-3.35-fix1), [[2]](https://github.com/JustOff/UXP/commits/nss-3.35-fix2)) and both save and restore Content Permissions without any problems.

I think it's better to use the second option (keep using DBM), as it looks more safe and keeps the backward compatibility of the db files.

**Comment by wolfbeast** [comment]
So, means I was right in that it's a clash with the SQLite driver.
Thanks for digging -- reverting to DBM is the right call; especially since Mozilla isn't telling anyone in that bug which changes were made to Firefox to make it fully NSS-SQL compatible.

**Comment by wolfbeast** [comment]
So in effect this means we'll have to get NSS, patch it, and enforce in-tree use of NSS again like we did before for Camellia-GCM.

**Comment by mattatobin** [comment]
This time I recommend completely removing the ability to build using system nss. If mozconfigure complains about the option being invalid so much the better. (Haven't looked up where it lives).

**Comment by JustOff** [comment]
It seems that there is simply no other option.

**Comment by mattatobin** [comment]
And you won't because Mozilla will likely remove support code for it in the future. NSS is forked, again, best track upstream and apply/port patches from here on in.

Moonchild Security Services anyone? ;)

**Comment by JustOff** [comment]
While I was digging into NSS, I found an interesting tool to track API/ABI changes. Although he did not really help in this particular case, I want to leave this link here: https://abi-laboratory.pro/tracker/timeline/nss/

**Comment by wolfbeast** [comment]
The SQL path can't be taken unless Mozilla comes out and lets us know exactly what was changed in Firefox to use and enable NSS-SQL.
I've made a work branch and tagged commit with the DBM patch method for testing.

**Comment by JustOff** [comment]
I went through the BZ dependency tree related to enabling NSS-SQL in Firefox and here is my list of bugs that need to be implemented in case we decide to follow this path:

* [1382866 - CERT_ChangeCertTrust can fail if the user hasn't logged in to softoken](https://bugzilla.mozilla.org/show_bug.cgi?id=1382866)
* [1389664 - have PSM always initialize the user's pin to the empty string if necessary at startup](https://bugzilla.mozilla.org/show_bug.cgi?id=1389664)
* [730495 - Need to guarantee that sqlite3_config is called before any other SQLite function](https://bugzilla.mozilla.org/show_bug.cgi?id=730495)
(supersedes [1380706 - PSM should depend on mozStorage, as a workaround for a sqlite3_config race](https://bugzilla.mozilla.org/show_bug.cgi?id=1380706))
* [1398932 - add a preference to make firefox use the sqlite-backed NSS databases](https://bugzilla.mozilla.org/show_bug.cgi?id=1398932)
* [783994 - switch Mozilla to use the cert9+key4 (aka sql) database file format](https://bugzilla.mozilla.org/show_bug.cgi?id=783994)
* [1428538 - Use UTF-8 file paths for NSS database](https://bugzilla.mozilla.org/show_bug.cgi?id=1428538)

I'm not sure that this list is complete, but perhaps it can still be useful, given that Mozilla devs do not hurry to share this information.

**Comment by JustOff** [comment]
> Unless we find a way to explicitly request to use DBM, by adding a type prefix to the database directory

Here is the [alternative method to keep using DBM](https://github.com/JustOff/UXP/commits/nss-3.35-fix3) with NSS 3.35, based on [bug 1398932](https://bugzilla.mozilla.org/show_bug.cgi?id=1398932).
It allows to build using `--with-system-nss`, as [the changes](https://github.com/JustOff/UXP/commit/b4babf656f976e9d224ac187890b4bad53dfdcfe) made outside the NSS tree.

**Comment by wolfbeast** [comment]
JustOff's method is using the API available to us with a prefix and is the best solution (until, of course, Mozilla decides that dbm should be removed from NSS entirely)

**Comment by JustOff** [comment]
Out of curiosity I created the build using nspr-4.19/nss-3.36.4 from esr60, and it looks like it also works well.

**Comment by wolfbeast** [comment]
That would be a next step. First wanted to see if 3.35 could be made to work properly.

**Comment by mattatobin** [comment]
I would hope the requesting DBM won't be removed because Linux but who can say.

**Comment by JustOff** [comment]
Btw, don't we need to update [NSPR_MINVER](http://xref.palemoon.org/uxp-trunk/search?string=nspr_minver&find=) to the current 4.18?

**Comment by wolfbeast** [comment]
I've not seen any further issues with the DBM: prefix in place. spun off the NSS update to a follow-up so we can close this as it's solved.
