### ISSUE TITLE
2 Addons stopped working in Basilisk 2018.04.24

### ISSUE THREAD

**Issue by sstiles** [MoonchildProductions/UXP#267]
Microsoft Web Clipper and Facebook Social Fixer have stopped working in the latest update.

(I hope this is the right place to post as I'm new to this)

**Comment by Sa-Ja-Di** [comment]
As it is the job of the add-on developer to make the add-ons compatible with the browser, report add-on related issues to the creator directly.

**Comment by wolfbeast** [comment]
Of note, this basilisk update may ave some extension quirks -- simply re-installing the add-on from its source may solve it.

**Comment by JustOff** [comment]
It's also useful to check whether these extensions work in Firefox 52 ESR.

**Comment by sstiles** [comment]
Re: [MoonchildProductions/UXP] 2 Addons stopped working in Basilisk 2018.04.24 (#267)


Thanks.

----------------------------------------------------------------

**Comment by wolfbeast** [comment]
Assuming a reinstall solved it then
