### ISSUE TITLE
[PALEMOON] FullScreen - this feature does not work properly

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#270]
Tag #121 

F11 key make window full screen but the upper bar remains visible (and the CSS is completely wrong here).

There are many changes. Maybe it would be best to try adding e.g. (without `browser-fullScreen.js`):
[fullscr-toggler element needs to be hidden in DOM fullscreen](https://hg.mozilla.org/mozilla-central/rev/cfbe5fc74ea2)
[Avoid exiting fullscreen mode when exit from DOM fullscreen](https://hg.mozilla.org/mozilla-central/rev/4ac24fe93a88)
[Prevent collapsing toolbar on fullscreen mode on OS X](https://hg.mozilla.org/mozilla-central/rev/d11b9d29d909)
[Skip changing fullscreen window controls when using OS X Lion native fullscreen](https://hg.mozilla.org/mozilla-central/rev/1bc7f9b2e95c)
[Skip hiding toolbars for fullscreen mode on OS X Lion](https://hg.mozilla.org/mozilla-central/rev/9a2ffd3b6381)
[Simplify fullscreen code](https://hg.mozilla.org/mozilla-central/rev/1f7db5d87e80)
[Restore the position the fullscreen toolbox collapsed flag is set](https://hg.mozilla.org/mozilla-central/rev/f021a650dd49)
[Work around the inDOMFullscreen attribute being removed too late by checking inFullscreen too](https://hg.mozilla.org/mozilla-central/rev/521e4737222b)
[Simplify gIdentityHandler and show connection type in the fullscreen notification](https://hg.mozilla.org/mozilla-central/rev/15fd1ffcc1be)
[Retry hiding toolbox when some of safe-to-collapse conditions change](https://hg.mozilla.org/mozilla-central/rev/f944a86418a9)
[Remove pointerlock permission requirement](https://hg.mozilla.org/mozilla-central/rev/06241d818e99)
[Follow up to fix localisation](https://hg.mozilla.org/mozilla-central/rev/6648e2942cf9)
[Remove UI leftovers from the pointerLock removal](https://hg.mozilla.org/mozilla-central/rev/863ce9e133e8)

and then add the file `browser-fullScreenAndPointerLock.js` (without some e10s work) from `/browser` (Basilisk).

But I don't know...

**Comment by JustOff** [comment]
I guess https://bugzilla.mozilla.org/show_bug.cgi?id=1161802 is the key.

**Comment by mattatobin** [comment]
Blocks #57

**Comment by JustOff** [comment]
I'm taking this to fix basic/critical full-screen functionality, PR will follow.

**Comment by mattatobin** [comment]
The CSS animation is too slow and it gets laggy on laggy sites like start.me.. Also it isn't being triggered at all for blank (or about:logo) pages.

**Comment by JustOff** [comment]
1. CSS animation is now in pair with how it works on Basilisk:

https://github.com/MoonchildProductions/UXP/blob/e25430117a67f5c898e5e9388ebd44b185d469ab/browser/base/content/browser.css#L299-L301

https://github.com/MoonchildProductions/UXP/blob/ec3d61fb3133c8d44a823ce4e20906d6e22beb7b/application/palemoon/base/content/browser.css#L764-L766

However, I'm not very happy with it too, and I'd suggest to reduce the transition time from 1.5s to 0.5s, I thinks this is more than enough. What do you think? @wolfbeast @Lootyhoof?

2. @mattatobin, I can't reproduce your issue with `about:logopage` and `about:blank` pages, the animation is triggered just fine. Could someone else check this, please?

3. The only obvious shortcoming I see at the moment is that the permission is not asked when you switch videos to full-screen, but I can't manage to fix it yet.

**Comment by mattatobin** [comment]
Doesn't the permission to go to full screen only show when it happens without user interaction? Purely by script in UXP?

**Comment by JustOff** [comment]
Firefox 41+ (and Basilisk) doesn't ask for full-screen permission, but displays an entering warning. But in its current state Pale Moon UXP does not display either a permission request, or a warning, and this needs to be addressed.

As for the new tab issue now I see. And apparently Firefox ESR 52 and Basilisk both have the same flaw. I'll try to resolve it, but the permission/warning issue seems more important.

**Comment by mattatobin** [comment]
> As for the new tab issue now I see. And apparently Firefox ESR 52 and Basilisk both have the same flaw. I'll try to resolve it, but the permission/warning issue seems more important.

Oh really.. strange on that.

**Comment by JustOff** [comment]
I finally managed to restore the permission dialog, but it's appeared incomplete, because Mozilla got rid of permission for DOM full-screen in the [bug 1160017](https://bugzilla.mozilla.org/show_bug.cgi?id=1160017). Thus, if we select "Allow and remember", the permission dialog will no longer appear, but if we select "Deny and remember", this will have no effect.

Now we need to decide what to do next: either try to revive the full-screen permission in UXP, or remove it from the Pale Moon permission manager, and replace the dialog with a simple warning, as it was done in the [bug 1160023](https://bugzilla.mozilla.org/show_bug.cgi?id=1160023).

Since I personally never got into a situation where I had to disable full-screen mode for a certain domain, and I think the full-screen permission dialog rather annoying, the second option seems more reasonable.

**Comment by wolfbeast** [comment]
I concur that a warning/notification for full-screen is fine. The only reason the permission was there to begin with is for the potential danger of a website spoofing the user interface.

**Comment by mattatobin** [comment]
If people are concerned about this being abused one can simply switch off the dom fullscreen api globally with a pref. However, I don't see it being an issue.. AFAIK the dom fullscreen api requires user interaction.. If not.. It should.

**Comment by JustOff** [comment]
> AFAIK the dom fullscreen api requires user interaction

You are absolutely right.

> I concur that a warning/notification for full-screen is fine.

Well, then I'm going this way.

**Comment by JustOff** [comment]
I've moved the non-blocking new tab issue to #336, the rest of this task seems complete.

**Comment by wolfbeast** [comment]
Apart from the issue with the address bar having focus (which is also present in Firefox), this all seems to work.
