### ISSUE TITLE
Add support for libavcodec 58/FFmpeg 4

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#277]
FFmpeg published release 4.0 last week. As part of this release the libavcodec version was bumped to 58. Currently we only support up to version 57 of libavcodec. We need to add support for version 58 so that H.264/MP4 playback will work on newer distros releases (such as the upcoming Fedora 28) as well as continue working on Arch and other rolling-release distros once they update to FFmpeg 4.

**Comment by trav90** [comment]
I've verified that the necessary code for libavcodec 58 does not break anything with previous versions. Will submit a PR to resolve this as soon as I have time to set up a VM and properly test against libavcodec 58.

**Comment by wolfbeast** [comment]
Built with the update on Windows, verified all is OK with media playback.
