### ISSUE TITLE
Update NSS to 3.35

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#28]
With accompanying NSPR, of course.

This is a blocker for #15

**Comment by janekptacijarabaci** [comment]
@wolfbeast

You see also:

- Fix a test
  - https://hg.mozilla.org/mozilla-central/rev/45e4387bc585
  - (https://bugzilla.mozilla.org/show_bug.cgi?id=1419721)

and

- Potential upgrade RootHashes
  - https://hg.mozilla.org/mozilla-central/rev/f3e41a81b136
  - https://hg.mozilla.org/mozilla-central/rev/ba3a2c41b4b9

- A fix: FIPS, PSM
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1337950
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1382994

I don't know what's good for you...

**Comment by wolfbeast** [comment]
> I don't know what's good for you...

What's good for me is not just throwing links at me without context.

**Comment by janekptacijarabaci** [comment]
Context is this issue (update NSS). Obviously it's just my opinion.

**Comment by wolfbeast** [comment]
Context is not this issue -- NSS was updated successfully and confirmed working.
If there are other problems as a result of the update, then those should not be posted here but in a separate GitHub issue with proper description in the actual entry. I would think you understood that by now after so much time working with us.

**Comment by janekptacijarabaci** [comment]
> I would think you understood that by now after so much time working with us.

[I don't care but don't complain about alt config breakages UNTIL WE SAY SO](https://github.com/MoonchildProductions/UXP/commit/5b30f18421670b13594f054175174b3abc69f11e#commitcomment-27508578)

I don't know what i can do anymore, but right...

**Comment by wolfbeast** [comment]
I'll repeat it again then

DON'T just say:
> You see also:
>    Fix a test
> {{reference}}

DO say:
> This will probably break a test for being able to toggle FIPS compliance mode.
> `canToggleFips` may be `false` after this update of NSS. If so, either the test needs to be fixed of FIPS needs to be made switchable again.
> See also:
> {{reference}}

Two brief summarizing sentences makes all the difference. It doesn't matter that the same is described in a BZ bug -- just providing a link isn't enough. It applies to the forum as a rule and even more so here.
Just please don't try to minimize your typing in places where explanations are IMPORTANT. By reading the github issue's content, I should be able to see if it needs to be reopened or needs more attention or similar, without having to dig through external links for the reasoning -- lift it out and write it down.
