### ISSUE TITLE
Incorrect osx include filepaths

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/UXP#286]
`/browser/themes/osx/shared.inc` line 1:
`%include ../../../../toolkit/themes/osx/global/shared.inc`
This causes build failure and should be `../../../toolkit/themes/osx/global/shared.inc`
After solving #285 and this I have been able to successfully build Serpent.

**Comment by SpockMan02** [comment]
That fixes it, but it sounds like it'll need to be reverted when Basilisk is put in /application. Feel free to close or keep open as a reminder.

**Comment by mattatobin** [comment]
Yes.

**Comment by mattatobin** [comment]
Blocks #303

**Comment by SpockMan02** [comment]
Except that we've got a similar problem in another place now.
`/application/basilisk/base/content/baseMenuOverlay.xul` line 32
looks for `../../../toolkit/content/macWindowMenu.inc`
FILE_NOT_FOUND

**Comment by wolfbeast** [comment]
That include has been fixed now. Anything else? :)

**Comment by SpockMan02** [comment]
Yep, gimme a sec, there's one more that I just fixed locally.

**Comment by wolfbeast** [comment]
That's it, then?

**Comment by SpockMan02** [comment]
And with that, it builds for me. :)
