### ISSUE TITLE
Remove GONK widget code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#288]
Since B2G has been nuked, the widget code for it can go.

- [x] Remove all conditional `MOZ_WIDGET_GONK` ifdefs and code blocks
- [x] Remove `/widget/gonk/*`
- [x] Remove `MOZ_B2G*`
- [x] Convert uses of `KEY_MAP_ANDROID_EXCEPT_B2G` to `KEY_MAP_ANDROID`
- [x] Remove other condition gonk widget code and unused files
- [x] Remove `moz_widget_toolkit_gonk`

**Comment by wolfbeast** [comment]
Total score: 139695+5017+6+13+750+1357 = 146838 axed lines of dead code.

**Comment by JustOff** [comment]
It seems you missed `MOZ_WIDGET_GONK` in `Performance.cpp` [here](https://github.com/MoonchildProductions/UXP/blob/e16bcd08aae85a7d9c2de5a4b1c733280cb81112/dom/performance/Performance.cpp#L30).

Also, I'm not sure about [MOZ_WIDGET_TOOLKIT == gonk](http://xref.palemoon.org/uxp-trunk/search?string=%28%22gonk%22|%27gonk%27%29&regexp=1&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk) and [MOZ_GONK_MEDIACODEC](http://xref.palemoon.org/uxp-trunk/search?string=MOZ_GONK_MEDIACODEC&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk).

**Comment by wolfbeast** [comment]
Strange -- I know for a fact I fixed that.
As for the other two, the first I didn't think about checking. the second isn't widget code but should also be cleaned up (separate issue)

**Comment by JustOff** [comment]
I actually have a half of [MOZ_WIDGET_TOOLKIT == gonk](http://xref.palemoon.org/uxp-trunk/search?string=%28%22gonk%22%7C%27gonk%27%29&regexp=1&find=&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=uxp-trunk) fixes already done in my test branch, so I can finish it and submit as a PR if you wish.

I also found [MOZ_GONK_MEDIACODEC](http://xref.palemoon.org/uxp-trunk/search?string=MOZ_GONK_MEDIACODEC&find=&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=uxp-trunk) as a consequence while working on this, but I can leave it to a separate issue if it's necessary.

**Comment by wolfbeast** [comment]
eh.. you should have told me immediately. Also, in your test branch, did you remove files no longer referenced?

**Comment by JustOff** [comment]
I have processed only files that contain ["gonk"](http://xref.palemoon.org/uxp-trunk/search?string=%22gonk%22&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk) and there was nothing to remove; perhaps all such cases are related to ['gonk'](http://xref.palemoon.org/uxp-trunk/search?string=%27gonk%27&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk).

**Comment by wolfbeast** [comment]
No, I guess you didn't think about it ...
if you remove a conditional block in moz.build files, any files referenced by that block usually become orphaned and should be removed.

**Comment by JustOff** [comment]
There was [only one moz.build](http://xref.palemoon.org/uxp-trunk/search?string=%22gonk%22&find=moz.build&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk) with `if CONFIG['MOZ_WIDGET_TOOLKIT'] != "gonk":` so there was actually nothing to delete.

**Comment by wolfbeast** [comment]
You are quite incorrect. There are [35 moz.build files](http://xref.palemoon.org/uxp-trunk/search?string=%28%22gonk%22|%27gonk%27%29&regexp=1&find=moz.build&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk) with a gonk conditional.

**Comment by JustOff** [comment]
Sorry, but you probably missed that I [said](https://github.com/MoonchildProductions/UXP/issues/288#issuecomment-388647648) that at the moment I only processed `"gonk"` and not `'gonk'`.

**Comment by wolfbeast** [comment]
I don't see how that would be "half", but anyway, this is larger than you probably realized. Took me a number of hours. I'll have to test build but otherwise I'm through the list.

**Comment by JustOff** [comment]
Well, I seem to have underestimated the amount of work. Thank you for taking the time to deal with this.

**Comment by wolfbeast** [comment]
Yeah it was another 232 changed files with 256 additions and 36,730 deletions. :P

**Comment by wolfbeast** [comment]
Calling this done.
