### ISSUE TITLE
[PALEMOON] SessionStore need to be aligned with the updated nsISHEntry API

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#305]
When restoring the session from Pale Moon 27, I ran into the following error (multiple times):

`SessionStore: [Exception... "Cannot modify properties of a WrappedNative"  nsresult: "0x80570034 (NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN)"  location: "JS frame :: resource:///modules/sessionstore/SessionStore.jsm :: ssi_deserializeHistoryEntry :: line 3408"  data: no]`

Here is the corresponding code (line 3406):
https://github.com/MoonchildProductions/UXP/blob/931950a880b3550490422b1855c509be10586858/application/palemoon/components/sessionstore/SessionStore.jsm#L3405-L3407

This is because [nsISHEntry.idl](https://github.com/MoonchildProductions/UXP/blob/5f8de423f190bbb79a62f804151bc24824fa32d8/docshell/shistory/nsISHEntry.idl) simply does not have `owner` attribute anymore, see [bug 1286472](https://bugzilla.mozilla.org/show_bug.cgi?id=1286472).

Most likely, we will also need to update other application modules related to the history API; this requires additional research.

Blocks #57.

**Comment by mattatobin** [comment]
Blocks #57
