### ISSUE TITLE
Port across devtools enhancements

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#31]
@janekptacijarabaci has done a lot of devtools work on Möbius, and this does not all graft cleanly (or at all) to UXP.
Since our base "catch-up" is pretty much done now, this can be put back in.

I'm assigning you to this, Janek -- could you please see about getting a working copy up with devtools changes ported across and **just make it a single (or a few) flattened PRs to get all this into our tree again**? No need to make a bunch of extra work here because it's related to a separate module, anyway, and would just mean a lot of overhead otherwise to make individual PRs for small changes (and would probably cause merge conflicts as well if so). Just make it the quickest way to get all this back into the devtools; listing the changes in the PR's description is enough.

**Comment by janekptacijarabaci** [comment]
OK, I will look at it.

**Comment by mattatobin** [comment]
I wonder if we can get by with pulling the whole thing across and bits and bobs related..

**Comment by wolfbeast** [comment]
> I wonder if we can get by with pulling the whole thing across and bits and bobs related..

You mean pull the entire devtools subdir across?... Probably not without issues (refactoring storm, remember? especially e10s BS); it's likely better to just not try to cut corners and do it carefully with minimal risk in one go.

**Comment by wolfbeast** [comment]
Do a /ignore on the mis-tagged accent color work in remotes.
