### ISSUE TITLE
[PALEMOON] Preferences - "Fallback Character Encoding" does not have a default value

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#315]
Go to:
`Tools` - `Preferences` - `Content`
\- `Fonts & Colors` - `Advanced` - `Character Encoding for Legacy Content`
\- `Fallback Character Encoding`

This setting does not have a default value.

I don't know how you want to use it (for `Basilisk`/`Pale Moon`/`UXP`):
https://github.com/MoonchildProductions/Pale-Moon/commit/0792b6d75c0800a1901d96e2d1966759203d1cdd

**Comment by wolfbeast** [comment]
Port forward what's in Pale Moon. It's a better solution than Mozilla has.
