### ISSUE TITLE
Clean up our Intl code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#325]
There's a whole bunch of legacy code that can be removed once we use ICU unconditionally. (Depends on #324)

- [x] Remove the legacy non-IDNA2008 code path from `nsIDNService`
- [x] Build ICUUtils unconditionally, now that we no longer build without `ENABLE_INTL_API` on any platform
- [x] Remove support for using legacy Gecko normalization in `gfxHarfBuzzShaper`
- [x] Remove obsolete implementation of Unicode normalization
- [x] Remove `ENABLE_INTL_API` conditional and non-Intl legacy codepaths from `js`
- [x] Remove `ENABLE_INTL_API` conditional and non-Intl legacy codepaths from line-breaker code
- [x] Remove `ENABLE_INTL_API` conditional and non-Intl legacy codepaths from `IndexedDB`
- [x] Remove `ENABLE_INTL_API` conditional and non-Intl legacy codepaths from `nsChromeRegistry`
- [x] Remove `ENABLE_INTL_API` conditional and non-Intl legacy codepaths from `nsNumberControlFrame`
- [x] Remove `ENABLE_INTL_API` conditional from installer files
- [x] Fix up build files
- [x] In lieu of #326 that will regenerate these tables when done, manually remove conditional code from generated files.
- [x] Remove Mozilla implementation of the bidi engine completely and use ICU
- [x] Remove `EXPOSE_INTL_API` conditionals
- [x] Remove `ENABLE_INTL_API` and `EXPOSE_INTL_API` flags.

**Comment by wolfbeast** [comment]
Blocks #321

**Comment by mattatobin** [comment]
Won't this have an extension compatibility impact?

**Comment by wolfbeast** [comment]
> Won't this have an extension compatibility impact?

No. This is old code that has not been used for a while on most platforms (actually only on android by our fork point and that's only because of some testing, apparently); we use ICU for our Intl features and the code that is to be removed is the old Mozilla code that was in place when ICU would not be used.
