### ISSUE TITLE
Hiding tabs feature

### ISSUE THREAD

**Issue by CitoplasmaX** [MoonchildProductions/UXP#33]
There is something uncomfortable that comes from Firefox and is the feature of hiding the tabs on the sides when you do many of them. This is something that does not happen in Chromium or the browsers based on it.

What I ask is to include optionality to this not that it is included as such only and/or by default.

**Comment by JustOff** [comment]
You can just add `.tabbrowser-tab:not([pinned]) {min-width: 1em !important}` to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css).

**Comment by wolfbeast** [comment]
A scrolling tabstrip is by design - Chrome's solution is terrible because you can't read the tab labels anymore when you open more than a certain amount. Making it a scrolling strip avoids too-narrow tabs which are worse.
