### ISSUE TITLE
WebExtensions

### ISSUE THREAD

**Issue by svnpenn** [MoonchildProductions/UXP#343]
Please allow WebExtensions to be installed, thank you

**Comment by svnpenn** [comment]
https://github.com/Crusta/CrustaBrowser/issues/7

**Comment by svnpenn** [comment]
https://github.com/felipedaragon/sandcat/issues/3

**Comment by svnpenn** [comment]
https://github.com/OtterBrowser/otter-browser/issues/42

**Comment by svnpenn** [comment]
github.com/textbrowser/dooble/issues/19

**Comment by svnpenn** [comment]
https://github.com/textbrowser/dooble/issues/19

**Comment by mattatobin** [comment]
Basilisk allows WebExtensions. Pale Moon will not. Deal with it.

**Comment by mattatobin** [comment]
Well we can ban you from the repository.. So I would say we have some control over what you can and can't do.
