### ISSUE TITLE
TychoAM nsBlocklistService does not support gfxBlacklist

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#347]
We need to either add this functionality or use the same source for both. It looks like they both have the same ins and outs so will do some practical testing with using the `WebExAM` version with `TychoAM`.

Blocks #346

**Comment by mattatobin** [comment]
Also blocks #57

**Comment by wolfbeast** [comment]
Code was unified.
`nsBlocklistService` now lives in `toolkit/components/blocklist`

**Comment by janekptacijarabaci** [comment]
__I'm sorry, but something is wrong:__

![_addons_1_error](https://user-images.githubusercontent.com/2373486/40083402-879dbbb8-5883-11e8-9827-a46b8efc8bc6.png)

__and throws an error in Browser Console (a new profile, after the browser starts):__

```
addons.manager	ERROR	Exception loading default provider
"resource://gre/modules/addons/XPIProvider.jsm":
TypeError: Cc[aContract] is undefined
(resource://gre/modules/XPCOMUtils.jsm:230:7)
JS Stack trace:
XPCU_serviceLambda@XPCOMUtils.jsm:230:7
< get@XPCOMUtils.jsm:198:21
< @XPIProvider.jsm:205:5
< startup@AddonManager.jsm:929:13
< startup@AddonManager.jsm:3033:5
< observe@addonManager.js:65:9¨
Log.jsm:753
App_append resource://gre/modules/Log.jsm:753:9
log resource://gre/modules/Log.jsm:389:7
error resource://gre/modules/Log.jsm:397:5
startup resource://gre/modules/AddonManager.jsm:942:13
startup resource://gre/modules/AddonManager.jsm:3033:5
observe resource://gre/components/addonManager.js:65:9
```

__After reversing this commit (https://github.com/MoonchildProductions/UXP/commit/f86673741dce0580a73d37b6f72418877b7380d6):__

![_addons_2_ok](https://user-images.githubusercontent.com/2373486/40083627-4c89a158-5884-11e8-9476-e4654e1252e5.png)

__and the Broweser Console is empty.__

**Comment by mattatobin** [comment]
Clobber

**Comment by mattatobin** [comment]
Is this from your own build?

**Comment by janekptacijarabaci** [comment]
> Is this from your own build? Have you clobbered recently?

If you can not confirm it, I will try it later...

**Comment by mattatobin** [comment]
That does not answer my questions.

**Comment by janekptacijarabaci** [comment]
> Is this from your own build?

Yes.

> Have you clobbered recently?

No. And I can't do it now.

**Comment by JustOff** [comment]
I can't reproduce the problem above.

**Comment by frankspace** [comment]
I'm just a user, but I can reproduce this problem.  On Arch linux, compiling as of commit 626419c, extensions work properly (first image); compiling as of commit f866737, extensions are totally broken (second image).  Absolutely nothing changed on the system other than the commit number.  Unfortunately, I an amateur and don't know where to begin at figuring out what else I can do to help figure out where the problem is, but I'd be happy to test-drive a specific diff or something if that'd be of use.

![basilisk_addons_626419c](https://user-images.githubusercontent.com/13141709/40132094-cfefbfac-5909-11e8-9c91-866900cf4c92.jpg)

![basilisk_addons_f866737](https://user-images.githubusercontent.com/13141709/40132099-d66f79f8-5909-11e8-9b6d-9451d0d6fba5.jpg)

**Comment by JustOff** [comment]
@frankspace, did you run `mach clobber` before `mach build` the latest sources?

**Comment by frankspace** [comment]
Unfortunately, I've found mach to be totally broken on Arch.  The command I use is `make -f client.mk build` followed by `make -f client.mk install`, pursuant to the suggestion [here](https://github.com/MoonchildProductions/UXP/issues/110).  I am not sure what clobbering even means, but I infer that it's some kind of nuke-n-pave; I can completely purge everything in the local git download (I'm afraid I don't even know if I'm using the right terminology there) and recompile it from scratch again, if that would achieve the same thing.  I apologize for my ignorance.  Would you like me to do that?

**Comment by mattatobin** [comment]
Looks like we may want to touch clobber to make sure the build system picks up the change properly. Seems, toolkit manifest files for components aren't as well tracked dependency wise as they should be.

I did have this exact error originally but I recompled and it picked it up on the second time so it was like w/e. Since then it has been fine across multiple applications.

**Comment by janekptacijarabaci** [comment]
With clobber - no change... so it will be something different.

**Comment by mattatobin** [comment]
@janekptacijarabaci look in `dist/bin/components/` for `blocklist.manifest`

**Comment by mattatobin** [comment]
@JustOff and because Basilisk doesn't have the work both Pale Moon and Borealis have when it comes to just include just about everything all the time from dist.. It needs specified.

THANKS!

**Comment by janekptacijarabaci** [comment]
Thanks to both of you!

So, the following helped:
- Rename the file `dist/bin/components/blocklist.manifest` to (e.g.) `_blocklist.manifest` (even though it contained: https://github.com/MoonchildProductions/UXP/blob/f86673741dce0580a73d37b6f72418877b7380d6/toolkit/components/blocklist/blocklist.manifest)
- Starting the browser (the same error + an error `the manifest is missing`)
- Closing the browser
- Rename the file `dist/bin/components/_blocklist.manifest` to `blocklist.manifest`
- Starting the browser

**Comment by mattatobin** [comment]
That is irrelevant.

Also, aa41605eeca4f68a1353120ecd8c02ef3262ef43

**Comment by janekptacijarabaci** [comment]
At the moment it was relevant - and for me. No one claims that this is a fix.

**Comment by wolfbeast** [comment]
@janekptacijarabaci please keep whiteboarding in issue comments to a minimum.

**Comment by frankspace** [comment]
I apologize for the delay.  I did completely wipe my entire build directory just to be sure and recompiled commit f866737 from scratch; that did not change anything.  However, as of commit 4462c34 (the most current as of typing this), extensions are back to working as expected.  Sorry I wasn't more help.

**Comment by janekptacijarabaci** [comment]
@frankspace 
> Sorry I wasn't more help.

You helped me - thank you.
