### ISSUE TITLE
basilisk browser idea,

### ISSUE THREAD

**Issue by FrostKnight** [MoonchildProductions/UXP#348]
you probably won't support webextensions I am guessing, but would you be willing to support, a built in script blocker that can be turned on like a plugin/extension for baslisk.

It would be like noscript only maybe more secure?  And it would be something you could turn on and off in about:config.  

I know what I am asking could be a huge task, but it would be a good way to keep basilisk and palemoon a secure browser in many different ways. 

I think if needed you could even have a crowdfunding for it if you think it would cost too much time/money.

Let me know your thought on this. 

ps, I would help test if you wanted. :)

**Comment by mattatobin** [comment]
Basilisk supports WebExtensions broadly compatible with Firefox 52/53.

As for a script blocker in-browser. No.
