### ISSUE TITLE
Release May edition of basilisk

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#354]
Let's publish an updated Basilisk version.
@trav90 : do you think you can build a 2018.05.15 edition?

**Comment by trav90** [comment]
Shouldn't be a problem.

**Comment by trav90** [comment]
Building now. I’ll post again once everything is uploaded to the FTP.

**Comment by trav90** [comment]
Signed tarball with all the goodies is uploading to FTP now.

**Comment by wolfbeast** [comment]
Published.
