### ISSUE TITLE
SSUAO will only work for primary requests

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#355]
It seems that SSUAO applies only to primary (main) requests to sites, while all subrequests pass by it.

STR:
1) Set `general.useragent.override.palemoon.org` to `palemoon ssuao test`
2) Open browser console (Ctrl+Shift+J) or toggle tools (Ctrl+Shift+K)
3) Go to http://www.palemoon.org/
4) Check request headers

I also verified this from the server side in a test environment.

**UDP**: Also SSUAO does not apply to XHR requests.

Blocks #57.

**Comment by JustOff** [comment]
I think this is even a blocker for the beta channel, as it's a serious security issue.

**Comment by mattatobin** [comment]
This is not a security issue but is a critical blocker.

**Comment by mattatobin** [comment]
I can reproduce this.. How strange.

**Comment by JustOff** [comment]
Also SSUAO does not apply to XHR requests at all.

**Comment by mattatobin** [comment]
Compare with Tycho please.

**Comment by janekptacijarabaci** [comment]
Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1331275 ?

But not tested (now).

**Comment by JustOff** [comment]
> Compare with Tycho please.

SSUAO works just fine with XHR in Tycho.

**Comment by mattatobin** [comment]
Unfortunately, a regression test cannot be done because Firefox hasn't shipped with SSUAO for a very long time. One will have to try reverting 1148544 manually and testing. Though, that was implemented 5 relative cycles ago.

**Comment by JustOff** [comment]
Yes, I confirm this is the freaking 1148544. Thanks for the hint @janekptacijarabaci & @mattatobin!

**Comment by JustOff** [comment]
Well, how will we deal with this? Revert it conditionally for Pale Moon only?

**Comment by JustOff** [comment]
Ok, , then I'll double-check it and make a PR.

**Comment by wolfbeast** [comment]
Yes, that bug needs reverting because https://bugzilla.mozilla.org/show_bug.cgi?id=1148544#c6 is incorrect behavior. Why on earth were they ever OK with that resulting behvior?
