### ISSUE TITLE
Pageshow no longer fires with persisted=true when restoring wikipedia from history

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#357]
While doing some testing with Reader View, I ran into [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1340502). Basically, pageshow no longer fires with persisted=true on certain websites when loading from cache, notably Wikipedia.

It's a minor thing, but according to the comments it is an issue in docshell and is web-observable.

Steps to reproduce in Basilisk:
1. Navigate to https://en.wikipedia.org/wiki/Wikipedia
2. Click the Reader View icon in the URL bar
3. Click the Close button on the left-hand-side toolbar

Expected results / Previous behavior:
Reader View closes and the icon reappears in the URL bar.

Actual results / Current behavior:
Reader View closes and the icon does not appear in the URL bar.

Affected versions:
Pale Moon 28.0.0a1 (with a yet-unreleased version of the Reader View add-on installed)
Basilisk 20180427 and later
The issue does not appear in Tycho.

**Comment by wolfbeast** [comment]
> The issue does not appear in Tycho.

Well d'uh, Tycho doesn't have a reader view :)
