### ISSUE TITLE
New Moon doesn't use it's own profile folder

### ISSUE THREAD

**Issue by alaviss** [MoonchildProductions/UXP#371]
## Description

When PM is built as New Moon, it's still using the Pale Moon profile folder.

## Affected versions

UXP

## Steps to reproduce

- Build UXP PM without official branding
- Run the resulting PM

## Expected result

- New Moon uses it's own profile folder (`~/.moonchild productions/new moon`)

## Actual result

- New Moon uses Pale Moon's profile folder (`~/.moonchild productions/pale moon`)

**Comment by wolfbeast** [comment]
How are you "building UXP without official branding" exactly? What is your mozconfig/build configuration?

**Comment by alaviss** [comment]
@mattatobin 

Thanks for the heads up. I wanted to build a version of Pale Moon that can be installed side-by-side with my current stable PM and have it's own profile folder. Where should I look into to perform such changes?

**Comment by mattatobin** [comment]
> **If you would like help fully re-branding the browser into something else, then let me know and I will help you.** _Otherwise, we shall not be inconveniencing users and builders that may gain or lose permission to use official branding merely because your expected results are not based in consistency, convention, or history._

**Comment by mattatobin** [comment]
Sigh, alright..

Here is a hint: `[application]/confvars.sh`, `[application]/app/application.ini`, `[application]/branding/[brand]/configure.sh`
