### ISSUE TITLE
[Question/Suggestion] Portable? i.e. Contained Local Settings

### ISSUE THREAD

**Issue by Aidolii** [MoonchildProductions/UXP#372]
Basilisk runs nicely from the zip file without needing installation, but it still depends on using my Windows AppData directory.

In Windows, is there a way to make Basilisk store ALL settings locally? If not, would you add a way to do so?

**Comment by Aidolii** [comment]
That does work, but this doesn't seem to use relative pathing.

**Comment by Aidolii** [comment]
Also... it seems that this is still dependent on %APPDATA%\Moonchild Productions\Basilisk\profiles.ini, which means there's still a file outside of the directory it depends on.

**Comment by Aidolii** [comment]
Okay, I'm looking at profiles.ini and I do notice that there's an 'IsRelative' boolean. If there's a parameter to get Basilisk to read from a profiles.ini kept inside of the directory, I should be golden.

**Comment by Aidolii** [comment]
Hmm... it seems -profile .\dirname will circumvent any need for a profiles.ini check entirely. It does mean you can't use the profile manager though. A way to get it to read a local profiles.ini would be more ideal than this.

**Comment by wolfbeast** [comment]
It's not designed like that. You can use shortcuts with `-profile` or use a custom launcher if you need multiple profiles all self-contained in non-standard folders.
