### ISSUE TITLE
IDless WebExtensions won't install

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#373]
Ad https://forum.palemoon.org/viewtopic.php?f=61&t=19175

> Dark Mode extension will not install in Basilisk and get a corrupted error however it installed before.
> https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/

Tags:
https://github.com/MoonchildProductions/moebius/issues/238
https://github.com/MoonchildProductions/moebius/pull/279

---

@JustOff 
Do you want to do it yourself? - https://github.com/MoonchildProductions/moebius/pull/279

**Comment by mattatobin** [comment]
At last word I thought IDless webextensions were SOL on Take 2.

@wolfbeast

**Comment by wolfbeast** [comment]
ID-less web extensions are a no.
