### ISSUE TITLE
Crash on macOS+Linux when loading pages

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/UXP#374]
https://forum.palemoon.org/viewtopic.php?f=61&t=19149

I found this by chance, and don't know the exact cause, but Basilisk, Pale Moon (28.0.0a2), and Borealis* all crash when trying to load at least the following pages:

http://brawlhalla.wikia.com/wiki/Yumiko
http://brawlhalla.wikia.com/wiki/Bodvar
http://brawlhalla.wikia.com/wiki/Cassidy
http://brawlhalla.wikia.com/wiki/Orion
http://brawlhalla.wikia.com/wiki/Lord_Vraxx
http://brawlhalla.wikia.com/wiki/Gnash
[I assume everything else under [Legends](http://brawlhalla.wikia.com/wiki/Category:Legends)]

I clicked around on the wiki a bit didn't experience the crash on most pages, so I assume there must be something common to the pages about "Legends" that causes the crash.

I built UXP a few times (more details in the forum thread) and found that **this crash only happens when UXP is built from commit 41cbe2d931d2742bb8dd6240eae9599e3bf3a512 ("Merge libhyphen fix from upstream.") or later.**

**OS: macOS 10.12.6 "Sierra"**

Reproducible always, at least with my builds on my computer. From the forum thread I opened, it sounds like Windows is unaffected.

(*Yes, I built Borealis on macOS, and yes, I know Borealis does not support my platform. The point is, this problem is not application-specific.)

**Comment by trav90** [comment]
Crash is reproducible on Linux as well.

**Comment by wolfbeast** [comment]
That's weird -- can anyone get me crash details and a call stack for this crash, so i know what exactly leads up to it?
If you back out that commit locally, does that resolve it?

**Comment by wolfbeast** [comment]
I looked at the update and I *think* I may know what's going on. Libhyphen uses specific functions from `<stdio.h>` and doesn't treat that line-ending agnostic - that's why there is glue code to correct that. This upstream update introduces the use of `fgetc()` that isn't overloaded in the glue code with something line-ending agnostic. It may try to read beyond EOF of the hyphenation dict in that case on LF-only systems. That's why Windows isn't affected.

Solution would be simply to update the glue code to teach it about libhyphen-compatible `fgetc()` and `EOF`. I'll have a patch to that effect shortly.

**Comment by wolfbeast** [comment]
Try this patch: https://gist.github.com/wolfbeast/fc71f96a30acab7956914fcebf979671#file-gistfile1-txt

**Comment by SpockMan02** [comment]
@mattatobin 
From about:buildconfig on a Basilisk build that experiences the crash:

target
--
x86_64-apple-darwin16.7.0

Compiler | Version | Compiler flags
-- | -- | --
/usr/bin/clang -std=gnu99 | 9.0.0 | -Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers  -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code  -Wclass-varargs -Wloop-analysis -Wstring-conversion -Wthread-safety  -Wno-error=deprecated-declarations -Wno-error=array-bounds  -fno-strict-aliasing -fno-math-errno -pthread -pipe

/usr/bin/clang++ -std=gnu++11 | 9.0.0 | -Qunused-arguments  -Qunused-arguments -Wall -Wc++11-compat  -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith  -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings  -Wno-invalid-offsetof -Wclass-varargs -Wloop-analysis  -Wc++11-compat-pedantic -Wc++14-compat -Wc++14-compat-pedantic  -Wc++1z-compat -Wimplicit-fallthrough -Wstring-conversion  -Wthread-safety -Wno-inline-new-delete  -Wno-error=deprecated-declarations -Wno-error=array-bounds  -Wno-unknown-warning-option -Wno-return-type-c-linkage -fno-exceptions  -fno-strict-aliasing -stdlib=libc++ -fno-rtti -fno-exceptions  -fno-math-errno -pthread -pipe  -g -O3 -fomit-frame-pointer
-- | -- | --

Configure options

--enable-application=browser MAKE=/Library/Developer/CommandLineTools/usr/bin/make --disable-tests

Sorry the text alignment's not the best there, but you get the gist, I hope.

@wolfbeast I applied the patch and that fixed it! Travis should probably confirm.

**Comment by wolfbeast** [comment]
I'm assuming here that it will also fix Linux, so I'll be merging that patch in. Please re-open if it doesn't solve the issue.

**Comment by trav90** [comment]
Sorry for the late response; been on the run all day.

I can confirm that the issue is fixed on Linux as well. All of the links in the original post load successfully with no crashes.
