### ISSUE TITLE
Undesired features are enabled by default in Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#382]
These features were previously deemed undesirable in Pale Moon:

- [Parental Controls](https://github.com/MoonchildProductions/Pale-Moon/pull/558)
- [Accessibility](https://github.com/MoonchildProductions/Pale-Moon/pull/558)
- [Gamepad](https://github.com/MoonchildProductions/Pale-Moon/issues/943)

It seems quite logical not to enable them by default in Pale Moon UXP as well.

Tag #57.

**Comment by wolfbeast** [comment]
This is why we have a build config. Think a little larger than one application please when dealing with UXP.

**Comment by mattatobin** [comment]
You're both right so why not make them enable bools and flip them on in applicable applications via confvars.

**Comment by JustOff** [comment]
This is exactly what I meant.

**Comment by mattatobin** [comment]
Then again there is wisdom in not doing it.. Like detecting improper configuration.
