### ISSUE TITLE
HSTS priming is obsolete

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#384]
HSTS priming was introduced in [bug 1246537](https://bugzilla.mozilla.org/show_bug.cgi?id=1246537), never enabled in release builds, and eventually removed in [bug 1424917](https://bugzilla.mozilla.org/show_bug.cgi?id=1424917).

This is an obvious candidate to remove from UXP as well.

**Comment by g4jc** [comment]
I adapted patches from https://hg.mozilla.org/mozilla-central/rev/c5e3aeaa3c3c and backported to UXP. I was particularly surprised that several files immediately threw errors about missing the "#include "mozilla/Unused.h" header file once HSTS was pulled. This was not mentioned in Mozilla's bug ticket, which made me wonder if something was wrong with the patch... I've gone ahead and added the missing headers and it seems to be working well, but could use some review. If deemed worthy, I'll send over a PR. :+1:

**Comment by wolfbeast** [comment]
> never enabled in release builds

Actually, HSTS priming is used in case of mixed-mode content in UXP.

**Comment by wolfbeast** [comment]
> several files immediately threw errors about missing the "#include "mozilla/Unused.h" header file once HSTS was pulled

Unified compilation at fault.

**Comment by JustOff** [comment]
But `security.mixed_content.send_hsts_priming=false` by default.

**Comment by wolfbeast** [comment]
No.
```
// If a request is mixed-content, send an HSTS priming request to attempt to
// see if it is available over HTTPS.
pref("security.mixed_content.send_hsts_priming", true);
```

**Comment by JustOff** [comment]
Then it all.js overrides it, because it actually `false` in both Basilisk and Pale Moon UXP (checked using about:config).

**Comment by wolfbeast** [comment]
tisk tisk. Mozilla should not put platform sec prefs in all.js, certainly not doubling them up.

**Comment by JustOff** [comment]
Yes, this is ugly config style, but anyway, HSTS priming was always supposed not to be enabled in release builds.

**Comment by wolfbeast** [comment]
Well, this mess at least will be cleaned up with the removal patch.

**Comment by wolfbeast** [comment]
Marking assigned as G4jc is prepping a PR.
