### ISSUE TITLE
Alt+Click doesn't save files

### ISSUE THREAD

**Issue by passingthru2** [MoonchildProductions/UXP#393]
As reported here:  https://forum.palemoon.org/viewtopic.php?f=63&t=19252

> If you Alt+Click on a download link, nothing happens. (Win 7 x86)
For instance, try any download link here: http://www.palemoon.org/palemoon-win32.shtml
Setting is default: browser.altClickSave = true

> `Error: TypeError: aFile is undefined
Source File: chrome://global/content/contentAreaUtils.js Line: 1166`

**Comment by janekptacijarabaci** [comment]
Works for me (I do not see this problem) - Win7 x64 / PM x86.

**Comment by JustOff** [comment]
I don't see this problem either.

**Comment by passingthru2** [comment]
It seems it was caused by an extension, [MozArchiver](https://addons.palemoon.org/addon/mozarchiver/).  
Sorry to take up people's time - I'll close the issue.  
Please feel free to delete it.

**Comment by JustOff** [comment]
Ping @Lootyhoof :ghost:
