### ISSUE TITLE
Pale Moon UXP does not work properly on Win 8.1

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#396]
See forum topics [Startup options](https://forum.palemoon.org/viewtopic.php?f=63&t=19253) and [Menu Bar issue](https://forum.palemoon.org/viewtopic.php?f=63&t=19254).

Also neither devtools nor error console are available:
![vmware_2018-05-27_19-44-59](https://user-images.githubusercontent.com/340855/40588539-881dbe40-61e7-11e8-8925-a9f1659ba6a6.png)

**Comment by mattatobin** [comment]
Start with -jsconsole?

**Comment by JustOff** [comment]
Error: TypeError: windows8WindowFrameColor is undefined
Source File: chrome://browser/content/browser.js
Line: 7550

**Comment by wolfbeast** [comment]
I had a feeling it would be that.

**Comment by wolfbeast** [comment]
Taking this.

**Comment by janekptacijarabaci** [comment]
Ad https://github.com/MoonchildProductions/UXP/issues/155 and:
https://hg.mozilla.org/integration/mozilla-inbound/diff/c6b267589d0d/browser/modules/Windows8WindowFrameColor.jsm
(not tested)

**Comment by JustOff** [comment]
I confirm this resolves all the issues mentioned above.
