### ISSUE TITLE
DevTools - inspector - support for css-color-4 (finish)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#4]
__Actual results:__

![before](https://user-images.githubusercontent.com/2373486/35751184-7fc104c4-084f-11e8-8355-e10c4c62500f.png)

__Expected results:__

![after](https://user-images.githubusercontent.com/2373486/35751187-822ddfa2-084f-11e8-92c1-6a803519e4db.png)

**Comment by wolfbeast** [comment]
@janekptacijarabaci Please hold off on creating issues and PRs for now. we're doing a catch-up cherrypicking and porting run first thing and your work will likely be cross-linking things it shouldn't, or be solved without a pr or issue attached if it was already done on moebius.

**Comment by janekptacijarabaci** [comment]
> ...be solved without a pr or issue attached if it was already done on moebius

This issues and PRs are from Firefox 53 - this feature was present in moebius/Basilisk from the beginning (without any issue/PR). Others have followed, e.g. https://github.com/MoonchildProductions/moebius/pull/74

**Comment by mattatobin** [comment]
Jane buddy, we will be glad to accept all those lovely devtools changes and such but for the moment.. We are rapidly working on doing several months of things in a matter of days.. Just give us a little time to get the obvious and easy (but maybe tedious) stuff done first. k?

:)

**Comment by janekptacijarabaci** [comment]
Who does not like devtools, there are also other things :-)

e.g.:
- https://github.com/MoonchildProductions/Pale-Moon/pull/1055
  - https://github.com/janekptacijarabaci/UXP/commit/2625cde90f5174cf9eb83b1176bb041cdeb51967
- https://github.com/MoonchildProductions/Pale-Moon/pull/1173
  - https://github.com/janekptacijarabaci/UXP/commit/ccb5766c85995fc2f7ed9846a12893607646fe95
- https://github.com/MoonchildProductions/Pale-Moon/pull/1175
  - https://github.com/janekptacijarabaci/UXP/commit/80f9b75efa08ea449937298b791ff278cbf5fa22
- https://github.com/MoonchildProductions/Pale-Moon/pull/1203
  - https://github.com/janekptacijarabaci/UXP/commit/15e4dcdedd91421e10b80a83b63899439956911a

All from Firefox 53, native in moebius from the beginning.
