### ISSUE TITLE
update.json does not actually update extension

### ISSUE THREAD

**Issue by Aris-t2** [MoonchildProductions/UXP#401]
Hi,
I'm the developer of "Classic Theme Restorer".

Recently CTR updates for Firefox forks/clones with add-ons signing requirements can be installed via auto-update from Github. This works fine in Firefox 56 develeper edition and Waterfox, but I'm not sure why it fails with Basilisk.

Install CTR_v1.7.5.xpi from here: https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.5 
Check for updates, but CTR won't be updated to CTR_v1.7.6.xpi: https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.6

`install.rdf` points to a custom update url:
```
<em:updateURL>https://raw.githubusercontent.com/Aris-t2/ClassicThemeRestorer/master/updates.json</em:updateURL>
```

https://github.com/Aris-t2/ClassicThemeRestorer/blob/master/xpi/install.rdf

`updates.json` looks like this:
```{
  "addons": {
    "ClassicThemeRestorer@ArisT2Noia4dev": {
      "updates": [
        { "version": "1.7.6",
          "update_link": "https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi",
          "applications": {
            "gecko": { "strict_min_version": "45" }
		  }
		}
      ]
    }
  }
}
```
https://github.com/Aris-t2/ClassicThemeRestorer/blob/master/updates.json

Any ideas why updating CTR like this fails in Basilisk?

**Comment by mattatobin** [comment]
I don't know when Mozilla enabled update.json or what state it is in UXP but you should not rely on it. Not every UXP application will use the Add-ons Manager that can support a JSON update manifest. For instance, a UXP based IceWeasel will not.

You should use the plain old install.rdf file instead.

**Comment by mattatobin** [comment]
Very strange..

```
1527501083882	addons.update-checker	DEBUG	Requesting https://raw.githubusercontent.com/Aris-t2/ClassicThemeRestorer/master/updates.json
1527501083910	addons.update-checker	DEBUG	Found an update entry for ClassicThemeRestorer@ArisT2Noia4dev version 1.7.6
```

So it seems it reads it and even parses it but then does nothing with it. Does this actually work with Firefox 52? Does update.json have everything it needs?

**Comment by Aris-t2** [comment]
Thanks for the explanation.

**Comment by JustOff** [comment]
So it turns out that Basilisk can no longer receive updates from AMO. Perhaps it makes sense to provide some additional level of compatibility with Gecko versions until Phoebus is ready to serve it directly?

**Comment by mattatobin** [comment]
Basilisk should be getting rdf files from Mozilla.. NOT JSON.

**Comment by JustOff** [comment]
Since around May 10, [AMO only provide JSON](https://blog.mozilla.org/addons/2018/05/10/switching-json-update-manifests/).

**Comment by mattatobin** [comment]
Oh for fuck sakes..

**Comment by mattatobin** [comment]
Ok.. We need to move this to a new bug.

**Comment by mattatobin** [comment]
Tag #402 

@Aris-t2
