### ISSUE TITLE
AMO only serves JSON manifests for AUS

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#402]
On May 10th Mozilla started serving JSON update manifests via legacy URL channels. I was aware of the switch over but was not aware this applied to the legacy URL. I figured they would use a different request version or a different URL provided by the AMOv3 API in later Firefox versions.

Since then Basilisk has not been able to get most if not all updates from AMO due to strict compatibility targeting and targeting ONLY toolkit versions which are a mismatch with our Platform (Goanna) version and even an internal mismatch with Firefox versions on AMO (using Firefox versions for Platform versions before 2.0 and such) it is quite the mess.

Despite the immediacy of Basilisk this also excludes TychoAM consumers completely from AMO's Automatic Update Service as it has no concept of a json based update manifest.

**Comment by mattatobin** [comment]
@JustOff please reiterate anything I may have missed

**Comment by JustOff** [comment]
I'd say everything is described with the utmost clarity and precision.

**Comment by JustOff** [comment]
It seems the fix is trivial, all we need is to replace this line:

https://github.com/MoonchildProductions/UXP/blob/d2bf1f169db9ba341636808b9902aee652727499/toolkit/mozapps/webextensions/internal/AddonUpdateChecker.jsm#L518

with:

`id: "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",`

**Comment by mattatobin** [comment]
Strict compatibility and being based on a webextension min_version when not indicated is a potential issue.

I am going to try my hand at this.

**Comment by JustOff** [comment]
AMO always provides `strict_min_version` in JSON, but even if it's not, [webExtensionsMinPlatformVersion is "42.0a1"](http://xref.palemoon.org/uxp-trunk/search?string=webExtensionsMinPlatformVersion&find=libpref&findi=&filter=^[^\0]*%24&hitlimit=&tree=uxp-trunk), so it should satisfy Basilisk.

**Comment by mattatobin** [comment]
Basilisk is not the only potential consumer of WebExAM.

**Comment by JustOff** [comment]
I'm more concerned about this line:
https://github.com/MoonchildProductions/UXP/blob/d2bf1f169db9ba341636808b9902aee652727499/toolkit/mozapps/webextensions/internal/AddonUpdateChecker.jsm#L542

It seems superfluous.

**Comment by mattatobin** [comment]
The whole thing is ridiculous. Let me logic this out.

**Comment by JustOff** [comment]
Not sure if this can be useful, but it seems AMO returns JSON only for Firefox and Fennec, but XML for SeaMonkey and Thunderbird.

**Comment by mattatobin** [comment]
K.. Here is what is gonna happen..
- WebExAM
    - The JSON Update Manifest parser will be ifdef'd to MOZ_PHOENIX and assume a Firefox targetApplication
    - minVersion will be set to the strict_min_version if existent or current compatible-by-default value if not
    - maxVersion will be set to strict_max_version if existent or 56.9
    - Strict compatibility will be ignored.. defer to install manifests
    - On Non-Phoenix applications `update.json` is not supported, PERIOD.
- TychoAM
    - Wait and see until after the AMO Cull and check the status of other Firefox forks and resistance from developers using `em:updateURL`

**Comment by JustOff** [comment]
This looks quite reasonable, and AFAIU will allow devs such as @Aris-t2 to use single update url that points to the JSON manifest for all applications they support, including Basilisk.

**Comment by mattatobin** [comment]
Indeed. Though, `update.json` as implemented is terrible and it may never come to `TychoAM` and depending on what the IceWeasel guys decide on which Add-ons Manager to use.

Also, we don't know if `WebExAM` will even be be long term or if `update.json` will be supported forever.

**Comment by Aris-t2** [comment]
@mattatobin 

I switched to "update.rdf" for the Github version of my CTR add-on. The main target Basilisk and Waterfox support it.

Not quite sure about Seamonkey, but Thunderbird definitively supports "update.json". I use it in CustomizeMyBird add-on for users preferring faster updates using my Github releases.

Update.json is supported since Firefox/Thunderbird 45, so I assumed forks/clones based on 45-56 will offer support automatically. 

From Firefox/Thunderbird 62 on only update.json will be supported, rdf will be dropped: https://blog.mozilla.org/addons/2018/05/10/switching-json-update-manifests/

**Comment by mattatobin** [comment]
Success!

```
1527515732534	addons.update-checker	DEBUG	Requesting https://raw.githubusercontent.com/Aris-t2/ClassicThemeRestorer/master/updates.json
1527515732760	addons.update-checker	DEBUG	Found an update entry for ClassicThemeRestorer@ArisT2Noia4dev version 1.7.6
1527515733422	addons.xpi	DEBUG	Download started for https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi to file D:\Temp\tmp-5mp.xpi
1527515734164	addons.xpi	DEBUG	Download of https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi completed.
1527515734214	addons.repository	DEBUG	cacheAddons: enabled false IDs ["ClassicThemeRestorer@ArisT2Noia4dev"]
1527515734222	addons.xpi	DEBUG	Starting install of ClassicThemeRestorer@ArisT2Noia4dev from https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi
1527515734352	addons.xpi	DEBUG	Addon ClassicThemeRestorer@ArisT2Noia4dev will be installed as a packed xpi
1527515734360	addons.xpi	DEBUG	Staged install of ClassicThemeRestorer@ArisT2Noia4dev from https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi ready; waiting for restart.
1527515734364	addons.xpi	DEBUG	removeTemporaryFile: https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.6/CTR_v1.7.6.xpi removing temp file D:\Temp\tmp-5mp.xpi
```

**Comment by mattatobin** [comment]
@Aris-t2

I have this fixed for WebExAM (The WebExtensions "native Firefox 52" Add-ons Manager).. So the next Basilisk update will have this fix and `updates.json` will work with it.

I am still thinking what I can do for the TychoAM consumers for these circumstances without introducing this madness to them.

**Comment by mattatobin** [comment]
@Aris-t2 BTW Thanks for deciding to switch back to `update.rdf` at least on the next Basilisk update the `update.json` will allow Basilisk to update to the next version pointing to `update.rdf`.
