### ISSUE TITLE
List of unsupported optimization flags

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#403]
I need a list of Windows and Linux optimization flags that are unsupported.

@wolfbeast @trav90

**Comment by trav90** [comment]
Off the top of my head for for GCC (some are probably redundant):

-mmmx
-msse
-mno-sse
-mno-sse2
-mfpmath=387

And might as well throw -Os and -O3 in the mix as well.

**Comment by wolfbeast** [comment]
For Windows:
-arch:ia32
-arch:sse
-fp:fast (known to cause inaccuracies)

**Comment by wolfbeast** [comment]
We'll probably need some of what was backed out for GCC to ensure sse2 is actually in use. With a build system error though, we won't need to use the hacky non-sse2 message upon startup.

**Comment by mattatobin** [comment]
What about -GS- for Windows?

**Comment by wolfbeast** [comment]
@trav90 for gcc, probably good to also add `-mfpmath=both` and `-mfpmath=sse+387` because gcc even states that it's experimental (by doubling the registers)

**Comment by trav90** [comment]
Yes, agreed those two should also be added.

**Comment by wolfbeast** [comment]
@mattatobin have you ever done anything with this? does this need to stay open?

**Comment by mattatobin** [comment]
Doesn't matter, we can close as WONTFIX.
