### ISSUE TITLE
SSL Error reporting

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#408]
It seems that [SSL Error Reporting](https://firefox-source-docs.mozilla.org/browser/base/sslerrorreport/index.html) is [enabled by default](http://xref.palemoon.org/uxp-trunk/search?string=security.ssl.errorReporting.enabled&find=) in UXP.

Do we really want to use this configuration or even the service at all?

**Comment by wolfbeast** [comment]
I don't think there's any reason whatsoever to keep the code for this service.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by wolfbeast** [comment]
This has baked a few days and doesn't seem to cause issues -- considering to be resolved.
