### ISSUE TITLE
Unify AddonUpdateChecker.jsm and improve/support updates.json

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#409]
We have a two different imperatives going on right now.. Eventual Unification of the Add-on Managers and the need to support a JSON Add-on Update Manifest.

Because of the latter this specific item gets special attention.

What I want to do is, in a backwards-forwards-backwards compatible way is support the newer update manifest format and make it as powerful as the current Mozilla RDF update manifest.

I have no plans to push for or endorse depercation, removal, or replacement of the Mozilla RDF Update Manifest Parser.

----

- [x] Resolve generational gaps between `TychoAM` and `WebExAM`
- [x] Ensure conditional Dual-GUID feature
- [x] update.json
  - [x] "gecko" Application
    - [x] Phoenix Applications (Pale Moon, Basilisk, IceWeasel)
        - Mozilla uses Firefox and Platform versions interchangeably because they are the same so assume a Firefox compatibility-by-default stance. Phoenix Applications not using Firefox's ID like Pale Moon will accept this because of the Dual-GUID system. Else the update is not applicable.
        - targetApplication is Firefox's ID
        - `strict_min_version` is `extensions.minCompatibleAppVersion` if not existent
        - `strict_max_version` is `*` unless Dual-GUID then it is `56.9`
    - [x] Non-Phoenix Applications
        - There is little that can be done for Non-Phoenix applications trying to use "gecko" as a targetApplication because UXP is not mozilla-central so we are just going to assume an update is always compatible and let the install manifests handle it. Developers targeting UXP applications SHOULD include direct application compatibility information in `update.json` to avoid this behavior.
        - targetApplication is Toolkit's ID
        - `strict_min_version` is `platformVersion`
        - `strict_max_version` is `*`
  - [x] Any other Application (by ID) including `toolkit@mozilla.org`
    - Normal `update.rdf`-alike rules apply
    - `strict_*_version` have no meaning as `strict_compatibility` will be honored (in each application)
    - `min_version` and `max_version` will be used and are **REQUIRED**
    - In the event Mozilla actually does end up adding multiple application support and does it by ID then the above version bits will be adjusted accordingly in a compatible way.
- [ ] Use unified `AddonUpdateChecker.jsm` for both Add-on Managers

**Comment by mattatobin** [comment]
Reference tags #401 #402 351cf27036d335e207b2a697423638dd4732cd08 2a36ae70f511d3eaf8594477934f640c6ff50c96 cf412a59f3499e548a49c84a751ff625043cda0d

**Comment by wolfbeast** [comment]
Reassigned @mattatobin as per IRC statement.

**Comment by mattatobin** [comment]
Current status of this as of today is that everything but the unification is done. I would appreciate some additional testing but currently only Pale Moon (or non-Basilisk) application has this.

ALSO as a matter of course here is what a Firefox and UXP compatible `update.json` would look like:

```
{
  "addons": {
    "test@aus.com": {
      "updates": [
        {
          "applications": {
            "gecko": {
              "strict_min_version": "38.0",
            },
            "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}": {
              "min_version": "52.9.2018.04.24",
              "max_version": "52.*",
              "strict_compatibility": true
            },
            "{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}": {
              "min_version": "27.0.0a1",
              "max_version": "28.*"
            }
          }
          "version": "2.0",
          "update_link": "https://addons-dev.palemoon.org/_tools/addon-test/test.xpi",
          "update_hash": "sha256:d76f392a0473ab7f85bc2ad6cf100a3c7ebd14439c241a1a6164dcc5a9c2035a"
        }
      ]
    }
  }
}
```
