### ISSUE TITLE
Use a final dist check to catch any unpreprocessed files.

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#428]
Because some want to have this discussion again.

**Comment by mattatobin** [comment]
Check for `#if` `#define` `#include` should be good enough for keywords.

**Comment by wolfbeast** [comment]
So we're not going to agree on anything, then, because it _should_ run every build to catch these things, otherwise it's pointless to even have.

Since we won't be able to come to a solution that agrees at least somewhat with everyone, let's wontfix it and let's forget i said anything. I'll hold my tongue in the future.

**Comment by JustOff** [comment]
> it should run every build to catch these things, otherwise it's pointless to even have.

You stole my words :stuck_out_tongue_winking_eye:

Actually `grep` within `@MOZ_OBJDIR@\dist\bin` is really *very cheap*, it takes less than 2 seconds even on my 10-year old PC using a non-SSD partition.

**Comment by mattatobin** [comment]
OH.. This is in `dist/bin/`? Sure why the hell not.. We should go for it then!

**Comment by wolfbeast** [comment]
@mattatobin using `$topsrcdir` wouldn't be very useful if you want to check if there are leftover unprocessed conditionals in the final product ;)

Common preprocessing keywords are `#ifdef` `#if defined` `#filter` `#include` `#else` `#endif` `#expand`, although you should be able to catch all `#if*` conditions by simply checking for `#endif` which always has to be present.

**Comment by mattatobin** [comment]
`#define` is something that is used as well..

So I think
- `#if`
- `#ifdef
- `#define`
- `#filter`
- `#expand`
- `#include`

Would do nicely to catch any sort of preprocessing.

**Comment by JustOff** [comment]
It seems here is the full list:

https://github.com/MoonchildProductions/UXP/blob/eb03d673884f809109a0b3c73c94bb1cb1fa5857/python/mozbuild/mozbuild/preprocessor.py#L293-L309

**Comment by wolfbeast** [comment]
That would make the list to check
`#define`
`#undef`
`#endif`
`#expand`
`#literal`
`#filter`
`#unfilter`
`#include`
`#includesubst`
`#error`
