### ISSUE TITLE
Findbar in Pale Moon does not open when you press "/" or "'" keys

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#430]
Reported on the forum [here](https://forum.palemoon.org/viewtopic.php?f=62&t=19312).

This is most probably because of [bug 1133981](https://bugzilla.mozilla.org/show_bug.cgi?id=1133981) and the [follow-ups](https://github.com/mozilla/gecko-dev/commits/esr52/toolkit/content/widgets/findbar.xml).

Tag #57.

**Comment by janekptacijarabaci** [comment]
I will look at it...

**Comment by Gittyperson** [comment]
Quick Find now works on a3 but it seems that when the browser starts, it won't work. Opening the standard Find bar (CTRL-F) once, will then make the Quick Find bar work normally.

**Comment by janekptacijarabaci** [comment]
I do not see this... Please provide some specific steps to reproduce the problem.

**Comment by Gittyperson** [comment]
You are right, it does not happen on a clean profile, Quick Find works instantly. It does happen on my profile (upgraded from v27), even on Safe Mode.

1. Open Browser
2. Press / or ' (nothing happens, nothing in Error Console)
3. Press CTRL-F (works as expected)
4. Press / or ' (works as expected)
5. Close and open browser
(2-5 repeated)

**Comment by janekptacijarabaci** [comment]
Partially reproduced...

**Comment by wolfbeast** [comment]
Confirmed; quick search doesn't launch unless the findbar is initialized first.

**Comment by janekptacijarabaci** [comment]
Please leave it assigned.
