### ISSUE TITLE
SVG placement misaligned (subpixel blur)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#438]
Layout-aligned SVG images should be snapped to pixels, but they aren't.
Some things depend on how they are embedded in the page.

Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1375720
See also: https://github.com/MoonchildProductions/Pale-Moon/issues/1188

**Comment by THEtomaso** [comment]
Is this related somehow?:
`https://www.chess.com/news/view/carlsen-wins-2018-world-chess-championship-in-playoff/`
Most images in that article only displays as grey boxes.
Right-clicking on them and selecting "View image" reveals that they're empty SVG files.
The images show just fine in SeaMonkey, where they're displayed as JPEG images.

**Comment by wolfbeast** [comment]
Completely unrelated. I'm not really sure how or why you think that SVG images not showing up would somehow be related to them showing up but having a display quirk...

**Comment by spectatorBH** [comment]
The related upstream bug has been finally marked as resolved in [Firefox 68](https://bugzilla.mozilla.org/show_bug.cgi?id=608812). Although SVG rendering is still not always ideal as in Chromium, it is quite decent now. Just verified in Fx 68.0.1 under Ubuntu-based Zorin OS 12.4 Lite (Xfce). 

Can this fix be backported to PM?

**Comment by wolfbeast** [comment]
I'm looking into this.
Can you provide some test URLs?

**Comment by wolfbeast** [comment]
I'll be spinning some new unstables for verification of this issue.

**Comment by win7-7** [comment]
I compiled New Moon build with this in it. Works without problems. Compared that build to Firefox ESR52 where problem is clearly seen.

Test link:

https://github.com/MoonchildProductions/Pale-Moon/commits/master

**Comment by wolfbeast** [comment]
The github commits issue was already solved quite a while back; the actual SVG element alignment was however not solved, so you can't really use github as a measure there.

Unstables are up.
The most obvious testcase I've used has been my own reduced testcase that fails in Pale Moon-release, but passes in the latest unstable. Attached here for convenience.

[svgblur.zip](https://github.com/MoonchildProductions/UXP/files/3502699/svgblur.zip)

**Comment by wolfbeast** [comment]
Other tests collected from various bug reports:

https://codepen.io/kleinfreund/pen/MLOWeX
https://iconify.design/test/blur-bug.html

**Comment by win7-7** [comment]
reduced testcase works fine in unstable while in Pale Moon release it fails.

https://iconify.design/test/blur-bug.html works fine in unstable while in Pale Moon release it fails.

https://codepen.io/kleinfreund/pen/MLOWeX works fine in unstable while in Pale Moon release it fails.

https://bug608812.bmoattachments.org/attachment.cgi?id=8636671 works fine in unstable while in Pale Moon release it has thick borders on top/bottom.

So these changes do seems to resolve this issue.

**Comment by wolfbeast** [comment]
Thanks for verifying. marking this solved.
