### ISSUE TITLE
Disable CSS Errors logging by default to improve performance

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#444]
By default CSS parser sends hundreds of errors to the Error Console for almost every page. This info is completely useless for the regular browsing and only wastes CPU time and memory. Such load can be quite significant, just open Error Console for evidences.

Setting layout.css.report_errors default to false will disable CSS Errors logging. The devs should turn it on only for actual purposes.

Extension devs that rely on this should take steps to enable this feature if and when they need it in their extension.

**Comment by JustOff** [comment]
Attn: @Lootyhoof, see https://github.com/MoonchildProductions/Pale-Moon/issues/747.

**Comment by JustOff** [comment]
Perfect, sorry to have bothered you.
