### ISSUE TITLE
Keep a running update of HSTS preload lists.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#447]
UXP should keep updated with somewhat recent HSTS preload lists.

@trav90  has offered to do this.

(responsibility tracking issue, leave open)

**Comment by trav90** [comment]
I am going to look into automating this on a dedicated machine to keep this list updated a bit more regularly.

**Comment by wolfbeast** [comment]
Since HSTS is a long-term commitment thing, once every fortnight should be frequent enough -- I wouldn't want to have near-daily updates like Mozilla does, that's just a waste and commit noise we don't want.

**Comment by wolfbeast** [comment]
@trav90 obviously doesn't have time to do this anymore and I don't think of running these updates with any sort of regularity either. We either need someone willing to run this regularly and committing these updates to the tree, or simply do away with the preload list altogether which is becoming less effective as it is anyway.

**Comment by wolfbeast** [comment]
Closing this because #1498 means we are no longer in need of updating.
