### ISSUE TITLE
Menu: "History" - "Recently Closed Tabs" and "Recently Closed Windows" - strange context menu

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#452]
Tag: https://github.com/MoonchildProductions/Pale-Moon/issues/608 (the frontend has not changed - not solved)

See:
![1](https://cloud.githubusercontent.com/assets/2373486/19420753/83eb3448-93f2-11e6-83c2-ba6127fcec28.png)

After run the function "Open All in Tabs"... nothing happens.
Also (AFAIK)... It makes no sense in this Popup menu: "Recently Closed Windows".

**The same problem is also in Pale Moon stable (including the latest version 27).**

---

__A suggestion of PR:__
[_testBranch_pm_places_contextMenu](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:_testBranch_pm_places_contextMenu)

__Based on:__
- [Bug 1006989](https://bugzilla.mozilla.org/show_bug.cgi?id=1006989)
  - The Bookmarks Toolbar Items context shouldn't have `Cut`, `Copy`, `Delete`, or `Properties` when right-clicking on a blank area
- Depends on:
  - [Bug 1090609](https://bugzilla.mozilla.org/show_bug.cgi?id=1090609)
    - Bookmark folder open all does not work with only one url in the folder
  - [Bug 1177639](https://bugzilla.mozilla.org/show_bug.cgi?id=1177639)
    - `Copy` context menu is missing on bookmarks
- Fix: `Open All in Tabs` not for the top of the menu `History`

**Comment by wolfbeast** [comment]
This was fixed in #882
