### ISSUE TITLE
The context menu: "Save Page As" - displaying incorrect file (*.htm) size in Downloads

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#453]
Tag: https://github.com/MoonchildProductions/Pale-Moon/issues/629 (the frontend has not changed - not solved)

---
## `Context menu` - `Save Page As`

Displaying incorrect file (*.htm) size (it's size of other files: e.g. "last" image on the page) in Downloads.

**Steps to reproduce**
1. Go to: http://www.palemoon.org/
2. Right-click context menu on the page: `Save Page As`
3. The result (e.g.): `2,6 KB -> twitter.png` instead `23,6 KB -> The Pale Moon Project homepage.htm`

![1](https://cloud.githubusercontent.com/assets/2373486/19828923/bf795dec-9dd3-11e6-9625-17c5d15bbd8d.png)

---

**It's associated with large change (downloads)...**

Last bad: 38.0a1 (2015-02-17)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Built from https://hg.mozilla.org/mozilla-central/rev/09f4968d5f42

First good: 38.0a1 (2015-02-18)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Built from https://hg.mozilla.org/mozilla-central/rev/9696d1c4b3ba

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=09f4968d5f42&tochange=9696d1c4b3ba

[Bug 1127867](https://bugzilla.mozilla.org/show_bug.cgi?id=1127867) - Use the new back-end property to get the size of downloads asynchronously

**Comment by wolfbeast** [comment]
Depends on
[bug 1117141](https://bugzilla.mozilla.org/show_bug.cgi?id=1117141)

**Comment by janekptacijarabaci** [comment]
__A suggestion of PR:__
[_testBranch_pm_downloads_rewrite_1](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:_testBranch_pm_downloads_rewrite_1)

__Based on:__
- [Bug 1127867](https://bugzilla.mozilla.org/show_bug.cgi?id=1127867) - Use the new back-end property to get the size of downloads asynchronously
  - __Depends on:__
    - [Bug 1115369](https://bugzilla.mozilla.org/show_bug.cgi?id=1115369) - Use notifications instead of getViewItem for DownloadsView
    - [Bug 1115971](https://bugzilla.mozilla.org/show_bug.cgi?id=1115971) - Don't fall back to the Places title for downloads without the target file name annotation
    - [Bug 1115972](https://bugzilla.mozilla.org/show_bug.cgi?id=1115972) - Don't fall back to the Places icon for downloads without the target file name annotation
    - [Bug 1120429](https://bugzilla.mozilla.org/show_bug.cgi?id=1120429) - Remove unused code handling nodeAnnotationChanged
    - [Bug 1115421](https://bugzilla.mozilla.org/show_bug.cgi?id=1115421) - Simplify download annotations handling in the Library
    - [Bug 1115983](https://bugzilla.mozilla.org/show_bug.cgi?id=1115983) - Keep only minimal state information in the DataItem
    - [Bug 1116176](https://bugzilla.mozilla.org/show_bug.cgi?id=1116176) - Create DownloadsHistoryDataItem and HistoryDownload objects
    - [Bug 1115379](https://bugzilla.mozilla.org/show_bug.cgi?id=1115379) - Streamline DownloadsViewItemController construction and remove now unneeded identifiers
    - [Bug 1117139](https://bugzilla.mozilla.org/show_bug.cgi?id=1117139) - Move code controlling the "download.xml" binding to a common place
    - [Bug 1117141](https://bugzilla.mozilla.org/show_bug.cgi?id=1117141) - Remove DownloadsDataItem
  - __Blocks:__
    - [Bug 1195279](https://bugzilla.mozilla.org/show_bug.cgi?id=1195279) - Fix typo in allDownloadsViewOverlay.js following landing of bug 1127867
    - [Bug 1129896](https://bugzilla.mozilla.org/show_bug.cgi?id=1129896) - Address review comments for the Downloads front-end refactoring
      - __Depends on:__
        - [Bug 1135348](https://bugzilla.mozilla.org/show_bug.cgi?id=1135348) - about:downloads broken

---

I've created the new build (x32, Windows) - `Pale Moon` - and tested (downloads: downloads, pause/resume,  `Retry`, `Open Containing Folder`, `Remove From History`, `Clear Downloads`, `Copy Download Link`...; Private Browsing...), but this fix must be __thoroughly__ (checked and) tested (`Verification Needed`)!
__- if you would like to use it, of course...__

**Comment by wolfbeast** [comment]
This has been fixed along the way (can no longer reproduce the reported issue).
Closing as WFM
