### ISSUE TITLE
SSL/TLS connections are claimed to be unencrypted for feeds.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#455]
Feeds delivered over SSL/TLS are claimed to be unencrypted when they are viewed from the feed subscription UI. The padlock and the identity panel are not displayed, and the page info dialog and the identity panel dropdown claims that the connections are unencrypted.

The reason for this is:
- the original content loads over https (secure)
- the preview page is loaded from a jar channel (insecure)

nsSecureBrowserUIImpl inspects the current channel for securityInfo and uses that to update the browser UI. 

In this "nested" channel situation we have no way of knowing what the securityInfo of the original channel is. 

This will potentially require significant API changes. Since this is lower priority (worst case is the user getting freaked out that content isn't secure when it actually is -- in any case https: is still shown in the address bar even if coloration and lock icon aren't present), it'll be on the backburner.

**Comment by janekptacijarabaci** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1172234#c9

> This is because the content is loaded in a page called about:feeds, and that's what the identity popup uses to make decisions. It no longer has access to the security info of the original https channel, and so it can't tell us anything about the cert or otherwise.

> Fixing this would require rearchitecturing the entire rss reader infrastructure, or fetching and keeping a reference to the ssl info somewhere and then plugging it in somewhere else, making sure to throw it away when done because it probably keeps other crap alive so there's a risk of leaks, which is also a lot of work.

**Comment by wolfbeast** [comment]
I already stated all that, myself.

**Comment by wolfbeast** [comment]
Wontfix, probably.

**Comment by mattatobin** [comment]
Didn't Basilisk work around this by claiming all internal pages are "Secure pages part of Basilisk" or some dipshit warm and fuzzy state?

**Comment by wolfbeast** [comment]
Well, not so warm and fuzzy, but they actually are secure, just by a different method... We could apply the same policy.

**Comment by wolfbeast** [comment]
Actually, Basilisk displays the feed preview page with the URL of the feed to subscribe to when previewing the feed, it's not marked as an internal page either (because it isn't).

I don't really have any idea how to work around this, since the way page security is (and I'd rather not change that in fear of opening up sec holes/vulnerabilities), the object that determines page security is the actual browser element, not the (arbitrary) address bar content, since that is just a chrome display element and can't be trusted to always reflect the internal state of the browser (this very page, for example, is an about: page but the attached URL is the feed URL)

**Comment by mattatobin** [comment]
I agree. The changes in Firefox throughout Australis to the feeds component may not be wise to keep either. However, I think we should do nothing unless it presents an issue. Worse comes to worse, we can port over the earlier incarnation.

So `RESOLVED WONTFIX`?

**Comment by wolfbeast** [comment]
Agreed.
