### ISSUE TITLE
[PALEMOON] Help - About Pale Moon: a right click on the highlighted text doesn't bring up a copy paste menu

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#478]
Ad https://forum.palemoon.org/viewtopic.php?f=63&t=19384

**Comment by wolfbeast** [comment]
... why do we need this, exactly?

**Comment by janekptacijarabaci** [comment]
To make it intuitive (same context menu as elsewhere) - if the text is highlighted.

**Comment by mattatobin** [comment]
What highlighted text?

**Comment by wolfbeast** [comment]
Effectively, the only text that can be highlighted is the version (by some arbitrary decision at Mozilla). I'd rather go the other direction and remove that highlight option for version.
