### ISSUE TITLE
Memory leak in the WebP decoder

### ISSUE THREAD

**Issue by SorceressEpele** [MoonchildProductions/UXP#483]
After closing a memory-demanding tab (Such as a page on giphy after scrolling down considerable length), the browser keeps a persistently high memory use (In this case, I'm sitting at 3.4GB even after using the built-in about:memory to try and reclaim some.)

Tested in Version: 28.0.0a4 (64-bit) (2018-06-10)
Reproduction: Scroll down on giphy.com for a bit.
Expectation: More memory from that tab to be reclaimed after closing.
Reality: Claimed back just 1.5GB of memory (4.9GB Peak down to 3.4GB after closing tab)

**Comment by wolfbeast** [comment]
Since you're familiar with about:memory, it would be nice to know where the memory report says the memory is allocated (which are the large consumers?)

**Comment by JustOff** [comment]
I confirm this, in my case the memory not used anymore after closing the 2GB tab with https://giphy.com stuck in the heap-unclassified:

```
Pale Moon:

1,432.45 MB (100.0%) -- explicit
├──1,351.01 MB (94.31%) ── heap-unclassified

Basilisk:

1,291.93 MB (100.0%) -- explicit
├──1,195.19 MB (92.51%) ── heap-unclassified
├─────38.17 MB (02.95%) -- heap-overhead
```

At the same time, I can't even get Firefox ESR 52 with e10s disabled to take more than 512 MB by scrolling https://giphy.com, and all memory is returned when I close the tab.

**Comment by JustOff** [comment]
Here is the basic bisection results:

Browser | Date | Result
------------------ | --- | -- 
Basilisk UXP [2018.06.01](https://github.com/MoonchildProductions/UXP/releases/tag/v2018.06.01) | 2018.06.01 | Problem
Basilisk UXP [CP1](https://github.com/MoonchildProductions/UXP/tree/FullFunction_CP1) | 2018.02.11 | Problem
... | ... | ?
Basilisk UXP [2018.02.02](https://github.com/MoonchildProductions/UXP/tree/c28c5b704fb3f3af6e7846abd73f63da1e35921f) | 2018.02.02 | Ok
Firefox ESR 52.6.0 | 2018.01.19 | Ok
Basilisk Moebius | 2017.12.01 | Problem

**Comment by JustOff** [comment]
Well, it seems I found the culprit: it's a WebP image decoder, and with `image.webp.enabled -> false` the problem goes away.

**Comment by wolfbeast** [comment]
Hmm.. seems webp doesn't properly deallocate memory then.

**Comment by wolfbeast** [comment]
Since the implementation in use is Mozilla's (from [Bug 1294490](https://bugzilla.mozilla.org/show_bug.cgi?id=1294490)) I've tossed the ball upstream, see what they say.

**Comment by JustOff** [comment]
It seems that WebP decoder in Tycho does not have this problem. 

Here is the file to test: [very_big_webp.zip](https://github.com/MoonchildProductions/UXP/files/2094191/very_big_webp.zip)

**Comment by JustOff** [comment]
I checked and was not surprised that the same problem is present in Waterfox as well.

**Comment by wolfbeast** [comment]
The decoder in Tycho doesn't use lexers (which I know nothing about and has been the blocker for me reimplementing jpeg-xr as well) and I think it's in that part where the leak occurs, not the webp lib itself.

**Comment by roytam1** [comment]
I wonder if libwebp-1.0.0 will change?

**Comment by JustOff** [comment]
It will not if @wolfbeast is right about lexers, but you can try and check - this will be helpful to know for sure.

**Comment by roytam1** [comment]
OK it seems that updating to libwebp-1.0.0 doesn't change the situation about memory leaking.

**Comment by JustOff** [comment]
Nice catch @roytam1, looks like this really resolves the leaking!

**Comment by wolfbeast** [comment]
Great job, guys!

**Comment by JustOff** [comment]
I verified this using both https://giphy.com/ and [the test file](https://github.com/MoonchildProductions/UXP/issues/483#issuecomment-396589232)  - no leak is observed.

**Comment by roytam1** [comment]
@wolfbeast so please comment in upstream as I can't post comment on it. :)

**Comment by wolfbeast** [comment]
> please comment in upstream as I can't post comment on it. :)

https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c126

**Comment by roytam1** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c126

Thanks! :)
