### ISSUE TITLE
Basilisk page indicator label should be green instead of orange

### ISSUE THREAD

**Issue by mrnhmath** [MoonchildProductions/UXP#484]
It's the little things...

![yahiparamvaastaviktahai](https://user-images.githubusercontent.com/13562431/41261972-b5702634-6db4-11e8-986d-6e55ce0e28b7.PNG)

**Comment by janekptacijarabaci** [comment]
...this color is here:
https://github.com/MoonchildProductions/UXP/blob/PM28.0.0a4_Unstable/application/basilisk/themes/shared/identity-block/identity-block.inc.css#L34
