### ISSUE TITLE
Personas not retained

### ISSUE THREAD

**Issue by Gittyperson** [MoonchildProductions/UXP#485]
1. Install a [persona](https://addons.mozilla.org/en-US/firefox/addon/amiga-light/)
2. Restart browser
3. Persona still indicated as enabled, but does not appear on UI.

Also tested on a clean profile (just Moon Tester Tool 1.1.6 installed)

Windows 10 x64 Pro, Pale Moon 28.0.0a4 (I don't think this happened on previous alpha versions)

**Comment by wolfbeast** [comment]
This is a regression from porting TychoAM.
Easy enough to fix by using the updated image fetching method.
