### ISSUE TITLE
Mac OS X: build fails at configure stage

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#49]
Python interpreter errors with:
`0:15.01 ['UnsortedError: An attempt was made to add an unsorted sequence to a list. The incoming list is unsorted starting at element 1. We expected "background.png" but got "disk.icns"\n']`

**Comment by SpockMan02** [comment]
For reference, 10.6 or 10.7?

**Comment by adeshkp** [comment]
@SpockMan02 High Sierra 10.13.3

**Comment by SpockMan02** [comment]
Oh, heh... Somehow I didn't see your PR doing the literal exact same thing as what I just did... But yeah, I can confirm that that fixes it.

**Comment by wolfbeast** [comment]
Yeah it's the arbitrary requirement that all moz.build source lists must be alphabetically sorted.
