### ISSUE TITLE
Pale Moon: macOS: Lightweight themes kill the titlebar

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/UXP#491]
Lootyhoof:
> On OS X … it would appear that using a persona kills the titlebar, including caption buttons.

> This appears to be due to 625989 (with additional back-end work having been already done in multiple dependant bugs), however applying this doesn't seem to restore the caption buttons (and in fact kills them entirely). … (though some of the dependant bugs on this one look promising).

https://github.com/MoonchildProductions/Pale-Moon/issues/623

**Comment by wolfbeast** [comment]
Has this been confirmed to be a problem on UXP, or did you just clone it?

**Comment by lewjasio** [comment]
Apparently this is still an issue: [https://github.com/MoonchildProductions/Pale-Moon/issues/623#issuecomment-396787519](https://github.com/MoonchildProductions/Pale-Moon/issues/623#issuecomment-396787519).

**Comment by SpockMan02** [comment]
I found the cause!

**Comment by Lootyhoof** [comment]
...Care to explain? Are you working on a patch for it?

**Comment by SpockMan02** [comment]
Yessir.

Sorry I waited 8 hours, I went to sleep.

**Comment by wolfbeast** [comment]
Please do enlighten us!
