### ISSUE TITLE
TypeError: this._recipeManager is null in LoginManagerParent.jsm

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#496]
Error: `TypeError: this._recipeManager is null[Learn More]  LoginManagerParent.jsm:106:9`

I'm not entirely sure what triggered this but should be investigated.

**Comment by janekptacijarabaci** [comment]
This is also the case for:
[Bug 1167872](https://bugzilla.mozilla.org/show_bug.cgi?id=1167872) - **Error: TypeError: this._recipeManager is null LoginManagerParent.jsm**
(it remains unfixed - also in Firefox Nightly)

**Comment by wolfbeast** [comment]
OK, harmless then -- I'll put it on hold and cc on the bugzilla bug.

**Comment by mattatobin** [comment]
When I was up late one night trying to merge conditionally the autocomplete behavior.. I simply wrapped the offending code in a trycatch to silence it. Maybe someone can just do that at some point.
