### ISSUE TITLE
[PALEMOON] Sanitize - Findbar not cleared when doing Clear private data

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#502]
After https://github.com/MoonchildProductions/UXP/commit/0b2ad9c9dd2282dc9fe2ec5c7e8ffd05fccca617:
Findbar (and its history - `Ctrl-Z`) not cleared
when doing Clear private data (`History` - `Clear Recent History` - `Form & Search History`).

__Steps to Reproduce:__
1. Make a few searches in Findbar
2. Clear private data (`History` - `Clear Recent History` - `Form & Search History`)
3. Select the Findbar
4. Hit `Ctrl-Z` to repeatedly cycle through previously viewed search requests

__Actual Results:__
I can see all previously viewed search requests.

__Expected Results:__
I see nothing since I've already cleared all private data

**Comment by wolfbeast** [comment]
Thank you.
