### ISSUE TITLE
HTM bookmarks importing bug

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#505]
Importing large amounts of bookmarks from HTM files will result in Pale Moon hanging for a long time (like 5 minutes), and potentialy giving a "Unresponsive script" error message.
Strangely enough though, in about 10% of the cases, the process works like expected, and only takes a few seconds.

(Pale Moon v28.0.0a4,x64,2018-06-14 / Win8.1Pro,x64)

Reference:
https://github.com/MoonchildProductions/Pale-Moon/issues/587/

**Comment by wolfbeast** [comment]
Ref forum discussion (see also): https://forum.palemoon.org/viewtopic.php?f=3&t=20754&start=20#p155377

**Comment by wolfbeast** [comment]
Closing this for being stale.
