### ISSUE TITLE
[low priority] [longterm] consider changing profile folder name

### ISSUE THREAD

**Issue by maws6502** [MoonchildProductions/UXP#510]
Hi, 
One small thing that I noticed is that you have a space in the filename for your profile directory (.moonchild productions). While not at all a priority, perhaps before final release, you would consider changing this to a space-less name, so it can be more easily handled by command line tools and scripts?

**Comment by wolfbeast** [comment]
Sorry but the answer is still no on that one. Changing the path would be a migration nightmare for existing users, and spaces in path names have been a thing for decades. Command-line shells will autocomplete, and scripts can simply escape the space if needed.
