### ISSUE TITLE
Tooltip bug

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#511]
In some cases, tooltips are shown where they shouldn't be.

This is very noticable in uBlock Origin, which comes with its own set of tooltips.
As you can see in this screenshot, Pale Moon's tooltips overlaps uBO's native ones, making them unreadable:

![ublockorigin-bug-tooltips](https://user-images.githubusercontent.com/9382674/39240428-41a5e0d8-4873-11e8-90fa-88bdc4beb2b5.jpg)

In this case, all of PM's tooltips simply says "uBlock Origin", and should be limited to the extension's icon only. 

According to gorhill (uBO's author), this is a browser bug, and not an extension bug:
https://github.com/uBlockOrigin/uBlock-issues/issues/63/

SeaMonkey is also affected, which makes this a Firefox legacy issue.
Apparently, all other browsers are unaffected.

(Pale Moon v28.0.0a4,x64,2018-06-14 / Win8.1Pro,x64)

**Comment by JustOff** [comment]
The issue was resolved in uBlock 1.16.4.2, thanks to @janekptacijarabaci.
