### ISSUE TITLE
Fix about:newtab/quick dial page in Pale Moon

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#517]
Pale Moon's Quick Dial page isn't working properly (thumb updates/site updates don't work, throws promise chain issues)

This needs to be fixed before beta.

- [x] Import Basilisk's NewTab page
- [x] Fix Search
- [x] Remove compact style
- [x] Fix tab pinning/blocking controls
- [x] Remove configuration menu (unnecessary since blank is already an option in the preferences)
- [x] Restyle for Pale Moon
- [x] Remove Mozilla service nonsense

Blocks #57

**Comment by wolfbeast** [comment]
Trying to use the platform's thumbnail getters has resulted in nothing but failures.

Change of approach: import Basilisk's newtab page and whip it into proper shape for Pale Moon.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn, considering #546.
