### ISSUE TITLE
Stop using old-style promises.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#521]
We should convert any old-style promises in use to the final-spec internal promises implementation.

@JustOff has offered to tackle this (IIUC) so I'll assign him to this.

**Comment by JustOff** [comment]
Do I understand correctly that `/application/palemoon/base/content/sanitize.js` is [the only place where it's left](http://xref.palemoon.org/uxp-trunk/search?string=resource%3A%2F%2F%2Fmodules%2Fpromise.js) after https://github.com/MoonchildProductions/UXP/commit/d84b169e75bbf0e4f1888e8d5287323bb3ed61da?

**Comment by mattatobin** [comment]
Promises.jsm isn't the problem. It's the localised jetpack module in Pale Moon code that needs to be converted to str8 Promises.jsm

**Comment by mattatobin** [comment]
@JustOff you are correct. Just sanitize is left. Everything else either uses direct promises or Promise.jsm (which is correct)

**Comment by JustOff** [comment]
I agree with @mattatobin,  but in any case, I propose to exclude the GRE promises module from this task.

**Comment by wolfbeast** [comment]
Task updated.

**Comment by JustOff** [comment]
Well, unless someone wants to rewrite Sanitizer using native promises, I'm just going to replace `resource:///modules/promise.js` with `resource://gre/modules/Promise.jsm`, remove `resource:///modules/promise.js` from the tree, and consider this task resolved.

**Comment by JustOff** [comment]
I think it should, but of course I will check this before submitting a PR.

**Comment by mattatobin** [comment]
From what little I can recall.. Mozilla had to change a lot to make this work.

**Comment by JustOff** [comment]
Since Sanitizer uses just a simple scheme (`var deferred = Promise.defer();` `deferred.reject();` `deferred.resolve();` `return deferred.promise;`), it should work with `Promise.jsm` without changes.

**Comment by JustOff** [comment]
> Promises.jsm isn't the problem. It's the localised jetpack module

Actually `Promises.jsm` is not jetpack, but toolkit module, while "old-style" `promise.js` is from the jetpack. So by using `Promises.jsm` instead of `promise.js` we get rid of the dependence on the jetpack.

**Comment by mattatobin** [comment]
I never said Promises.jsm was jetpack...

**Comment by JustOff** [comment]
Sorry, it seems I just misunderstood what exactly "it" refers to in the above. However, it's not so important.
