### ISSUE TITLE
[PALEMOON] Sync - return "404 Not Found" for "storage/meta/fxa_credentials"

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#522]
Tag #468 

After synchronization throws:
```
https://pmsync.palemoon.org/sync/index.php/1.1/[id]/storage/meta/fxa_credentials
[HTTP/1.1 404 Not Found]
```

~~http://xref.palemoon.org/uxp-trunk/search?string=fxa_credentials&filter=%5E%5B%5E%5C0%5D*%24&tree=uxp-trunk~~

**Comment by wolfbeast** [comment]
I know how to use xref, tyvm. It would be more useful if you actually point out the resulting location where this call is made.

**Comment by janekptacijarabaci** [comment]
OK: https://github.com/MoonchildProductions/UXP/blob/PM28.0.0a4_Unstable/services/sync/modules/service.js#L1344

**Comment by wolfbeast** [comment]
We need a better way to control these FxA specific functions. A pref would do instead of conditional defines.

**Comment by mattatobin** [comment]
Why is FxA being retained? No one but Mozilla has any hope of running it and no one is going to keep the client code up to date.

**Comment by wolfbeast** [comment]
Because Basilisk and other applications might want to use it? As long as Mozilla doesn't restrict the use to official Firefox only...

**Comment by mattatobin** [comment]
https://mozilla-services.readthedocs.io/en/latest/tos.html

**Comment by wolfbeast** [comment]
We are in full compliance with that, Tobin.
