### ISSUE TITLE
Pinned tiles indicators and controls are confusing in the newtab page

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#529]
Follow-up to #525.

I found a strange issue with pinned tiles, ~some of them have pinned status and at the same time allowed to be pinned:~

![palemoon_2018-06-22_13-56-38](https://user-images.githubusercontent.com/340855/41773278-34262b96-7624-11e8-930d-0509684dbf2f.png)

~And I'm sure I did not pin any tiles at all.~

The issue is about styling, see comments below.

**Comment by JustOff** [comment]
It seems this happens after tiles drag&drop.

**Comment by wolfbeast** [comment]
I'm not sure what your issue is? youtube is marked as pinned, and the indicator top-left is blue, meaning it's pinned.

Dragging/dropping a tile pins the tile in that location -- you want it there specifically, after all.

**Comment by JustOff** [comment]
It seems I just being confused by the two absolutely equally styled indicators shown at the same time. Perhaps it's better to have them different, like in Basilisk.

**Comment by JustOff** [comment]
@Lootyhoof, what do you think?

**Comment by wolfbeast** [comment]
I have an idea already.

**Comment by wolfbeast** [comment]
![image1](https://user-images.githubusercontent.com/3359132/41775891-0cfd30a8-7626-11e8-8fbc-576e824ab79d.png)

**Comment by JustOff** [comment]
The idea is excellent! (I hope the indicator will be smaller than on the layout)

**Comment by mattatobin** [comment]
2px smaller would do it i'd say.

**Comment by wolfbeast** [comment]
![image1](https://user-images.githubusercontent.com/3359132/41778250-6c333e16-762e-11e8-8687-fb5c77ba0f28.png)

**Comment by mattatobin** [comment]
That looks right. Can you nudge the text up a couple of pixels?

**Comment by JustOff** [comment]
Sorry for the pickiness, but this seems even better:
```
.newtab-site[pinned] .newtab-title::before {
   left: 5px;
   top: 3px;
}
```
![palemoon_2018-06-22_18-19-52](https://user-images.githubusercontent.com/340855/41784650-08c5b5c8-7649-11e8-9ae1-ee9bb15b9eb4.png)
instead of
```
.newtab-site[pinned] .newtab-title::before {
   left: 2px;
   top: 2px;
}
```
![palemoon_2018-06-22_18-20-28](https://user-images.githubusercontent.com/340855/41784659-0d529bc4-7649-11e8-9cf1-5d899021e38e.png)

**Comment by wolfbeast** [comment]
Sorry but I disagree. The indicator should not take any more horizontal space than it has to.
