### ISSUE TITLE
Toolkit - "Create a New Profile" throws an error

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#531]
__Steps to reproduce:__
Go to `about:profiles`
Click on `Create a New Profile`
Click on `Next`
Click on `Choose Folder...`
Click on `Storno`

Throws an error in Browser Console:
```
TypeError: newProfileRoot is null  createProfileWizard.js:102:1
```

**Comment by wolfbeast** [comment]
So, does it actually create a profile if you choose but actually don't choose anything else?

**Comment by janekptacijarabaci** [comment]
Yes, there's no need to choose something.
