### ISSUE TITLE
Make "about:webrtc" dependent on build config.

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#536]
__Steps to reproduce:__
Go to `about:webrtc`

Throws an errors in Browser Console:
```
ReferenceError: WebrtcGlobalInformation is not defined  aboutWebrtc.js:206:1
ReferenceError: WebrtcGlobalInformation is not defined  aboutWebrtc.js:29:5
ReferenceError: WebrtcGlobalInformation is not defined  aboutWebrtc.js:34:5
```

I suggest:

- Remove JavaScript code: e.g. https://github.com/janekptacijarabaci/UXP/commit/532c1078d784e5fdb875a92606a55ff6f55cd582

or

- Remove `about:webrtc`: e.g. https://github.com/janekptacijarabaci/UXP/commit/b98bdfad92f130194e3ee3c4da8d9e14981cd9ec

Backward compatible (e.g. for extensions): My guess is that the first option is better.

Both:
I've created the new build (x32, Windows) - `Pale Moon UXP / Basilisk (--enable-webrtc)` - and tested.

**Comment by wolfbeast** [comment]
If WebRTC isn't built, then `about:webrtc` should not exist. This should include all unique files comprising `about:webrtc`, not just killing the redirector address.

**Comment by janekptacijarabaci** [comment]
OK. I leave it to you to explore this problem.

**Comment by wolfbeast** [comment]
I wish you wouldn't be so selective, but it's fine, I'm sure someone will pick it up. I have other things to do.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
[Without completely removing the suffix `webrtc` in `docshell/build/nsDocShellModule.cpp`](https://github.com/janekptacijarabaci/UXP/commit/b98bdfad92f130194e3ee3c4da8d9e14981cd9ec#diff-2535d024fda2f932a1dfd8239981c5f4)
there is this difference between e.g. `about:webrt` (which never existed) and `about:webrtc`:

`about:webrt` - throws:
```
The address isn't valid
The URL is not valid and cannot be loaded.
```

`about:webrtc` - the page remains unchanged
