### ISSUE TITLE
Tree object reports wrong selection

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#541]
Tree object used to display entries in _Show Cookies_ dialog reports wrong selection count. Due to this button to remove cookies is enabled even when there are no cookies to be removed. This is easily reproducible when there are no cookies. Just open the cookies window.
<img width="508" alt="screen shot 2018-06-24 at 1 07 39 pm" src="https://user-images.githubusercontent.com/29352104/41817216-c48c7746-7785-11e8-9816-0c6d2bd2bf01.png">
**Actually, `onselect` is fired twice for some reason, which should be an issue in itself.** In first call, count is correct (_0_), but in the immediate next call it becomes _1_. This can be checked by putting a `console.log(seln);` inside `onCookieSelected` function in `cookies.js`.
<img width="1012" alt="screen shot 2018-06-24 at 1 08 02 pm" src="https://user-images.githubusercontent.com/29352104/41817227-ef83ac1c-7785-11e8-83d8-25d600117e7d.png">
Same behaviour can be seen in _Password Manager_ also, if there are no passwords.
1. Open _Saved Logins_ window. Make sure both the remove buttons are disabled.
2. Type something in search box. Nothing major will happen.
3. _Ctrl+A_, then _Backspace_ to remove search terms.
4. Now, _Remove_ button is enabled.
<img width="607" alt="screen shot 2018-06-24 at 1 08 23 pm" src="https://user-images.githubusercontent.com/29352104/41817247-9813d60e-7786-11e8-82ee-59b4d4048ed4.png">
Both Pale Moon and Basilisk are affected.

**Comment by janekptacijarabaci** [comment]
Confirmed.

Also - `Saved Passwords` throw an error in Browser Console:
```
TypeError: table[selections[0]] is undefined passwordManager.js:236:7
```

I propose these fixes - `tree.view.rowCount` is used for everything:
https://github.com/janekptacijarabaci/UXP/commits/cookies_logins_1
