### ISSUE TITLE
Pale Moon: macOS: Private browsing indicator missing

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/UXP#553]
What it says on the tin. Private browsing windows should have a little purple indicator with a mask, but they don't. This is a default theme issue because with e.g. the XMoon theme, the indicator is present. I believe this issue began when BitVapor replaced the osx theme with all the Windows junk, see the bottom of the `browser/themes/osx/browser.css` diff [here](https://github.com/MoonchildProductions/Pale-Moon/commit/01681421e707f84319bc3fa21c8c88d6aabe4e51) and the deletion of `privatebrowsing-mask.png` and `privatebrowsing-mask@2x.png`. There is no e.g. `#toolbar-menubar` or `#appmenu-button`.

I think I can take this, so please assign me if you would.

**Comment by SpockMan02** [comment]
My bad, there _is_ a `#toolbar-menubar`—It just can't be styled because the OS handles that.

@wolfbeast There's a bit of the styling I'm restoring that uses `-moz-mac-lion-theme`. wicknix is still building for OS X 10.7; do I have your blessing to revert [Mozilla bug 1302937](https://bugzilla.mozilla.org/show_bug.cgi?id=1302937)?

**Comment by wolfbeast** [comment]
As indicated on IRC, it's fine to do that but make sure it works first.

**Comment by SpockMan02** [comment]
I got the indicator to show up properly on a local branch today, but I need to clean up the patch and will be unavailable to do so for a couple days. Expect a pull request on Sunday.
