### ISSUE TITLE
"Snap to default button" does not work.

### ISSUE THREAD

**Issue by projectBoy** [MoonchildProductions/UXP#559]
As the title says, this windows feature stopped to work in Pale Moon v22, the same as 
in Firefox v22. 
Mozilla fixed it in a version of Firefox between 48-55 (in v48 does not work, in v55 works).

**Comment by projectBoy** [comment]
I am sorry about Pale Moon v22, i was wrong.. 
I can not understand how I was confused this way..
I just finished my tests and these are the results (accurate this time): 
In Pale Moon v20.3 works, in Pale Moon v24.7.2 does not.

in Firefox v21.0 works, in Firefox v22.0 does not.
Getting the versions of Firefox between 48-55 from here: 
https://archive.mozilla.org/pub/firefox/releases/ and trying them one-by-one, 
Mozilla eventually fixed it in Firefox v55 (i have v55.0.3). 
In Firefox v54.0.1 does not work.

**Comment by wolfbeast** [comment]
Thanks, that narrows it down somewhat.

**Comment by projectBoy** [comment]
I have some more info on this issue, hopefully helpful: 
This feature was first introduce in Firefox 3.6. 
In [bug 76053](https://bugzilla.mozilla.org/show_bug.cgi?id=76053) you can see a comprehensive conversation about its implementation. 
You can see also this: [notifyDefaultButtonLoaded()](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDOMChromeWindow#notifyDefaultButtonLoaded%28%29)

Summarizing app versions:
In Firefox it works in v3.6-21, in v22-54 does not, in v55-62 it works. 
in Pale Moon it works in v3.6-20 and in v 24+ is broken.

**Comment by wolfbeast** [comment]
Thanks for the info. We'd still need to see which BZ bug fixed it for 55 though. Historic background is interesting but has little practical use here.

**Comment by SpockMan02** [comment]
Possibly [bug 1197497](https://bugzilla.mozilla.org/show_bug.cgi?id=1197497)?

**Comment by wolfbeast** [comment]
One-liner fix -- why did this survive 23 versions without getting fixed?

**Comment by wolfbeast** [comment]
Also, I'm assuming here that "does not work" means that it moves the mouse, but to the wrong location?
And you're using DPI scaling other than 100% in Windows?

**Comment by projectBoy** [comment]
I just finished some tests after reading of bug 1197497 and i think i have interesting things. 
First, yes, when i say "does not work", i mean that the mouse pointer is moved automatically, 
but not at the correct position. 

When i use windows, traditionally i use 125% of screen scaling. 
Now i tested Pale Moon v24-28 and some versions of Firefox v22+ in 100% screen scaling 
and the "Snap to ..." feature works fine! 
I also tested some Pale Moon v20 and older and some Firefox v21 and older in 150% screen 
scaling and this feature works fine always. 

I you are wondering, i have all versions of Pale Moon 2-28 and several versions of Firefox 1.5+ 
in a Sandboxie, to use in extension development. 
So, if you need any further help/info, just let me know.

**Comment by wolfbeast** [comment]
OK then this one-liner fix should resolve this issue.
