### ISSUE TITLE
JS - RegExp - match updated spec for `/\b/iu` and `/\B/iu`

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#56]
See https://github.com/MoonchildProductions/moebius/pull/81

`kIgnoreCaseWordRangeCount` isn't defined in UXP. Needs research which BZ bug this was introduced in and ported as a dependency before that PR can be ported.

**Comment by janekptacijarabaci** [comment]
[Bug 1320121](https://bugzilla.mozilla.org/show_bug.cgi?id=1320121)
