### ISSUE TITLE
Provide UI ifdef in toolkit/themes so multiple applications can use it

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#560]
As discussed, there is an issue after commit 87eaf4410455694b3337fd145d9b157c289babd5 that affects our application by breaking the new tab icons.

Since MC_BASILISK ifdef contains multiple changes unique to Basilisk it shouldn't be needed to obtain the Australis layout on other applications. One solution could be to define the layout in the toolkit so applications that need a particular base can get the right layout.

e.g. Replace MC_BASILISK with UI_AUSTRALIS on toolkit/themes/linux/global/global.css and related areas.

**Comment by mattatobin** [comment]
Is there a reason it can't be `MOZ_AUSTRALIS`? I really don't like the form of `UI_AUSTRALIS`.

**Comment by wolfbeast** [comment]
`MOZ_PHOENIX_AUSTRALIS` has no objections from me.

**Comment by JustOff** [comment]
I like the initial @mattatobin 's proposition of `MOZ_AUSTRALIS` more, it seems less confusing.

**Comment by wolfbeast** [comment]
`AUSTRALIS` is unique enough that it doesn't need `PHOENIX` -- and prevents an overly long define ;) so, no objections to that either.

**Comment by mattatobin** [comment]
Alright ;) MOZ_AUSTRALIS it is then.

**Comment by mattatobin** [comment]
@g4jc When this is merged you will want to add `MOZ_AUSTRALIS=1` to your `confvars.sh`

and the following to your application specific `configure.in`:
```
AC_DEFINE(MOZ_AUSTRALIS)
AC_SUBST(MOZ_AUSTRALIS)
```

These patches should also fix some issues you may have been encountering.. Namely lack of invoking the migrator's password import function AND the customizableUI features of devtools such as not adding the Developer Tools icon to the hamburger menu.

**Comment by JustOff** [comment]
It seems this requires CLOBBER.

**Comment by mattatobin** [comment]
Shouldn't..

**Comment by JustOff** [comment]
At least in my case `mach build` didn't pick these changes for either Pale Moon or Basilisk.

**Comment by mattatobin** [comment]
I have issued a patch that SHOULD remedy that.
