### ISSUE TITLE
Add back the "blank out" option for about:newtab

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#563]
As per IRC discussion, follow-up to #517 -- bring back the (rather redundant) option to blank out the newtab page with a control top-right.

**Comment by JustOff** [comment]
Just in case, it would be nice if you use the same string names as before. i.e.:
https://github.com/MoonchildProductions/UXP/blob/49ee0794b5d912db1f95dce6eb52d781dc210db5/application/palemoon/locales/en-US/chrome/browser/newTab.properties#L8-L9

**Comment by wolfbeast** [comment]
... there aren't any strings attached to it.
