### ISSUE TITLE
Widevine/EME needs support for sbgp and sgpd

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#575]
Some Widevine videos fail to play for us.
It looks like this is happening because the video has a default key which should be overridden by the key in the sgpd box but isn't, because we don't parse sgpd at the moment.

To be able to properly play back Widevine files that don't supply the key in the sample header, we need to extend our support with sbgp and sgpd as specced in https://www.w3.org/TR/eme-stream-mp4/#detect-encrypted-blocks (ISO-14496-12 Section 8.9.2.3 and 8.9.4)

See also: [Bug 1318792](https://bugzilla.mozilla.org/show_bug.cgi?id=1318792) - [Widevine] Widevine encoded content not working in Firefox (works in Chrome)
We probably also need [this bugfix](https://bugzilla.mozilla.org/show_bug.cgi?id=1387798)

@trav90 when you get back after your holiday, maybe you want to have a look at this? You're still our media expert after all ;)

**Comment by trav90** [comment]
Yup I will definitely have a look once I get back.

**Comment by trav90** [comment]
Adding support for sgpd and sbgp boxes exposes an issue with our ByteReader (which was fixed by Mozilla in the extra [bugfix](https://bugzilla.mozilla.org/show_bug.cgi?id=1387798) mentioned above). However, this is involved enough that I'm going to split it out its own issue.

**Comment by trav90** [comment]
I have tested general EME playback (using YouTube's EME conformance tests) and no issues were seen so I will be submitting a PR for this, However, I do not have a way to test this specific functionality. The URL's contained in the linked Mozilla bugs for reproducing/testing are no longer valid, and I've been unable to find any test cases for sbgp or sgpd boxes searching with DDG.

**Comment by wolfbeast** [comment]
> I do not have a way to test this specific functionality. The URL's contained in the linked Mozilla bugs for reproducing/testing are no longer valid

Well, shit. How are we going to verify this even works, now?

**Comment by Gpower2** [comment]
This link: https://shaka-player-demo.appspot.com/demo/
still works, however, in PaleMoon 27.9 does not fill the combo with the assets.
In Chrome and in Firefox (61.0.1) it works as expected.
For example this asset: 
https://shaka-player-demo.appspot.com/demo/?#asset=https://content.uplynk.com/1eb40d8e64234f5c9879db7045c3d48c.mpd?ad=cleardash&rays=cdefg;lang=el-GR;logtoscreen;vv;play;build=uncompiled

should be good for testing since it says it contains multi periods with encrypted and unencrypted content.

**Comment by wolfbeast** [comment]
Unfortunately the multi-periods one doesn't use these boxes afaict and just uses MSE-stream switching (right, @trav90 ?)

**Comment by trav90** [comment]
@wolfbeast afaict that is correct.

**Comment by wolfbeast** [comment]
I haven't been able to find anything else that uses these boxes, so I'm going to assume this is fixed and closing this issue. It's obviously not used a lot -- probably an understatement -- and this code _should_ work as-is. I'll leave the verification needed label on it for potential future verification "just in case".
