### ISSUE TITLE
Get rid of rust

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#58]
We'll never use Rust components in UXP, so we need to get rid of what is weaved into the tree:

- [x] MOZ_RUST_MP4PARSE and MP4 parser components
- [x] MOZ_RUST_URLPARSE and URL parser components
- [x] Rust NSString replacement
- [x] MOZ_RUST build system and rust compiler, etc.

**Comment by joey04** [comment]
Remove `.cargo` in repo base dir too?
