### ISSUE TITLE
Prevent suppressing executable warnings using the "don't ask me this again" checkbox.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#581]
Launching executable files from extensions or the download manager is handled 1 of 2 ways:
- For .exe files, the OS prompts the user for confirmation
- For associated executable files (scripts, jars, macro files, etc.) the browser prompts the user for confirmation.

The second option has always had a one-shot checkbox to "not ask me this again" which would from that moment forward give a blanket waiver to all associated executables from all sources and of all types. That's dangerous (especially when launched from extensions).

A more complex solution (e.g. blocking from add-ons and if there's potential confusion about file type but allowing suppression from interaction with the browser by the user) would be perfect, but for the time being disallowing to suppress is the best option.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
