### ISSUE TITLE
Pale Moon: macOS: Caption buttons placed incorrectly in application-drawn titlebar

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/UXP#586]
Now that the titlebar is back with lightweight themes, and private browsing windows have caption buttons (#585, #588)...

<img width="1080" alt="screenshot 2018-07-03 01 53 23" src="https://user-images.githubusercontent.com/11634417/42235929-c8ba3208-7ee8-11e8-9582-3b4f856e6341.png">

Correct positioning is on the left of the titlebar, not the top-right. I've been able to move them to the bottom-right with CSS, but that's still wrong and I haven't figured out how to fix it properly.

**Comment by Lootyhoof** [comment]
The XUL for this is mainly for Windows, so you can at least fix the caption buttons like this:

````
#titlebar-spacer {
  display: none;
}

#titlebar-buttonbox-container {
  margin-left: 7px;
  margin-top: 3px;
}
````
I've not tested this fully though.

I'm not sure about the title text though - it's not possible to use the selector in use on Windows for this, and as far as I know there's nothing else suitable.

**Comment by SpockMan02** [comment]
Silly me, I didn't even notice the missing window title.

Thanks for the CSS! I anticipate more old Firefox + DOMi in my future. ;)

**Comment by wolfbeast** [comment]
Don't worry about the missing window title.

**Comment by wolfbeast** [comment]
Yeah just `#ifdef` in browser.xul -- it's the simplest solution and avoids unnecessary xul structures that are never used.

**Comment by wolfbeast** [comment]
Changes to browser XUL, might need theme changes?
