### ISSUE TITLE
[Regression] [Pale Moon] Save password popover lacks key icon

### ISSUE THREAD

**Issue by mrnhmath** [MoonchildProductions/UXP#593]
![cj](https://user-images.githubusercontent.com/13562431/42293343-e8c2ab94-7faf-11e8-8b96-a323400db91d.png)

**Comment by Lootyhoof** [comment]
Confirmed, this happens in both default and third-party themes. Looks like `.popup-notification-icon[popupid="password-save"]` changed to `.popup-notification-icon[popupid="password"]` in the backend with our shift to UXP.

I'll take this.
