### ISSUE TITLE
nsIContentPolicy.shouldLoad getted the node parameter with null

### ISSUE THREAD

**Issue by fdsc** [MoonchildProductions/UXP#600]
It seems the defect https://github.com/MoonchildProductions/moebius/issues/181 has reappeared.

**Comment by wolfbeast** [comment]
@janekptacijarabaci you tackled this last time, and it doesn't look like the changes done to möbius will graft to UXP. Could you port this?

**Comment by janekptacijarabaci** [comment]
It was added:
https://github.com/janekptacijarabaci/UXP/commit/ccbd5ecf57fcd53ac8b28ddf7466b6c930f764df
But there is one omission... (but I don't know, if it's that sufficient patch... - in every way, I don't know anything else)...

**Comment by wolfbeast** [comment]
which part is omitted?

**Comment by janekptacijarabaci** [comment]
https://github.com/MoonchildProductions/UXP/pull/601

**Comment by wolfbeast** [comment]
Wait, I'm confused now.
You said "it was added" but that links to a commit in your forked tree. Was it added to our repo or not, and if so, where?

**Comment by wolfbeast** [comment]
OK, so we got this in commit ccbd5ecf57fcd53ac8b28ddf7466b6c930f764df in April.

**Comment by janekptacijarabaci** [comment]
> to a commit in your forked tree

I'm sorry.
