### ISSUE TITLE
Privacy possum query

### ISSUE THREAD

**Issue by FrostKnight** [MoonchildProductions/UXP#621]
that I know of, yet it doesn't work in the linux 64 bit version. Weird yes?

I just tried to install it on windows 64 bit and it worked. But on linux 64 bit it doesn't. 

Cannot say what happens with 32 bit, but it is peciular.

PS, thank you for this wonderful browser.

**Comment by wolfbeast** [comment]
If you want to discuss extension compatibility/development, please go to [the forum](https://forum.palemoon.org/)
