### ISSUE TITLE
aAddon.markAsSeen is not a function newaddon.js

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#634]
```
TypeError: aAddon.markAsSeen is not a function newaddon.js:87:48
```

Tag:
https://github.com/MoonchildProductions/UXP/commit/bde02587cd2733f0e423c46989e6574fd2cf0d35
and maybe also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1237820
https://bugzilla.mozilla.org/show_bug.cgi?id=1249074
(implemented `addon.seen` and `addon.markAsSeen`)

**Comment by mattatobin** [comment]
for which add-ons manager? We have two, you know.

**Comment by mattatobin** [comment]
I'll take care of it since it was my doing.

**Comment by mattatobin** [comment]
And... FIXED..

@janekptacijarabaci Take note. This is how issues are supposed to be handled. If you had not asked you would have potentially spent time to create a pull request with code we didn't want or need.

There is a method to my rational insanity, you know ;)
