### ISSUE TITLE
WebGL2 after the flood demo intermittently crash Nvidia drivers

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#635]
WebGL2 after the flood demo causes Nvidia driver crash on "compiling shaders" part intermittently on UXP platform and also on Firefox ESR 52. Other times it works fine without any issues.

Operating System: Windows 7 x64

Nvidia drivers version:

24.21.13.9811

https://byumjin.github.io/The-Shrines/

This game demo is somewhat similar but not quite same as after the flood demo and does not crash Nvidia drivers. Other WebGL2 games also do not crash with Nvidia drivers, only this demo does.

It also crash if you switch between settings default and ultra. It also can crash if you switch between high and ultra. All those settings work fine normally but switching between them too quickly can cause crash.

This is deep rooted problem in Mozilla codebase since I tested some other versions with mozregression and ever since this WebGL2 demo was working with Firefox it causes same crash. It also crashes on nightly 63.0a1 (2018-07-05) (64-bit).

This is not related to angle rollback done on UXP recently as like I said it can be reproduced ever since this demo worked on Firefox with WebGL2.

Changing settings to:

webgl.disable-angle;true
webgl.bypass-shader-validation;true

This stops crashes but causes ocassional blinking shadow at demo. It is Angle/Nvidia drivers not working well together for some reason and native opengl works after webgl.bypass-shader-validation;true.

On Mozilla nightly build there is failure log which has information after crash happened that could help troubleshooting as this issue has been on Mozilla codebase for long time with Nvidia drivers and this particular WebGL2 demo only.

Failed to create Pbuffer surface error: 0x300e Size : Size(1920,966)
Invalid canvas front buffer or screen

Crash doesn't happen in non-Mozilla based browsers that also use angle. I tested on chromium with this same WebGL2 demo and there is no drivers crash so it's Mozilla-based browsers problem.

**Comment by wolfbeast** [comment]
There is no point in reporting this here. If the driver crashes, then the driver needs to be fixed.

**Comment by mattatobin** [comment]
And Angle is google technology.
