### ISSUE TITLE
Acid3 test - Fail!

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#636]
Pale Moon UXP fails the Acid3 test (varies between 98/100 and 99/100):
`http://acid3.acidtests.org/`

(Pale Moon v28.0.0b3,x64 2018-07-08 / Win8.1Pro,x64)

**Comment by kn-yami** [comment]
I can confirm this. Test 35 will always fail. Test 72 will fail sometimes.
Errors reported by the test itself:
```
Test 35 failed: expected '0' but got '1' - root element, with no parent node, claims to be a :first-child
Test 72 failed: expected '10' but got '19' - prerequisite failed: style didn't affect image
```
It is probably worth noting that test 72 will also sometimes fail in Tycho.

**Comment by Lootyhoof** [comment]
These tests are very old, the web has changed a lot since then.

Other browsers also fail this test.

**Comment by wolfbeast** [comment]
Not an issue. standards do change and have changed.

Quote from the very page this test is on:
"Acid3, in particular, contains some controversial tests and no longer reflects the consensus of the Web standards it purports to test"

So, some tests are expected to fail in 2018 (as opposed to 2008 when this test was published)

**Comment by wolfbeast** [comment]
As a side note: I appreciate you wanting to give this as much of a workout as possible, but please do keep context and perspective in mind. The browser failing a test isn't necessarily a bad thing -- same with HTML5test; we will never score full marks there because we exclude some things for a good reason.

**Comment by mattatobin** [comment]
Also, please stop creating bugspam. Use the forum. We will decide if it needs to have an issue created or not.
