### ISSUE TITLE
Add "media playing"/"mute" indicator/control to tabs

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#638]
As a requested enhancement, with UXP we now have the ductwork to detect media playing in tabs, and an indicator/control to display a tab's media playing state/muting capability should be fairly straightforward to hook up in Pale Moon's front-end.

This will touch a number of things though, since we're adding a control to the tabs, adding an indicator, themes will have to be adjusted. New graphics in line with Pale Moon's theme are needed (SVG)

**Comment by wolfbeast** [comment]
@FranklinDM if you take an issue to work on, please let us know when you start on it, especially if more involved, so we can avoid double work being bone by people working on the same issue unbeknownst to each other? Just a comment on an issue that you'll be "taking this" is fine, but communicate it, please :)

**Comment by FranklinDM** [comment]
I'm sorry for that, will make sure to do so next time.

**Comment by mattatobin** [comment]
Would it make a difference if I said I was against this feature being added?

Simply because we already have an extension that easily adds this to Pale Moon if desired.

**Comment by wolfbeast** [comment]
To be fair, I have not looked in detail at the extension. If it is the complete works as it seems to be (without the all tabs icons though...) and fully compatible with Pale Moon 28 (compatibility seems to be indicated as v27 max?) then that does make this less desirable of an issue to be solved.

How well does the extension perform; performance impact, response times, latency between media playing and being muted or media playing and the indicator being updated, muting capabilities? What are the notable differences between the extension and the ported Mozilla solution? Are there known limitations to the extension or the built-in solution?

**Comment by FranklinDM** [comment]
> The extension works only with HTML5 media elements. **Flash is not supported.**
- The in-browser solution can mute flash with audio. (i.e. [Hello, Fred The Beard](https://www.albinoblacksheep.com/flash/hellofred))
- It had conflicts with certain pages. (wsdfhjxc/expose-noisy-tabs#7)
- If I remember it correctly, the extension inserts itself as a script to every page visited and uses a mutation observer to observe audio changes.

**Comment by JustOff** [comment]
I'm not sure we need to take special care of Flash, but using the API, natively provided by the platform, rather than mutation observer scripting hack, definitely seems like a better way to handle such things.

**Comment by JustOff** [comment]
> The built-in solution can mute flash with audio. (i.e. [Hello, Fred The Beard](https://www.albinoblacksheep.com/flash/hellofred))

I applied your PR, but it does not mute the sound here when I click on the indicator.

**Comment by mattatobin** [comment]
My stance is this.. I would not like to see feature creep in Pale Moon. We have enough lingering issues from the twice over port of Pale Moon up the line.

Adding new features should be limited to simple bits and bobs until all the remaining issues are solved.

Additionally, this being a complex piece of work is yet another maintenance burdon at a time where bustages and flaws real or perceived aren't being taken so kindly by the userbase.

On top of all that I personally still don't want it. For what ever that counts for.

**Comment by FranklinDM** [comment]
@JustOff Flash muting seems to works fine in my end.

**Comment by JustOff** [comment]
@FranklinDM, are you sure you get the flash player on this page? For example, in Firefox 63, where by default Flash plugin is set to "Ask to activate", the video is processed using html5 and so can be muted, but if you set Flash player to "Always activate", then Firefox can't mute it too. Perhaps Flash can't be muted this way at all?

**Comment by mattatobin** [comment]
Pref controlled eh? I can live with that then.

**Comment by FranklinDM** [comment]
However, the pref doesn't hide the context menu item for muting a tab and doesn't disable the hotkey (Ctrl+M).

I can extend that pref to also hide and disable those features if desired.

**Comment by mattatobin** [comment]
Make it so that it all bypassed when disabled, please.

**Comment by FranklinDM** [comment]
Done with af0164310dd94e24bf7b44ebb6d9b146eb5db241. I used the same preference for controlling this behavior.

**Comment by wolfbeast** [comment]
@JustOff there are a few string changes involved (tooltips only AFAICT).

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

PS: Could you please bump the version on master to 28.3.0a1 to avoid issues with LP betas?

**Comment by bogachenko** [comment]
Why is she white? @JustOff  @wolfbeast theme standard (for win 10), version of 28.3.1
![default](https://user-images.githubusercontent.com/8535285/51721660-a4704280-204a-11e9-8374-315a70c31ce4.png)

**Comment by wolfbeast** [comment]
@bogachenko Please open a new issue. That's likely a bug because of the Windows accent color being considered dark and needing white text and icons otherwise.
