### ISSUE TITLE
Flex/grid spec change for relative computed properties.

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#649]
Ad https://forum.palemoon.org/viewtopic.php?f=63&t=19692

__Examples:__
https://www.real.video/5810872932001
https://www.real.video/5811441940001

> The video's don't show at all.
> It seems like it's playing as I can hear the video but I cannot see it nor does it show any video frame.

__Pushlog:__
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=d2b86105593665fb53ea47b4a1934404474d94b2&tochange=62e956da98b9b145347f5658aa48697921e54d5d

__A suggestion of PR:__
[css_layout_flex-grid_1](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:css_layout_flex-grid_1)

__Based on:__
https://bugzilla.mozilla.org/show_bug.cgi?id=958714

**Comment by wolfbeast** [comment]
Changes merged, please verify.
