### ISSUE TITLE
Fix ByteReader's error checking for MP4 files

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#654]
ByteReader doesn't always return an error when parsing files, which can result in assertions and or hangs/crashes.

Unfortunately ByteReader is used _everywhere_ in the media subsystem, so it's no small task to fix. This problem is predominately only with MP4 files, so this issue is about fixing ByteReader's error checking when parsing MP4 files only. Fixing it for other formats can be evaluated later if need be.

Blocks #575.

**Comment by wolfbeast** [comment]
Verification needed, see comment in PR #665

**Comment by JustOff** [comment]
> I've tested this (MP4, MSE+MP4, EME+MP4, and WebM/VP9 just in case)

How can I test EME+MP4 on Win?

**Comment by trav90** [comment]
Compile with EME enabled.

**Comment by JustOff** [comment]
Well, then I probably leave EME check for someone else. 

MP4, MSE+MP4 and WebM/VP9 seems work just fine on Win.

**Comment by wolfbeast** [comment]
I'll make a fresh build of Basilisk (that has EME enabled) and test EME+MP4

**Comment by wolfbeast** [comment]
Basilisk built, verified with AMP using PlayReady and Widevine, both auto DASH and progressive MP4. Everything seems to be working in that respect.
