### ISSUE TITLE
[PALEMOON] Permissions Manager - the box/content size should be constant

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#660]
If the content is less than the height screen - it would change the size of the box between `All Sites` and [a site].

__A suggestion of PR:__
[pm_permissions-manager_css_content_1](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:pm_permissions-manager_css_content_1)

**Comment by wolfbeast** [comment]
Doesn't make sense that you're using vh in your code.

**Comment by janekptacijarabaci** [comment]
I do not know another solution...

**Comment by wolfbeast** [comment]
Well, do some research then.

**Comment by wolfbeast** [comment]
You know what, I'll take this otherwise it'll just go stale like other half-done issues.
