### ISSUE TITLE
WebGL2 gpu instancing crash

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#668]
There is recently one WASM/WebGL2 game that crashes in UXP.

Using Mozregression I was able to find what is fix to one webgl2 game that is crashing.  

https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=194be07f3d4b8a5988e730eb984eaf5c87685782&tochange=8adf0199bc28eae9dc2dbb07e927d420b094316c

https://files.unity3d.com/marcot/instancing/ 

that is test link in bugzilla bug that also crashes in UXP. 

Fixed by:

https://bugzilla.mozilla.org/show_bug.cgi?id=1405600

This should be backported to UXP.

**Comment by janekptacijarabaci** [comment]
With `mProgram->assignUniformBlockRegisters();` it does not crash anymore.
But maybe it's not enough - it's just information...

**Comment by wolfbeast** [comment]
I'm not sure what you're talking about -- the bug pointed to doesn't mention anything about `assignUniformBlockRegisters()` in its patches that I can see. Please explain in detail.

**Comment by janekptacijarabaci** [comment]
It's just an attempt:
[_testBranch_angle_crash](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:_testBranch_angle_crash)
because `ensureUniformBlocksInitialized()` doesn't exist in this version.

**Comment by wolfbeast** [comment]
Well that's because it was renamed.
A bit of research would have shown you this: https://hg.mozilla.org/mozilla-central/diff/fa4b8dca11bb/gfx/angle/src/libANGLE/renderer/d3d/ProgramD3D.cpp#l1.1815
