### ISSUE TITLE
Performance - "secureConnectionStart" should be 0 for http

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#67]
__Suggestions:__

Split out 1st point to separate issue #69 

#### 2) `secureConnectionStart` should be 0 for pages with HTTP scheme - [bug 1417431](https://bugzilla.mozilla.org/show_bug.cgi?id=1417431)

An example:
http://www.palemoon.org/
and in Web Console:
`console.log(performance.timing);`
`console.log(performance.timing.secureConnectionStart);`

Actual results:
```
PerformanceTiming { navigationStart: 1521247522419... }
1521247522419
```

Expected results:
```
PerformanceTiming { navigationStart: 1521247522419... }
0
```

~~__Some test/personal branch:__~~
~~[tree@js_dom_performancetiming_resolution_1](https://github.com/janekptacijarabaci/UXP/tree/js_dom_performancetiming_resolution_1)~~
~~(I've created the new build (x32, Windows) and tested)~~

~~I can divide it into two PRs (or do only one PR).~~

**Comment by wolfbeast** [comment]
Yeah the timer clamping should have been used there. Doesn't look like Mozilla was consistent there either.

Please make it 2 PRs, they are not related so should be separate commits/merges
