### ISSUE TITLE
Possible thumbnail generation issue

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#670]
Using Pale Moon beta on Linux.
Following is printed on the command line:

```
*************************                                                       
A coding exception was thrown and uncaught in a Task.                           
                                                                                
Full message: TypeError: invalid arguments                                      
Full stack: Storage_writeData@resource://gre/modules/PageThumbs.jsm:612:13      
PageThumbs__store/<@resource://gre/modules/PageThumbs.jsm:454:13                
TaskImpl_run@resource://gre/modules/Task.jsm:319:42                             
TaskImpl@resource://gre/modules/Task.jsm:277:3                                  
asyncFunction@resource://gre/modules/Task.jsm:252:14                            
Task_spawn@resource://gre/modules/Task.jsm:166:12                               
PageThumbs__store@resource://gre/modules/PageThumbs.jsm:452:12                  
_done@resource://gre/modules/BackgroundPageThumbs.jsm:475:7                     
notify@resource://gre/modules/BackgroundPageThumbs.jsm:428:5                    
                                                                                
*************************
```

**Comment by wolfbeast** [comment]
Hmm that would probably be because we're trying to write a null file (since de85309fb), but `new Uint8Array(aData)` doesn't accept `null` for `aData` (that's new in the ES2017 spec).

**Comment by wolfbeast** [comment]
Solution: patch this with a `try/catch`, and follow-up with implementing ES2017's (Draft spec) allowance for `new Uint8Array(aData)`.

**Comment by Gpower2** [comment]
Why not use a placeholder image data?

**Comment by wolfbeast** [comment]
Placeholder was already planned, see the commit I linked to. Just needs a small png encoded the right way to drop in there.

**Comment by wolfbeast** [comment]
Possible placeholder solution in https://github.com/MoonchildProductions/UXP/commit/19b35e92511718fb5cfe653df535e072c7ccd748

Considering my severe lack of sleep at the moment I have no idea if this works XD feel free to try/improve/etc.

**Comment by wolfbeast** [comment]
@adeshkp Can you please try building commit 1de0d64e0f08d3cc3d3970666126aff33eb06115 and see if that actually saves placeholder images for thumbnails?

**Comment by adeshkp** [comment]
https://github.com/MoonchildProductions/UXP/commit/19b35e92511718fb5cfe653df535e072c7ccd748 does not build. Gives this:
```
 3:40.22     raise Preprocessor.Error(self, 'FILE_NOT_FOUND', str(args))
 3:40.22 mozbuild.preprocessor.Error: ('/home/admin/labs/UXP/toolkit/components/thumbnails/PageThumbs.jsm', 32, 'FILE_NOT_FOUND', '/home/admin/labs/UXP/toolkit/components/thumbnails/"blankthumb.inc"'
```

I think you need to remove double quotes around `blankthumb.inc`:
`#include "blankthumb.inc"` should be `#include blankthumb.inc`

**Comment by wolfbeast** [comment]
No, you probably verified e437d80133c96096460bf9418f17f25a65a2db46 (on master) or you would have run into the same build error as you did now (commit is on a separate branch). Can you please check if 9fc1381e11a0a6adcd3be93b1d0524fd5336282b fixes all issues?

**Comment by adeshkp** [comment]
Yes, all issues seem to be fixed. Thumbnails get generated and console is clean.

There is a related issue which might be filed separately. Image generation stops at first "error" (for example due to redirect for _start.palemoon.org_) if I clean all thumbnails and relaunch the browser. In this case, thumbnails for websites after _start.palemoon.org_ remain empty unless visited again manually.

**Comment by wolfbeast** [comment]
They will probably remain empty "for a while" but should eventually be filled in. Either way if that's an issue then it should be a follow-up.
Closing this one.

**Comment by wolfbeast** [comment]
Automated tests aren't guaranteed to work or pass since we don't really use them and in general it's a lot of extra overhead to update them every time a line of code changes. Thanks for the report though I'll see if I can fix it up.

**Comment by wolfbeast** [comment]
I don't see a quick way to fix this test and it should be removed. The internal thumbnail placeholder has no leaf name and that is what it will default to on error of the test. Basically that part of the test is no longer relevant because the thumbnail will "never fail" now.
