### ISSUE TITLE
[Windows] "about:profiles" - "Launch profile in new browser" doesn't work

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#673]
__Steps to reproduce:__
Go to `about:profiles`
Click on `Launch profile in new browser` (another profile)
...and we are still running the same instance.

__A suggestion of PR:__
[toolkit_startup_instance-with-profile_1](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:toolkit_startup_instance-with-profile_1)

__Based on:__
[Bug 1367743](https://bugzilla.mozilla.org/show_bug.cgi?id=1367743) - About:profiles `launch profile in new browser` doesn't work

I don't know if it has any side effects though. But I do not think so.

**Comment by wolfbeast** [comment]
I'm not even sure why this is a thing.

**Comment by wolfbeast** [comment]
Just make a PR -- this is so straightforward it doesn't even need review.
