### ISSUE TITLE
Please add a section in your README.md file that shows how to build the applications

### ISSUE THREAD

**Issue by sebma** [MoonchildProductions/UXP#683]
Hi,

Thanks to @SpockMan02, I managed to build palemoon because he told me to add `ac_add_options --enable-application=palemoon` to a new `mozconfig` file and then run `./mach build`.

Can you please add this information to your README.md file so that others don't bother you with this question anymore ?

Thank you for your comprehension.

**Comment by wolfbeast** [comment]
Doesn't belong in the readme for UXP.
Build instructions are in several places (developer wiki, forum, ...
