### ISSUE TITLE
[suggestion] about:support - more information about graphical parameters

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/UXP#687]
__I suggest adding:__
`Driver Version`
`Driver Extensions`
`Extensions`
`Driver WSI Info`

__Based on:__
[Bug 1335296](https://bugzilla.mozilla.org/show_bug.cgi?id=1335296) - Provide more information in about:support
[Bug 1341957](https://bugzilla.mozilla.org/show_bug.cgi?id=1341957) - Add webgl.getSupportedExtensions() to about:support

__A suggestion of PR:__
[about-support_WebGL-information_expand_1](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:about-support_WebGL-information_expand_1)

It could sometimes help when there are problems. Maybe.

**Comment by wolfbeast** [comment]
It could sometimes help if you actually also make a PR if you've already done the coding. Maybe.

**Comment by janekptacijarabaci** [comment]
Unfortunately, it is not quite clear to me - with these comments:
https://github.com/MoonchildProductions/UXP/pull/630#issuecomment-404574512
https://github.com/MoonchildProductions/UXP/pull/630#issuecomment-404677681
https://github.com/MoonchildProductions/UXP/issues/634#issuecomment-404909925
Can you please give a brief explanation?

But I will do a PR now.

And I don't know if it is related to this label (`Issue with code work but no PR`):
https://github.com/MoonchildProductions/UXP/labels/PR%20requested

**Comment by JustOff** [comment]
Just out of curiosity, can anyone give an example for what these data might be needed? 

> GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object 

For me they look like some sort of cipher message :alien:

**Comment by janekptacijarabaci** [comment]
I do not have such an example. However, you have a completely different list.

https://www.khronos.org/opengl/wiki/OpenGL_Extension
> OpenGL extensions are a means for OpenGL implementations to provide new or expanded functionality that the core of OpenGL does not provide.
and
https://www.khronos.org/registry/OpenGL/index_gl.php

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
