### ISSUE TITLE
Support spaces in Mac app name

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/UXP#701]
Until [27.7.0](https://forum.palemoon.org/viewtopic.php?f=41&t=18047), sugis' Pale Moon builds were called Palemoon, and since then, it's been NewMoon. For #689, we want Pale Moon, not PaleMoon. Apparently Mozilla [changed Nightly to Firefox Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1378834) a few months ago, and this had [some](https://bugzilla.mozilla.org/show_bug.cgi?id=1404717) [issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1404796).

I think we want to port:
- [Bug 1407285 - Support spaces in MOZ_MACBUNDLE_NAME](https://bugzilla.mozilla.org/show_bug.cgi?id=1407285)
- [Bug 1424098 - Support spaces in MOZ_MACBUNDLE_NAME when signing packages.](https://bugzilla.mozilla.org/show_bug.cgi?id=1424098)
- [Bug 1424294 - Also manage spaces in tools/update-packaging/common.sh](https://bugzilla.mozilla.org/show_bug.cgi?id=1424294)
- [Bug 1404796 - On mac, the app name is "FirefoxNightly" when it should be "Firefox Nightly"](https://bugzilla.mozilla.org/show_bug.cgi?id=1404796)

**Comment by wolfbeast** [comment]
What's the status of this? Is this ready to be used, and if so, could you make a PR?

**Comment by mattatobin** [comment]
I'd say it is abandoned cause he doesn't exist anymore.

**Comment by wolfbeast** [comment]
Not very helpful for moving this forward
if it is an issue then it should be fixed before we publish official Mac builds

**Comment by mattatobin** [comment]
@wicknix @adeshkp

**Comment by wicknix** [comment]
Done. PR sent.
![space](https://user-images.githubusercontent.com/39230578/61433788-d677a880-a8f9-11e9-91fb-f747bc9a0e60.png)

**Comment by adeshkp** [comment]
> @wicknix @adeshkp One of both of you wanna look into this?

I tries @SpockFan02 PR, fixed some bitrot but still it's not usable. Build works fine, but there is an issue in "package" command. It seems there are still a few places left where the APP name needs quoting. I'll try to finish it in a day or two.
