### ISSUE TITLE
"Microsoft Print To PDF" virtual printer doesn't work

### ISSUE THREAD

**Issue by Gittyperson** [MoonchildProductions/UXP#702]
Windows 10 1803 x64 (17134.165), Pale Moon 28.0.0.b5 x64 (2018-08-01)

1. Enable Windows 10's PDF virtual printer (Turn Windows Features on or off)
2. Try to 'Print' (or Print Preview) a web page using "Microsoft Print To PDF" as printer (File/Print...)

Error Console/Errors section:

```

Error: In Printing:Print:Done handler, got unexpected rv
                        2147500037.
Source File: chrome://global/content/browser-content.js
=================================
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIPrintSettingsService.initPrintSettingsFromPrinter]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/browser-content.js :: getPrintSettings :: line 486"  data: no]
=================================
Timestamp: 09-Aug-18 16:51:14
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebBrowserPrint.printPreview]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/browser-content.js :: enterPrintPreview :: line 646"  data: no]
```

**Comment by Ascrod** [comment]
I do not see this issue on my Windows 10 machine. Print and Print Preview with this issue page using MS Print to PDF both work for me, with no errors in the console.
Windows 10 1803 x64 (17134.167)
Pale Moon 28.0.0b5 (64-bit) (2018-08-01)

**Comment by Gittyperson** [comment]
Manually installed the [17134.167](https://support.microsoft.com/en-us/help/4345421) update - problem remains.    :confused:

**Comment by Ascrod** [comment]
Does Print to PDF work in other applications on Windows 10? Are you able to print to other printers from Pale Moon?

**Comment by Gittyperson** [comment]
Works on some (Edge, IE), fails on others (Word: "_We couldn't print because there doesn't seem to be a printer installed - this error can appear if a default printer has not been designated or if the application is unable to locate an existing default printer_."

Other printers work fine on Pale Moon.

**Comment by wolfbeast** [comment]
Sounds like Microsoft screwed up their PDF printer then.
Closing this -- nothing we can do about it.

**Comment by Gittyperson** [comment]
I restored an earlier Windows backup and it now works... (Windows has auto-updated to 17134.191).
