### ISSUE TITLE
crash: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jerome-diver** [MoonchildProductions/UXP#703]
antergos distribution: kernel-4.17.13-arch1-1-ARCH x86_64
strace basilisk:
https://ptpb.pw/2AcJ

latest "stable" source downloaded from your own web site.

but also, the latest version was working, it is after update the kernel that segmentation fault happened, so it is not directly due to your code, but it should have something to update inside.
I also see that basilisk is going to try to find things in my HDD where it is not located (tls)...

good luck...

**Comment by wolfbeast** [comment]
Your strace won't load (the URL gives back 0-length content).
You'll also have to provide information how exactly you built from source -- and have you tried using the official binaries?

**Comment by Bfgeshka** [comment]
Also having this issue. Linux, palemoon 28.0, self compiled and from tarballs.

Segfaults are happening in specific moments, for example:
- Trying to load animated gifs
- Trying to load h264 videos
- In menu: Help / Troubleshooting inforbation

May provide strace later if needed, or any library version information.

**Comment by wolfbeast** [comment]
You'll also have to provide information how exactly you built from source -- and have you tried using the official binaries?

**Comment by Bfgeshka** [comment]
I told you I did:
> and from tarballs

So it's not fault of configuration flags or compiler.

**Comment by wolfbeast** [comment]
"and from tarballs" really doesn't say much :) the source is also supplied as a tarball.

In any case, a stack trace and exact code crash point would certainly help.

**Comment by Bfgeshka** [comment]
Here's strace of my binary: https://gist.github.com/Bfgeshka/d78123633bb15009a17476a67952c5f4

**Comment by wolfbeast** [comment]
I'm sorry but I don't know how to interpret that. What I'm looking for is a stack trace (call stack) of the crash you experience, not an execution trace.
@trav90 maybe you can help pinpoint the cause? *nix debugging is really not my forte.

**Comment by Bfgeshka** [comment]
Sorry, I though you literally want a `strace` utility log, which is system call trace. Stack trace will be later.

**Comment by Bfgeshka** [comment]
Here\s gdb log, built with debug symbols: https://gist.github.com/Bfgeshka/61538dbd3d210a629c982fe62a6fd195

**Comment by g4jc** [comment]
@wolfbeast Bug appears to be related to the use of "mozconfig_enable jemalloc" in mozconfig. This is switched on by default in the third-party [ebuild](https://web.archive.org/web/20180907153236/https://gpo.zugaina.org/AJAX/Ebuild/39387133/View) the user is using according to the provided backtrace.
	
> Thread 1 "palemoon" received signal SIGSEGV, Segmentation fault.
> MOZ_CrashOOL (aLine=aLine@entry=3255, aReason=aReason@entry=0x555555579004 "diff == regind * size")
>    at /usr/src/debug/www-client/palemoon-9999-r3/palemoon-9999/mfbt/Assertions.cpp:33
> 33 MOZ_REALLY_CRASH(aLine);

The specific assersition has a hint on this old [mozbug](https://bugzilla.mozilla.org/show_bug.cgi?id=1182277):
> RELEASE_ASSERT(diff == regind * size);

While not a PM issue (I don't think this is being built properly, even firefox official ebuild does not use jemalloc) it could be a UXP issue.

**Comment by Bfgeshka** [comment]
Reverting from ffmpeg trunk to 3.x fixes crashes. So, it's either issue of ffmpeg itself or its support in palemoon. I'm going with the latter since with nothing else of whatever uses ffmpeg I've expierenced any crashes.

**Comment by Bfgeshka** [comment]
Excuse me if it's hard to understand in the comment above, I've replaced ffmpeg git version with ffmpeg 3.4.

**Comment by wolfbeast** [comment]
@trav90 aren't we normally using our in-tree version of ffmpeg code (which is v3.4.2, anyway)? IIRC our vpx and h.264 decoding is done with in-tree code... so, wouldn't the actual solution be to not use system libs? Or is it just glue code we're using?

**Comment by trav90** [comment]
@wolfbeast the in-tree ffmpeg code is used only for vp8/vp9 playback (http://xref.palemoon.org/uxp-trunk/source/media/ffvpx/README_MCP#6), falling back to libvpx if disabled.

Unfortunately h.264 decoding is still dependent on system-installed libavcodec.

**Comment by wolfbeast** [comment]
Right. Potentially a risky endeavor, then.

**Comment by wolfbeast** [comment]
Agreed.
