### ISSUE TITLE
Support GCC 8

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#705]
While UXP can be compiled with GCC 8 out of the box, there's a lot of warnings spewed by the compiler that need to be investigated before we can say we officially support GCC 8.

**Comment by kn-yami** [comment]
FYI an user at #palemoon reported that building Pale Moon with GCC 8.2 on Gentoo does not work.

**Comment by khronosschoty** [comment]
Can't reproduce this on Slackware.
