### ISSUE TITLE
Pale Moon ignores intl.properties settings from language packs

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#710]
As reported at [the forum](https://forum.palemoon.org/viewtopic.php?f=3&t=19932), STR:
 * Install and activate any of [the language packs](http://addons.palemoon.org/language-packs/)
 * Make sure that `chrome://global/locale/intl.properties` is overridden by the language pack
 * The `intl.accept_languages` and [other intl preferences](http://xref.palemoon.org/uxp-trunk/search?string=intl.properties&find=init%2Fall&tree=uxp-trunk) in `about:config` are not overridden

**Comment by wolfbeast** [comment]
Are you sure this is a regression?
These settings would only apply if the browser is built using a different language (which we never do), and in other cases you have to set these manually (through the UI in Preferences -> Content -> Choose your preferred language for diplaying content). That has always been the case for accepted content languages.

**Comment by JustOff** [comment]
> Are you sure this is a regression?

Absolutely, this worked just fine in Tycho.

**Comment by wolfbeast** [comment]
Hmm okay. that needs some digging then what has changed and when/why.

**Comment by wolfbeast** [comment]
Wouldn't this cause issues if you install more than one language pack or if you change `general.useragent.locale`, overwriting any custom-made settings?

**Comment by JustOff** [comment]
The problem exists with the one or multiple language packs installed. It seems that in PM28 the `libpref` started to init [the intl preferences](http://xref.palemoon.org/uxp-trunk/search?string=intl.properties&find=init%2Fall&tree=uxp-trunk) before `chrome://global/locale/intl.properties` override is done, but I'm a little stuck trying to trace this.

**Comment by JustOff** [comment]
I just checked FF ESR52 and found it has the same problem, so now there's a long road with mozregression to find when and how Mozilla broke it :angry:

**Comment by JustOff** [comment]
Last good: [51.0a1 2016.08.29](https://ftp.mozilla.org/pub/firefox/nightly/2016/08/2016-08-29-03-02-02-mozilla-central/firefox-51.0a1.en-US.win32.zip)
First bad: [51.0a1 2016.08.30](https://archive.mozilla.org/pub/firefox/nightly/2016/08/2016-08-30-03-02-01-mozilla-central/firefox-51.0a1.en-US.win32.zip)

Here [the regression log](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1a5b53a831e5a6c20de1b081c774feb3ff76756c&tochange=26e22af660e543ebb69930f082188b69ec756185), but nfortunately I do not have any idea what is the cause ...

**Comment by wolfbeast** [comment]
That regression log is huge. It needs to be reduced to find out what's the potential culprit as I didn't see anything stand out either.

**Comment by wolfbeast** [comment]
Perhaps seeing if nightly still has the issue might help, and if not, see if you can `-find-fix` it to get the other end of the bad window?

**Comment by JustOff** [comment]
Unfortunately, there are no intermediate builds within the range above available anymore, and both current nightly and ESR60 use a new type of language packs, that don't use chrome overwrite, but `manifest.json` to load things dynamically.

**Comment by JustOff** [comment]
Well, it seems the issue was fixed in FF55, so I'll try to find the other end of the bad window in 55a1.

**Comment by JustOff** [comment]
Here is the other end of the bad window:

Last bad: [55.0a1 2017.04.19](https://ftp.mozilla.org/pub/firefox/nightly/2017/04/2017-04-19-03-02-23-mozilla-central/firefox-55.0a1.en-US.win32.zip)
First good: [55.0a1 2017.04.20](https://archive.mozilla.org/pub/firefox/nightly/2017/04/2017-04-20-03-03-46-mozilla-central/firefox-55.0a1.en-US.win32.zip)

Compatible language pack to check with the above: [ru_lpack-55.x-fx.zip](https://github.com/MoonchildProductions/UXP/files/2298450/ru_lpack-55.x-fx.zip) (only locale global included)

[The regression log](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=bb38d935d699e0529f9e0bb35578d381026415c4&tochange=27311156637f9b5d4504373967e01c4241902ae7), which still doesn't help me very much ...

**Comment by JustOff** [comment]
Well, it seems [the bug 1356066](https://bugzilla.mozilla.org/show_bug.cgi?id=1356066) is the candiadate, I'm going to check it.

**Comment by wolfbeast** [comment]
> Especially since JS Context is initialized very early, we do end up with it having the default locale not reflecting current UI locale.

That does sound like what's going on, especially with what you said about a race condition because it would be dependent on how quickly JS Context is done initializing.
You may also want to look at the blocking [bug 1344355](https://bugzilla.mozilla.org/show_bug.cgi?id=1344355) that seems to describe pretty accurately what happens here, with the same STR as what caused this issue to be filed.

**Comment by Vangelis66** [comment]
Fortunately, the five years I've spent as a Firefox Nightly tester (on this Vista laptop) have taught me things... 

@JustOff wrote: 

> Last good: **51.0a1 2016.08.29**
> First bad: **51.0a1 2016.08.30**
> (snip)
> Here the **regression log**, but unfortunately I do not have any idea what is the cause ...

@wolfbeast wrote: 

> That regression log is huge. **It needs to be reduced to find out what's the potential culprit**

@JustOff wrote: 

> Unfortunately, **there are no intermediate builds within the range above available anymore**

Well, that claim is fortunately _**not true**_; here's how I did things back at my time:

1. buildID of last-good-build is **20160829030202** (from [here](https://ftp.mozilla.org/pub/firefox/nightly/2016/08/2016-08-29-03-02-02-mozilla-central/firefox-51.0a1.en-US.win32.txt)); this is PDT, i.e. UTC-0700; so, buildID=**20160829100202 UTC** => unix timestamp=**1472464922** 
2. Simirarly, buildID of first-bad-build is **20160830030201** (PDT) = **20160830100201 UTC** => unix timestamp=**1472551321**

Mozilla provide interim builds to the "nightly/mozilla-central" (simply **m-c**) repo inside their **tinderbox-builds** repo; for win32 builds, this is the link 

`http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/`

**WARNING**: Please be patient with that URL; your browser might require quite a lot of time to load it fully, 
during which it might show non-responding messages - disable your AV/ad-blocker, close any other not needed tab and be patient; it will eventually load!

With `CTRL+F` locate the `1472464922` folder (last-good); locating the folder of the first bad (1472551321) is easy in this case; there exist eight (8) intermediary builds, 

![t-b](https://user-images.githubusercontent.com/9669492/44556182-33e29400-a741-11e8-9553-8cb27e3367a5.jpg)

on which you can apply mozregression to narrow down the regression range!
And if still no joy with _the tinderbox-builds regression range_ produced, you can dissect even further 
by going into the **mozilla-inbound** hourly builds repo: 

`https://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-inbound-win32/`

where builds are only a few mercurial commits apart (you should be looking in the `1472464831` to `1472550921` directory range); hopefully, you can produce a regression range of only 2 - 3 mercurial commits :wink: 

Kind regards 😃

**Comment by JustOff** [comment]
I tried to apply [bug 1005640](https://bugzilla.mozilla.org/show_bug.cgi?id=1005640), replacing `intl:app-locales-changed` with `selected-locale-has-changed`, but it did not help.

@wolfbeast, could you please remind me how to add debug messages to the cpp code to trace what's happening via console?

**Comment by wolfbeast** [comment]
You should just be able to use `sprintf()` or similar to dump debug messages to stdout from C++

**Comment by JustOff** [comment]
Perhaps I'm doing something wrong, but when I add 
```
printf("nsHttpHandler::PrefsChanged [pref=%s]\n", pref);
```
[here](https://github.com/MoonchildProductions/UXP/blob/e16bcd08aae85a7d9c2de5a4b1c733280cb81112/netwerk/protocol/http/nsHttpHandler.cpp#L954) in `nsHttpHandler.cpp` and start the browser with `-console`, I see nothing in the console while I change `intl.accept_languages` or any other preferences observed by `nsHttpHandler::PrefsChanged`.
