### ISSUE TITLE
View Selection Source opens blank window in Pale Moon

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#711]
As reported on the [forum](https://forum.palemoon.org/viewtopic.php?f=29&t=19959), selecting some text and picking "View Selection Source" from the context menu opens a blank window. A single error is reported in the browser console:

11:15:22.915 TypeError: args is null 1 viewPartialSource.js:20:3
onLoadViewPartialSource chrome://global/content/viewPartialSource.js:20:3
onload chrome://global/content/viewPartialSource.xul:1:1

It looks like docUrl is not being set correctly in [nsContextMenu.js](https://github.com/MoonchildProductions/UXP/blob/26debee73392b4d138663204b343c8ca805e6b3f/application/palemoon/base/content/nsContextMenu.js#L861-L865), so the call to `loadViewSourceFromSelection` in [viewPartialSource.js](https://github.com/MoonchildProductions/UXP/blob/26debee73392b4d138663204b343c8ca805e6b3f/toolkit/components/viewsource/content/viewPartialSource.js#L19-L20) fails.

**Comment by JustOff** [comment]
I already have a solution for this, PR will follow.
