### ISSUE TITLE
When hiding the tab bar, the border of the lowest toolbar is also hidden.

### ISSUE THREAD

**Issue by RobertZenz** [MoonchildProductions/UXP#725]
This was [Pale-Moon#1560](https://github.com/MoonchildProductions/Pale-Moon/issues/1560)

---

When the tab bar is being hidden, the bottom border of the lowest toolbar is being hidden as well. This occurs on a Linux system (GTK2 frontend).

Here is a screenshot with tabs being visible:

![Palemoon with tabs visible.](https://i.imgur.com/6pN5Ebz.png)

Now when the option "Always show the tab bar" is unchecked, it will be hidden when there is only one tab. But the border between the toolbars and the content will disappear as well:

![Palemoon with no tabs visible.](https://i.imgur.com/dLp2Nyv.png)

This occurs no matter if tabs or on top or not, and with the bookmarks bar visible or not.

**Comment by FranklinDM** [comment]
Just an idea:
What if we add an attribute `[tabshidden]` (or something similarly named) on the navigator toolbox and set it to `true` when the tab bar is hidden in order for us to have an indicator that we should add a border below the bookmarks toolbar?

**Comment by Lootyhoof** [comment]
Had a bit of a thought about this one.

If you run this style, does it get the result you're looking for?:

````
#TabsToolbar[collapsed="true"] {
  visibility: visible;
  height: 1px;
  border-bottom-width: 1px;
  border-bottom-style: solid;
  border-bottom-color: ThreeDShadow;
}
````

What we're doing here is a bit of a hack. Since the `TabsToolbar` is hidden, and we know it will always be `[tabsontop="false"]` in this state, we enable it, but only make it 1px tall. In this space, we give it a `border-bottom` (which is the only thing it has space to show), and make that act like the bottom border of the interface. This should result in (for example) something like the below:

![Bottom border with no tab bar](https://i.imgur.com/ecLGtWl.png)

If this is OK I can send a patch for this.

**Comment by kn-yami** [comment]
If this behaviour is changed, please consider making the no-border variant optional.

**Comment by Lootyhoof** [comment]
Sorry, but I don't see how that would be beneficial at all. In what use case justifies having no border between the UI and content? Especially given that it isn't even consistent with the rest of the theme (in any other configuration there is a border, including when the tab bar is present).

It's possible to do this with `userChrome.css`, anyway:
````
#TabsToolbar[collapsed="true"] {
  visibility: collapse !important;
}
````

**Comment by kn-yami** [comment]
> In what use case justifies having no border between the UI and content?

It just my preference, nothing more.

Also, thanks for the `userChrome.css` code.

**Comment by RobertZenz** [comment]
@Lootyhoof That is not working for me on Linux, the tabbar is not collapsing to a height of 1px, instead to something like 8px. Might be something theme specific which forces a minimum height.

If I do the following:

~~~css
#TabsToolbar[collapsed="true"] {
  visibility: visible;
  height: 1px !important;
  min-height: 1px !important;
  max-height: 1px !important;
  border-bottom-width: 1px;
  border-bottom-style: solid;
  border-bottom-color: ThreeDShadow;
  overflow: hidden;
}
~~~

The tabbar collapses correctly to a height of 1px, the `overflow` is needed as otherwise the tabs are visible outside of the bar.

**Comment by Lootyhoof** [comment]
Seems `overflow: hidden;` was the key here, rather than forcing the min/max-height. I've simplified this a bit - try this one and let me know if this works:

````
#TabsToolbar[collapsed="true"] {
  visibility: visible;
  height: 1px;
  border-bottom: 1px solid ThreeDShadow;
  overflow: hidden;
}
````
Seems to work as-expected when testing on Windows and Linux here.

**Comment by RobertZenz** [comment]
Yes, that did the trick for me too.
