### ISSUE TITLE
Show tab previews in the Windows taskbar: Broken function

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#731]
### Issue:
The '**Show tab previews in the Windows taskbar**' option doesn't work anymore in Pale Moon v28.
The thumbnails simply shows a spinning loading wheel.

### Screenshot:
![palemoon-bug-tabpreviewsinwindowstaskbar](https://user-images.githubusercontent.com/9382674/44616945-53211480-a85a-11e8-8786-d5f117765c02.jpg)

### Forum reference:
`https://forum.palemoon.org/viewtopic.php?f=29&t=20037/`

### Note:
The issue have been confirmed under Windows 7, 8.1 and 10.

**Comment by wolfbeast** [comment]
Anything in the console?

**Comment by mattatobin** [comment]
Not that I saw.

**Comment by THEtomaso** [comment]
No, there's nothing IN it.
..but at least, the console actually shows up in the previews:

![palemoon-bug-tabpreviewsinwindowstaskbar2](https://user-images.githubusercontent.com/9382674/44626585-2edb3b80-a91f-11e8-821d-6b850c1e9a3a.jpg)

**Comment by wolfbeast** [comment]
Ah, well, in that case this is probably another case of having to change the code to suit platform rearchitecturing for content browsers (e10s fallout)
