### ISSUE TITLE
Blank dialog when attempting to install on unsupported system

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#735]
As reported by Vista users, the dialog box of the installer that is supposed to inform them of the minimum version requirements or CPU requirements is blank.

This is caused by platform installer components having renamed nsis strings.

**Comment by wolfbeast** [comment]
Verified in a Windows Vista x64 VM

**Comment by wolfbeast** [comment]
@JustOff Please note the string changes.

**Comment by mattatobin** [comment]
Yeah those would only be applicable if someone was gonna try an l10n build.

**Comment by wolfbeast** [comment]
Just thought I'd ping you, anyway.
