### ISSUE TITLE
Attempting to register application/vnd.mozilla.maybe.video.feed throws an exception but partly registers the feed

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/UXP#737]
Using

      const WebContentHandlerRegistrar = Components.classes[
          "@mozilla.org/embeddor.implemented/web-content-handler-registrar;1"
          ].getService(Components.interfaces.nsIWebContentHandlerRegistrar);

      WebContentHandlerRegistrar.registerContentHandler(
        "application/vnd.mozilla.maybe.video.feed",
        uri,
        title,
        null);

You get this error:

    filename: "resource://app/components/WebContentConverter.js" linenumber: 773
    message: "Component returned failure code: 0xc1f30100 (NS_ERROR_FACTORY_EXISTS) [nsIComponentRegistrar.registerFactory]"

If you go to options it looks like the thing has been registered under video podcast. but nothing is stored in the preferences.

**Comment by mattatobin** [comment]
Same question as in https://github.com/MoonchildProductions/UXP/issues/883#issuecomment-442037462

**Comment by ThosRTanner** [comment]
Um. Right. I've given you the code that causes the problem.

**Comment by mattatobin** [comment]
RESOLVED INCOMPLETE
