### ISSUE TITLE
macOS: Window caption buttons missing in private/persona modes in 10.14

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/UXP#740]
As reported in #689 (though the reporter's OS version is unknown), and confirmed in macOS 10.14 "Mojave", caption buttons for windows in private and persona modes are missing again. They're there, just don't seem to be showing correctly. This happens in both the default and third-party themes.

![No caption buttons](https://i.imgur.com/U7fQFcR.png)

They appear to work in the last publicly available build, [28.0.0b4](https://forum.palemoon.org/viewtopic.php?f=41&t=19796), so something looks to have regressed.

**Comment by SpockFan02** [comment]
I don't have Mojave and cannot confirm on 10.12.6. No commits in the last month jump out at me... _maybe_ https://github.com/MoonchildProductions/UXP/commit/803dfd7b1f24f8f455b888f814080ec2e0391621, but it shouldn't be, especially if it's not theme-dependent. Could it be a difference between @wicknix's and my build environments?

**Comment by wicknix** [comment]
It shouldn't have anything to do with 803dfd7 as that was applied in the 28.0.0b4 build.

**Comment by asimperson** [comment]
I was using 10.13 when I reported the issue.

**Comment by Lootyhoof** [comment]
Hm, seems it's fixed in @wicknix's latest build:

![Caption buttons](https://i.imgur.com/iPCbRM4.png)

A building error perhaps, @SpockFan02? Either way, doesn't seem to be a browser bug, so I'm closing this.
