### ISSUE TITLE
No work skrolling in 28.0.1

### ISSUE THREAD

**Issue by Alzimzim** [MoonchildProductions/UXP#743]
No work skrolling in maps 
https://yandex.ru/maps

**Comment by trav90** [comment]
Everything seems to work for me as well (Pale Moon 28.0.1 64-bit Linux).

Please provide more information about your system and what exactly the problem is.

**Comment by Alzimzim** [comment]
New Moon (Linix 64-bit)

cat << EOF > $MOZCONFIG
mk_add_options MOZILLA_OFFICIAL=0
mk_add_options BUILD_OFFICIAL=0
mk_add_options MOZ_MAKE_FLAGS="%{_smp_mflags}"
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/../obj
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-application=palemoon
ac_add_options --host=%{_host}
ac_add_options --target=%{_target_platform}
ac_add_options --enable-optimize
ac_add_options --prefix="%{_prefix}"
ac_add_options --libdir="%{_libdir}"
ac_add_options --includedir="%{_includedir}"
ac_add_options --datadir="%{_datadir}"
ac_add_options --with-system-nspr
ac_add_options --without-system-nss
ac_add_options --with-system-zlib
ac_add_options --with-pthreads
ac_add_options --disable-webrtc
ac_add_options --enable-jemalloc
ac_add_options --enable-gio
ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-debug
ac_add_options --without-system-libvpx
ac_add_options --disable-official-branding
ac_add_options --enable-libproxy
ac_add_options --with-system-jpeg
ac_add_options --enable-system-cairo
ac_add_options --enable-system-pixman
ac_add_options --enable-system-sqlite
ac_add_options --enable-extensions=default
ac_add_options --enable-startup-notification
ac_add_options --disable-crashreporter

**Comment by wolfbeast** [comment]
Your bug is likely to be found in your build configuration, not in our code. Building with system libs (and especially mixing system/non-system pairs like NSPR+NSS) is not supported.
Please retry with a sane build configuration. If you need more help for a custom setup like this, post on the forum in the [Linux board](https://forum.palemoon.org/viewforum.php?f=37).
