### ISSUE TITLE
SVG images with local-href "use" link don't resolve properly

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#748]
Reported on the forum: https://forum.palemoon.org/viewtopic.php?f=57&t=20287

Demonstration link:
https://info.pmu.fr/programme/courses/R1/C3

Under "Rapports définitifs" should be logos in SVG that are rendered with tiny dimensions because all the SVG includes is a single `use` statement referring to an anchor on the same page. The parent element is sized correctly. As a result, the images are not visible.

This is the same in ESR52 but fixed in Firefox nightly. Fix window wanted.

**Comment by JustOff** [comment]
Last bad: http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1492682626/
First good: http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1492724788/

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=27311156637f9b5d4504373967e01c4241902ae7&tochange=5e3dc7e1288af835220871fefdb18d520efb06d4

Suspected: https://bugzilla.mozilla.org/show_bug.cgi?id=1357432

**Comment by wolfbeast** [comment]
Suspect looks exactly right. Thanks, @JustOff

**Comment by wolfbeast** [comment]
I'll be taking this.
