### ISSUE TITLE
SVG image allows non-functioning set wallpaper window from context menu

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#749]
This can confuse users since apparently we don't have the facility to convert SVGs to something that can be set as a wallpaper. I suggest we simply don't show the context menu item for SVGs unless someone wants to spend time creating an overly elaborate solution to ACTUALLY doing this.

This will have to be handled on an application basis with possible platform involvement.

**Comment by wolfbeast** [comment]
I don't think making something elaborate like drawing it on a canvas and then getting a raster from there to set as wallpaper is a good idea, so best just to not show the option.

**Comment by mattatobin** [comment]
It doesn't work on Windows 7 on Basilisk or Pale Moon. Does not show a preview or anything.

**Comment by JustOff** [comment]
I have no problem adding SVG image from [this example](https://jsfiddle.net/ds4pL1z0/) as wallpaper using Pale Moon and Basilisk.

**Comment by mattatobin** [comment]
Seems to be when an SVG document has an `<image>` tag in it. If there is nothing else in the SVG it will appear to be a blank transparent image and not include what is in the `<image>` tag like a png that is what I was encountering.. So not optimal but not busted either.. I dunno where this leaves us.
