### ISSUE TITLE
Drawing issues with xvideos and xenforo's icons

### ISSUE THREAD

**Issue by Felipefpl** [MoonchildProductions/UXP#759]
Basilisk 32 bit on win7 x64 released on 09/05:

Some of the squares where you can see the images of the videos of xvideos.com are bigger for no reason at all, the images inside them arent displayed here, i dont have this problem with Opera 12 for example.

A small problem: i cant see the icons in the quick reply box of xenforo's forum, the pic below shows it:

http://www.hostpic.org/images/1809090149150113.gif

**Comment by mattatobin** [comment]
You want us to debug a porn site?

**Comment by Felipefpl** [comment]
hi matt, thanks for the suggestion, i went to about:config and found out that is already enabled. :/

**Comment by wolfbeast** [comment]
This doesn't look like a browser code bug, but rather a browser configuration bug by the user.

Please ask for support on the forum with your configuration. Closing as invalid.
