### ISSUE TITLE
ES6 Error.prototype and .prototype should be ordinary objects

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#76]
Blocks #71 

- __ECMAScript 6 - Error.prototype and .prototype should be ordinary objects__

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-error-prototype-object

> 19.5.3 Properties of the Error Prototype Object
>
> The Error prototype object is the intrinsic object %ErrorPrototype%. The Error prototype object is an ordinary object. It is not an Error instance and does not have an [[ErrorData]] internal slot.
>
> The value of the [[Prototype]] internal slot of the Error prototype object is the intrinsic object %ObjectPrototype% (19.1.3).

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-nativeerror-prototype-objects

> 19.5.6.3 Properties of the NativeError Prototype Objects
>
> Each NativeError prototype object is an ordinary object. It is not an Error instance and does not have an [[ErrorData]] internal slot.
>
> The value of the [[Prototype]] internal slot of each NativeError prototype object is the intrinsic object %ErrorPrototype% (19.5.3).

[Bug 1213341](https://bugzilla.mozilla.org/show_bug.cgi?id=1213341)

**Comment by wolfbeast** [comment]
Janek already did work on this:

__Some test/personal branch:__
[tree@js_error_ordinary-object_1](https://github.com/janekptacijarabaci/UXP/tree/js_error_ordinary-object_1)
(I've created the new build (x32, Windows) and tested (shortly))

**Comment by wolfbeast** [comment]
@janekptacijarabaci your work branch has quite a few changes -- do you feel confident that it's complete?

**Comment by janekptacijarabaci** [comment]
The following test works:
``` javascript
if (![Error, EvalError, RangeError, ReferenceError,
      SyntaxError, TypeError, URIError].every(function (E) {
  return (Object.prototype.toString.call(E.prototype) === "[object Object]");
})) {
  alert("Something is not an (ordinary) Object!");
}
```

If you think it's not complete (I'm not aware of that), please check this in detail.

**Comment by wolfbeast** [comment]
Thanks; a simple "yes, I think it's complete" would also have sufficed ;)
