### ISSUE TITLE
Addon debugging/developer tools do not work

### ISSUE THREAD

**Issue by RomanHargrave** [MoonchildProductions/UXP#760]
In trying to troubleshoot why bitwarden's addon will not work with my custom server in basilisk (while it will in chrome...) I enabled the addon debugging tools (in about:debugging). When I opened the debugger for the bitwarden addon, I was greeted with, more or less, a blank page.

**Comment by GitCartel** [comment]
related? web console does not work at all for me 28.1.0 x64 W64

**Comment by wolfbeast** [comment]
No issues seen with the devtools/web console here.
