### ISSUE TITLE
Facebook Security Check does not work in Basilisk

### ISSUE THREAD

**Issue by gitbugged** [MoonchildProductions/UXP#762]
1. Download official latest binary of Basilisk (I am testing it on Linux)
2. Use Facebook and wait for security check (use proxy to trigger it faster)
3. It is not possible to enter security check since it never loads

This problem does not affect Pale Moon which I also tested.

Attached image of what it looks like for me. 

![basilisk](https://user-images.githubusercontent.com/22638840/45271754-23d3ef80-b477-11e8-9c4d-6e0b06bcfb33.png)

**Comment by wolfbeast** [comment]
On the facebook home page there is a constant stream of errors (about 2/second) that point to an issue in a loaded Google recaptcha iframe. That's probably what's going on here. I haven't been able to trigger the "security check" so can't verify anything.

**Comment by gitbugged** [comment]
I found a reliable way to reproduce. Visit a community page such as: https://www.facebook.com/FreenetCommunity

Use Tor as Proxy. You'll get the security check every-time.

**Comment by mattatobin** [comment]
So, they are flagging suspect proxies like the criminal network Tor and you are surprised? In any case, I don't see how this has anything to do with Basilisk or indeed if there is anything to be done on our side.

Can we close this as `RESOLVED INVALID`?
