### ISSUE TITLE
Direct users properly for blocking site data and remove the IndexedDB master pref.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#765]
We have an undocumented preference "dom.indexedDB.enabled" that exists so that we could easily disable IndexedDB in case of a massive security problem. The preference was changed so that it only impacted content, in recognition of the use of IndexedDB under-the-hood by our applications' chrome.

In practice, this preference has been used in the wild in an attempt to disable storage APIs, and our permissions manager (incorrectly!) flips this pref also when storage is blocked for "all sites".  (Which makes sense because the preference seems self-describing!)

**Confusingly for users, the actual preference that controls all storage is the _cookies_ one.**

The good news is that the preferences UI can easily be improved by renaming a few "cookies" strings to "Cookies and site data" (similar to what Firefox has done), and the "Cookies and Site Data" UI can entirely disable APIs like IndexedDB for sites by setting "Block cookies and site data".  Individual sites can then be granted permissions as well, which isn't possible when IndexedDB is disabled overall.

To restate that for anyone who ends up in this issue wanting to disable IndexedDB: **We treat all types of storage as equivalent.**  The "cookies and site data" permissions are sufficient to block use of IndexedDB APIs.  They also allow modes of operation where storage is closed at shutdown and allow manual clearing of storage.

Please see the following [support article](https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences) at Mozilla for more information how this works.

In any event, because it's an unsupported pref that's insufficiently tested, holes have developed, resulting in scenarios where we can end up crashing, and at the very least cause confusion and web compatibility issues for users.
It's better that the pref and its checks should be removed since it's a misleading preference and we already have privacy mechanisms in place that comprehensively block storage.

What we need to do for this:
- [x] Rename "Cookies" to "Cookies and Site Data" in preferences where applicable.
- [x] Update the Permissions Manager to unify cookies with cookies and site data/storage
- [x] ~Remove manipulation of dom.indexedDB.enabled from the permissions manager~ (already done)
- [x] Remove the pref and its effects
- [x] Verify availability/blockage of storage APIs based on cookies settings

**Comment by wolfbeast** [comment]
@JustOff Note string changes, please.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
