### ISSUE TITLE
RegExp.prototype should be an ordinary object

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#77]
Blocks #71 

- __ECMAScript 6 - RegExp.prototype should be an ordinary object__

http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-regexp-prototype-object

> 21.2.5 Properties of the RegExp Prototype Object
>
> The RegExp prototype object is an ordinary object.

e.g.
`RegExp.prototype.exec();` should throws exception:
`exec method called on incompatible Object`

`alert(Object.prototype.toString.call(RegExp.prototype));`
`[object Object]`

[Bug 1192038](https://bugzilla.mozilla.org/show_bug.cgi?id=1192038)

**Comment by janekptacijarabaci** [comment]
__Some test/personal branch:__
[tree@js_regexp_ordinary-object_1](https://github.com/janekptacijarabaci/UXP/tree/js_regexp_ordinary-object_1)
(I've created the new build (x32, Windows) and tested (shortly))

\+ [Prototypes should be regular objects](https://github.com/MoonchildProductions/UXP/commit/faa5f0df26e09d1f2e633618476294d112c24322) - an example:
``` javascript
try {
  // It is important for this issue: RegExp.prototype should be an ordinary object
  RegExp.prototype.exec();
  console.log("1: false");
} catch (e) {
  console.log("1: true");
}
try {
  Date.prototype.valueOf();
  console.log("2: false");
} catch (e) {
  console.log("2: true");
}

if (![Error, EvalError, RangeError, ReferenceError,
      SyntaxError, TypeError, URIError].every(function (E) {
  return (Object.prototype.toString.call(E.prototype) === "[object Object]");
})) {
  console.log("3: false");
} else {
  console.log("3: true");
}

/*
Actual results:

// It is important for this issue: RegExp.prototype should be an ordinary object
1: false

2: true
3: false

Expected results:

// It is important for this issue: RegExp.prototype should be an ordinary object
1: true

2: true
3: true
*/
```

and:
![builtin](https://user-images.githubusercontent.com/2373486/37593778-1ad84cea-2b6b-11e8-9f68-21221f3251be.png)
