### ISSUE TITLE
Pale Moon for Android? 

### ISSUE THREAD

**Issue by ibuprophen1** [MoonchildProductions/UXP#771]
Are there any plans for rebooting the Pale Moon for Android app? 

I've got an older version of this and did notice that it was no longer available for Android. 

Thank you very much for your time and understanding with this question! :-) 

~Ibuprophen

**Comment by THEtomaso** [comment]
Your question belongs in the Pale Moon forum, here:
`https://forum.palemoon.org/viewforum.php?f=39/`
