### ISSUE TITLE
"Restore Previous Session" is missing from Pale Moon's Start Page

### ISSUE THREAD

**Issue by projectBoy** [MoonchildProductions/UXP#772]
This is happening at least in Pale Moon 28.0.1, 64b, i'm not aware for other versions. 

Steps to reproduce: 
1. In Preferences -> General, leave "Show my home page" (default). 
    In "Home Page:", delete "`http://start.palemoon.org/`". 
2. Close the browser with at least two tabs and then open it again. 

When Pale Moon starts, it has one tab with its home page, but the option 
"Restore Previous Session" is missing. 
Investigating this issue, i saw that if the home page is refreshed once, the 
missing option gets appeared. 

I think this issue must be prioritized because gives to the user the impression 
that there is no session to be restored.

**Comment by JustOff** [comment]
I confirm this, most likely, the reason is some kind of async bs.
