### ISSUE TITLE
Quickly pressing the close button on tabs has a delay which is not seen in Firefox or chrome

### ISSUE THREAD

**Issue by shellye5** [MoonchildProductions/UXP#775]
new profile

Open 10-20 tabs

now quickly press close button/x button on tabs to close 5-10 tabs,
tabs close but when closing quickly it has a wait of 1second or so which ignores next click to close.
which causes another click required to close. Basically 2 clicks to close as opposed to one click when closing tabs fast(less than half a second).

when closing these tabs quickly Double clicking the x button closes the tabs instantly no matter how fast.

now try closing the tabs using x button slowly(1sec between clicks)
tabs close with one click instead of two.

In Firefox and chrome it's not an issue no matter how fast the user closes the tabs.

KB shortcut works fine.

can you guys fix this quickly

@JustOff 
@wolfbeast 

win/lin

**Comment by mattatobin** [comment]
Which browser is this on?

It is important because Basilisk's UI is more async than Pale Moon's. Though, there can always be somewhat of a delay because it does take time depending on just how much there is to de-allocate and destroy.

Chrome is n/a because it works totally differently. Current day Firefox uses e10s so all main UI events are async with promises so a UI action can be considered complete even if it isn't actually internally done.

**Comment by shellye5** [comment]
> 
> 
> Which browser is this on?
> 
> It is important because Basilisk's UI is more async than Pale Moon's. Though, there can always be somewhat of a delay because it does take time depending on just how much there is to de-allocate and destroy.
> 
> Chrome is n/a because it works totally differently. Current day Firefox uses e10s so all main UI events are async with promises so a UI action can be considered complete even if it isn't actually internally done.
> 
> Also. in the future, please do not specifically mention contributors in your issues unless you actually need direct comment from them.

New here so sorry for the wrong mention @mattatobin but though they might want to know this.

PM28.0.1 & PM28.1.0
The delay is not related to e10s but recent switch to UXP?

Before that it was instant like 10ms now more like 400-500ms or more.
Clicking slowly like with a gap of 1second is fine but quicker than that it miss-clicks
Double clicking is the only work around.

**Comment by shellye5** [comment]
> 
> 
> As far as I remember, this (in my opinion flawed) behavior existed since forever.
> 
> I am not familiar with the code, so the following is pure speculation:
> 
> After a shot in the dark I found [this passage](https://github.com/MoonchildProductions/UXP/blob/d118d486a680ed42030b1bdee263a29831da3e86/application/palemoon/base/content/tabbrowser.xml#L4674), which, I presume, implements single and double click actions of the close tab button:
> 
> ```
> <binding id="tabbrowser-close-tab-button"
>    [...]
>    <handlers>
> 	
> 	<handler event="click" button="0">
> 	   [...]
> 	   tabContainer.tabbrowser.removeTab(bindingParent, {animate: true, byMouse: true});
> 	   [...]
> 	</handler>
> 
> 	<handler event="dblclick" button="0" phase="capturing">
> 	  // for the one-close-button case
> 	  event.stopPropagation();
> 	</handler>
> ```
> 
> I suspect that, while pressing the mouse button quickly, Pale Moon does not receive single click events, but instead double click events every other click.

@mattatobin MaxKoll thank you, you might be right as waiting a second between click doesn't cause a problem but any quicker it does.
maybe that's why Firefox without multiprocessing on or off doesn't have the problem.
A way to test it would be by disabling dblclick somehow?

**Comment by shellye5** [comment]
webcast of the problem

palemoon with new profile 28.1.0-
https://gfycat.com/NaiveDependableArthropods

Firefox with new profile and multi-process off 62.0.2-
https://gfycat.com/AmpleFaintAkitainu

**Comment by mimecry** [comment]
does this happen with middle click to close?

**Comment by shellye5** [comment]
> 
> 
> No, it doesn't.
> 
> FYI, I've done some testing and verified that the code passage I pointed to is indeed the cause of this. I intend to open a pull request in the next few days.

thank you, will this be in next beta which will be out in a few days so can test it?

**Comment by mattatobin** [comment]
What does Firefox have to do with anything?

**Comment by shellye5** [comment]
> 
> 
> What does Firefox have to do with anything? You do realize none of us use Firefox right? Why would we? We have two (later three) browsers based on UXP.
> 
> No one here is chasing after Firefox for purely apparent UI speed. See what I wrote before.

Sorry for the miss understanding, you misunderstood me with in relation to Firefox
What was Meant is the UI closing speed similar to other browsers(including the later three) or Basilisk

**Comment by shellye5** [comment]
@MaxKoll thanks & waiting for a new build to test this.
