### ISSUE TITLE
Buttons on menu bar are not clickable when menubar is autohiden

### ISSUE THREAD

**Issue by intika** [MoonchildProductions/UXP#779]
This is an old firefox bug that have never been fixed, when the menu bar is set to hidden we can display it with the key ALT... if the bar is customized with button, we can not click them. 

There is an extension that fix the bug [Menubar Autohide Fixed](https://addons.mozilla.org/en-US/firefox/addon/menubar-autohide-fixed/)

Tested on Palemoon v28.1.0 & v28.0.1

**Comment by mattatobin** [comment]
Why would you hide the menubar if you also have buttons on it? How is this a bug?

**Comment by wolfbeast** [comment]
This is not an expected situation for normal use.
Edge case workflow which has an extension to cater to it (extension tested and working).
