### ISSUE TITLE
.msi files can't be opened from the downloads library in Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#780]
As [reported on the forum](https://forum.palemoon.org/viewtopic.php?f=3&t=20466) Pale Moon does not open `.msi` files from the downloads library.

The error console displays:
```
TypeError: DownloadsCommon.strings.fileExecutableSecurityWarning is not a function  
DownloadsCommon.jsm:539:11
```

It seems that `fileExecutableSecurityWarning` and `fileExecutableSecurityWarningTitle` were mistakenly removed from `downloads.properties` in https://github.com/MoonchildProductions/UXP/commit/8be0c16be614d54183ee3d4877e2243cb9e468c8.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by mimecry** [comment]
same issue with .reg files, hope restoring the strings will fix it as well

![image](https://user-images.githubusercontent.com/10742312/46284470-27ecbc00-c5a2-11e8-9731-c1c91e941f0d.png)
