### ISSUE TITLE
Remove sites allowed to store data offline doesn't work

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#783]
Advanced >> Network >> domains allowed to store data for offline use.

Selecting and removing doesn't work, FE vs BE problem from the move to UXP, most likely.

**Console error:**
```
Error: TypeError: BrowserUtils.principalFromOrigin is not a function
Source File: chrome://browser/content/preferences/advanced.js
Line: 454
```

**Comment by THEtomaso** [comment]
Duplicate of this one?:
https://github.com/MoonchildProductions/UXP/issues/734/

**Comment by wolfbeast** [comment]
Yup.
