### ISSUE TITLE
Basic Auth window does not resize based on content

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#785]
As reported via private communication:

The basic auth window does not resize based on its content. If e.g. extensions add controls or information to this window, standard controls are hidden through overflow. This is likely also the reason people have reported layout issues with this window, complaining about uneven spacing.

Apparently this _is_ a regression from v27, so it would serve to find a regression window first and foremost, if looking at the code doesn't make it blatantly obvious. Potentially this was fixed to certain sizes to prevent oversized windows based on server-supplied realm information?

![palemoon_inflexible-authentication-window_23-09-2018_07-40-03](https://user-images.githubusercontent.com/3359132/45925283-8961ba80-bf12-11e8-9a7a-35e415702e15.png)

**Comment by JustOff** [comment]
Last good: http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1465305751/
First bad: http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1465306171/

Push log: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=bc9db3800f3c2bd3c25a98614dc6b40571d25795&tochange=7f7c7d24700eb80ce328b05fd260ec58e9725ca4

Suspect: https://bugzilla.mozilla.org/show_bug.cgi?id=1230462

**Comment by mattatobin** [comment]
![b803dba4-4efc-4fb4-bb6d-c4b4035e0ee0](https://user-images.githubusercontent.com/3889475/45927719-3b928580-bf05-11e8-92e4-4dedde43988b.jpg)

?

**Comment by JustOff** [comment]
I checked that the removal of `window.sizeToContent ();` from `commonDialog.js` fixes the problem, but I'm not sure that we will not encounter [the issue described in the linked bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1230462#c75).

**Comment by JustOff** [comment]
See also [bug 1277895](https://bugzilla.mozilla.org/show_bug.cgi?id=1277895) (already in our tree); perhaps this follow-up made it safe to simply remove `window.sizeToContent();` from `commonDialog.js`.
