### ISSUE TITLE
Improve handling of MOZ_GAMEPAD and NECKO_WIFI

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#794]
`MOZ_GAMEPAD` enables its self right before it's disable bool

This should become an enable bool that can be set from confvars.

`NECKO_WIFI` enables its self based on target os

This is correct, but should be handled like other build configuration options with a switch to override enabling from either mozconfig or confvars.

Both are in `old-configure.in`

**Comment by mattatobin** [comment]
This is incomplete as described.

**Comment by wolfbeast** [comment]
what is incomplete? described where?

**Comment by mattatobin** [comment]
Reload.

**Comment by wolfbeast** [comment]
It's not clear to me what you want then. I moved it to above where confvars is called so you can set it from confvars instead of .mozconfig only, which I understood was the intention. If it was not, then you should have described it more clearly.

**Comment by mattatobin** [comment]
Well I thought it was obvious, sorry.

**Comment by wolfbeast** [comment]
No it isn't :P What exactly was your intent for change then, **exactly**?

**Comment by mattatobin** [comment]
Well not to split logic across half the configure file for starters..

Basically, I was going to flip gamepad to be an enable bool (putting `MOZ_GAMEPAD=` up the file) with Basilisk set with it on and then change necko-wifi to be LIKE what gamepad does where it does it's checking based if `MOZ_NECKO_WIFI=1` then it can set `NECKO_WIFI` and `NECKO_WIFI_DBUS`.

**Comment by wolfbeast** [comment]
Updated the issue title and desc. according to what i understood. please correct me if I'm still wrong.

**Comment by mattatobin** [comment]
Looks perfect. Yeah I should have properly described it or assigned it to my self and THEN properly described it. I almost forgot it was open.. Really, I should have gotten it done long ago not sit without an assignee and barely any info at all.
