### ISSUE TITLE
Make nsUserInfo component optional at build time.

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#795]
While investigating some things to speedup the startup, I bumped into nsUserInfo, an old mostly abandoned codebase that [was going to be used for TB22](https://bugzilla.mozilla.org/show_bug.cgi?id=29593) to auto-populate fields. It appears to not be used anywhere at the moment, and isn't working in the latest TB.

As an aside, this module scrapes full username, e-mail, and hostname and makes it available to all applications using the toolkit. So I suppose it is a privacy improvement. Test XPI showing this "feature" attached.

[userinfotest.xpi.zip](https://github.com/MoonchildProductions/UXP/files/2430230/userinfotest.xpi.zip)

**Comment by mattatobin** [comment]
I already told you that removing this could affect add-on compatibility.. Also, your patch is woefully incomplete.. It does not contain a configure argument nor is it defined anywhere globally by default.

I see no reason to remove this.

**Comment by wolfbeast** [comment]
Before deciding we can remove this, we'll have to know if it is in fact in use by extensions or not.
Usefulness seems limited (only really supported on *nix systems), but as pointed out there is no privacy concern unless you consider malicious extensions being installed a valid working environment (and in that case, you have bigger problems than leaking the user's system login name!).

**Comment by GitCartel** [comment]
how do we use userinfotest.xpi.zip? thanks

**Comment by g4jc** [comment]
> At any rate your patch is woefully incomplete.. It does not contain a configure argument nor is it defined anywhere globally by default.

I've updated the PR so that it is enabled by default unless --disable-userinfo is specified in the mozconfig.


> Before deciding we can remove this, we'll have to know if it is in fact in use by extensions or not.

In case it is needed for some reason, this does not remove it unless an application specifically decides to opt-out. However, I've never seen an addon use this in the wild.

**Comment by mattatobin** [comment]
Since your pull request is a mess I want you to close it and submit a clean version for consideration.

This is why you don't submit unsolicited pull requests without talking about it first.

**Comment by wolfbeast** [comment]
> Since your pull request is a mess I want you to close it and submit a clean IF this goes forward. This is why you don't submit unsolicited pull requests without talking about it first.

There's always squash merging if the PR is too messy.

**Comment by mattatobin** [comment]
Oh yeah, I forgot that was a thing.

**Comment by wolfbeast** [comment]
Would you mind rewriting the define to `MOZ_USERINFO` and treating it as a feature enabler (with default being defined at `1` at the top of configure) to align with the rest of the build system code and preventing double-negative conditions that are easily misread?

**Comment by g4jc** [comment]
>  treating it as a feature enabler (with default being defined at 1 at the top of configure)

I believe I did this correctly? The enabler is set to 1 just above the pref, if you need it moved elsewhere just let me know.

**Comment by mattatobin** [comment]
Are we really making this conditional?! If so tell me and I will do the patch so it is done correctly. This is ridiculous.

**Comment by wolfbeast** [comment]
PR backed out in #851 due to build bustage; reopening.

**Comment by g4jc** [comment]
Sorry! In order to avoid busting the whole tree, please review. It is working for me as of now. 
(I recompiled it twice. Once with the pref disabled, and it works, and once without, and it was enabled by default)

**Comment by mattatobin** [comment]
Once again, configure flags/options are NOT preferences. Correct terminology is important here.
