### ISSUE TITLE
Update libnestegg from upstream

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#799]
Our in-tree version of libnestegg is quite old (over 2 years) and should be updated from upstream.

In addition to the regression fixes, performance improvements, and compatibility improvements a newer libnestegg will provide, it will also be required for AV1 support (#87) as well as WebM subsample encryption for EME.

**Comment by g4jc** [comment]
As long as the EME functionality will be behind the existing pref to disable it this is a good idea. Don't want to accidentally have EME enabled in any of our applications.

**Comment by trav90** [comment]
No this PR does not touch EME functionality at all. It will only make the WebM subsample encryption possible with future patches which will extend the current EME functionality if Built/enabled. No chance of EME being enabled accidentally.
