### ISSUE TITLE
Setting to hide the popup window in full-screen HTML5 video does not work in Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#803]
[As reported on the forum](https://forum.palemoon.org/viewtopic.php?f=13&t=20577), Pale Moon does not hide the status text in full-screen HTML5 video when it's selected to display in a pop-up.

**Comment by JustOff** [comment]
You need to restart the browser after changing "Detect full-screen mode and show links/status appropriately" and "Hide status popup in full-screen HTML5 video" options.

**Comment by mimecry** [comment]
..of course. thanks so much!
