### ISSUE TITLE
Taskbar tab previews don't have proper favicons

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#809]
When the tab previews on the taskbar are enabled, fetching the favicons for the entries doesn't work, and a generic icon is displayed, instead.

This is probably a leftover issue from fixing the taskbar previews that didn't fetch the thumbnails properly. Using the favicon service probably needs some more adjustment there to work with the UXP back-end.

**Comment by LigH-de** [comment]
Persists in v28.2.0.

**Comment by wolfbeast** [comment]
@LigH-de If an issue is not marked resolved, then the issue will persist. Reporting that it persists in specific versions in the interim is not necessary.

**Comment by LigH-de** [comment]
Basilisk 2018.12.18 works well and already did work before.

Pale Moon 28.3.0 still shows default icons. It's not "fixed" for me.

![pm_28 3 0_taskbar-icons](https://user-images.githubusercontent.com/5917225/51248640-184a8500-1991-11e9-83f5-d3e4fe0b000d.png)

Shall I try enabling `browser.chrome.favicons.process` ?

**Comment by FranklinDM** [comment]
I can confirm the same observations with @LigH-de except that one site had the correct favicon (the difference was this site's tab was restored from the previous session).
![cs](https://user-images.githubusercontent.com/11641537/51249542-96794c80-19ce-11e9-87a0-3752f868e2d2.PNG)

**Comment by wolfbeast** [comment]
Well in that case it's strange, especially if Basilisk does work.
If anyone wants to have a look at this, go ahead. I'm not entirely sure where to start.

**Comment by ThatBrickster** [comment]
From what I can see, Basilisk has the following:
https://github.com/MoonchildProductions/UXP/blob/master/application/basilisk/modules/WindowsPreviewPerTab.jsm#L104

I found it as a result of this Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1433037

Pale Moon doesn't have WindowsPreviewPerTab.jsm in its modules folder although it is referenced in a few places.

**Comment by JustOff** [comment]
> Pale Moon doesn't have WindowsPreviewPerTab.jsm in its modules folder

You are wrong, Pale Moon also includes it.

**Comment by ThatBrickster** [comment]
> You are wrong, Pale Moon also includes it.
Apologies, I have just found it. Last time I trust GitHub's search functionality.

That aside, Pale Moon's code is synchronous and it was fixed in the associated bug by calling the async image decode function. If it's still up for grabs later, I'll fix it once I'm home.

**Comment by mattatobin** [comment]
You should use our code cross reference tool which is an incarnation of a modified ancient tool that Just Works(tm).

http://xref.palemoon.org/

**Comment by mattatobin** [comment]
Any progress on this?

**Comment by mattatobin** [comment]
Reopened for Uplift

**Comment by wolfbeast** [comment]
Uplifted in dabd43c914c826c8cb66b6b224c5581256cb6f05

**Comment by Scribe-uk** [comment]
![Capture](https://user-images.githubusercontent.com/44050114/57909538-fa2b5d80-787a-11e9-9d12-1df30cd6ec0e.PNG)
Not a big deal, and code goes over my head I'm afraid, but as originally reported on the forum here - https://forum.palemoon.org/viewtopic.php?f=29&t=20512&p=156189&hilit=taskbar+icons#p156189 there are still no favicons on PM 28.5.0 Win7 64bit

**Comment by LigH-de** [comment]
I believe this was not yet implemented in v28.5.0 - release notes don't contain the keyword "icon" since v28.3.1. So ... a little more patience, I guess.

**Comment by wolfbeast** [comment]
Read, please?

> mattatobin added this to the 28.5.1 milestone 4 days ago

**Comment by Scribe-uk** [comment]
> 
> 
> Read, please?
> 
> > mattatobin added this to the 28.5.1 milestone 4 days ago

Ah, thanks very much :-)
