### ISSUE TITLE
Make all arguments to init*Event() optional except the first

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#810]
Pending spec change to gravitate towards Webkit/Blink at WhatWG.

WebIDL changes only and making arguments optional with set defaults - low risk and backwards compatible, so might as well do this before it becomes TR, to improve web compat.

https://bugzilla.mozilla.org/show_bug.cgi?id=1345044

**Comment by kn-yami** [comment]
I can do this, if you want.

**Comment by wolfbeast** [comment]
I got it.
