### ISSUE TITLE
TypeError: class constructors must be invoked with |new|

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#815]
### Error:
`TypeError: class constructors must be invoked with |new|`

### Example:
`https://www.gog.com/`

### Fix?:
`https://bugzilla.mozilla.org/show_bug.cgi?id=1406150`

### Forum reference:
`https://forum.palemoon.org/viewtopic.php?f=3&t=20610#p154131`

**Comment by wolfbeast** [comment]
Class constructors must be invoked with |new| according to the standard.

**Comment by Sa-Ja-Di** [comment]
Like Yami_ wrote in the topic:

The News section issue was fixed in Firefox 55:
Last bad: 2017-04-17
First good: 2017-04-18
Pushlog: https://hg.mozilla.org/mozilla-central/ ... 81026415c4

**Comment by wolfbeast** [comment]
Unrelated to this issue.

**Comment by THEtomaso** [comment]
Yeah, none of the commits from the pushlog refers to bug #1406150.

**Comment by THEtomaso** [comment]
Just a quick question, regarding the "Won't fix" decision..
Does this mean that Mozilla's fix doesn't comply with the standard?

**Comment by wolfbeast** [comment]
You obviously didn't look at the bug. You would have seen that the bug addresses internal scripting that doesn't use `new` when it should.

**Comment by THEtomaso** [comment]
More like I didn't understand it. :)

**Comment by wolfbeast** [comment]
That's also possible :)
