### ISSUE TITLE
Improve the security of a stored master password.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#82]
Created as a clone of https://github.com/MoonchildProductions/Pale-Moon/issues/1648

re: https://forum.palemoon.org/viewtopic.php?f=4&t=18643

Apparently the encrypted storage of the master password isn't sufficiently hashed and a brute-force password cracking run could potentially recover the master password.

To mitigate, we need to apply a sufficient number of hashing rounds to make this kind of password guessing infeasible.

From: https://bugzilla.mozilla.org/show_bug.cgi?id=524403#c11

> We definately should change this, the current iteration count for the database is 1. There are 2 places in sftkpwd.c that need to change: 
>             sftkdb_EncryptAttribute() and sftkdb_SignAttribute. 
>             Both call nsspkcs5_NewParam with a hard coded interation count of 1. 
> 
> The only affect of changing the interaction count is the performance of login and private key operations. Old versions of NSS can still read the database (the iteration count for decrypt is read from the database record). Old databases will still be able to be read, though they will still have an iteration count of 1. Changing the password (even to the same password) on those database will update the iteration count.
> 
> The only other concession is what we need to change that value to. pkcs12 is set to 10000 (10K) in debug builds and 1000000 (1M) in optimized builds.

setting this on par with PKCS12 (1M) should mitigate this transparently, without further need to migrate (just ask users to update their master password for the new value to take effect and secure the password store).

**Comment by wolfbeast** [comment]
Anything exceeding a short int isn't possible right now, so 30k has been chosen as a decent value (> industry standard 10k).
To mitigate too short passwords, the minimum length will also be enforced to 8 characters.

**Comment by wolfbeast** [comment]
Considering this only works in a busted version of NSS, this had to effectively be backed out, and is still open.

**Comment by trav90** [comment]
Now that we've gotten NSS updated is this able to be re-landed?

**Comment by wolfbeast** [comment]
I'm not sure -- I ran into some strange issues with increased rounds (mainly the master password not being accepted after setting it) which is the main reason why I haven't re-landed this.
Feel free to see if there are any issues relanding this or if this is still a problem.

**Comment by wolfbeast** [comment]
The problem was that we are using dbm (and not sql) for which the proposed change is not working.
A better solution has been found based on patches provided by Robert Relyea and Kai Engert.
I'll patch our current NSS with it and disable building with system NSS to prevent discrepancies with support for increased rounds.

Number of rounds increased from 1 to 60,000 to provide a considerable strength to the master password hashing for short passwords, and increased strength to sufficiently long ones, at the cost of 1-2 seconds pause when unlocking the password store.

**Comment by mattatobin** [comment]
@Khonosschoty reports bustage on the commit its self.. again.

**Comment by mattatobin** [comment]
I'm looking into it cause obviously I am the only one who can.

**Comment by wolfbeast** [comment]
Backed out. running into the same issue on Windows. Weird because I didn't touch anything even close to the base `/netwerk` code.
