### ISSUE TITLE
[Suggestion] Make "browser.download.lastDir.savePerSite" false by default

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/UXP#823]
Today, I understood why Firefox was, on an irregular basis, not saving my downloads in the last used dir.

That's because I was downloading files from some CDN, i.e. several subdomains, attributed depending on their current network load. So because of the preference [browser.download.lastDir.savePerSite](https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/browser.download.lastDir.savePerSite), Firefox was often picking back the dir from an old CDN server, instead of my last used dir.

So, today I discovered this setting, missing from the default configuration and set to true by default. For the reason exposed above, and generally speaking, I think it brings many confusion. See [bugzilla 702748](https://bugzilla.mozilla.org/show_bug.cgi?id=702748). Thus I think it should be false by default.

You may disagree, or want to limit the discrepancies with Firefox, in this case I would have an alternative suggestion: at least add this setting to the default configuration (currently to tweak it, it has to be created), to increase visibility/ease access of this setting.

**Comment by wolfbeast** [comment]
I'm sorry but setting that to false will prevent any retention of download folders, regardless of host downloaded from. That is less desirable than having to occasionally re-choose it and a behavior change that would certainly not be appreciated by most users.

So, the default will stay as it is - if you want different behavior, then flip the preference yourself; it's configurable by the user for a reason.

**Comment by vlakoff** [comment]
The last download dir would still be stored in `browser.download.lastDir` and reused, wouldn't it?

**Comment by vlakoff** [comment]
Also, please consider my "alternative suggestion", if not changing the default value, at least make the setting visible :)

**Comment by wolfbeast** [comment]
You seem to misunderstand where this comes into play. For many users, having separate download folders remembered depending on where things are downloaded from (as a content preference) is desirable, and not having a single "wherever was downloaded to last regardless of host/site". `lastDir` is used when no content preference exists.

**Comment by wolfbeast** [comment]
As for the alternative, that's not a problem.

**Comment by wolfbeast** [comment]
Fixed using the alternative suggestion.
