### ISSUE TITLE
Add QCMS to WebP + fix animated WebP

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#831]
As a follow-up to 3e0351aa49be56434df121d9b4d9f283c422a670 we should make the WebP decoder ICC-aware and make it call into QCMS for tagged images.

This should be based on the changes proposed in https://bugzilla.mozilla.org/attachment.cgi?id=9015618

> Created attachment 9015618 [details]
> Bug 1294490 - Part 3. Implement WebP decoder.
> Depends on D8115
> This added support for QCMS, fixed the performance/extra copying issues I had comments in the code about, and support for skipping pixel premultiplication (if a canvas ends up accessing images for example).

**Comment by shellye5** [comment]
Bug 1294490 (WebP)
has landed and fix for this Add QCMS to WebP
https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c147.
Can the patches be integrated into 28.2.x beta?

**Comment by wolfbeast** [comment]
Not as-is. The Mozilla patches build on some other changes made to image decoders that will either have to be ported or worked around.

**Comment by roytam1** [comment]
They get them merged: https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c159

**Comment by wolfbeast** [comment]
We will need:
- [ ] Bug 1462355 - Avoid mutex contention between FrameAnimator/Decoders
- [ ] Relevant nsWebPDecoder.* changes

There are some issues with animated WebPs in our current implementation, as well, which the first bug should address while we're at it. That bug is rather involved as it rewrites the handling of image animations significantly and has a lot of code churn.

I'll see if I can manage it this week. It will take time and focus.

**Comment by wolfbeast** [comment]
The rearchitecturing of image decoders was pretty much contained in part 1 of the BZ bug mentioned. With that in place, animated WebP should now be fully functional. I do plan to take the rest of that bug since it's a good improvement for data flow, but is unrelated to this particular issue so will be a follow-up.

Verification of animated images and if possible ICC-tagged WebP would be appreciated.

**Comment by JustOff** [comment]
I confirm at https://github.com/MoonchildProductions/UXP/commit/238b430ec0446d08a8fd513ae7b4000b5996fd69 all tests from http://littlesvr.ca/apng/gif_apng_webp.html now pass without errors :+1:

**Comment by trav90** [comment]
I get the same results as @JustOff on Linux. :+1:

**Comment by wolfbeast** [comment]
Awesome! Closing as verified fixed.
