### ISSUE TITLE
Cropped media boxes

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#840]
### Issue:
Some media boxes are cropped.

### Example:
`https://www.vg.no/forbruker/helse/i/0EyRLG/`

(The image sliding box at the top of the article is cropped)

### Mozregression results:
* Last bad: Firefox v55.0a1 (2017-04-18)
* First good: Firefox v55.0a1 (2017-04-19)

Changelog for Firefox v55.0a1 (2017-04-19):
`http://forums.mozillazine.org/viewtopic.php?f=23&t=3029528/`

**#1356820** looks like it might be the relevant one:
`https://bugzilla.mozilla.org/show_bug.cgi?id=1356820`

### References:
Pale Moon forum:
`https://forum.palemoon.org/viewtopic.php?f=3&t=20691/`

Issue # 649 (Possibly related?):
https://github.com/MoonchildProductions/UXP/issues/649/

**Comment by JustOff** [comment]
I confirm that back-porting the [bug 1356820]( https://bugzilla.mozilla.org/show_bug.cgi?id=1356820) resolves the issue, PR will follow.
