### ISSUE TITLE
Enable Array.prototype.values

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#85]
Because of buddy reasons, this was disabled in Firefox.
We should enable this for full ES6 standards compliance.

Blocks #71

**Comment by wolfbeast** [comment]
Not sure why GitHub didn't tag #71 here while it's in the desc... :/

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
Isn't this a better solution? - https://github.com/janekptacijarabaci/UXP/commit/0c36b27511c1fbca594f0426c493ef601fda3e4c (based on [bug 1420101](https://bugzilla.mozilla.org/show_bug.cgi?id=1420101))

**Comment by wolfbeast** [comment]
Um, no. Why is adding all that unnecessary complexity and making it prefable with varying degrees of enablement better than simply enabling it across the board?

**Comment by wolfbeast** [comment]
**Looking at what other browsers do:** Edge has it enabled. Safari has it enabled. Chrome will enable it by the looks of it but with a possible kill switch and Mozilla will enable it in FF60 also with a possible kill switch.

**Compatibility risk:** mainly some Microsoft enterprise products... but Edge ships with it enabled :thinking:

**Comment by mattatobin** [comment]
I think a pref is a good idea..

We are not in a position to maintain or even set the status quo as far as javascript is concerned.. That is up to Google and to a lesser extent Microsoft as defacto dictators of emcascrpt.

Parity behavior should be the default for the pref.

**Comment by wolfbeast** [comment]
Of course you're right. Having more flexibility in this case is good. What was I thinking :)

**Comment by wolfbeast** [comment]
Swapped over to prefable approach (thanks Janek) in dc8aad9b9dc6983bb88aa586f34d9db007840eb8

**Comment by trav90** [comment]
I'm late to the party but I agree completely with Tobin.

**Comment by mattatobin** [comment]
If parity aligns or stays aligned with spec for a good while we can always revisit and clean up the pref and workaround/compat code..
