### ISSUE TITLE
Add support for AV1 in MP4 + MSE

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#853]
Now that #87 is resolved and we have initial support for AV1 in WebM, we should also add support for AV1 in MP4 + MSE. This will allow AV1 video playback on sites such as YouTube.

**Comment by trav90** [comment]
Most of the ductwork for this is already in place, however it is also going to require changes to the MP4 parser as well (UXP currently uses libstagefright for MP4 parsing). Additional research is required to get AV1 in MP4 to be recognized as a valid format.

**Comment by bogachenko** [comment]
+
