### ISSUE TITLE
Evaluate SSLKEYLOGFILE usage in builds

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#855]
A (new to me) feature was introduced in NSS that allows any user/environment to dump their SSL session keys to disk using an environment variable. This was originally turned on in Firefox 48, switched back off briefly for security concerns, and then re-enabled in Firefox >51 on optimized builds if a configure option is set.

As per the [wiki](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format):
> Key logs can be written by NSS so that external programs can decrypt TLS connections. 

While this is certainly an interesting feature, I do not think most users outside of debuggers will be using this which is why a few comments on the original ticket even [suggested it should be opt-in and for nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1183318#c27). It is currently enabled in Pale Moon due to M-C Bug 1188657 landing the configure option as "on" by default.

Turning this feature back off involves simply switching two configure options to zero. 

* In `config/external/nss/Makefile.in` set `DEFAULT_GMAKE_FLAGS += NSS_ALLOW_SSLKEYLOGFILE=0`

* In `security/nss/lib/ssl/ssl.gyp` set `'NSS_ALLOW_SSLKEYLOGFILE=0'`

Ultimately, I think it would make sense to leave this on if --enable-debug is set, otherwise I'm not sure it's a great idea for release builds.

**Comment by wolfbeast** [comment]
This has come up on the forum a few times and a small percentage of users do actively use this. I do not want to switch this off.
