### ISSUE TITLE
Pale Moon creates a content process for the Quickdial page

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#856]
Despite the fact that e10s is disabled in Pale Moon, it creates a content process for the Quickdial page.

1. `Preferences` -> `Tabs` -> `When opening a new tab, show` -> `The Quickdial page`
2. Open a new tab

Initially reported here: https://forum.palemoon.org/viewtopic.php?f=26&t=20734.

28.0.0b2 - affected
28.0.0 - affected
28.1.0 - affected
28.2.0a1 - affected

FTR, the Quickdial page was imported from Basilisk in #517.

**Comment by JustOff** [comment]
I confirm that this regression arose right after #525 was merged. Just amazing how we did not notice before.

**Comment by JustOff** [comment]
I think I found the culprit:

https://github.com/MoonchildProductions/UXP/blob/3555533f7f48582e9d1790489e406946e4f99da3/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#L209

@wolfbeast, what is the best way to handle this? Can we just unconditionally make hidden browser created by `BackgroundPageThumbs.jsm` don't be remote by removing the line above?

**Comment by wolfbeast** [comment]
The latter solution is more complete.
Thanks for your research here -- I had the vague suspicion it might have been a capture process.

Could you make a PR for this?

**Comment by JustOff** [comment]
> Could you make a PR for this?

Done.

> The same should be done in Basilisk.

The fix applies to Toolkit, so all applications are covered.
