### ISSUE TITLE
NSS: MOZ_ASSERT on Unkown cipherSuite during Debug

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#858]
When encountering an unknown cipherSuite in debug mode, all applications will SIGSEGV on the `MOZ_ASSERT` break point defined in `security/manager/ssl/nsNSSCallbacks.cpp:1165`.

I suppose the intention for putting this there is to allow developers to debug the unknown cipher and potentially add it to the list of known cipherSuite cases which resides just above the break point. However, this could also be done with `NS_ASSERTION` in a way that doesn't crash.

[Example crash log for reference.](https://dpaste.de/iXTb/raw)

**Comment by g4jc** [comment]
Possible replacement:
```
-  MOZ_ASSERT(value != 0);
+  // Warn about an unkown cipherSuite value in debug builds.
+  // Replace with MOZ_ASSERT(value != 0) to set a breakpoint here.
+  NS_ASSERTION(value != 0, "Unknown cipherSuite value!");
```

**Comment by wolfbeast** [comment]
That whole function is a no-op; it asserts because the telemetry accumulation list doesn't match the actual list used in the platform. It shouldn't be fixed, it should be yanked because it has no further function without a reporting part that has already been removed.

**Comment by wolfbeast** [comment]
Tag #21
