### ISSUE TITLE
Sync preferences website does not work

### ISSUE THREAD

**Issue by ghost** [MoonchildProductions/UXP#86]
Android and IOS links on Sync settings reditect to a broken website.
![captura de pantalla de 2018-03-28 16 35 39](https://user-images.githubusercontent.com/30677099/38039983-6d677502-32a6-11e8-8b01-54fef1f2e725.png)
![captura de pantalla de 2018-03-28 16 35 42](https://user-images.githubusercontent.com/30677099/38039984-6dbcc3c2-32a6-11e8-81ba-9f567ec1f2ab.png)
![captura de pantalla de 2018-03-28 16 35 56](https://user-images.githubusercontent.com/30677099/38039986-6dedbd4c-32a6-11e8-8ccd-8ed2d2efb2f7.png)

**Comment by wolfbeast** [comment]
I got around to testing this today and the links work by redirecting to a Mozilla page just fine.
Both when logged into a Firefox account and logged out.

**Comment by wolfbeast** [comment]
Closing due to lack of response and not being reproducible.
