### ISSUE TITLE
Redirect for WLAN login pages is not working well.

### ISSUE THREAD

**Issue by RobertZenz** [MoonchildProductions/UXP#860]
When accessing a WLAN which requires a login, the redirect to the login page is not working very well.

When navigating to a site, the warning page is being shown that the connection is insecure and if I want to proceed. However, Firefox f.e. is displaying a small dialog which tells me that the WLAN requires a login and if I want to navigate to the login page.

It would be nice if either Palemoon would automatically redirect correctly, or would work similar to Firefox.

**Comment by khronosschoty** [comment]
I can offer you this tip: This doesn't happen, the warning about being insecure, if you visit a site that doesn't use ssl (or https) -- when you use a site that is just http it should redirect without issues. I wouldn't mind seeing a quality life improvement with something that takes care of this for the user, or informs him better.

**Comment by wolfbeast** [comment]
You can enable the captive portal detection with `network.captive-portal-service.enabled` -- note that this relies on a Mozilla service URL at the moment. We may reinstate this with a URL of our own but have not gotten around to it and disabled the service to avoid pingbacks to Mozilla (and resulting potential privacy issues) from our fork.

**Comment by wolfbeast** [comment]
The service URL has been changed to one of our own, so captive portal detection should work (at least in the unstable).

**Comment by kn-yami** [comment]
It still needs to be manually enabled in Pale Moon, right?

**Comment by wolfbeast** [comment]
Yes, but it can be enabled for testing. I'd rather test before I flip it on ;)

**Comment by RobertZenz** [comment]
I was wondering how exactly is this service working? I mean, does it try to fetch some information from the website and if it sees a redirect, assumes it is a portal?

**Comment by kn-yami** [comment]
Yes, that is basically how its work.

**Comment by wolfbeast** [comment]
It's actually a bit more specific. It tries to get a page and compares the contents of what is received with what it should be. If the content is different, it knows the request did not get to the page it was requesting, and assumes it's a portal.

**Comment by RobertZenz** [comment]
I see, thanks for the explanation.

That's true that it needs to be a little bit more sophisticated, because the portal might not do a redirect but instead delivers its own content (which would be quite evil, but hey). When is that redirect check run anyway? On the first request?

**Comment by kn-yami** [comment]
IIRC it is a time based check. It may also be checked on startup.

**Comment by wolfbeast** [comment]
I believe it's a check on startup and when a network change has been detected/offline-online state changes.

**Comment by wolfbeast** [comment]
@RobertZenz could you please enable the captive portal detection and test it? Set `network.captive-portal-service.enabled` to true; the URL is already correct in the release version of Pale Moon.

**Comment by RobertZenz** [comment]
Unfortunately (or maybe more fortunately) I'm currently not anywhere near such a network, sorry.

**Comment by wolfbeast** [comment]
Okay, I'll clear the milestone for this then. It needs testing before I enable it for everyone in case it misdetects.

**Comment by wolfbeast** [comment]
Considering it's better (both for our servers and for people's privacy) to not have this enabled by default and always running in the background, I've added a UI option (Preferences -> Advanced -> tab "General") to control whether this captive portal detection is enabled or not.

I've also run with the option "enabled" for a while and haven't seen any misdetection so far. I'm fairly confident it's working as-is, but seeing whether this actually works in an actual captive portal network situation is blocking the closure of this issue.

@JustOff Notice the added strings - I'm uplifting this one to the planned 28.3.1 point release.

**Comment by JustOff** [comment]
> I'm uplifting this one to the planned 28.3.1 point release.

Sorry, but I do not think this is a good idea, since considering how things are now organized, we cannot guarantee that the browser will update the language packs until the next major release is published.

If you consider it so important to make these changes to a point release, I would suggest hardcoding these new strings into the corresponding xul file or users using localization will inevitably encounter errors.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.

**Comment by mattatobin** [comment]
Since this string is not in the main window the risk is reduced. While I agree that strings in the main window should be avoided in point releases ones in secondary UIs won't cause a total init failure.

A notice in the release notes should be sufficient in this case.

**Comment by wolfbeast** [comment]
The risk of issues will also be minimized if the language packs are pushed out as early as possible for this change, since users will then most likely already have an updated language pack through their normal update cycle.
