### ISSUE TITLE
The bookmark properties window should focus on the Name Picker text box on init

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/UXP#861]
Steps:
* The Bookmarks sidebar is open
* I do "right-click > New Folder..."
* There is no focus, I have to click in the input before typing the name

Adding this focus would make the process much more convenient!

Other notes:
* For consistency, the same should be done with the entry "right-click > New Bookmark..."
* Firefox already has these focus

<br> Pale Moon 28.1.0 - Windows 7

**Comment by wolfbeast** [comment]
The patch here causes major issues and was backed out.
