### ISSUE TITLE
Throttle back on opportunistic encryption

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#863]
Since our platform upgrade, http connectivity **unconditionally** sets the `Upgrade-Insecure-Requests` header on all navigation connections (requesting a document or subdocument). In addition `altsvc` by default is used for opportunistic encryption as well.
This mechanism is a transparent, under-the-hood opportunistic encryption method that should be under the user's control, considering upgraded requests generally mean more client exposure to the web as part of the authentication step of setting up a secure connection, and it otherwise does not provide a truthful connection state (it remains marked as unencrypted/plain-http) or rewrites page content.

There are other valid reasons (e.g. in-transit caching, corporate monitoring, masking mixed content on sites, https session tracking, etc.) why "hidden" or unrequested encryption of requests is undesired and should be configurable.

- [x] Make sending the request to upgrade unencrypted connections configurable
- [x] Make opportunistic encryption as a whole opt-in for all applications by default
- [x] Make opportunistic encryption option GUI configurable on Pale Moon, encompassing all methods in the browser: `network.http.altsvc.oe` and the new pref.

**Comment by wolfbeast** [comment]
@g4jc You may want to evaluate if you want this enabled for your projects or not.

**Comment by JustOff** [comment]
I'm sorry, but the naming you chose seems a little confusing to me, because Wikipedia [associates](https://en.wikipedia.org/wiki/Opportunistic_encryption) `Opportunistic encryption` with deprecated [HTTP Alternative Services](https://tools.ietf.org/html/rfc7838), whereas we are dealing with [Upgrade Insecure Requests](https://www.w3.org/TR/upgrade-insecure-requests/). 

Wouldn't it be better to just use the name `Upgrade Insecure Requests` in the UI (and `network.http.upgrade-insecure-requests` for the pref)?

**Comment by wolfbeast** [comment]
I'm not sure what you don't understand beyond "search gives me more hits on this -other- mechanism for opportunistic encryption". It is a form of opportunistic encryption and just as transitional as alt-svc (and will likely be deprecated soon enough as well, although having tie-ins with CSP probably makes this a more persistent bugger).

Anything that transparently rewrites http to https when offered by the server is opportunistic encryption.
I don't like the implied meaning of "Upgrade insecure requests" for requests that are labeled "insecure". The term just strikes a wrong chord. If you have a better idea, then let me know.

**Comment by wolfbeast** [comment]
I can, of course, tie this one option together with both alt-svc and upgrade-insecure-request support, flipping both on or off.

**Comment by wolfbeast** [comment]
@JustOff By the way, the wikipedia article you linked in no way clearly associates OE with Alt-Svc specifically -- it provides a generic description of methods used for OE and is clearly as open about it as my interpretation.

**Comment by wolfbeast** [comment]
Updated the original description of this issue for re-implementation.

**Comment by wolfbeast** [comment]
> How about this?

It's an idea, but HTTP Alternative Services isn't controlled overall by the `.oe` pref so that would need clarification. I'd suggest making the group label mention "OE" as an abbreviation in parenthesis, and add "for OE" to the altsvc label, to be correct in what it does.

**Comment by wolfbeast** [comment]
> How about we remove opportunistic encryption et all because it isn't safe or recommended.

You **know** the proponents of encrypt-everywhere will freak and then have a reason to justify their claims of "insecure".

**Comment by JustOff** [comment]
> I'd suggest making the group label mention "OE" as an abbreviation in parenthesis, and add "for OE" to the altsvc label, to be correct in what it does.

![palemoon_2018-11-05_15-32-01](https://user-images.githubusercontent.com/340855/48001045-169e4e80-e110-11e8-81ef-a3adddd0d270.png)

Like this?

> The quote about Firefox rolling out OE doesn't link it specifically to alt-svc. It just mentions that Firefox started implementing a form of OE.

You are probably right, but for me it still looks pretty confusing.

**Comment by wolfbeast** [comment]
> Like this?

Yes, like that. Did you want to do the coding for re-implementation, then? Looks like you're already working on it -- no need for double effort.

**Comment by mattatobin** [comment]
Yeah, they need to upgrade their insecure comments.

Sorry but I don't see how supporting this at all is anything but https everywhere. Also, how does this relate to alt-svc?

**Comment by wolfbeast** [comment]
> Also, how does this relate to alt-svc?

`Alt-Svc` is used among other things for opportunistic encryption because the Alt service will be given priority, following the spec. Webmasters sending alt-svc to an https version of their website will have a browser connect over https in the background, while the presented page will be http:// and marked unencrypted.

**Comment by JustOff** [comment]
> Did you want to do the coding for re-implementation, then? Looks like you're already working on it -- no need for double effort.

Actually, I just hacked around the pref window, but I can take the whole task, if you wish. Do you want to disable both OE methods by default for UXP, but enable them for Basilisk? Does `network.http.upgrade-insecure-requests` look good enough?

**Comment by wolfbeast** [comment]
If you don't have it yet and just hacked around I'll finish what I started.

**Comment by JustOff** [comment]
> If you don't have it yet and just hacked around I'll finish what I started.

Ok.

**Comment by wolfbeast** [comment]
> I see.. Alright, so are we thinking that these features should be bound to one another in a all or nothing way, then?

I was thinking doing that, but since they do cover slightly different areas, keeping the two apart might be OK for as long as they are commonly implemented in mainstream.

**Comment by JustOff** [comment]
String changes were pushed to CrowdIn.
