### ISSUE TITLE
Support AV1 video

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#87]
The groundwork for this was done by Mozilla in https://bugzilla.mozilla.org/show_bug.cgi?id=1314147 as the first browser to get a reference implementation in.
Since the distance from our fork point is relatively small yet (FF55), it _should_ be fairly straightforward to port this across to UXP.
As the codec is still being finalized, there might need to be some adjustments made after this bug's set of patches and related bugs mentioned/linked, and it's imperative that this remains as experimental (and disabled by default) for the time being, but getting this work in now will prevent blocking issues later on.

**Comment by g4jc** [comment]
Related bug: aom update -> https://bugzilla.mozilla.org/show_bug.cgi?id=1445683
