### ISSUE TITLE
Copy and paste does not work for bookmark folders  in Pale Moon

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#872]
As reported [on the forum](https://forum.palemoon.org/viewtopic.php?t=20059) an attempt to copy&paste of bookmark folders results to the error:

```
TypeError: aChildren is undefined
PlacesUIUtils.jsm:156:7
   getChildItemsTransactions resource://app/modules/PlacesUIUtils.jsm:156:7
   PUIU__getFolderCopyTransaction resource://app/modules/PlacesUIUtils.jsm:208:24
   PUIU_makeTransaction resource://app/modules/PlacesUIUtils.jsm:340:18
   PC_paste chrome://browser/content/places/controller.js:1538:9
   PC_doCommand chrome://browser/content/places/controller.js:220:7
```

This is regressed from `Tycho` because of `PlacesUtils.wrapNode` was changed in [bug 1095411](https://bugzilla.mozilla.org/show_bug.cgi?id=1095411).

I see two options to resolve this issue:
* update Pale Moon's `components/places` to match the new `PlacesUtils.wrapNode` API

or
* provide the previous version of `PlacesUtils.wrapNode` using `#ifdef MC_PALEMOON`

If we follow the first option, we must consider that it adds an extra regression that prevents the copying of bookmark folders between two browser instances (see [bug 1177654](https://bugzilla.mozilla.org/show_bug.cgi?id=1177654)). The second option looks quite safe, as `PlacesUtils.wrapNode` in Pale Moon is used only by `components/places/content/controller.js`, however it introduces some inconsistency between UXP applications. I'm not sure which one is better.

**Comment by wolfbeast** [comment]
The new API is a lot leaner and simpler than the old code. I'd say adapt the Pale Moon fe to the new API, and deal with the follow-up bug.

**Comment by JustOff** [comment]
The problem is that the old `wrapNode` function processes folders recursively and then serialize and places the full result to the clipboard, while the new `wrapNode` only stores the outer folder name and id. This means that with the new API we can never copy folders between browsers (or profiles), just by design.

Are you ok with that?

**Comment by wolfbeast** [comment]
Yes I'm fine with that - I would not have expected that to ever work to begin with.
