### ISSUE TITLE
Remove VR hardware support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#881]
This is total nonsense for a web browser (or anything else building on UXP).

- [x] Remove Oculus support
- [x] Remove webidl interfaces
- [x] Remove VR content manager from IPC
- [x] Remove DOM parts
- [x] Cleanup misc parts

**Comment by wolfbeast** [comment]
I think the commit has everything, but verification of buildability on Linux would be appreciated -- might have missed a tidbit or two.

**Comment by JustOff** [comment]
Basilisk build error:

`d:/UXP/dom/gamepad/GamepadManager.cpp(31): fatal error C1083: Cannot open include file: 'VRManagerChild.h': No such file or directory`

**Comment by trav90** [comment]
Pale Moon build fine on Linux however Basilisk chokes with the same error as JustOff reports above.

**Comment by trav90** [comment]
All good building on Linux now. :+1:
