### ISSUE TITLE
In Bookmarks sidebar, right-click command "Open All in Tabs" is broken

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/UXP#882]
How to reproduce:
* Open Bookmarks sidebar
* In the Search input, type something so that your bookmarks are filtered to a few links
* Right-click in empty space in the sidebar
* Click on "Open All in Tabs"

Current result:
* Nothing happens

Expected:
* Links should be loaded

I'm on Pale Moon 28.2.1 (Windows 7 64-bit), and it's very presumably a regression from the last versions.
**edit:** according to below messages, the bug seems to be quite old actually; my bad, I wasn't using this command on Pale Moon previously, only on Firefox, hence my confusion.

**Comment by mattatobin** [comment]
So it never worked :P

**Comment by mattatobin** [comment]
Works for me..

**Comment by mattatobin** [comment]
I don't think this ever worked at our UI code level.. So, fix it..

**Comment by JustOff** [comment]
Last bad: 2014-07-07
First good: 2014-07-08
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1dc6b294800d&tochange=c45f6e6d6005
Suspect: https://bugzilla.mozilla.org/show_bug.cgi?id=1006989

**Comment by mattatobin** [comment]
33.0a1 sounds about right..

**Comment by vlakoff** [comment]
As a workaround, you can:

1. Click on an empty space in the filtered bookmarks pane (to change focus from the search input to the bookmarks themselves).
2. Do "Ctrl+A" to select all these bookmarks.
3. Right-click (works on the bookmarks as well as on empty space) and select "Open All in Tabs".

Though, it would be better if the bug could be fixed :)

**Comment by mattatobin** [comment]
.

**Comment by vlakoff** [comment]
As a workaround, you can:

1. Click on an empty space in the filtered bookmarks pane (to change focus from the search input to the bookmarks themselves).
2. Do "Ctrl+A" to select all these bookmarks.
3. Right-click (works on the bookmarks as well as on empty space) and select "Open All in Tabs".

Though, it would be better if the bug could be fixed :)
