### ISSUE TITLE
When you view source from browser console it produces a warning in the console

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/UXP#884]
If you're logging javascript warnings at least. This:

    ReferenceError: reference to undefined property "shouldWrap"[Learn More]     viewSource-content.js:132:1

which comes from omni.ja!/chrome/toolkit/content/global

To reproduce:

Open browser console from Tools/Web Developer/
Enable javascript errors/warnings
Visit pretty much any website (this one will do)
At the extreme right you will see file names and line number
Click on any of them
The above message is produced every time you click

**Comment by ThosRTanner** [comment]
Oh come on. In the browser console when it produces messages, it has file and line numbers. Click on one. You get this message.

Two issues is not 'spamming us with this shit'.

**Comment by wolfbeast** [comment]
> Two issues is not 'spamming us with this shit'.

Not the first time, though, and just saying "it has line numbers" doesn't really help. It may show where the warning (not actually an error...) is thrown but not in what situation.
**Please provide exact steps to reproduce.**

**Comment by ThosRTanner** [comment]
updated issue. hope that helps.

**Comment by mattatobin** [comment]
Which application?

**Comment by ThosRTanner** [comment]
Palemoon 28.2.1 64 bit on windows 10 version 1803 build 17134.345

**Comment by ThosRTanner** [comment]
Oddly enough, this is only an issue from the browser console. i don't get the same message from the error console when clicking on filename/linenumber to display a file.

**Comment by ThosRTanner** [comment]
I discovered I have `javascript.options.strict` in about:config set to true.

**Comment by mattatobin** [comment]
And you didn't think to check your settings or check a clean profile?

Thanks for wasting our time.
