### ISSUE TITLE
Clean up the Pale Moon tree

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#889]
- [x] Move largely self-contained components to `components`
  - [x] abouthome
  - [x] newtab
  - [x] pageinfo
  - [x] sync
- [x] Clean up build files for format and structure
  - [x] moz.build
  - [x] jar.mn

**Comment by JustOff** [comment]
Speaking of cleanup, do we really need `/application/palemoon/base/content/test/general/audio.ogg`?
