### ISSUE TITLE
Server name being "searched" by Google

### ISSUE THREAD

**Issue by pmprog** [MoonchildProductions/UXP#89]
I'm running Basilisk 2018.02.14 (64bit), and when I type "http://myserver" in the URL bar, it searches Google for my server name.

I have already been into about:config and set "keyword.enabled" to false and "browser.fixup.alternate.enabled" to false. I also do not have Google set as my default search engine (in fact, I've actually explicitly removed it from the Preferences, so it's not even an option).

How do I stop Basilisk from leaking server names, especially to search engines I don't use?

Cheers

**Comment by wolfbeast** [comment]
Basilisk doesn't search Google - I just verified that all it does (as intended) is try a DNS lookup first for `myserver` and then a lookup for the fixed up versions with `www` and `.com`, and that is all -- giving a "cannot find server" response afterwards. Basilisk also doesn't include Google as a search engine, so it's likely something outside of the browser that catches NXDOMAIN responses and redirects you to Google Search.

**Comment by pmprog** [comment]
Thanks for the reply.

I've just got home and tried it on my personal PC and yes, it does as I expected, and as you said, so must clearly be something with the way the network is set up at my workplace.

Sorry to have raised a non-issue
