### ISSUE TITLE
Cleanup old code in the media subsystem

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#894]
The massive endeavor of rewriting the media subsystem to work with the MediaFormatReader that I started in the Tycho era is now mostly complete in UXP. However, there are several places where bits of the old MediaDecoderReader system are still in our tree. Most of this code in our tree was either overlooked by Mozilla or purposely left to be used by ancient and now unsupported OS's. In addition to some of the DecoderReaders themselves, there is also several code paths that should either be removed completely or optimized to work with the MediaFormatReader directly, as well as at least one frame parser that should be removed.

Net result of all this is that quite a bit of dead code will be removed, the media system will no longer cater to old unsupported OS's in some circumstances and for some formats, and the code as a whole will be more easily maintainable without all this extra junk.

**Comment by wolfbeast** [comment]
I feel sorry for the people still trying to monkey-patch for XP instead of forking. This will throw a wrench in the works for them. Ohwell...

**Comment by mattatobin** [comment]
So I guess there isn't likely there is anything new coming for this issue. So do we keep it open or just close it as good enough?
