### ISSUE TITLE
Download Button styling has pressed state when downloading files on Windows 10

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#904]
Does not seem to be a problem in Windows 7.

![qa0jxqs](https://user-images.githubusercontent.com/3889475/49850565-fb2c0080-fdab-11e8-830a-9008a58af852.png)

----

Reported by user via IRC https://freenode.logbot.info/palemoon/20181212#c1871355

**Comment by Lootyhoof** [comment]
This is intended. See: https://github.com/MoonchildProductions/Pale-Moon/issues/849

**Comment by mattatobin** [comment]
I see.. I think MAYBE it should use something other than the pressed styling in that case. But I dunno. I don't use the thing, and it doesn't seem to have the same behavior on Windows 7... So what is that about?

**Comment by Lootyhoof** [comment]
It's only shown on Windows 7 in a dark `lwtheme` (i.e. when `#nav-bar` has the `brighttext` element). It's shown elsewhere (Win8/10) because those can use dark window frames.

It's also not the pressed state; that's actually lighter.

![Pressed](https://i.imgur.com/BaCiUrv.png)

**Comment by wolfbeast** [comment]
As-intended.
