### ISSUE TITLE
Finish CSS Masking implementation

### ISSUE THREAD

**Issue by kn-yami** [MoonchildProductions/UXP#908]
The CSS Masking was mostly implemented before UXP was forked. Mozilla implementation of this feature was shipped in Firefox 53. The bugs that where implanted after UXP was forked are listed below (hopefully I did not miss anything):
- [x] [Bug 1251161](https://bugzilla.mozilla.org/show_bug.cgi?id=1251161)  - Ship CSS positioned mask support on beta & release channels
    - [x] [Bug 1319667](https://bugzilla.mozilla.org/show_bug.cgi?id=1319667) - Enable mask longhands on SVG elements
        - [x] [Bug 1303623](https://bugzilla.mozilla.org/show_bug.cgi?id=1303623) - Parsing mask-clip/mask-origin: fill-box|stroke-box|view-box|no-clip values
        - [x] [Bug 1311270](https://bugzilla.mozilla.org/show_bug.cgi?id=1311270) - Implement rendering of mask-clip/mask-origin: fill-box|stroke-box|view-box|no-clip values
        - [x] [Bug 1341149](https://bugzilla.mozilla.org/show_bug.cgi?id=1341149) - Use of uninitialized value in SetupImageLayerClip
    - [x] [Bug 1322286](https://bugzilla.mozilla.org/show_bug.cgi?id=1322286) - Crash near null [@nsSVGMaskFrame::GetMaskForMaskedFrame]
    - [x] [Bug 1329091](https://bugzilla.mozilla.org/show_bug.cgi?id=1329091) - mask-position animation out-of-order

[Bug 1338767](https://bugzilla.mozilla.org/show_bug.cgi?id=1338767) may or may not be related.

**Comment by wolfbeast** [comment]
If I understood correctly from IRC you're working on this? Just so I know it's assigned and prevent double work done :)

**Comment by wolfbeast** [comment]
@kn-yami Thank you very much for your work on this!
