### ISSUE TITLE
Release Basilisk Christmas 2018 edition

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#913]
We should publish another Basilisk version this week. When do you have time, Travis?

**Comment by wolfbeast** [comment]
tag @trav90

**Comment by trav90** [comment]
Today or tomorrow would be easiest for me, but I can do any day this week except for Thursday.

**Comment by wolfbeast** [comment]
Let's do today -- still have about 12 hours to make a dated build.

**Comment by trav90** [comment]
Sounds like a plan. :+1:

**Comment by wolfbeast** [comment]
I'm working on the release notes now. We do have AV1 support for MP4 now, right?

**Comment by trav90** [comment]
Yes AV1 in supported in both WebM and MP4 now.

**Comment by wolfbeast** [comment]
Okay!
Intended release notes are then:

This is a development and security release.

- Added a preference (network.http.upgrade-insecure-requests) to allow disabling requests for opportunistic encryption.
- Removed more telemetry code from the platform.
- Added experimental support for the AV1 video codec for MP4 containers.
- Cleaned up some media handling code, removing obsolete components for older target platforms.
- Ported all applicable security fixes from Gecko/64. Most of these fixes were merely defense-in-depth.
- Fixed a crash when using http pipelining over some broken proxies.
- Enhanced the WebP decoder to properly handle animated lossy and lossless WebP.
- Removed VR hardware support (both display and input types) from the platform.
- Updated the GMP update service URL to improve compatibility with DRM-encumbered media.
- Removed support for Firefox Accounts and changed the Sync client to work with Sync 1.1 (Weave).
    The default server for using Sync is now the Pale Moon Sync server.
    Please see [this announcement](https://forum.palemoon.org/viewtopic.php?f=61&t=21091) on the forum for more details.
- Updated NSPR to 4.20.
- Updated NSS to 3.41, finalizing our platform support for TLS 1.3.
- Fixed a spec compliance issue with the location.protocol setter.

**Comment by JustOff** [comment]
Perhaps it worth to mention that AV1 is still disabled by default.

**Comment by wolfbeast** [comment]
Edited (cursive) to inform users who don't understand what experimental means and don't take note of (disabled by default) in the previous relnotes.

**Comment by wolfbeast** [comment]
@trav90 let me know when you have uploaded the linux binaries so I can publish.

**Comment by trav90** [comment]
@wolfbeast Linux binaries are uploading now as I post this comment.

**Comment by wolfbeast** [comment]
Published
