### ISSUE TITLE
Use the new FFmpeg decode API with recent FFmpeg version

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#915]
Beginning with libavcodec 58 (which we now use after #806), the older avcodec_decode_video2 API is broken and will in some instances cause frames to be dropped (giving the appearance of stuttering) when playing VP9 video.

Our FFmpeg code needs to be updated so that libavcodec 58+ will use the new API.

**Comment by wolfbeast** [comment]
Assuming this is solved by way of #921
