### ISSUE TITLE
Perpetual evaluation of GTK3 support

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/UXP#92]
There were a lot of GTK3-related patches that landed upstream after our Take 2 fork off point and these should be evaluated and ported to prevent any potential regressions in future GTK3 products released.

This will require much research and testing so as to not break our GTK2 support (which from my research thus far appears to be completely intact).

I've been working on this the past couple days and will submit a PR once thorough research and testing are complete.

**Comment by trav90** [comment]
Current status on this is that our GTK3 support is now on-par with current Basilisk-release and GTK2 is still functional and can be used. Leaving this issue open for now as there are additional (lower priority) GTK3-related patches that should be researched and ported if found desirable.

**Comment by mattatobin** [comment]
Status update?

**Comment by trav90** [comment]
This issue likely can be closed as I've not seen any complaints here or on the forum about GTK3 related issues for Basilisk. This issue can be reopened or a new specific issues can be opened if any problems do crop up in the future.
