### ISSUE TITLE
[Pale Moon] Option for disabling HSTS sets the wrong preference

### ISSUE THREAD

**Issue by Ascrod** [MoonchildProductions/UXP#930]
While poking through the HSTS code, I noticed that the checkbox in Pale Moon's security preferences for enabling or disabling the use of HSTS appears to toggle the use of the preload list, not the entire HSTS feature as the box's label seems to indicate. Personally I'm all for using HSTS all the time, but if this option is going to be available, I think it should either do what it says or say what it does.

To make this checkbox disable the entire HSTS feature, I believe [this commit](https://github.com/MoonchildProductions/Pale-Moon/commit/9bc65e235b62c4e84c69f301bd89de29769f4abf) can be ported from Tycho, and the checkbox's preference changed from 'preloadlist' to 'enabled'.

Thoughts? I can submit a PR for this if desired.

**Comment by wolfbeast** [comment]
Hmm.. not sure where this went wrong -- it should enable/disable the entire feature, not the preloadlist.

Feel free to offer a PR.

**Comment by wolfbeast** [comment]
Seems this was a mistake made by @trav90 in e370a636baa5435c7c57a3aebf2fca647023b7c8 -- assuming the pref was renamed while it was actually a new pref introduced in Tycho.
Thanks again for catching this -- I certainly wouldn't have ever noticed.

**Comment by trav90** [comment]
Yeah, that was my mistake.. Thanks for catching @Ascrod.

**Comment by Ascrod** [comment]
Happy to help @trav90. This should be fixed with PR #931, so I'll close this issue.
