### ISSUE TITLE
Unable to install dictionary in palemoon 28.3.0

### ISSUE THREAD

**Issue by vimes666** [MoonchildProductions/UXP#933]
When I was filling out a webform I wanted to check the spelling in dutch by clicking the right mouse button.
Since I do not have a dutch dictionary installed I chose 'Add Dictionaries'. I was led to [this](https://addons.mozilla.org/en-US/firefox/language-tools/) mozilla(?) page.
I selected the dutch dictionary and was presented with an install button saying '[Only with Firefox-Get Firefox Now](https://addons.mozilla.org/en-US/firefox/addon/woordenboek-nederlands/)'.
It looks like this functionality is broken by mozilla.
Is there another way to add a dictionary?

I am using palemoon in linux mint mate 19.1(64b)

**Comment by JustOff** [comment]
You should install the non-WebExtensions version of the dictionary from the all versions history page.

For the Dutch it's here: https://addons.mozilla.org/en-US/firefox/addon/woordenboek-nederlands/versions/

**Comment by JustOff** [comment]
@wolfbeast, it seems we need to revert https://github.com/MoonchildProductions/UXP/commit/93705a7d00b2b09ee9b5d036b71c5be79b8d10a1, since after that Mozilla does not allow to download dictionaries.

**Comment by vimes666** [comment]
@Justoff:  I cant do anything on the first link, same 'Only with Firefox—Get Firefox Now' buttons,
but clicking your second link succesfully installed the dutch dictionary. Thanks you!

**Comment by JustOff** [comment]
@mattatobin, @wolfbeast 
Perhaps we should consider hosting dictionaries at https://addons.palemoon.org, as it seems that Mozilla is going to soon remove all the non-WebExtensions version of them from the AMO?

**Comment by mattatobin** [comment]
Yes, we do need to do do that. It would be very helpful if someone would collect the last versions that work for our platform for me. Then I will add a static list to Phoebus 2.0.

I just want the last known working incarnations.. We can take a look see if future converting of the webex versions back to our format is possible.

**Comment by JustOff** [comment]
> It would be very helpful if someone would collect the XPI and License info for the last versions that work for our platform for me. I just want the last known working incarnations.

This should be not so difficult to do using the [AMO API](https://addons-server.readthedocs.io/en/latest/topics/api/), I'll try to handle it.

> We can take a look see if future converting of the webex versions back to our format is feasible.

Yes, I have already verified that reverse conversion can be done easily.

> Also, is there a timeline for the removal?

AFAIK, there is no timeline yet, although support for WE dictionaries [has already been uplifted to ESR60](https://bugzilla.mozilla.org/show_bug.cgi?id=1410214#c56), so this can happen at any time.

**Comment by mattatobin** [comment]
I don't need manifest files.. It will be a simple list and will follow the langpack model as far as the `SITE` goes in Phoebus 2.0.

**Comment by JustOff** [comment]
> We just need to simply have a list and the latest versions. Which @kn-yami is retrieving and making sure only open source ones are gathered.

If @kn-yami is already engaged in this, then I will step aside to avoid double work. I'm fine with this, but next time it would be good to know right away if someone takes the task assigned to me.

**Comment by wolfbeast** [comment]
please do communicate assignments -- it avoids not only double work but frustration on the part of contributors.

**Comment by kn-yami** [comment]
Sorry. I will try to remember to communicate such things next time.

**Comment by mattatobin** [comment]
@kn-yami I think that was directed towards me. Sorry I didn't update the issue. I was busy working on Phoebus in the middle of my 15 hour marathon when @kn-yami volunteered.

**Comment by wolfbeast** [comment]
Either/or, really. Just something to keep in mind for next time when someone else might already have taken responsibility for a task.

**Comment by JustOff** [comment]
> I think that was directed towards me.

I'm glad we sorted out this little misunderstanding, thank you.
