### ISSUE TITLE
Crashes with some animated webp images.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#940]
Animated image implementations wouldn't be complete without at least some crash bugs ;-)

URL: https://i.giphy.com/media/3tls0c4QUHKUg/giphy.webp

This will crash due to some buffer state issues. I have a good idea where this comes from (I think there's a rather blatant bug in the decoder when dealing with chunks) so self-assigning this.

**Comment by roytam1** [comment]
it seems that buffer is not fully filled and tail portions seem to be uninitialized

**Comment by wolfbeast** [comment]
> 
> 
> it seems that buffer is not fully filled and tail portions seem to be uninitialized

The buffer is filled, but fragmented -- the frame decoder expects a buffer to be in a contiguous chunk which isn't the case, so is trying to read metadata from the wrong chunk in memory.
