### ISSUE TITLE
Pale Moon: Bookmark backup import/export is using deprecated file access.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#941]
Importing/exporting bookmark backups from/to JSON is passing an `nsIFile` object to a function; this is a deprecated file access method and should be converted to using `OS.File`.

*Restore:*

> 18:10:05.821 DEPRECATION WARNING: Passing an nsIFile to BookmarksJSONUtils.importFromFile is deprecated. Please use an OS.File path string instead.
You may find more details about this deprecation at: https://developer.mozilla.org/docs/JavaScript_OS.File
Callstack:
resource://gre/modules/BookmarkJSONUtils.jsm 91 BJU_importFromFile
chrome://browser/content/places/places.js 474 PO_restoreBookmarksFromFile/<
resource://gre/modules/Task.jsm 336 TaskImpl_run
resource://gre/modules/Task.jsm 277 TaskImpl
resource://gre/modules/Task.jsm 252 asyncFunction
resource://gre/modules/Task.jsm 166 Task_spawn
chrome://browser/content/places/places.js 472 PO_restoreBookmarksFromFile
chrome://browser/content/places/places.js 421 PO_onRestoreMenuItemClick/<
resource://gre/modules/Task.jsm 336 TaskImpl_run
resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js 932 process
resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js 813 walkerLoop
resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js 747 scheduleWalkerLoop/<
 1 Deprecated.jsm:85
	warning resource://gre/modules/Deprecated.jsm:85:5
	BJU_importFromFile resource://gre/modules/BookmarkJSONUtils.jsm:91:7
	PO_restoreBookmarksFromFile/< chrome://browser/content/places/places.js:474:15
	next self-hosted:1171:9
	TaskImpl_run resource://gre/modules/Task.jsm:336:41
	TaskImpl resource://gre/modules/Task.jsm:277:3
	asyncFunction resource://gre/modules/Task.jsm:252:14
	Task_spawn resource://gre/modules/Task.jsm:166:12
	PO_restoreBookmarksFromFile chrome://browser/content/places/places.js:472:5
	PO_onRestoreMenuItemClick/< chrome://browser/content/places/places.js:421:11
	next self-hosted:1171:9
	TaskImpl_run resource://gre/modules/Task.jsm:336:41
	bound TaskImpl_run self-hosted:958:17
	process resource://gre/modules/Promise-backend.js:932:23
	walkerLoop resource://gre/modules/Promise-backend.js:813:7
	bound walkerLoop self-hosted:914:17
	bound bound walkerLoop self-hosted:914:17
	scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:747:11

*Backup:*

> 18:14:54.698 DEPRECATION WARNING: Passing an nsIFile to BookmarksJSONUtils.exportToFile is deprecated. Please use an OS.File path string instead.
You may find more details about this deprecation at: https://developer.mozilla.org/docs/JavaScript_OS.File
Callstack:
resource://gre/modules/BookmarkJSONUtils.jsm 138 BJU_exportToFile
chrome://browser/content/places/places.js 502 fpCallback_done
 1 Deprecated.jsm:85
	warning resource://gre/modules/Deprecated.jsm:85:5
	BJU_exportToFile resource://gre/modules/BookmarkJSONUtils.jsm:138:7
	fpCallback_done chrome://browser/content/places/places.js:502:9

**Comment by Ascrod** [comment]
Unless I'm mistaken, the fix for this is simply replacing `nsIFile` with `nsIFile.path` in two calls to `BookmarkJSONUtils` in Pale Moon's `places.js` code.

I can PR this.
