### ISSUE TITLE
incorrect display of the sound icon on the tab

### ISSUE THREAD

**Issue by bogachenko** [MoonchildProductions/UXP#942]
#638 This is probably a bug, due to the Windows 10 theme.
She white. And it's hard to notice. Theme standard (for win 10), version of 28.3.1
![default](https://user-images.githubusercontent.com/8535285/51721912-8d7e2000-204b-11e9-9552-719cf294d12f.png)

When switching to another window, the icon is displayed correctly.
![default](https://user-images.githubusercontent.com/8535285/51721996-bef6eb80-204b-11e9-8727-759b555344f6.png)
 @JustOff  @wolfbeast @mattatobin

**Comment by bogachenko** [comment]
If you turn off the "Show color in the window title" option in the Windows settings,
![default](https://user-images.githubusercontent.com/8535285/51735643-d8b22600-207f-11e9-86f1-69f2987fec3f.png)


 everything is displayed correctly. But if you return it back, see above what happens.

**Comment by Ascrod** [comment]
I do not see this in my installation of Windows 10 version 1803 when I enable accent colors in the title bar.

What version of Windows 10 are you using?

![capture](https://user-images.githubusercontent.com/32915892/51746820-676d7580-2075-11e9-8e92-dce45d97a178.png)

**Comment by bogachenko** [comment]
@Ascrod win10x64 ltsb 1607 (year 2016)

**Comment by FranklinDM** [comment]
Confirmed, it only happens when tabs are on top and when using the accent color on the title bar. Will come up with a fix soon.
