### ISSUE TITLE
Re-implement Configurable Security Policies (CAPS)

### ISSUE THREAD

**Issue by ThatBrickster** [MoonchildProductions/UXP#957]
I've been looking for a way to get per-domain JS blocking working without an extension. The prefs.js entries are along the lines of this (taken from https://www-archive.mozilla.org/projects/security/components/ConfigPolicy.html):
user_pref("capability.policy.default.javascript.enabled", "noAccess");
user_pref("capability.policy.jsok.javascript.enabled", "allAccess");
user_pref("capability.policy.jsok.sites", "http://www.example.com/");
user_pref("capability.policy.policynames", "jsok");

The prefs above rely on CAPS. As of Firefox 29, Mozilla removed support for them. They added back a few dribs and drabs in v30 and v41, allowing local file links and click-to-copy to work again. (https://www.fxsitecompat.com/en-CA/docs/2014/per-domain-configurable-security-policies-are-no-longer-available/)

CAPS are quite a powerful feature but I'd imagine it would be a big undertaking. I'm currently using uMatrix 1.1.4 for my needs in lieu of this to block third-party JS.

**Comment by wolfbeast** [comment]
Sorry this is a big fat WONTFIX. No matter how powerful a feature it was once upon a time, bringing it back as a pref glob while much more intuitive extension-based solutions exist that achieve the exact same is not in line with our approach of what features are maintained in the core by us.
Please use any of the available JS blocking extensions to control JS permissions on a per-domain basis.
