### ISSUE TITLE
Release Basilisk, Feb 2019 edition

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#966]
Depending on if there is a solution for #962 or not we may be releasing Basilisk with or without functional DRM this month, but a release has to be made either way for other reasons.

For release, the following points need to be addressed:
- [x] Disable WebExAM in confvars
- [x] Fix applicable sec issues from the FF 65.0 cycle
- [x] Merge master to release branch
- [x] Write release notes
- [x] Synchronize build date with @trav90 
- [x] Build
    - [x] Windows
    - [x] Linux
- [x] Publish

**Comment by trav90** [comment]
Unfortunately I don't think I will have a solution to #962 prior to needing to publish the next release.

Just about any build date should work for me.

**Comment by wolfbeast** [comment]
That's unfortunate but so it goes. 
I still don't understand why Google just refuses to reply to my e-mails about licensing Widevine. Isn't it in their own best interest to have as wide as possible adoption?

**Comment by wolfbeast** [comment]
Does the 11th of Feb sound OK to you, @trav90 ?

**Comment by trav90** [comment]
Yup works for me.

Been working on the Widevine issue all day; hoping to be able to have a last-minute patch but we'll see.

**Comment by trav90** [comment]
Yup works for me!

Been working on the Widevine issue all day; still hoping to have a last minute patch but we'll see.

**Comment by trav90** [comment]
Linux build is uploading to FTP as I post this.

**Comment by wolfbeast** [comment]
Crap, going to have to rebuild windows, I forgot to explicitly enable the updater.
