### ISSUE TITLE
Preload the permissions manager with permissions file

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#968]
At some point Mozilla switched from pre-loading permission manager items from naked default preferences to using an app-central permissions file.

We should adopt this in Pale Moon at some point. This would render `xpinstall.whitelist.add` obsolete.

----

http://xref.palemoon.org/uxp-trunk/source/application/basilisk/app/permissions
http://xref.palemoon.org/uxp-trunk/source/application/basilisk/app/moz.build#21
http://xref.palemoon.org/uxp-trunk/source/application/basilisk/app/profile/basilisk.js#364
http://xref.palemoon.org/uxp-trunk/source/application/basilisk/installer/package-manifest.in#624

**Comment by wolfbeast** [comment]
> This would render xpinstall.whitelist.add obsolete.

So what if users want add their own preferred hosts to install XPIs from with minimal fuss?

**Comment by mattatobin** [comment]
This has nothing to do with users. There is also a UI for that called the Permissions Manager both proper and webby.

**Comment by wolfbeast** [comment]
Well, there is no UI to permanently add sites to the list of "don't bug me about this site" for XPI installations, as far as I know -- so it'd definitely be desirable to keep the pref or to come up with a UI if the pref is removed.

**Comment by mattatobin** [comment]
There absolutely is:
![xpinstall-pref](https://user-images.githubusercontent.com/3889475/52535462-9265f380-2d1c-11e9-8190-8cadce003a67.png)

Additionally it can be controlled tho not with arbitrary sites via:
![xpinstall-pageinfo](https://user-images.githubusercontent.com/3889475/52535466-a4479680-2d1c-11e9-89c3-274dbd056fef.png)

Same thing but this also allows or blocks for all sites:
![xpinstall-about](https://user-images.githubusercontent.com/3889475/52535468-a873b400-2d1c-11e9-8912-0006e87b1ea4.png)

**Comment by wolfbeast** [comment]
I stand corrected - I didn't think of the preferences window -- the doorhanger UI most definitely doesn't offer it.
