### ISSUE TITLE
Split applications off from platform

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#969]
For organizational reasons and to make it easier for other developers to build UXP applications, we need to split our applications out into separate repositories and set the build system up to do a comm-like build where application code is application code, and the platform is pulled in as a submodule.

Advantages:
- Clear separation of applications (releases/etc.)
- Independent development possible on arbitrary back-end commits
- Clarity about the platform/application structure for the platform
- Separation of application-specific issues that aren't necessarily relevant for the platform, and v.v.
- Uniform build procedure for all UXP applications

Disadvantages:
- Some issues that impact both FE and BE will have to be split, with FE patches including a branch pointer shift.

This should be tackled later in 2019, probably Q4.

**Comment by mattatobin** [comment]
As per IM discussion that took place but wasn't documented: post commization of the MCP Phoenix-class browsers will result in an official stable release branch being established for Pale Moon.

This will allow for Pale Moon and those other applications that match platform states with Pale Moon to easily target a consistant release state for comparative and debug reasons. BinOC projects will also follow this branch for release.

Basilisk being rolling will likely use trunk at arbitrary stable luls between major development cycles.

Individual projects will decide their own commit points of the platform. The current hacks that allow the application subdirectory to work will be kept for those whom already use it.

**Comment by mattatobin** [comment]
Pale Moon has been returned back to its original repository.

**Comment by mattatobin** [comment]
Depends on https://github.com/MoonchildProductions/Pale-Moon/issues/1697

**Comment by JustOff** [comment]
I have a problem building on win32:

```
 0:48.11 Unified_cpp_editor_libeditor0.cpp
 0:48.12 d:\UXP-build-palemoon\dist\include\mozilla/css/Declaration.h(24): fatal error C1083: Cannot open include file:
'nsCSSDataBlock.h': No such file or directory
 0:48.14
 0:48.19 In the directory  /d/UXP-build-palemoon/editor/libeditor
 0:48.20 The following command failed to execute properly:
 0:48.21 d:/UXP-build-palemoon/_virtualenv/Scripts/python.exe -m mozbuild.action.cl cl.EXE -FoUnified_cpp_editor_libedit
or0.obj -c -Id:/UXP-build-palemoon/dist/stl_wrappers -DNDEBUG=1 -DTRIMMED=1 -DWIN32_LEAN_AND_MEAN -D_WIN32 -DWIN32 -D_CR
T_RAND_S -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DOS_WIN=1 -D_UNICODE -DCHROMIUM_BUILD -DU_STATIC_IMPLEMENTATION -DUNICODE -
D_WINDOWS -D_SECURE_ATL -DCOMPILER_MSVC -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXU
L -Id:/Pale-Moon/platform/editor/libeditor -Id:/UXP-build-palemoon/editor/libeditor -Id:/Pale-Moon/platform/dom/base -Id
:/Pale-Moon/platform/editor/txmgr -Id:/Pale-Moon/platform/extensions/spellcheck/src -Id:/Pale-Moon/platform/layout/gener
ic -Id:/Pale-Moon/layout/style -Id:/Pale-Moon/platform/layout/tables -Id:/Pale-Moon/platform/layout/xul -Id:/UXP-build-p
alemoon/ipc/ipdl/_ipdlheaders -Id:/Pale-Moon/platform/ipc/chromium/src -Id:/Pale-Moon/platform/ipc/glue -Id:/UXP-build-p
alemoon/dist/include -Id:/UXP-build-palemoon/dist/include/nspr -Id:/UXP-build-palemoon/dist/include/nss -MD -FI d:/UXP-b
uild-palemoon/mozilla-config.h -DMOZILLA_CLIENT -TP -nologo -wd5026 -wd5027 -Zc:sizedDealloc- -wd4752 -wd4091 -wd4577 -D
_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -utf-8 -arch:SSE2 -FS -Gw -wd4251 -wd4244 -wd4267 -wd4345 -wd4351 -wd4800 -wd4595 -
we4553 -GR- -Zi -O2 -GS- -Oy- -Fdgenerated.pdb d:/UXP-build-palemoon/editor/libeditor/Unified_cpp_editor_libeditor0.cpp
 0:48.27 d:/Pale-Moon/platform/config/rules.mk:884: recipe for target 'Unified_cpp_editor_libeditor0.obj' failed
 0:48.29 mozmake.EXE[4]: *** [Unified_cpp_editor_libeditor0.obj] Error 1
```

It seems this path is wrong: `-Id:/Pale-Moon/layout/style`

**Comment by mattatobin** [comment]
You are building win32 or you are building ON win32? Also, those paths don't make any sense and it is out of context. Though I am doing a win32 build now.

**Comment by JustOff** [comment]
win32 target on win64 host, the path above is only one that has no `platform` included, it should be `-Id:/Pale-Moon/platform/layout/style` like all others.

**Comment by mattatobin** [comment]
Yeah.. and I don't understand why.. IF this was something specifically to do with the comm-configuration then Borealis and Interlink as well as the Hyperbola applications would ALSO fail.

As I said, I am doing a win32 build right now.

**Comment by mattatobin** [comment]
Is that objdir reused?

**Comment by JustOff** [comment]
Clobber build is failed exactly the same way.

**Comment by mattatobin** [comment]
What is your directory structure and what is your `mozconfig`

**Comment by JustOff** [comment]
I'm sorry, but it's 2:50am local time, I'll provide all you requested in about 10 hours, as it's really hard to collect it right now using vnc session from my tablet.

**Comment by wolfbeast** [comment]
Not entirely sure why you immediately jumped on building this when stuff is still being organized and in-progress :)
Anyway, just provide when you're awake again; I'm sure it's something like setting the MOZ_OBJDIR to an absolute path or something.

**Comment by JustOff** [comment]
I had to manually purge all the `*.pyc` files (some of them were even from 2017), and now everything builds properly. Apparently, this because I continued to work in the old PM repo.

It seems I really shouldn't have to build at night, sorry for the noise.

**Comment by mattatobin** [comment]
Well it is good to know of that case so if someone runs into it we have an answer.

**Comment by adeshkp** [comment]
Mac build is currently busted. Fix is this:
```diff --git a/palemoon/base/content/baseMenuOverlay.xul b/palemoon/base/content/baseMenuOverlay.xul
index bccdec265..dc3d5ec6e 100644
--- a/palemoon/base/content/baseMenuOverlay.xul
+++ b/palemoon/base/content/baseMenuOverlay.xul
@@ -29,7 +29,7 @@
         <menuitem id="menu_mac_show_all" label="&showAllAppsCmdMac.label;"/>
     </menupopup>
 <!-- Mac window menu -->
-#include ../../../../toolkit/content/macWindowMenu.inc
+#include ../../../platform/toolkit/content/macWindowMenu.inc
 #endif
 
 #ifdef XP_WIN
diff --git a/palemoon/themes/osx/shared.inc b/palemoon/themes/osx/shared.inc
index ef27746a3..7b77db28a 100644
--- a/palemoon/themes/osx/shared.inc
+++ b/palemoon/themes/osx/shared.inc
@@ -1,4 +1,4 @@
-%include ../../../../toolkit/themes/osx/global/shared.inc
+%include ../../../platform/toolkit/themes/osx/global/shared.inc
 %include ../shared/browser.inc
 
 %define hudButton -moz-appearance: none; color: #434343; border-radius: 4px; border: 1px solid #b5b5b5; background: linear-gradient(#fff, #f2f2f2); box-shadow: inset 0 1px rgba(255,255,255,.8), inset 0 0 1px rgba(255,255, 255,.25), 0 1px rgba(255,255,255,.3); background-clip: padding-box; background-origin: padding-box; padding: 2px 6px;
```

https://pastebin.com/raw/BLWHe4jR

@mattatobin This is same as mentioned on IRC.

**Comment by mattatobin** [comment]
You're not gonna issue a pull request? Ok.

**Comment by adeshkp** [comment]
Sorry I commented on the wrong issue. I had to go through extra work to set up the new repo, but now you have a PR. Be happy!

**Comment by mattatobin** [comment]
I am :)

**Comment by mattatobin** [comment]
Basilisk is now switched to its new repository at https://github.com/MoonchildProductions/Basilisk

It is NOT build-ready yet so don't jump the gun, guys. Watch for an issue at Basilisk's repo for Linux, Mac, and Windows buildablity verification.
