### ISSUE TITLE
Style artifacts on webpages after recent changes

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#976]
<img width="1392" alt="screenshot 2019-02-17 at 9 48 55 am" src="https://user-images.githubusercontent.com/29352104/52910185-bba4f780-32b9-11e9-9e5f-f2895604f8c1.png"><img width="1392" alt="screenshot 2019-02-17 at 1 33 33 pm" src="https://user-images.githubusercontent.com/29352104/52910184-bb0c6100-32b9-11e9-854c-24f4cc99136a.png">

Screenshots are taken on a Mac system.

After a few hours of bisection process, I found skia changes (https://github.com/MoonchildProductions/UXP/commit/a6ddde9097fbef2940c6a4f785dae15978ef2533) to be the culprit.

The glitch is not immediately visible on Linux as we are using trustworthy cairo backend there. Changing azure content backend to "skia" reveals the problem on Linux also.

**Comment by wolfbeast** [comment]
Why are you using Skia for content to begin with?

**Comment by roytam1** [comment]
github network graph is drawn with skia and that commit makes black dot becoming transparent.
https://github.com/MoonchildProductions/UXP/network
