### ISSUE TITLE
CR and LF characters not honored as line breaks in textarea placeholders

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#977]
As reported [on the forum](https://forum.palemoon.org/viewtopic.php?f=29&t=21490):

In textarea placeholder, the carriage return and Line feed characters and ignored. Tested and reproduce with the latest version and a 27.x version, with an old profile and a new created profile.

Theses characters are well interpreted in this place by Chrome, firefox, Edge, even IE 11.

On the W3C documentation, we can read this :

> User agents should present this hint to the user when the element’s value is the empty string and the control is not focused (e.g., by displaying it inside a blank unfocused control). All U+000D CARRIAGE RETURN U+000A LINE FEED character pairs (CRLF) in the hint, as well as all other U+000D CARRIAGE RETURN (CR) and U+000A LINE FEED (LF) characters in the hint, must be treated as line breaks when rendering the hint.

Source : [W3C html 5.2 spec](https://www.w3.org/TR/html52/sec-forms.html#element-attrdef-textarea-placeholder)

- OS tested : Win 7 and Win 10
- The exact version of Pale Moon you are using : 28.3.1 x64 desktop
- Basic hardware information if relevant: CPU, graphics card, amount of RAM : AMD
- Steps to reproduce the problem : bug can see here : https://en.webtools.eu.org/dnsview/index_test.php

HTML code :
```HTML
<textarea name="domaine" cols="40" rows="5" autofocus="autofocus" 
  placeholder="Type the domains to query...\r\nwebtools.eu.org\radmin.google.com\r1.1.1.1\r...">
</textarea>
```

**Comment by JustOff** [comment]
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=574f4f58fe09dd590ea892406e237318c31705b4&tochange=88b2d7276416f8b69191ca5fb1b5c670ec8178b8

Suspect: [Bug 1391044 - Preserve newlines in textarea placeholders](https://bugzilla.mozilla.org/show_bug.cgi?id=1391044)

**Comment by wolfbeast** [comment]
Thanks for the mozregression run

**Comment by wolfbeast** [comment]
Well, this is peculiar to say the least.
Porting the relevant simple change has absolutely no effect...?

**Comment by JustOff** [comment]
I believe the above solution should work, I just had no free time to deal with it, mainly due to the large bunch of reference tests need to be updated along with the actual fix.

**Comment by wolfbeast** [comment]
Don't worry about the tests for now, first just getting the code working is our primary concern.

**Comment by JustOff** [comment]
Well, I'll try to do this tonight.

**Comment by wolfbeast** [comment]
FTR, I already tried replacing:
```C++
nsContentUtils::RemoveNewlines(placeholderTxt);
```
with 
```C++
  if (IsTextArea()) { // <textarea>s preserve newlines...
    nsContentUtils::PlatformToDOMLineBreaks(placeholderTxt);
  } else { // ...<input>s don't
    nsContentUtils::RemoveNewlines(placeholderTxt);
  }
```
in the appropriate location (line 350 in `nsTextControlFrame.cpp`) , but for some reason it has no effect at all on the placeholder text.

**Comment by JustOff** [comment]
It seems that in our codebase this patch should be applied to `nsTextEditorState.cpp`:

https://github.com/MoonchildProductions/UXP/blob/3029dee77bd01e867bc3c7e49bfd14c1484581bb/dom/html/nsTextEditorState.cpp#L2258

The above line should be replaced with:

```
  if (mTextCtrlElement->IsTextArea()) { // <textarea>s preserve newlines...
    nsContentUtils::PlatformToDOMLineBreaks(placeholderValue);
  } else { // ...<input>s don't
    nsContentUtils::RemoveNewlines(placeholderValue);
  }
```

And `nsTextControlFrame.cpp` does not require any changes.

**Comment by wolfbeast** [comment]
Ah-ha. Thanks for digging into that mess.

**Comment by wolfbeast** [comment]
Verified fixed. Reopening this to get the reftests updated.

**Comment by wolfbeast** [comment]
@JustOff by the way, adding web platform tests you can simply add the test files. You should never edit the manifest.json manually but instead use `mach wpt-manifest-update` to have it updated (takes a couple minutes to run).

**Comment by JustOff** [comment]
@wolfbeast, thanks, I didn't know this.
