### ISSUE TITLE
Arrows style inconsistency on hover in Windows

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#981]
Both `arrow-lft-hov.gif` and `arrow-rit-hov.gif` are missing from the default Windows theme, although they are used in `datetimepicker.css` and `arrow.css`:

https://github.com/MoonchildProductions/UXP/blob/a219152bddead6b34f40ae86217f39fbda91aab6/toolkit/themes/windows/global/datetimepicker.css#L109-L115

https://github.com/MoonchildProductions/UXP/blob/a219152bddead6b34f40ae86217f39fbda91aab6/toolkit/themes/windows/global/arrow.css#L34-L36

https://github.com/MoonchildProductions/UXP/blob/a219152bddead6b34f40ae86217f39fbda91aab6/toolkit/themes/windows/global/arrow.css#L45-L47

This results to visual glitches, as [reported on the forum](https://forum.palemoon.org/viewtopic.php?f=3&t=21543).

**Comment by wolfbeast** [comment]
Pulling discussion to the issue instead of the PR
https://github.com/MoonchildProductions/UXP/pull/982#issuecomment-469004351

**Comment by wolfbeast** [comment]
Just because the situation of mapping normal and hover to the same image existed for a long time doesn't make it right.

Let's improve what we have and make actually -different- images for the hover state (e.g. brightness) to provide the user with immediate feedback (Improve intuitive responsiveness of the UI)

**Comment by JustOff** [comment]
Sorry, but in this case, I have to step aside, because I don't have the necessary graphic design skills.

**Comment by wolfbeast** [comment]
LOL. Okay I guess using a paint program is too difficult.

**Comment by JustOff** [comment]
Your assumption is wrong, but whatever. Good there is someone to do it **properly** :+1:
