### ISSUE TITLE
Remove DarkMatter certificates

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#983]
QuoVadis certificates should be removed from both Pale Moon and Basilisk.

Article @ gHacks.net:
https://www.ghacks.net/2019/02/24/how-to-remove-darkmatter-certificates/
> A Reuter's article links DarkMatter to the United Arab Emirates government and surveillance operations.
One such operation, called Karma, saw the team hack iPhones of "hundreds of activists, political leaders, and suspected terrorists" according to Reuters.

Discussions @ forum.palemoon.org:
https://forum.palemoon.org/viewtopic.php?f=4&t=21534/
https://forum.palemoon.org/viewtopic.php?f=4&t=21545/

**Comment by wolfbeast** [comment]
Not going by one article when there is no conclusive evidence to support it.

Discussions in the mozilla sec group where the onboarding [is discussed](https://groups.google.com/forum/#!msg/mozilla.dev.security.policy/nnLVNfqgz7g/YiybcXciBQAJ): 

> DarkMatter has several business units that focus on a broad range of cyber security activities. The Trust Services BU is responsible for the DarkMatter CA and primarily focused on enabling secure communications and digital transformation. We utilize the services of other DM BU’s who are primarily focused on defensive cyber security activities e.g. Cyber Network Defense and Managed Security Services to protect and ensure the integrity of the CA operations. 

> In response to your post overnight (included below), I want to assure you that DarkMatter’s work is solely focused on defensive cyber security, secure communications and digital transformation. We have never, nor will we ever, operate or manage non-defensive cyber activities against any nationality.
> 
> Furthermore, in the spirit of transparency, we have published all our public trust TLS certificates to appropriate CT log facilities (including even all our OV certificates) before this was even a requirement.  We have been entirely transparent in our operations and with our clients as we consider this a vital component of establishing and maintaining trust.
> 
> We have used FIPS certified HSMs as our source of randomness in creating our Authority certificates, so we have opened an investigation based on Corey Bonnell’s earlier post regarding serial numbers and will produce a corresponding bug report on the findings.
