### ISSUE TITLE
Feature Request: FIDO2 + WebAuthn

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/UXP#987]
It looks like there is emerging consensus around FIDO2 WebAuthn as a possible post-password login mechanism:

https://fidoalliance.org/fido2/

It is now W3C standard and adopted by Chrome, FF, Safari, and Edge:
https://venturebeat.com/2019/03/04/w3c-approves-webauthn-as-the-web-standard-for-password-free-logins/

Adding this feature would allow Pale Moon users to securely authenticate to cooperating websites without the need to generate insecure and inconvenient passwords.  Please consider including it.  Thanks!

```
>> navigator.credentials.create()
TypeError: navigator.credentials is undefined [Learn More]
```

**Comment by wolfbeast** [comment]
I'm afraid our current team does not have the spare capacity to implement this feature.
In addition, there is already an extension that supports the U2F API for e.g. yubikeys at https://github.com/prefiks/u2f4moz

**Comment by wolfbeast** [comment]
See also:
https://forum.palemoon.org/viewtopic.php?f=26&t=17012
https://forum.palemoon.org/viewtopic.php?f=13&t=19802
