### ISSUE TITLE
nsIPrefBranch.get*Pref should support providing a default value

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#988]
I think this would be awesome to have so we can avoid try blocks as well as the duplicate functions that replicate this behavior scattered about the codebase.

----

**Bug:** [1338306](https://bugzilla.mozilla.org/show_bug.cgi?id=1338306)
**Git:** https://github.com/mozilla/gecko-dev/commit/8e85c687b436fd7c7972b3ced57fb984db0979d7
**HG:** https://hg.mozilla.org/mozilla-central/rev/f6479c35a73c

**Comment by mattatobin** [comment]
As a note: I am not a fan of the implementation as to why they decided to wrapping functions in cpp.. But @wolfbeast will have to eval. If we do it as-is, it is simple as hell to port.

**Comment by wolfbeast** [comment]
I think it was wrapped in C++ to catch this change at as low a level as possible (so it's really global) and to prevent the need for explicit type checking of the default values in JS.

**Comment by Ascrod** [comment]
Has the decision been made to port this over directly? if so, I can submit a PR.

**Comment by mattatobin** [comment]
Go for it.

**Comment by wolfbeast** [comment]
With this solved, releasing #989 and #991 for resolution.
