### ISSUE TITLE
palemoon hangs after dragging the window on other screen

### ISSUE THREAD

**Issue by pizdjuk** [MoonchildProductions/UXP#990]
I suspect, that the problem is in changing the resolution.
The behavior is follows:

start palemoon, connect other monitor, drag the palemoon onto other monitor.

the palemoon seems not to respond. For example: typing :open google.com dont result in anything. But after this, if one press on maximaze button on the palemoon's window the typed text appears.

Seems that palemoon receives the keyboard and process it correctly, but doesn't display till the window size changes.

I hope this description helps to fix this annoying bug.

**Comment by mattatobin** [comment]
What operating system, what hardware, why was this posted here and not the forum first?

**Comment by kn-yami** [comment]
Was this tested without Pentadactyl enabled?

**Comment by pizdjuk** [comment]
@kn-yami
Just tested: with pentadactyl disabled the bug doesn't trigger.
Second: With pentadactyl enabled there is workaround: the window with a browser needs to be minimized when the new screen is connected.

**Comment by pizdjuk** [comment]
@mattatobin
I've searched for the bugtracker, and the posted it here.

OS: Linux Mint 18.3
Hardware: Thinkpad T470s + Dockstation/other monitors.

**Comment by wolfbeast** [comment]
Extension-caused.
