### ISSUE TITLE
Align default Accept: headers with the fetch spec

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#993]
See https://fetch.spec.whatwg.org/#fetching Step 1.3

For navigation: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
For images: `image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5`
For style: `text/css,*/*;q=0.1`
Anything else: `*/*`

This will replace the singular default accept string currently preffed in `network.http.accept.default`

**Comment by mattatobin** [comment]
So are you going to make `network.http.accept.default` = `*/* and then do `network.http.accept.navigation`, `network.http.accept.image` etc?

**Comment by wolfbeast** [comment]
For maximum flexibility I can keep this prefable, although these would be default accept headers only if not yet otherwise defined.

**Comment by wolfbeast** [comment]
I've kept our image accept header the way it was because strictly following the current spec would completely nullify any sort of image conneg (and would hard-code preference of png and svg formats over other image formats, as well as not being able to negotiate new/newer formats or formats that are not universally supported like `image/webp` `image/apng` or `image/jxr` -- I consider this to be a spec bug so have filed an issue with whatwg for this: https://github.com/whatwg/fetch/issues/877
