### ISSUE TITLE
Configure ERROR: Must export JS symbols when building a shared library.

### ISSUE THREAD

**Issue by swedebugia** [MoonchildProductions/UXP#994]
I'm trying to update palemoon in guix. I keep getting this error and would like some help.

sdb@parabola:/tmp/guix-build-newmoon-28.4.0.drv-0/source$ /gnu/store/7j3941iannrngdvgbclyxid12vds5w9i-make-4.2.1/bin/make -f client.mk build
> /tmp/guix-build-newmoon-28.4.0.drv-0/source/o/.mozconfig.mk
/gnu/store/7j3941iannrngdvgbclyxid12vds5w9i-make-4.2.1/bin/make -f /tmp/guix-build-newmoon-28.4.0.drv-0/source/client.mk realbuild 
CREATE_MOZCONFIG_JSON=
make[1]: Entering directory '/tmp/guix-build-newmoon-28.4.0.drv-0/source'
Adding client.mk options from /tmp/guix-build-newmoon-28.4.0.drv-0/source/.mozconfig:
    PYTHON=python2
    AUTOCONF=autoconf
    MOZ_OBJDIR=/tmp/guix-build-newmoon-28.4.0.drv-0/source/o
    OBJDIR=/tmp/guix-build-newmoon-28.4.0.drv-0/source/o
    FOUND_MOZCONFIG=/tmp/guix-build-newmoon-28.4.0.drv-0/source/.mozconfig
make[2]: Entering directory '/tmp/guix-build-newmoon-28.4.0.drv-0/source'
cp /tmp/guix-build-newmoon-28.4.0.drv-0/source/.mozconfig /tmp/guix-build-newmoon-28.4.0.drv-0/source/o/.mozconfig
cd /tmp/guix-build-newmoon-28.4.0.drv-0/source/o
/tmp/guix-build-newmoon-28.4.0.drv-0/source/configure
Reexecuting in the virtualenv
Adding configure options from /tmp/guix-build-newmoon-28.4.0.drv-0/source/.mozconfig
  --enable-application=browser
  --prefix=/gnu/store/zp149xjzrrcw4xhqqibh3wwp0n99dlcy-newmoon-28.4.0
  --disable-debug
  --disable-debug-symbols
  --disable-accessibility
  --disable-updater
  --disable-parental-controls
  --disable-install-strip
  --disable-tests
  --with-system-libevent
  --with-system-zlib
  --with-system-bz2
  --with-system-libvpx
  --enable-system-hunspell
  --enable-system-ffi
  --enable-system-sqlite
  --enable-system-cairo
  --enable-system-pixman
  --enable-shared-js
  --disable-valgrind
  --with-pthreads
  --disable-optimize
  --enable-ffmpeg
  --enable-default-toolkit=cairo-gtk2
  --disable-alsa
  --enable-strip
  --disable-gamepad
  --enable-chrome-format=omni
  --enable-startup-notification
  --enable-shared-js
  --enable-devtools
  --with-system-png
  --enable-pulseaudio
  --disable-necko-wifi
  --with-system-jpeg
  --disable-official-branding
  --with-system-nspr
  --enable-sandbox
  --enable-content-sandbox
  --enable-skia
  --enable-jemalloc
  --with-system-icu
checking for a shell... /gnu/store/qn1ax1fkj16x280m1rv7mcimfmn9l2pf-bash-4.4.23/bin/bash
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... x86_64-pc-linux-gnu
checking whether cross compiling... no
checking for pkg_config... /gnu/store/xyiyf12w4i7zf5g5b4ah0bi1mmd6i8xa-pkg-config-0.29.2/bin/pkg-config
checking for pkg-config version... 0.29.2
checking for yasm... /gnu/store/sf4gcyx9plxgds3qpr5lqf55zxc9l892-yasm-1.3.0/bin/yasm
checking yasm version... 1.3.0
checking for the target C compiler... /gnu/store/n2p1zs14y89lwkg9da68y12pc10c6sw9-gcc-5.5.0/bin/gcc
checking whether the target C compiler can be used... yes
checking the target C compiler version... 5.5.0
checking the target C compiler works... yes
checking for the target C++ compiler... /gnu/store/n2p1zs14y89lwkg9da68y12pc10c6sw9-gcc-5.5.0/bin/g++
checking whether the target C++ compiler can be used... yes
checking the target C++ compiler version... 5.5.0
checking the target C++ compiler works... yes
checking for the host C compiler... /gnu/store/n2p1zs14y89lwkg9da68y12pc10c6sw9-gcc-5.5.0/bin/gcc
checking whether the host C compiler can be used... yes
checking the host C compiler version... 5.5.0
checking the host C compiler works... yes
checking for the host C++ compiler... /gnu/store/n2p1zs14y89lwkg9da68y12pc10c6sw9-gcc-5.5.0/bin/g++
checking whether the host C++ compiler can be used... yes
checking the host C++ compiler version... 5.5.0
checking the host C++ compiler works... yes
checking for 64-bit OS... yes
checking for stdint.h... yes
checking for inttypes.h... yes
checking for malloc.h... yes
checking for alloca.h... yes
checking for sys/byteorder.h... no
checking for getopt.h... yes
checking for unistd.h... yes
checking for nl_types.h... yes
checking for cpuid.h... yes
checking for sys/statvfs.h... yes
checking for sys/statfs.h... yes
checking for sys/vfs.h... yes
checking for sys/mount.h... yes
checking for sys/quota.h... yes
checking for linux/quota.h... yes
checking for linux/if_addr.h... yes
checking for linux/rtnetlink.h... yes
checking for sys/queue.h... yes
checking for sys/types.h... yes
checking for netinet/in.h... yes
checking for byteswap.h... yes
checking for linux/perf_event.h... yes
checking for perf_event_open system call... yes
checking whether the C compiler supports -Wclass-varargs... no
checking whether the C++ compiler supports -Wclass-varargs... no
checking whether the C compiler supports -Wloop-analysis... no
checking whether the C++ compiler supports -Wloop-analysis... no
checking whether the C++ compiler supports -Wc++11-compat-pedantic... no
checking whether the C++ compiler supports -Wc++14-compat... yes
checking whether the C++ compiler supports -Wc++14-compat-pedantic... no
checking whether the C++ compiler supports -Wc++1z-compat... no
checking whether the C++ compiler supports -Wimplicit-fallthrough... no
checking whether the C compiler supports -Wstring-conversion... no
checking whether the C++ compiler supports -Wstring-conversion... no
checking whether the C compiler supports -Wthread-safety... no
checking whether the C++ compiler supports -Wthread-safety... no
checking whether the C++ compiler supports -Wno-inline-new-delete... no
checking whether the C compiler supports -Wno-error=maybe-uninitialized... yes
checking whether the C++ compiler supports -Wno-error=maybe-uninitialized... yes
checking whether the C compiler supports -Wno-error=deprecated-declarations... yes
checking whether the C++ compiler supports -Wno-error=deprecated-declarations... yes
checking whether the C compiler supports -Wno-error=array-bounds... yes
checking whether the C++ compiler supports -Wno-error=array-bounds... yes
checking whether the C compiler supports -Wno-error=multistatement-macros... no
checking whether the C++ compiler supports -Wno-error=multistatement-macros... no
ERROR: Must export JS symbols when building a shared library.
*** Fix above errors and then restart with\
               "/gnu/store/7j3941iannrngdvgbclyxid12vds5w9i-make-4.2.1/bin/make -f client.mk build"
make[2]: *** [/tmp/guix-build-newmoon-28.4.0.drv-0/source/client.mk:378: configure] Error 1
make[2]: Leaving directory '/tmp/guix-build-newmoon-28.4.0.drv-0/source'
make[1]: *** [/tmp/guix-build-newmoon-28.4.0.drv-0/source/client.mk:391: /tmp/guix-build-newmoon-28.4.0.drv-0/source/o/Makefile] Error 2
make[1]: Leaving directory '/tmp/guix-build-newmoon-28.4.0.drv-0/source'
make: *** [client.mk:170: build] Error 2

**Comment by kn-yami** [comment]
AFAIK building with shared JS is currently broken: https://github.com/MoonchildProductions/UXP/issues/62. Also, your `.mozconfig` is not valid.

**Comment by mattatobin** [comment]
They aren't using official branding so their mozconfig doesn't matter to us. Of course, not an official build so it doesn't matter to us.. Gotta love the low IQ builders and their half-assed mozconfigs and inability to actually check issues (or search the forum if applicable).

Also, yes, shared-js is busted .. we will get to it.. eventually.

**Comment by swedebugia** [comment]
I figured it out. I was missing --enable-export-js

**Comment by swedebugia** [comment]
Hi. I dislike your tone @mattatobin but your pointers were useful to get it to build correctly. 
Would any of you mind linking to the wiki? I did not find any wiki with build instructions on palemoon.org nor in this repo.

**Comment by kn-yami** [comment]
Here: http://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux#head:Mozconfig_Files.

**Comment by cbehan** [comment]
"Of course, not an official build so this entire issue doesn't matter to us.."
You don't want anyone who's not you to be able to build your browser?
