### ISSUE TITLE
File Drag & Drop fails 

### ISSUE THREAD

**Issue by elig0n** [MoonchildProductions/UXP#996]
When I drag an image file from windows file explorer to a "drag & drop file here" box in a certain website the image gets loaded in the same tab as if I opened a file instead of uploaded. It doesn't happen on latest Firefox.
Not true for a GitHub message reply box such as this. 

Palemoon version 28.4.0 (64-bit) on Windows 10

**Comment by JustOff** [comment]
How do you expect someone to help you without knowing the site in question?

**Comment by elig0n** [comment]
By handing required instructions for example. A login based website is useless to you.

**Comment by wolfbeast** [comment]
If the website is behind a login, then please provide a reduced test case showing the problem so we can investigate.

**Comment by wolfbeast** [comment]
Considering the reported closed this issue without further testcase or explanation, marking as incomplete.
