### ISSUE TITLE
[suggestion] Alternate selection search new tab focus with a key modifier

### ISSUE THREAD

**Issue by elig0n** [MoonchildProductions/UXP#997]
Other browsers implement a modifier key that serves to alternate the focus (i.e. between foreground/background) of the new tab that is to be opened.

In case I'm not clear I'm speaking of the "Search [search-engine] for '[selection]'..." menu entry that appears in the right click context menu that pops after right clicking a selected text portion in a web-page.

**Comment by wolfbeast** [comment]
... did you even check the preferences window, or are you just assuming that Pale Moon = Firefox?
![prefs1](https://user-images.githubusercontent.com/3359132/54221457-d6067580-44f3-11e9-8904-7262557c9acd.png)

**Comment by elig0n** [comment]
I was talking about a key modifier, not a menu option.
And I was not assuming anything either. I actually gotten to know that feature from Chrome...

**Comment by wolfbeast** [comment]
In general, users will prefer one or the other behavior and switching between either mode rapidly is extremely uncommon - a modifier key for the option is not something to be implemented in the core; but it should be easy enough to make this happen with a simple extension.
