### ISSUE TITLE
Use xdg-desktop-portal for file selection dialogs on Linux

### ISSUE THREAD

**Issue by Macribit** [MoonchildProductions/UXP#999]
just asking

looks like a slim diff.

https://bugzilla.mozilla.org/show_bug.cgi?id=1490186

https://hg.mozilla.org/integration/autoland/rev/2fd7d3ae070e

**Comment by Macribit** [comment]
looks like this commit has raised this bug 
https://bugzilla.mozilla.org/show_bug.cgi?id=1516491

which has been fixed with this other commit

https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/toolkit/system/gnome/nsGIOService.cpp#27

**Comment by wolfbeast** [comment]
@Macribit Are you wanting to port this across yourself or not? Travis has only limited time at the moment and we're not able to give Linux-specific enhancements much attention at the moment otherwise.

**Comment by Ascrod** [comment]
I was able to manually implement the first patch, and it seemed to work okay on my system (Mint 19.2, GTK 3.22) with some casual testing. However, if [1516491](https://bugzilla.mozilla.org/show_bug.cgi?id=1516491) is going to be an issue, we may want to hold off until GTK 3.24 is more widespread.

As best I can tell, the patch implemented in [1517074](https://bugzilla.mozilla.org/show_bug.cgi?id=1517074) (which is referenced as a fix for 1516491) would be useless to us because we don't target Flatpak as a distribution system.

**Comment by wolfbeast** [comment]
I guess we can implement it behind a pref, and people can enable it with the pref themselves if they want to have it. We can reconsider later if we want to enable it by default -- which would require all major distributions, including supported LTS versions of them, to have a sufficiently updated GTK 3.*

**Comment by Ascrod** [comment]
Actually, a pref may not be necessary here. GTK only uses the native file selector if the application is run with the environment variable `GTK_USE_PORTAL=1` (and if `xdg-desktop-portal` is installed and running). This variable is normally set to zero unless the user has explicitly exported it.

**Comment by wolfbeast** [comment]
Isn't it cumbersome for end users to do it that way?

**Comment by Ascrod** [comment]
I should clarify - if that environment variable is not set, the change won't take effect at all. If the user wants to use the native file picker, `GTK_USE_PORTAL` *must* be set to 1. Since that is the case, I don't think an additional preference serves a purpose here.

**Comment by wolfbeast** [comment]
Can it be safely assumed then that everyone who DOES have this set (I'm assuming system-wide then, not just for Pale Moon) has a recent-enough GTK 3 setup?

**Comment by Ascrod** [comment]
Sorry for the response delay. Been busy on my end, including trying to test this feature in Kubuntu (Ubuntu with pre-installed with KDE) 16.04 and 18.04 VMs. The package `xdg-desktop-portal-kde` is required for this feature to work in KDE, but isn't available in 16.04. I also wasn't able to reproduce the "Cannot save as HTML" issue on 18.04 (with libgtk 3.22).

> Can it be safely assumed then that everyone who DOES have this set (I'm assuming system-wide then, not just for Pale Moon) has a recent-enough GTK 3 setup?

No, I don't think that's a safe bet. My next suggestion was going to be gating the code with `gtk_check_version`, but that would limit the feature only to users with GTK 3.24 installed. Taking all of these points into account, using a preference is probably... preferable. :wink:

I can include a pref, do a bit more testing, and put in a PR.

**Comment by wolfbeast** [comment]
Considering this is a GTK+ 3 thing, it'd apply to Basilisk and other GTK 3 builds of applications on UXP, not necessarily Pale Moon (which is GTK 2), IIUC? Just trying to get my release notes notes straight.

**Comment by Ascrod** [comment]
Correct, specifically GTK+ 3.20, so it won't work for systems using older versions of GTK.
